### ISSUE TITLE
Benchmark RubyKon

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#1]
Put RubyKon into our CI benchmark system, track performance, and improve.

https://github.com/jruby/jruby/issues/4400

**Comment by PragTob** [comment]
I'm issue #1 :D 

Jokes aside, I hope that tomorrow I can get back to this, see if my custom build works and then finally run the benchmarks hopefully publishing results some time next year.

Thank you everybody for the help along the way :)

**Comment by pitr-ch** [comment]
The results are published https://pragtob.wordpress.com/2017/01/24/benchmarking-a-go-ai-in-ruby-cruby-vs-rubinius-vs-jruby-vs-truffle-a-year-later/, thanks @PragTob.

**Comment by chrisseaton** [comment]
Sorry, the intention was to put this into our CI so we can detect regressions early. I'll reopen.

**Comment by bjfish** [comment]
@chrisseaton This is now setup at in CI at https://github.com/oracle/truffleruby/commit/54932f334905933c9dbd0215f0893a448a56b598.

**Comment by PragTob** [comment]
Just in time when I wanted to make a new round of benchmarks :eyes: 

Thanks!
