### ISSUE TITLE
rbenv support?

### ISSUE THREAD

**Issue by aemadrid** [oracle/truffleruby#1050]
I know we have #9  already but I want to make sure we don't forget about rbenv.

**Comment by nirvdrum** [comment]
We do have docs on how to [set up TruffleRuby with rbenv](https://github.com/oracle/truffleruby/blob/master/doc/user/ruby-managers.md). I have it set up and use it regularly.

I think what you likely want is ruby-build support so you can seamlessly install TruffleRuby and have it set up within rbenv. It's something we're working towards. But in the meanwhile if you don't mind putting in a bit of manual effort, you can use TruffleRuby with rbenv.

**Comment by aemadrid** [comment]
yes, what I meant was using `rbenv install truffleruby` to easily getting it installed/upgraded. That would help me and a lot of others I think to get going quickly with TR.

**Comment by chrisseaton** [comment]
rbenv is documented and tested in https://github.com/oracle/truffleruby/pull/1061.

I'll close this issue and open a new one for installing via Ruby version managers.

**Comment by chrisseaton** [comment]
https://github.com/oracle/truffleruby/issues/1062
