### ISSUE TITLE
Require semantics not the same as MRI

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#1079]
With https://github.com/thbar/kiba/, https://github.com/thbar/kiba-common, https://github.com/thbar/system_bang, and https://github.com/thbar/kiba-ruby-benchmarks.

```
$ ruby -I ../kiba/lib -I ../kiba-common/lib/ -I ../system_bang/lib/ ../kiba/bin/kiba csv_processing.etl 
I, [2018-02-05T21:06:16.734271 #6058]  INFO -- : Running with ruby 2.3.5
I, [2018-02-05T21:06:19.732966 #6058]  INFO -- : Processing done (took 3.0 seconds)
1406423187 519371 data/output.csv
$ jt ruby -I ../kiba/lib -I ../kiba-common/lib/ -I ../system_bang/lib/ ../kiba/bin/kiba csv_processing.etl 
$ /Users/chrisseaton/Documents/truffleruby/truffleruby/bin/truffleruby -Xcore.load_path=/Users/chrisseaton/Documents/truffleruby/truffleruby/src/main/ruby -Xgraal.warn_unless=false -I ../kiba/lib -I ../kiba-common/lib/ -I ../system_bang/lib/ ../kiba/bin/kiba csv_processing.etl
csv_processing.etl:2:in `require_relative': cannot load such file -- csv_processing.etl/etl/csv_source (LoadError)
	from csv_processing.etl:2:in `<top (required)>'
	from /Users/chrisseaton/Documents/truffleruby/kiba/lib/kiba/parser.rb:20:in `instance_eval'
	from /Users/chrisseaton/Documents/truffleruby/kiba/lib/kiba/parser.rb:20:in `parse'
	from /Users/chrisseaton/Documents/truffleruby/kiba/lib/kiba/cli.rb:12:in `run'
	from ../kiba/bin/kiba:5:in `<main>'
```

Maybe something to do with the `instance_eval`?

From https://github.com/oracle/truffleruby/issues/1054.

**Comment by chrisseaton** [comment]
Using `-Xlog.load -Xlog.feature_location`, I can see where this starts to go wrong:

```
[ruby] INFO starting search from csv_processing.etl:2 for feature csv_processing.etl/etl/csv_source...
```

`require_relative` is treating the whole file name as a directory, so it's looking for `etl/csv_source` relative to `csv_processing.etl`, and is trying `csv_processing.etl/etl/csv_source`.

**Comment by chrisseaton** [comment]
I've fixed all the remaining `require_relative` specs here https://github.com/oracle/truffleruby/compare/require_relative.

**Comment by chrisseaton** [comment]
I looked at the two remaining specs in `instance_eval` but don't think they're relevant. Tidied up a lot of things to do with line numbers in the various `eval` methods as we have some problems here.

**Comment by chrisseaton** [comment]
I've got a failing spec for it:

```ruby
  it "loads a path relative to a file base name as specified in an #instance_eval" do
    Dir.chdir File.dirname(File.join(__dir__, @path)) do
      Object.new.instance_eval("require_relative(#{File.basename(@path).inspect})", "foo.rb").should be_true
    end
    ScratchPad.recorded.should == [:loaded]
  end
```

**Comment by chrisseaton** [comment]
As is usually the case, the actual fix was pretty simple.

https://github.com/oracle/truffleruby/pull/1346/commits/892d9200a54cb0f67a53f91bb34b8c04e2953db1

But I took the opportunity to improve some more things along the way and properly spec this behaviour.

By the way, JRuby fails on this new spec https://github.com/oracle/truffleruby/pull/1346/commits/6e0bcd1d77099117e3fc3dfc0c947a54f9b23f65 as well! MRI passes of course, and the behaviour doesn't look like a bug, otherwise I wouldn't have added the spec. Do you test on JRuby? Rubinius seems to work ok.

A smaller test case:

`a.rb`:

```ruby
puts 'a'
Object.new.instance_eval("require_relative('b.rb')", "x.rb")
```

`b.rb`:

```ruby
puts 'b'
```

```
$ ~/.rbenv/versions/2.3.7/bin/ruby a.rb 
a
b
$ ~/.rbenv/versions/2.5.1/bin/ruby a.rb 
a
b
$ ~/.rbenv/versions/jruby-9.1.16.0/bin/ruby a.rb 
a
Errno::ENOENT: No such file or directory - /Users/chrisseaton/Documents/truffleruby/kiba-ruby-benchmarks/x.rb
          realpath at org/jruby/RubyFile.java:850
  require_relative at uri:classloader:/jruby/kernel/kernel.rb:11
            <eval> at x.rb:1
     instance_eval at org/jruby/RubyBasicObject.java:1703
            <main> at a.rb:2
$ ~/.rbenv/versions/rbx-3.84/bin/ruby a.rb 
a
b
$ jt ruby a.rb
a
b
```

You could send the issue to JRuby if you wanted to, or they'll find it themselves when we upstream specs and they downstream them.

**Comment by chrisseaton** [comment]
Thanks very much for the report. This will be fixed in RC 2. Please open issues for any more problems you find.

**Comment by thbar** [comment]
@chrisseaton I missed your notification - thanks for the fix, great work!
