### ISSUE TITLE
Supply a curl-able download that doesn't need an account or a click-through to use.

### ISSUE THREAD

**Issue by pitr-ch** [oracle/truffleruby#118]

**Comment by chrisseaton** [comment]
More documentation soon, but you can now install TruffleRuby without a click-through.

```
$ wget https://github.com/oracle/graal/releases/download/vm-1.0.0-rc1/graalvm-ce-1.0.0-rc1-linux-amd64.tar.gz
$ tar -zxf graalvm-ce-1.0.0-rc1-linux-amd64.tar.gz
$ export PATH=graalvm-1.0.0-rc1/bin:$PATH
$ gu install -c org.graalvm.ruby
$ ruby --version
truffleruby 1.0.0-rc1, like ruby 2.3.7 <native build with Graal> [x86_64-linux]
```

**Comment by chrisseaton** [comment]
New documentation here, but I'll leave this issue open because we hope to simplify further.

https://github.com/oracle/truffleruby/blob/master/doc/user/installing.md

**Comment by eregon** [comment]
This is now done, for example for 1.0.0-RC2:
https://github.com/oracle/truffleruby/releases/download/vm-1.0.0-rc2/truffleruby-1.0.0-rc2-linux-amd64.tar.gz
https://github.com/oracle/truffleruby/releases/download/vm-1.0.0-rc2/truffleruby-1.0.0-rc2-macos-amd64.tar.gz

And those are used by Ruby installers (#1062).
The only remaining thing is documenting how to use these directly, for, e.g., testing in CI.

**Comment by eregon** [comment]
The standalone distribution, which is available publicly as GitHub releases, is now documented in https://github.com/oracle/truffleruby/blob/master/doc/user/standalone-distribution.md, as well as how to use it for testing in CI.
