### ISSUE TITLE
Erro installing with rvm 

### ISSUE THREAD

**Issue by ricsdeol** [oracle/truffleruby#1339]
Hi, I'm installed  GraalVM Community Edition 1.0 RC1and add component by `gu -c install org.graalvm.ruby`

and add config rvm (https://github.com/oracle/truffleruby/blob/master/doc/user/ruby-managers.md#rvm)

but don't work: 

Errors:

> rvm mount  ~/.opt/graalvm/jre/languages/ruby -n truffleruby
Mounting 'ext-truffleruby' from '/home/ricsdeol/.opt/graalvm-1.0.0-rc1/jre/languages/ruby' with 'bin/ruby'
ext-truffleruby - #gemset created /home/ricsdeol/.rvm/gems/ext-truffleruby@global
ext-truffleruby - #importing gemset /home/ricsdeol/.rvm/gemsets/global.gemsthere was an error installing gem gem-wrappers
there was an error installing gem rubygems-bundler
.....................................................-there was an error installing gem rvm
there was an error installing gem bundler
there was an error installing gem rubocop
....................................................../there was an error installing gem pry-byebug
there was an error installing gem httparty
.........................
ext-truffleruby - #generating global wrappers..................
Error running 'run_gem_wrappers_regenerate',
please read /home/ricsdeol/.rvm/log/1524256402_ext-truffleruby/gemset.wrappers.global.log
ext-truffleruby - #gemset created /home/ricsdeol/.rvm/gems/ext-truffleruby
ext-truffleruby - #importing gemsetfile /home/ricsdeol/.rvm/gemsets/default.gems evaluated to empty gem list
ext-truffleruby - #generating default wrappers..................
Error running 'run_gem_wrappers_regenerate',
please read /home/ricsdeol/.rvm/log/1524256422_ext-truffleruby/gemset.wrappers.default.log
╭─ricsdeol at ricsdeol-solvian in ~/bin using ‹ruby-2.4.1› 18-04-20 - 17:33:45
╰─⠠⠵ rvm use ext-truffleruby
Using /home/ricsdeol/.rvm/gems/ext-truffleruby
╭─ricsdeol at ricsdeol-solvian in ~/bin using ‹ext-truffleruby› 18-04-20 - 17:33:49
╰─⠠⠵ ruby --version
truffleruby 1.0.0-rc1, like ruby 2.3.7 <native build with Graal> [x86_64-linux]
╭─ricsdeol at ricsdeol-solvian in ~/bin using ‹ext-truffleruby› 18-04-20 - 17:33:54
╰─⠠⠵ gem install bundler
[ruby] WARN A nonstandard GEM_HOME is set /home/ricsdeol/.rvm/gems/ext-truffleruby
[ruby] WARN The bad GEM_HOME may come from a ruby manager, make sure you've called one of: `rvm use system`, `rbenv system`, or `chruby system` to clear the environment.
ERROR:  Loading command: install (RuntimeError)
	java.io.IOException: Error while trying to parse null (RuntimeException)
	from java.lang.Throwable.<init>(Throwable.java:310)
	from java.lang.Exception.<init>(Exception.java:102)
	from java.lang.RuntimeException.<init>(RuntimeException.java:96)
	from com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1062)
	from com.oracle.truffle.api.TruffleLanguage$Env.parse(TruffleLanguage.java:1568)
	from org.truffleruby.language.loader.FeatureLoader.lambda$loadCExtLibrary$2(FeatureLoader.java:279)
	from org.truffleruby.language.loader.FeatureLoader$$Lambda$1224/1911388477.accept(Unknown Source)
	from org.truffleruby.cext.Linker.loadLibrary(Linker.java:135)
	from org.truffleruby.language.loader.FeatureLoader.loadCExtLibrary(FeatureLoader.java:275)
	from org.truffleruby.language.loader.RequireNode.requireCExtension(RequireNode.java:172)
Caused by:
Error while trying to parse null (IOException)
	from java.lang.Throwable.<init>(Throwable.java:287)
	from java.lang.Exception.<init>(Exception.java:84)
	from java.io.IOException.<init>(IOException.java:81)
	from com.oracle.truffle.llvm.Runner.parse(Runner.java:273)
	from com.oracle.truffle.llvm.Sulong.parse(Sulong.java:114)
	from com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:596)
	from com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1058)
	from com.oracle.truffle.api.TruffleLanguage$Env.parse(TruffleLanguage.java:1568)
	from org.truffleruby.language.loader.FeatureLoader.lambda$loadCExtLibrary$2(FeatureLoader.java:279)
	from org.truffleruby.language.loader.FeatureLoader$$Lambda$1224/1911388477.accept(Unknown Source)
Caused by:
External function @SSLv23_method cannot be found. (LinkageError)
	from java.lang.Throwable.<init>(Throwable.java:265)
	from java.lang.Error.<init>(Error.java:70)
	from java.lang.LinkageError.<init>(LinkageError.java:55)
	from com.oracle.truffle.llvm.runtime.NFIContextExtension.getNativeFunction(NFIContextExtension.java:293)
	from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$UnresolvedFunction.resolve(LLVMFunctionDescriptor.java:213)
	from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$UnresolvedFunction.createNativeWrapper(LLVMFunctionDescriptor.java:231)
	from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor.toNative(LLVMFunctionDescriptor.java:495)
	from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$LLVMFunctionDescriptorNativeLibrary.toNative(LLVMFunctionDescriptor.java:458)
	from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$LLVMFunctionDescriptorNativeLibrary.toNative(LLVMFunctionDescriptor.java:436)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMObjectNativeFactory$CachedToNativeNode.toNative(LLVMObjectNativeFactory.java:232)
Translated to internal error
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

Could anyone help me fix this?

**Comment by chrisseaton** [comment]
Hi did you mean to close this? Do you still need help?

**Comment by chrisseaton** [comment]
Yes this does look like an OpenSSL version see. Please see the document linked above, and ask if you need more help.

**Comment by Confusion** [comment]
I encountered this error when attempting to use TruffleRuby on Ubuntu 18.04. As the documentation suggests, only 16.04 may currently be expected to work.

**Comment by eregon** [comment]
Support for more recent versions of OpenSSL is coming, which should solve this issue and using TruffleRuby on recent distributions in general.
