### ISSUE TITLE
Get the rbtree gem working

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#1343]
The `rbtree` C extension gem doesn't compile or work.

From #702.

**Comment by eregon** [comment]
I started a list of not yet supported C extensions in #1400 to list them together as one issue.

**Comment by eregon** [comment]
It appears to install and require fine now with 5f3339321c6bf3f30e7993101b2f2abce7f1b0f4:
```
$ gem i rbtree
Fetching rbtree-0.4.4.gem
Building native extensions. This could take a while...
Successfully installed rbtree-0.4.4
1 gem installed
$ ruby -rrbtree -e 'p RBTree'
RBTree
```
