### ISSUE TITLE
DivMod Optimization

### ISSUE THREAD

**Issue by havenwood** [oracle/truffleruby#1371]
In a [little benchmark calculating Easter](https://gist.github.com/havenwood/23bb57241f6ca6c75bc24d4e1c6b301c), it seems that #divmod is substantially slower than #div and #mod separately.

Sorry for the ugly code in the benchmark. It was just a spike out of curiosity. Once again TruffleRuby's performance is incredible. Thanks for the amazing work!

**Comment by eregon** [comment]
Wow, so on these benchmarks we are 3 order of magnitudes faster than MRI, but only 1 order of magnitude faster on the divmod variant :D

I'll try to take a look at this soon, thank you for the report.

**Comment by eregon** [comment]
This turned out to be trivial :)
The code for divnum contains a `@TruffleBoundary`, a barrier for compilation used when there is too complex code behind (like a multiplication of 2 Bignum for instance).

But actually nothing for Integer#divmod(Integer) needs that, it was added by mistake back in 2014 (https://github.com/oracle/truffleruby/commit/d7cf4962ea47095d28252523fc6d8fd726ebe3c1#diff-3a21257a826d391d011c582eda51fd0dR81 by @chrisseaton) so we can remove it and get the performance we expect :smiley: 

```
$ jt ruby --graal easter_bench.rb              
Warming up --------------------------------------
            easter_1     2.562M i/100ms
            easter_2     2.893M i/100ms
            easter_3     2.953M i/100ms
Calculating -------------------------------------
            easter_1      1.825B (± 6.4%) i/s -      8.123B in   4.989183s
            easter_2      1.216B (± 8.7%) i/s -      5.676B in   4.998144s
            easter_3      1.246B (± 3.7%) i/s -      5.732B in   4.990985s

Comparison:
            easter_1: 1825367866.2 i/s
            easter_3: 1245597109.3 i/s - 1.47x  slower
            easter_2: 1216402166.8 i/s - 1.50x  slower
```

**Comment by eregon** [comment]
BTW, the compilation graphs for this are very interesting, all 3 methods are completely folded away, which explains these billions of iterations per second.

Here is `easter_3` after compilation.
It only reads arguments, compare against 2018, and return an Array containing 4 and 1 (see the rightmost grey boxes).

![easter_3](https://user-images.githubusercontent.com/168854/39839948-123c6508-53de-11e8-9f65-c46f04c1ed48.png)

When the loop in the benchmark harness is compiled, the Array no longer needs to be allocated as it's not used, thanks to escape analysis, and we end up with a mostly empty loop just checking a few conditions to call the benchmarking block (notably that it's still the same).

**Comment by eregon** [comment]
This will be fixed for RC2, thank you for the bug report!
