### ISSUE TITLE
Enumerable#sort_by implementation does not match MRI's implementation

### ISSUE THREAD

**Issue by ivoanjo** [oracle/truffleruby#1378]
Hello again ;)

* TruffleRuby version: `truffleruby 1.0.0-rc2, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]`
* Linux version: `Linux maruhime 4.13.0-45-generic #50-Ubuntu SMP Wed May 30 08:23:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* OS version: `Ubuntu 17.10`

I've been on a small quest to try running the test suites for some of the gems I use using TruffleRuby. This example was extracted from a broken test in the [`hamster`](https://github.com/hamstergem/hamster) gem.

It seems like TruffleRuby's `Enumerable#sort_by` implementation does not match MRI's in two ways:

* MRI iterates the `Enumerable` using `each`, whereas TruffleRuby uses `map`
* TruffleRuby assumes that the output of `map` is a regular ruby Array, which it then tries to sort in-place

Testcase:

```
puts RUBY_DESCRIPTION

class Foo
  include Enumerable

  def each(&block)
    block.call(:foo)
  end

  def map(&block)
    [block.call(:bar)]
  end
end

puts Foo.new.sort_by { }

class Bar
  include Enumerable

  def each(&block)
    block.call(:foo)
  end

  def map(&block)
    [block.call(:bar)].freeze
  end
end

puts Bar.new.sort_by { }
```

Output in MRI:

```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
foo
foo
```

Output in TruffleRuby:

```
truffleruby 1.0.0-rc2, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]
bar
testcase.rb:29:in `sort!': can't modify frozen Array (RuntimeError)
        from testcase.rb:29:in `sort_by'
        from testcase.rb:29:in `<main>'
```

I've used the `freeze` to illustrate that the result of `map` cannot be trusted to be sorted in-place, which in the case of the hamster gem happened because their `map` implementation returns an immutable data structure with no `sort!`.

**Comment by aardvark179** [comment]
Thanks for excellent bug report. I've got a fix for this locally and I'm running it through our CI at the moment.

**Comment by aardvark179** [comment]
This has now been merged and should be in the rc4 release.

**Comment by ivoanjo** [comment]
Thank you for the awesome quick fix! :)
