### ISSUE TITLE
Implement ObjectSpace::WeakMap

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1385]
This is notably [used by mustermann](https://github.com/sinatra/mustermann/blob/66100613ee9ba720575be5dfc6d4a02f496e0924/mustermann/lib/mustermann/equality_map.rb#L21-L23).

Even though it has a fallback to use `Hash` instead, that's likely not quite behaving as a weak map.
See https://github.com/oracle/truffleruby/issues/1375#issuecomment-402548699 for the original report showing warnings due to ObjectSpace::WeakMap not being implemented.

**Comment by norswap** [comment]
Implemented by 6ff7b590b66956194ec2a071643fa48e0e65507f
