### ISSUE TITLE
List of unsupported gems with C exstensions

### ISSUE THREAD

**Issue by rsmything** [oracle/truffleruby#1399]
bootsnap
msgpack
brotli
hiredis
mini_racer
oj

all these gems do not compile with truffleruby, even with --use-system-libraries

Gist with Gemfile and Gemfile.lock for test (note: Gemfile.lock created with ruby 2.6)
https://gist.github.com/rsmything/bb81cc89174c35cb707dffe27f75f1b5

**Comment by eregon** [comment]
Thank you for the report.
I started a list of not yet supported C extensions in #1400 to list them together as one issue.
