### ISSUE TITLE
'SYSTEM_DEFAULT' is valid argument for Signal.trap

### ISSUE THREAD

**Issue by fniephaus** [oracle/truffleruby#1411]
I want to run [`rouge`](https://github.com/jneen/rouge) on TruffleRuby, but got the following error when trying to run `rougify` because of [this line](https://github.com/jneen/rouge/blob/7f027b1dc9417c15ee6dce491bd5bab906416e63/bin/rougify#L7):

> bin/rougify:7:in `trap': Unsupported command 'SYSTEM_DEFAULT' (ArgumentError)

Apparently, `'SYSTEM_DEFAULT'` is not correctly supported in TruffleRuby's `Signal.trap`.

**Comment by eregon** [comment]
Thank you for the report.
I have a fix being integrated.

**Comment by fniephaus** [comment]
Could you mention the commit, so I can learn how you fixed it? :)

**Comment by eregon** [comment]
Yes, of course, I just needed to wait for the PR to get merged: https://github.com/oracle/truffleruby/commit/53243c774d7e4d40d62d558abf7196e70f1f7d17
The fix will be in the next release, and I can confirm `rougify test.rb` works.

I forgot to add this fix to the ChangeLog, I will add a commit for that.

**Comment by fniephaus** [comment]
Thanks! And keep up the good work :)

**Comment by eregon** [comment]
ChangeLog entries added in 2a22ba40707e7db10c2dac7af55c161edf1af9bd.
I'll close this issue, it will be in the next release.

**Comment by eregon** [comment]
@fniephaus This is now fixed in the TruffleRuby 1.0.0-rc6 release.
