### ISSUE TITLE
Unable to run bundler master on truffle ruby

### ISSUE THREAD

**Issue by segiddins** [oracle/truffleruby#1413]
Due to the patch that forces Bundler 1.16.x, I am currently unable to use Bundler master, and perhaps more importantly, run the tests against truffleruby.

**Comment by eregon** [comment]
Hello,
Thank you for the report.

Could you describe the commands to reproduce?
I guess cloning bundler master and some rake command?

Of course, it would be great to test Bundler against TruffleRuby :)

**Comment by segiddins** [comment]
Clone Bundler, run `bin/rake spec:deps; bin/rspec`

**Comment by eregon** [comment]
I can reproduce, running `ruby bin/rake spec:deps` in Bundler's repo gives:
```
$ cd bundler
$ git checkout master
$ chruby truffleruby
$ ruby bin/rake spec:deps
Could not find 'automatiek' (~> 0.1.0) among 13 total gem(s)
Checked in 'GEM_PATH=/home/eregon/.gem/truffleruby/2.4.0:/home/eregon/code/truffleruby-ws/truffleruby/lib/ruby/gems/2.4.0', execute `gem env` for more information (Gem::MissingSpecError)
Could not find 'mustache' (= 0.99.6) among 13 total gem(s)
Checked in 'GEM_PATH=/home/eregon/.gem/truffleruby/2.4.0:/home/eregon/code/truffleruby-ws/truffleruby/lib/ruby/gems/2.4.0', execute `gem env` for more information (Gem::MissingSpecError)
Could not find 'rake' (~> 10.0) - did find: [rake-12.0.0]
Checked in 'GEM_PATH=/home/eregon/.gem/truffleruby/2.4.0:/home/eregon/code/truffleruby-ws/truffleruby/lib/ruby/gems/2.4.0', execute `gem env` for more information (Gem::MissingSpecVersionError)
Could not find 'rdiscount' (~> 2.2) among 13 total gem(s)
Checked in 'GEM_PATH=/home/eregon/.gem/truffleruby/2.4.0:/home/eregon/code/truffleruby-ws/truffleruby/lib/ruby/gems/2.4.0', execute `gem env` for more information (Gem::MissingSpecError)
Could not find 'ronn' (~> 0.7.3) among 13 total gem(s)
Checked in 'GEM_PATH=/home/eregon/.gem/truffleruby/2.4.0:/home/eregon/code/truffleruby-ws/truffleruby/lib/ruby/gems/2.4.0', execute `gem env` for more information (Gem::MissingSpecError)
Could not find 'rspec' (~> 3.6) among 13 total gem(s)
Checked in 'GEM_PATH=/home/eregon/.gem/truffleruby/2.4.0:/home/eregon/code/truffleruby-ws/truffleruby/lib/ruby/gems/2.4.0', execute `gem env` for more information (Gem::MissingSpecError)
rake aborted!
unsupported bundler version 2.0.0.dev, please use 1.16.x
/home/eregon/code/bundler/lib/bundler/gem_helper.rb:4:in `<top (required)>'
/home/eregon/code/bundler/lib/bundler/gem_tasks.rb:6:in `<top (required)>'
/home/eregon/code/bundler/task/release.rake:3:in `<top (required)>'
/home/eregon/code/bundler/Rakefile:390:in `load'
/home/eregon/code/bundler/Rakefile:390:in `load'
/home/eregon/code/bundler/Rakefile:390:in `load'
/home/eregon/code/bundler/Rakefile:390:in `each'
/home/eregon/code/bundler/Rakefile:390:in `<top (required)>'
```

One workaround is disabling patching with the option `-Xpatching=false`:
```
ruby -Xpatching=false bin/rake spec:deps
TRUFFLERUBYOPT="-Xpatching=false" bin/rspec
```
Unfortunately, this currently means disabling all patches and not just the ones for Bundler.
So, for instance, the patch for RSpec is not applied and I get `cannot load such file -- ripper (LoadError)`.

We plan to upstream these patches, but we might need to keep some of them to keep supporting already-released versions of e.g., `rspec`.

Regarding the [version check](https://github.com/oracle/truffleruby/blob/c322c2112014ee30b6935678dd32ee0d4add08d4/lib/patches/bundler.rb), we could make it conditional (based on an ENV var) or accept more versions, but then we'd need to ensure [the patches](https://github.com/oracle/truffleruby/tree/master/lib/patches/bundler) apply correctly to both Bundler 1.16.x and Bundler 2.x.

**Comment by segiddins** [comment]
Iirc most of the patches were adding truffleruby to the list of platforms Bundler supports (which in turn we do by monkeypatching RubyGems classes, isn’t ruby great). If we were to add that into Bundler master, could we limit the patching to only apply to 1.16.x versions, while allowing newer versions to be used unpatched?

**Comment by eregon** [comment]
I think the safest would be to make these patches conditional and detect themselves if they are needed.
I'll give that a try. Then I'd like to remove all Bundler-related patches and integrate that upstream, both in Bundler 1.16.x and 2.x.

**Comment by eregon** [comment]
I tried to make the patches conditional but it seems non-trivial for some of them, where only the logic inside a method changes.

So now I'm thinking to integrate the patches upstream, remove the version check or also allow Bundler 2 and then once Bundler 1.16.x is released, drop the patches (except maybe the version check).

**Comment by eregon** [comment]
I relaxed the version check in 0ffdaaa1643ab55b561eb14cc166323b3d5c7b2f.
This will be in the next release, so I will close this issue.
Thanks for the report!
