### ISSUE TITLE
Geom2D testsuite fails because of compatibility with only Ruby 2.4

### ISSUE THREAD

**Issue by gettalong** [oracle/truffleruby#1416]
I ran TruffleRuby (`truffleruby 1.0.0-rc6, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]`) installed via RVM against the [geom2d](https://github.com/gettalong/geom2d) testsuite (cloning the repo and then `rake test` will run the testsuite), resulting in the following error:

~~~
/home/thomas/exthdsync/personal/repos/geom2d/lib/geom2d/utils.rb:19:in `Utils': private method `attr_accessor' called for Class (NoMethodError)
~~~

TruffleRuby is compatible with Ruby 2.4.4, this is a feature of Ruby 2.5 (see https://bugs.ruby-lang.org/issues/14132) - will the final TruffleRuby 1.0.0 release be compatible with Ruby 2.5.?

**Comment by chrisseaton** [comment]
Yes we're aiming at 2.5 compatibility soon, but we're adding backwards-compatible 2.5 features as we find we need them.

This sounds compatible so we will take a look at implementing it.

Thanks very much for the report.

**Comment by chrisseaton** [comment]
This seems to work fine on latest TruffleRuby. Sorry about how long that took! This looks like a nice gem - have you thought about writing some benchmarks with it?

**Comment by gettalong** [comment]
Thanks! And thanks for fixing this!

As for a benchmark: No, not really. The library is used by HexaPDF and it has some benchmarks, though none yet that use the part where Geom2D is used. However, I will add one to HexaPDF once the document composition part is more in place.
