### ISSUE TITLE
mechanize: cannot load such file -- kconv (LoadError)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1439]
When I try to require `mechanize` gem (web scrapping library) on `truffleruby-1.0.0.rc8`, this error is issued. `kconv` (Kanji Converter) is standard Ruby library.

To reproduce:
```
gem install mechanize
irb
irb(main):001:0> require 'mechanize'
```

**Comment by eregon** [comment]
Interesting, I didn't even know `kconv` and the `nkf` extension existed in standard library.
https://github.com/ruby/ruby/blob/trunk/ext/nkf/lib/kconv.rb

I'm not sure why mechanize `require 'kconv'`, it doesn't seem used:
https://github.com/sparklemotion/mechanize/blob/b959fb10d2e5943e69c268993481a1b73c80717e/lib/mechanize/http/agent.rb

We should likely import this extension from MRI and build it, but maybe a faster workaround would be to remove the `require` in mechanize if it's indeed not used.

**Comment by deepj** [comment]
@eregon I've created a PR removing it but I doubt it will be merged in a near future.

**Comment by eregon** [comment]
@deepj Thank you for creating the PR.
I see, looks like the only reasonable way to solve this is adding kconv in TruffleRuby, I'll take a look at that.

**Comment by eregon** [comment]
I imported the `nkf` C extension and `kconv` stdlib in https://github.com/oracle/truffleruby/commit/fb970c4711675321f655763991795affb198bf7e.
Now, `require 'mechanize'` succeeds.
This will be in the next release.
