### ISSUE TITLE
Official Docker images of Truffleruby

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1449]
Hello,
I believe for faster adaptation of Truffleruby is offering official Docker images of Truffleruby crucial. They would be similar to [Ruby Docker images](https://github.com/docker-library/ruby). Including Alpine versions of the images. I haven't tried Truffleruby under Alpine Linux yet. I have some doubts `truffleruby` and `muslc` aren't friends.

Anyway, it'd be nice to have in a project `Dockerfile`

```dockerfile
FROM truffleruby:1.0

RUN bundle install
...

CMD rackup -o 0.0.0.0
```

😺

**Comment by chrisseaton** [comment]
Docker images are here

https://hub.docker.com/r/oracle/graalvm-ce/

It's based on Oracle Linux, because some of our dependencies, especially for building C extensions, are a bit complicated. What does the official Ruby Docker imagine do for development tools?

**Comment by chrisseaton** [comment]
> BTW: the base Docker image of GraalVM is extremely huge (557 MB). Ruby Alpine based Docker image has only 35 MB.

Yes, it does include a lot of things, that's true. It may be worth investigating a pure Ruby Docker image as well.

**Comment by deepj** [comment]
@chrisseaton And what I wanted to say also. I'd like to just replace `FROM ruby:2.5.3` for `FROM truffleruby:1.0.0` in my `Dockerfile`. And the whole would be kept in as-is. That would be wonderful and it helps to expand truffleruby. With Oracle Linux is not used much by other Ruby folks. It's better to support ecosystems (Debian/Alpine) which are familiar to more Ruby folks. That's my main point I guess.

**Comment by eregon** [comment]
This is obviously not an official image, but here is minimal TruffleRuby Docker image one can build, based on the [release binaries](https://github.com/oracle/truffleruby/releases). It's 148MB uncompressed as reported by `docker images` (`ruby:2.5.3-slim` is 178 MB for comparison).
```dockerfile
FROM oraclelinux:7-slim
ENV LANG=en_US.UTF-8
RUN yum install -y zlib-devel openssl-devel && rm -rf /var/cache/yum
ADD truffleruby-1.0.0-rc9-linux-amd64.tar.gz /test
ENV PATH=/test/truffleruby-1.0.0-rc9-linux-amd64/bin:$PATH
RUN ruby --version
CMD bash
```

It doesn't contain dependencies for compiling C extensions though, so trying to install any C extension will fail. It's also unstested.

We have a [tool](https://github.com/oracle/truffleruby/blob/master/doc/contributor/docker.md) for generating Dockerfiles with all necessary dependencies for testing TruffleRuby, using either `ubuntu`, `fedora` or `oraclelinux` as base image, that can be used like this:
```
tool/jt.rb docker print --standalone path/to/truffleruby-1.0.0-rc9-linux-amd64.tar.gz
```
We run those images for testing releases, so these images should work reliably. They are obviously larger, notably because they include LLVM, and they do not try minimize size.

Using the release binary on alpine doesn't work (`/bin/sh: ./truffleruby: not found` even though it does), and that would likely be a significant effort to compile TruffleRuby and all dependencies on alpine.

**Comment by deepj** [comment]
@eregon It'd be really worth to support Alpine Linux. There is @jirutka (rubyist and one of the largest package contributor to Alpine). He could help in this if he would interest in that.

**Comment by deepj** [comment]
BTW: JRuby has an own official Alpine Docker version as well

https://hub.docker.com/_/jruby/

^^ @chrisseaton

**Comment by nirvdrum** [comment]
FYI, "official" is a little strange here. The JRuby Dockerfiles were created by a (former?) Docker employee. The JRuby team does not and never have maintained their Docker images available on Docker Hub, to the best of my knowledge.

**Comment by deepj** [comment]
@nirvdrum thanks for clarification about JRuby. I believed they're behind it.

**Comment by ms-ati** [comment]
Is it possible, as an intermediate step, to publish the generated Dockerfiles somewhere, so that they can be seen and used without having to install the dev environment and run `jt`?

**Comment by chrisseaton** [comment]
(Can't answer that, but do you want me to generate a `Dockerfil`e for you now since I already have the environment set up?)

**Comment by jodosha** [comment]
@chrisseaton Please do. It would be helpful for me too. Thanks a lot!

**Comment by chrisseaton** [comment]
```
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y locales
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
RUN apt-get install -y curl
RUN apt-get install -y libz-dev
RUN apt-get install -y libssl-dev
RUN apt-get install -y make
WORKDIR /test
RUN useradd -ms /bin/bash test
RUN chown test /test
USER test
RUN curl -OL https://github.com/oracle/graal/releases/download/vm-19.2.1.0/graalvm-ce-19.2.1.0-linux-amd64.tar.gz
RUN mkdir /test/graalvm
RUN tar -zxf graalvm-ce-19.2.1.0-linux-amd64.tar.gz -C /test/graalvm --strip-components=1
RUN /test/graalvm/bin/gu install org.graalvm.ruby | tee install.log
RUN grep 'The Ruby openssl C extension needs to be recompiled on your system to work with the installed libssl' install.log
RUN grep '/jre/languages/ruby/lib/truffle/post_install_hook.sh' install.log
RUN /test/graalvm/jre/languages/ruby/lib/truffle/post_install_hook.sh
ENV PATH=/test/graalvm/bin:$PATH
RUN ruby  --version
RUN ruby --jvm --version
RUN ruby --native --version
CMD bash
```

Feel free to ask any questions.

**Comment by nirvdrum** [comment]
While not quite official images of just TruffleRuby, Oracle does have [an official GraalVM CE image](https://github.com/oracle/docker-images/tree/master/GraalVM/CE). I haven't tried, but you should be able to use that as a base image and add the step to install TruffleRuby via GraalVM's `gu` utility.

**Comment by eregon** [comment]
Quick update: we're looking into this but it takes some time to get official Docker images approved.

Here is a Dockerfile to get started in the meanwhile:
```Dockerfile
FROM oraclelinux:7-slim

ARG GRAALVM_VERSION=20.1.0
ARG TRUFFLERUBY_PKG=https://github.com/oracle/truffleruby/releases/download/vm-$GRAALVM_VERSION/truffleruby-$GRAALVM_VERSION-linux-amd64.tar.gz

RUN yum update -y oraclelinux-release-el7 \
    && yum install -y curl tar gzip zlib openssl-devel gcc make \
    && rm -rf /var/cache/yum

RUN curl --fail --location --retry 3 ${TRUFFLERUBY_PKG} | tar xz -C /opt

ENV LANG=en_US.UTF-8 \
    PATH=/opt/truffleruby-$GRAALVM_VERSION-linux-amd64/bin:$PATH

RUN echo "gem: --no-document" > ~/.gemrc
RUN /opt/truffleruby-$GRAALVM_VERSION-linux-amd64/lib/truffle/post_install_hook.sh

RUN ruby --version
```

See https://github.com/oracle/truffleruby/blob/master/tool/docker-configs.yaml and https://github.com/oracle/truffleruby/blob/master/README.md#dependencies for the dependencies needed if you want to use another distribution.

It's also possible to use a multi-stage build in order to have a smaller image at the end (which is then no longer able to install gems, so they need to be installed in the first stage):
```Dockerfile
# Builder image which needs dev tools to run post_install_hook.sh
FROM oraclelinux:7-slim AS builder

ARG GRAALVM_VERSION=20.1.0

RUN yum update -y oraclelinux-release-el7 \
    && yum install -y zlib openssl-devel gcc make \
    && rm -rf /var/cache/yum

ADD truffleruby-$GRAALVM_VERSION-linux-amd64.tar.gz /opt

ENV LANG=en_US.UTF-8 \
    PATH=/opt/truffleruby-$GRAALVM_VERSION-linux-amd64/bin:$PATH

RUN /opt/truffleruby-$GRAALVM_VERSION-linux-amd64/lib/truffle/post_install_hook.sh

# TODO: add commands to install gems here

# Resulting slim image without dev tools
FROM oraclelinux:7-slim

ARG GRAALVM_VERSION=20.1.0

RUN yum update -y oraclelinux-release-el7 \
    && yum install -y zlib openssl \
    && rm -rf /var/cache/yum

COPY --from=builder /opt/truffleruby-$GRAALVM_VERSION-linux-amd64 /opt/truffleruby-$GRAALVM_VERSION-linux-amd64

ENV LANG=en_US.UTF-8 \
    PATH=/opt/truffleruby-$GRAALVM_VERSION-linux-amd64/bin:$PATH

RUN echo "gem: --no-document" > ~/.gemrc

RUN ruby --version
```

**Comment by flavorjones** [comment]
If it's helpful for anyone, I've published some Dockerfiles and have set up Docker Hub to build images:

- Docker Hub images: https://hub.docker.com/repository/docker/flavorjones/truffleruby/general
- Dockerfiles: https://github.com/flavorjones/docker-truffleruby

Possibly of note: This configuration is also publishing **nightlies** every 24 hours or so.

**Comment by HoneyryderChuck** [comment]
any news on getting official truffleruby images? I've been using what @flavorjones provided, but these seem not to be coordinated with truffleruby's release schedule.

**Comment by eregon** [comment]
@ezzarghili Any ETA for official TruffleRuby Docker images?
Note those images would be based on `oraclelinux`, like the [oracle/graalvm-ce](https://hub.docker.com/r/oracle/graalvm-ce) image.

I'd suggest filing an issue to https://github.com/flavorjones/docker-truffleruby and discuss there how to keep it up-to-date. Maybe it can be mostly automated?

**Comment by flavorjones** [comment]
My images are being generated by dockerhub now! Should be available within the hour.

**Comment by eregon** [comment]
TruffleRuby now has official Docker images for releases at https://github.com/orgs/graalvm/packages/container/package/truffleruby. These images are based on `oraclelinux:7-slim` and `oraclelinux:8-slim`.
They should be relatively small, and there is a `-slim` variant of the images where only the strict minimum is included (and then you need to use a multi-stage Dockerfile to install C extensions first like in https://github.com/oracle/truffleruby/issues/1449#issuecomment-639006857).

For dev builds/nightlies or for users who prefer a Debian-based image, I can recommend https://github.com/flavorjones/docker-truffleruby which was already mentioned above.

**Comment by ylluminate** [comment]
@flavorjones any chance you could add Apple Silicon ARM64 images to your builds?

**Comment by flavorjones** [comment]
@ylluminate I'd love a PR for this if you're interested in doing the work! See https://github.com/flavorjones/truffleruby/tree/master/tool/dockerfiles for details.

**Comment by ylluminate** [comment]
Thank you @flavorjones - unfortunately I won't be able to do this anytime soon due to some demands I have presently, but thanks for the link! Hopefully someone else will pick this up from our conversation and do it sooner than later.

**Comment by eregon** [comment]
@ylluminate 
> @flavorjones any chance you could add Apple Silicon ARM64 images to your builds?

What do you mean? AFAIK one can't have a Docker image with macOS/darwin inside, can they?
I guess you mean linux-aarch64 docker images.
We do have those for releases, e.g., https://github.com/graalvm/container/pkgs/container/truffleruby-community/103903583?tag=23.0.0-debian

(We can't have those for nightly builds because GitHub Actions Runners hosted by GitHub are not available for aarch64.)
