### ISSUE TITLE
byebug: `rb_tr_error': rb_tracepoint_new not implemented

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1450]
Hello,
I'm getting with truffleruby 1.0.0-rc8 on macOS 10.14 the following issue when I'm trying to use `byebug` (10.0.2). Since `byebug` is a recommended tool for debugging in Rails =>
https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-byebug-gem

It'd be worth to take a look at Tracepoint API support in C gems by Truffleruby.

How to reproduce it:

```ruby
require 'byebug'

byebug

puts 'Hello byebug'
```

The error:

```
/Users/graal/slave/e/truffleruby/src/main/c/cext/ruby.c:in `rb_tr_error': rb_tracepoint_new not implemented (RuntimeError)
	from /Users/graal/slave/e/truffleruby/src/main/c/cext/ruby.c:in `rb_tracepoint_new'
	from ~/.gem/truffleruby/2.4.4/gems/byebug-10.0.2/ext/byebug/byebug.c:501:in `register_tracepoints'
	from ~/.gem/truffleruby/2.4.4/gems/byebug-10.0.2/ext/byebug/byebug.c:711:in `Start'
	from ~/.rubies/truffleruby-1.0.0-rc8/lib/truffle/truffle/cext.rb:221:in `execute_without_conversion'
	from ~/.rubies/truffleruby-1.0.0-rc8/lib/truffle/truffle/cext.rb:221:in `execute_with_mutex'
	from ~/.rubies/truffleruby-1.0.0-rc8/lib/truffle/truffle/cext_ruby.rb:36:in `start'
	from ~/.gem/truffleruby/2.4.4/gems/byebug-10.0.2/lib/byebug/attacher.rb:16:in `attach'
	from ~/.gem/truffleruby/2.4.4/gems/byebug-10.0.2/lib/byebug/attacher.rb:38:in `byebug'
```

**Comment by chrisseaton** [comment]
We do support trace points from Ruby, even in optimised code, so we should be able to provide this from C as well. Thanks for the issue.

**Comment by deepj** [comment]
@chrisseaton I guess it would be interesting to have working `byebug` since it's a recommended tool for debugging in Rails. But there is a question how it will work under Truffleruby. But I have some doubts when I look at https://github.com/deivid-rodriguez/byebug/tree/master/ext/byebug

**Comment by eregon** [comment]
As reported in #1528 by @deepj, this also happens for the `web-console` gem (one of default Rails dependencies):
> `web-console` uses the `bindex` gem (accessing exception bindings) which uses `rb_tracepoint_new`. The gem doesn't support TruffleRuby itself but it's easy to add the support.

**Comment by deepj** [comment]
@chrisseaton @eregon  I've noticed of your last work on TracePoint support. If it's not too much work, is it possible to provide some support TracePoint API to C extensions?

**Comment by chrisseaton** [comment]
In order to support `byebug`? Do you mean code like this? https://github.com/deivid-rodriguez/byebug/blob/af25ece0b5a43fd857d19a45206653d0c402cd10/ext/byebug/byebug.c#L78

**Comment by deepj** [comment]
@chrisseaton yes, I'd like to see byebug and to try on TruffleRuby

**Comment by chrisseaton** [comment]
Ok I'll mark this as priority as well, but I don't think it's as easily achievable as the others. We should try to fix this set now and then ask for more if we have time. Let us know if you want to swap one priority issue out for another.

**Comment by chrisseaton** [comment]
Sorry I'm going to have to de-priortise this. I've taken a look and it's not realistic to get it done soon. It uses a ton of C APIs that we don't have yet, and the underlying `TracePoint` implementation also is not totally complete.

TruffleRuby includes it's own Chrome-based debugger, and we'd recommend that for now.

**Comment by deepj** [comment]
`scout_apm` depends on this missing C-API

**Comment by bjfish** [comment]
`rb_tracepoint_new` is now implemented at: https://github.com/oracle/truffleruby/commit/20fe8661961ddcd56f5c9fc1d516429459bd8e81
