### ISSUE TITLE
ObjectSpace.trace_object_allocations appears to cause infinite recursion

### ISSUE THREAD

**Issue by ioquatix** [oracle/truffleruby#1456]
I've worked around the issue here, but if you try running v1.11.0 you can reproduce the issue.

https://github.com/socketry/async-rspec/issues/5

There are more details in that linked linked issue, including a backtrace.

**Comment by eregon** [comment]
@ioquatix  I fixed this in 6f0e4136eb6e4cc8282bc3de1e07f272c06ad10f, thank you for the bug report.

Note that enabling `ObjectSpace.trace_object_allocations` might be very expensive both performance and memory-wise, as [documented](https://docs.ruby-lang.org/en/2.6.0/ObjectSpace.html#method-c-trace_object_allocations), so I would be careful about enabling it for running specs by default.
