### ISSUE TITLE
Socket#setsockopt broken with nil or false value.

### ISSUE THREAD

**Issue by ioquatix** [oracle/truffleruby#1460]
If `optval` is false, it would fail to match correctly. Proposed fix:

```
  def setsockopt(level_or_option, optname = nil, optval = nil)
    if level_or_option and optname
```

**Comment by ioquatix** [comment]
I worked around this issue by ensuring I only call this function with `optval = 1`.

**Comment by ioquatix** [comment]
The Ruby documentation specifically allows `true`/`false` just FYI.

**Comment by ioquatix** [comment]
@eregon has this been fixed yet?

**Comment by eregon** [comment]
I'm not sure, I'll take a look.

**Comment by eregon** [comment]
We already have a failing spec for this, great:
`BasicSocket#setsockopt sets the socket option Socket::SO_OOBINLINE`
https://github.com/oracle/truffleruby/blob/5defdc8fe1ec25ed5ba0893c8b5e611df3ec7b41/spec/ruby/library/socket/basicsocket/setsockopt_spec.rb#L56
