### ISSUE TITLE
dry-system: Pathname is not loaded but under MRI yes in their specs

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1463]
I used Truffleruby 1.0.0-rc9

To reproduce:

```
git clone https://github.com/dry-rb/dry-system.git
cd dry-system
bundle
rspec
```

Error:

```
NoMethodError: undefined method `Pathname' for main:Object
```

**Comment by chrisseaton** [comment]
Don't you have to 'require `pathname`' first?

**Comment by deepj** [comment]
@chrisseaton Sorry, my misunderstanding (here is midnight). I just met with error `NoMethodError: undefined method `Pathname' for main:Object` when I tried to run `dry-system` specs under Truffleruby. And it failed on the error here https://github.com/dry-rb/dry-system/blob/v0.10.1/spec/spec_helper.rb#L12.

It seems `rspec` requires `Pathname` somewhere. And under Truffleruby it's not available in `spec/spec_hepler.rb` of `dry-system` specs

**Comment by eregon** [comment]
@deepj It seems a bug of `dry-system`, there should be a `require 'pathname'` before the call to `Pathname()`. Could you file a bug there or a PR?

The reason it works on MRI seems to be https://github.com/dry-rb/dry-system/blob/v0.10.1/spec/spec_helper.rb#L3-L6 which likely requires `pathname` indirectly.
Bundler seems to play a role too, as the Gemfile has `gem 'codeclimate-test-reporter', platforms: :mri` and I guess that will require that gem eagerly with `bundle exec`.

Removing those lines, and not using `bundle exec` but just `rake spec` gives on MRI:
```
An error occurred while loading ./spec/spec_helper.
Failure/Error: SPEC_ROOT = Pathname(__FILE__).dirname

NoMethodError:
  undefined method `Pathname' for main:Object
```

**Comment by deepj** [comment]
@eregon thx, I'll make PR to `dry-system` fixing that issue. Thanks for clarifying.
