### ISSUE TITLE
Getting java integer as return from Polyglot eval

### ISSUE THREAD

**Issue by rbotafogo** [oracle/truffleruby#1464]
Doing:

```ruby
p Polyglot.eval("R", "dev.cur()")
```

```
TypeError:
  Truffle doesn't have a case for the org.truffleruby.interop.InteropNodesFactory$HasSizeNodeFactory$HasSizeNodeGen node with values of type  java.lang.Integer=1
'# ./lib/R_interface/rdevices.rb:85:in `size?
'# ./lib/R_interface/rdevices.rb:85:in `inspect_foreign'
'# ./lib/R_interface/rdevices.rb:85:in `special_form'
'# ./lib/R_interface/rdevices.rb:85:in `p'
'# ./lib/R_interface/rdevices.rb:85:in `each'
'# ./lib/R_interface/rdevices.rb:85:in `p'
'# ./lib/R_interface/rdevices.rb:85:in `open'
'# ./specs/tmp.rb:27:in `<top (required)>'
```

**Comment by chrisseaton** [comment]
This should be easy to fix. Thanks for the report.

**Comment by rbotafogo** [comment]
Hi Chris,

Any idea when this will be fixed?

Thanks

**Comment by chrisseaton** [comment]
We're back from holiday now so we'll take a look.

**Comment by eregon** [comment]
This seems very similar to what I mentioned in https://github.com/oracle/truffleruby/issues/1534#issuecomment-454198892.
If we unbox, it should be printed as a Ruby Integer.

This works though:
```ruby
Polyglot.eval("R", "print(dev.cur())")
# null device 
#           1 
puts Polyglot.eval("R", "dev.cur()")
# 1
```

**Comment by ssnickolay** [comment]
Test with [GraalVM CE 20.2.0-dev-20200718_0205](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/20.2.0-dev-20200718_0205):
```ruby
root@28fe7ecdabff:/app# irb --polyglot
irb(main):001:0> p Polyglot.eval("R", "dev.cur()")
#<Foreign Integer:0x464cb377>
=> #<Foreign Integer:0x464cb377>
irb(main):002:0> puts Polyglot.eval("R", "dev.cur()")
1
=> nil
```

Looks like the issue could be closed //cc @eregon

**Comment by eregon** [comment]
This looks fine enough.
I might expect just `1` for the `p ...` variant but here it's not just a simple integer, it's a tiny 1x1 data frame I guess, so that seems reasonable.
