### ISSUE TITLE
ArgumentError exception returns a different default message than MRI but like JRuby

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1467]
I don't know the origin reason why the default message of `ArgumentError` exception is a slightly different in JRuby beside to MRI. 

**MRI**:  `wrong number of arguments (given 1, expected 0)`
**JRuby**: `wrong number of arguments (1 for 0)`

Due to this, one of `hanami-utils` specs fails on this. See: https://github.com/hanami/utils/blob/master/spec/unit/hanami/utils/string_spec.rb#L59

They have a special check for JRuby though.

My opinion is, if Truffleruby wants to be compatible to MRI as possible, the message from MRI would be used instead of JRuby's one.

Any thoughts @eregon @chrisseaton

**Comment by chrisseaton** [comment]
Hmmm this is going to be a bit of a struggle. We don't have any testing of error strings, and I think neither does JRuby nor Rubinius. You won't find much testing of error strings in the Ruby spec suite. We thought that'd be ok, and we know they differ in many cases, but if we're finding that doesn't work in practice then it's a problem.

I think what we'll do is fix differences we find that matter when they turn up, like this one, and keep thinking about what to do in general.

**Comment by chrisseaton** [comment]
This is the test case you're specifically interested in, right?

```ruby
def foo
end

foo(14)
```

**Comment by deepj** [comment]
@chrisseaton yes

**Comment by nirvdrum** [comment]
To provide a bit more context, MRI used to provide the message `wrong number of arguments (1 for 0)` up until 2.3. JRuby, like TruffleRuby, probably just missed that the message format had changed. Hanami would be better off with a Ruby version check, rather than trying to handle JRuby specifically.

**Comment by eregon** [comment]
> Hanami would be better off with a Ruby version check, rather than trying to handle JRuby specifically.

Would be better with a Regexp to match the message like:
```ruby
expect {
  Hanami::Utils::String.transform(input, -> { "blossom" })
}.to raise_error(ArgumentError, /wrong number of arguments/)
```

Checking `RUBY_ENGINE` or Ruby versions is directly affecting how portable is a library.

**Comment by eregon** [comment]
But more generally, it seems a case of specifying too much here, I would suggest Hanami specs to specify the error class, but not the message, which is an implementation detail.

Anyway, I agree it's worth fixing here as the new MRI message is clear and in general there is rarely a good reason to differ.

**Comment by chrisseaton** [comment]
This is fixed and will be in the next release.
