### ISSUE TITLE
dalli:  Cannot convert LLVMTypedForeignObject+0x0 to LLVMNativePointer (IllegalStateException)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1475]
When I wanted to try to run `activesupport` tests I got this exception comes from `dalli` gem

To reproduce:

```ruby
require 'dalli'
```

Error:
```
RuntimeError: Cannot convert LLVMTypedForeignObject+0x0 to LLVMNativePointer (IllegalStateException)
	from java.lang.Throwable.<init>(Throwable.java:287)
	from java.lang.Exception.<init>(Exception.java:84)
	from java.lang.RuntimeException.<init>(RuntimeException.java:80)
	from java.lang.IllegalStateException.<init>(IllegalStateException.java:75)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode$LLVMObjectToNativeNode.transitionToNative(LLVMToNativeNode.java:117)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen$LLVMObjectToNativeNodeGen.executeAndSpecialize(LLVMToNativeNodeGen.java:301)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen$LLVMObjectToNativeNodeGen.executeWithTarget(LLVMToNativeNodeGen.java:201)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode.doOther(LLVMToNativeNode.java:78)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen.executeAndSpecialize(LLVMToNativeNodeGen.java:129)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen.executeWithTarget(LLVMToNativeNodeGen.java:50)
Caused by:
Message not supported: TO_NATIVE (UnsupportedMessageException)
	from java.lang.Throwable.<init>(Throwable.java:265)
	from java.lang.Exception.<init>(Exception.java:66)
	from com.oracle.truffle.api.interop.InteropException.<init>(InteropException.java:52)
	from com.oracle.truffle.api.interop.UnsupportedMessageException.<init>(UnsupportedMessageException.java:57)
	from com.oracle.truffle.api.interop.UnsupportedMessageException.raise(UnsupportedMessageException.java:84)
	from org.truffleruby.interop.RubyMessageResolution$ForeignToNativeNode.access(RubyMessageResolution.java:190)
	from org.truffleruby.interop.RubyMessageResolutionForeign$ForeignToNativeSubNode.accessWithTarget(RubyMessageResolutionForeign.java:503)
	from org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignToNativeSubNodeGen.executeAndSpecialize(RubyMessageResolutionForeignFactory.java:602)
	from org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignToNativeSubNodeGen.executeWithTarget(RubyMessageResolutionForeignFactory.java:588)
	from org.truffleruby.interop.RubyMessageResolutionForeign$ForeignToNativeSubNode$TO_NATIVERootNode.execute(RubyMessageResolutionForeign.java:520)
Translated to internal error
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ~/.gem/truffleruby/2.4.4/gems/kgio-2.11.2/lib/kgio.rb:21:in `<top (required)>'
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/mri/rubygems/core_ext/kernel_require.rb:133:in `gem_original_require'
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/mri/rubygems/core_ext/kernel_require.rb:133:in `require'
	from ~/.gem/truffleruby/2.4.4/gems/dalli-2.7.8/lib/dalli/socket.rb:14:in `<top (required)>'
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ~/.gem/truffleruby/2.4.4/gems/dalli-2.7.8/lib/dalli.rb:6:in `<top (required)>'
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/mri/rubygems/core_ext/kernel_require.rb:133:in `gem_original_require'
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/mri/rubygems/core_ext/kernel_require.rb:133:in `require'
	from (irb):1
	from ~/.rubies/truffleruby-1.0.0-rc9/bin/irb:29:in `<main>'
```

**Comment by eregon** [comment]
Looks like it's due to an issue in the C extension support when using `kgio`:
```
	from ~/.gem/truffleruby/2.4.4/gems/kgio-2.11.2/lib/kgio.rb:21:in `<top (required)>'
```
Does `dalli` depend on `kgio` somehow?

**Comment by eregon** [comment]
BTW this backtrace makes me think we should maybe hide `lib/mri/rubygems/core_ext/kernel_require.rb` from backtraces by default as they are very noisy.

**Comment by deepj** [comment]
@eregon It seems yes. 

https://github.com/petergoldstein/dalli/blob/master/README.md

Unfortunately, `kgio` is obsolete for Ruby 2.3 and later. See https://github.com/petergoldstein/dalli/pull/689
It seems `kgio` is not installed as a direct dependency of `dalli`. It has been installed by something else. But, if it's avalable in gems, so it's loaded.

**Comment by deepj** [comment]
In my case, it was installed together with `unicorn` gem.

**Comment by eregon** [comment]
Mmh, that's unfortunate.
One workaround could be to have `dalli` try requiring `kgio` only if Ruby < 2.3, because otherwise it's unnecessarily loaded, even on MRI (larger footprint, more chances for bad interactions or bugs).

BTW, shouldn't Bundler prevent requiring a gem not registered as a dependency if using `bundle exec` or `require 'bundle/setup'`? I thought it would. But in the example above bundler is not used.

Of course, it'd be nice to just have `kgio` work. OTOH, `fork` is not supported so I guess there is not so much value to support much of `unicorn` as long as `fork` is not supported.

**Comment by eregon** [comment]
> BTW, shouldn't Bundler prevent requiring a gem not registered as a dependency if using `bundle exec` or `require 'bundle/setup'`? I thought it would. But in the example above bundler is not used.

Indeed, and so this works:
```
$ bundle exec ruby -rdalli -e0
```
while
```
$ ruby -rdalli -e0
```
does not as in the report, assuming `kgio` is installed.

**Comment by deepj** [comment]
@eregon `unicorn` was installed by something what I don't remember what was it. But I haven't tried `unicorn` myself at all.

Unfortunately, `activesupport` tests don't use Bundler

https://github.com/rails/rails/blob/master/activesupport/Rakefile

After running `activesupport` tests, only two tests failed due to missing `Thread#report_on_exception=`. I'm going to create a new issue.

**Comment by deepj** [comment]
@eregon I guess this can be closed. The original issue comes from `kgio`. `dalli` just "works" on TruffleRuby even some `dalli` tests just fail.

**Comment by eregon** [comment]
@deepj Thanks, good news :)
I will close this issue then.
If you have the logs of `dalli` tests failing, feel free to open a new issue with it.
