### ISSUE TITLE
Thread.report_on_exception= is not supported

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1476]
`Thread.report_on_exception=` is available since 2.4. See https://ruby-doc.org/core-2.4.0/Thread.html#method-i-report_on_exception-3D

This is used for instance in `activesupport` tests https://github.com/rails/rails/blob/master/activesupport/test/cache/behaviors/connection_pool_behavior.rb#L30

To reproduce

```
Thread.report_on_exception = true
```

Error:

```
NoMethodError: undefined method `report_on_exception=' for Thread:Class
	from (irb):1
	from ~/.rubies/truffleruby-1.0.0-rc9/bin/irb:29:in `<main>'
```

**Comment by eregon** [comment]
I plan to work on this one, seems like I ought to do it with https://eregon.me/blog/2017/12/28/thread-report-on-exception.html :)

**Comment by eregon** [comment]
I implemented Thread.report_on_exception and related in d08c70c54e0294ac2b49ed135a43fdd81999444e. All specs pass now.
