### ISSUE TITLE
Cannot push a gem

### ISSUE THREAD

**Issue by rbotafogo** [oracle/truffleruby#1477]
Trying to push a gem is giving me the following error:

Pushing gem to https://rubygems.org...
ERROR:  While executing gem ... (RuntimeError)
    rb_io_wait_writable wait case not implemented

**Comment by bjfish** [comment]
I was able to successfully build and push a gem by following all the steps [here](https://guides.rubygems.org/make-your-own-gem/) using the current version: https://github.com/oracle/truffleruby/commit/950d2afec730b34460dfd6a46e9b9aea9e1bd694.
