### ISSUE TITLE
Implement non-ℕ line numbers

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1482]
I'm not sure how to describe it exactly, but this test fails due to it:

https://github.com/rack/rack/blob/master/test/spec_builder.rb#L257

**config.ru**

```ruby
# frozen_string_literal: true

run lambda{ |env| [200, { 'Content-Type' => 'text/plain' }, [__LINE__.to_s]] }
```

To reproduce:

```ruby
require 'rack'

app, _ = Rack::Builder.parse_file('./config.ru')

puts Rack::MockRequest.new(app).get("/").body
```

It returns **3** under MRI (correct), but it returns **4** under Truffleruby.

**Comment by chrisseaton** [comment]
Here's the documentation that explains the current limitation, by the way.

https://github.com/oracle/truffleruby/blob/master/doc/user/compatibility.md#line-numbers-other-than-1-work-differently

**Comment by chrisseaton** [comment]
We will probably implement this by storing a Ruby-specific offset in root nodes, that we will apply when creating error messages. We'll still have a limitation in how debuggers interpret this.

**Comment by eregon** [comment]
This also happens in AsciiDoctor's CI (#1742)
https://travis-ci.org/asciidoctor/asciidoctor/jobs/576533763:
```
[ruby] WARNING: negative line number (__TEMPLATE__):-8 not supported in #class/module_eval - will be reported as starting at 1
...
```
We should try to figure what uses negative line numbers and how to make this work, so there is no need to warn.

**Comment by deepj** [comment]
Closed due to I'm not welcome anymore in Ruby community

**Comment by bjfish** [comment]
This is now implemented at: https://github.com/oracle/truffleruby/commit/d7d99fc15440d25a6b5bd5d457e94432c8c39873.
