### ISSUE TITLE
Nightly builds of TruffleRuby

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1483]
This is based on @eregon's request https://github.com/oracle/truffleruby/issues/1440#issuecomment-441390956

Since it's not so trivial to build GraalVM/TruffleRuby, it would be nice to offer own compiled versions as nightly builds. Nightly builds would help you to get faster feedback from developers. `JRuby` or `MRI` has own nightly builds (or their building is trivial).

This would help integrate it into `RVM`/`ruby-build`/`ruby-install`. In case of `RVM`, gem developers could test their gems against to TruffleRuby on Travis as a part of their CI. It would help to support TrufflyRuby across Ruby ecosystem.

In my case, I would could install the latest changes in TruffleRuby just using `ruby-build truffleruby-head ~/.rubies/...`

**Comment by eregon** [comment]
> This would help integrate it into `RVM`/`ruby-build`/`ruby-install`. In case of `RVM`, gem developers could test their gems against to TruffleRuby on Travis as a part of their CI. It would help to support TrufflyRuby across Ruby ecosystem.

Note that TruffleRuby releases are already integrated in `RVM`/`ruby-build`/`ruby-install`.
And it's already [possible](https://github.com/oracle/truffleruby/blob/master/doc/user/standalone-distribution.md#testing-truffleruby-in-travisci) for gem developers to  test their gems against TruffleRuby releases, although it is still a bit cumbersome currently (waiting on https://github.com/travis-ci/travis-build/pull/1604).

But indeed, if we provide nightly builds, then those could also be integrated in `RVM`/`ruby-build`/`ruby-install` as `truffleruby-head` for more convenience.

> Since it's not so trivial to build GraalVM/TruffleRuby

That's also something that might be improved, ideally it could be as simple as:
```
git clone https://github.com/oracle/truffleruby.git
tool/jt.rb build native
```
or similar, and that would output an archive similar to the [releases](https://github.com/oracle/truffleruby/releases).
I think we are quite close and the general build steps are documented in https://github.com/oracle/truffleruby/blob/master/doc/contributor/workflow.md
Did you try the steps there? Did you have any problems with them?

**Comment by deepj** [comment]
Yeah, I meant it in near future. I know RCs are there. But the state of TruffleRuby is not ready to be release as 1.0.0. So nightly builds will be handy when you're fixing the issues quietly quick.

I'm not sure when you want to release 1.0.0. If the goal of 1.0.0 is running Rails and getting regular Rails experience with a development under TruffleRuby, so it takes some time in my point of view.

Right now, I can't run a lot of my Ruby small applications under TruffleRuby. True, the most of them are not Rails app. And many of tests in Rails parts fail now. Even some tests star just handing up. They are one of reasons why I've started to reported issues here.

**Comment by chrisseaton** [comment]
The 1.0 release is of the wider GraalVM. TruffleRuby is just one part of that and is staying 'experimental' while the wider project goes to a 1.0 release. We don't expert TruffleRuby to be ready for production use in 1.0.

Please keep the issues coming though - they're extremely helpful and we're happy that we're able to fix most of them pretty quickly.

**Comment by chrisseaton** [comment]
Here's the blog post describing what is experimental in 1.0.

https://blogs.oracle.com/developers/announcing-graalvm

**Comment by eregon** [comment]
I think it's very valuable to have nightly builds regardless of before/after 1.0, to get a much faster feedback cycle and easily confirm an issue is fully solved.
We need some discussion internally on how to achieve nightly builds, I'll start the discussion soon after RC10.

**Comment by MaxLap** [comment]
I don't think you need more arguments for this, but here is one anyways: It would also help people verify if an issue is still exists before reporting it. Saving time for everyone involved.

**Comment by eregon** [comment]
There are now nightly builds of TruffleRuby and of GraalVM at
https://github.com/graalvm/graalvm-ce-dev-builds/releases

The TruffleRuby standalone are the files:
* truffleruby-20.1.0-dev-linux-amd64.tar.gz
* truffleruby-20.1.0-dev-macos-amd64.tar.gz

Those builds have passed the GraalVM CI and so should work relatively well.

Currently there is not yet a way to automatically find the latest build.

Another thing to be aware of is those builds use the commit of truffleruby imported [in the vm suite](https://github.com/oracle/graal/blob/master/vm/mx.vm/suite.py), not truffleruby `master`. We update that import rather infrequently currently, but we'll try to update it more often. Updating that import currently entails running the entire GraalVM CI which takes a while.

**Comment by chrisseaton** [comment]
Thanks for this work!

> Another thing to be aware of is those builds use the commit of truffleruby imported in the vm suite

Could you try to make a habit of updating it for example at least every Monday morning?

**Comment by eregon** [comment]
Internal issues to track the two shortcomings mentioned above: GR-13460 and GR-21069.

> Could you try to make a habit of updating it for example at least every Monday morning?

I'll try to update it more often and report how it goes. We'll want to automate this though because it's not fun to wait for the entire GraalVM CI.

**Comment by deepj** [comment]
@eregon it is possible not to set the releases as `pre-release`? Then `https://github.com/graalvm/graalvm-ce-dev-builds/releases/latest/download/truffleruby-20.1.0-dev-macos-amd64.tar.gz` doesn't work.

BTW: this works https://github.com/oracle/truffleruby/releases/latest/download/truffleruby-19.3.1-macos-amd64.tar.gz because it's not marked like `pre-release`

**Comment by eregon** [comment]
> Thanks for this work!

@soufianenassih did most of this work actually, thanks goes to him.

**Comment by eregon** [comment]
@deepj Interesting, I tried something like that in the past by replacing the tag name with `latest` (https://github.com/oracle/truffleruby/releases/download/latest/truffleruby-19.3.1-linux-amd64.tar.gz) but that doesn't work, it needs to be in the order you show (releases/latest/download). Is that documented anywhere?

Builds at https://github.com/graalvm/graalvm-ce-dev-builds/releases are not full releases and so I think it makes sense to mark them as prerelease. Besides, the version number and the filename cannot easily be guessed there.

**Comment by deepj** [comment]
@eregon It's mentioned here https://help.github.com/en/github/administering-a-repository/linking-to-releases#linking-to-the-latest-release

**Comment by eregon** [comment]
https://github.com/ruby/truffleruby-dev-builder/releases is a repository building TruffleRuby once a day (or more if triggered manually). Those builds are used for [ruby/setup-ruby](https://github.com/ruby/setup-ruby) with `ruby-version: truffleruby-head`.

The main advantage there is it uses truffleruby `master`, so it always picks the latest truffleruby commit. That commit has passed the TruffleRuby CI but not the GraalVM CI, so those builds might be slightly less stable. Also, they are built on a less controlled environment than https://github.com/graalvm/graalvm-ce-dev-builds/releases.

Per the disclaimer [in the README](https://github.com/ruby/truffleruby-dev-builder):
> These builds are only meant to be used inside GitHub Actions with ruby/setup-ruby.
> They might not work in any other environment.

Recompiling OpenSSL by running `truffleruby-head/lib/truffle/post_install_hook.sh` is probably enough to make it work for most Linux and macOS though.

That repository also provides a way to find the latest build, since `ruby/setup-ruby` needs it.

Longer term, we might want to deprecate those builds and just use https://github.com/graalvm/graalvm-ce-dev-builds/releases. However, for now, since it solves both shortcomings (using latest truffleruby & an easy way to find the latest build) it seems worth to give it a try.

It would be useful to hear if they work for you, because we might want to integrate nightly builds (in general) with ruby-install/ruby-build/RVM for convenience once we get more experience with them.

**Comment by deepj** [comment]
Unfortunately, any of my current work & personal projects is on Github :( So, I can't try it

**Comment by eregon** [comment]
@deepj Sorry, I probably wasn't clear. I meant the nightly builds at https://github.com/ruby/truffleruby-dev-builder should also work locally/on other machines, and it would be good to see if they actually do.

These nightly builds now have fixed URLs for convenience (thanks to what @deepj suggested above):
* Linux: https://github.com/ruby/truffleruby-dev-builder/releases/latest/download/truffleruby-head-ubuntu-18.04.tar.gz
* macOS: https://github.com/ruby/truffleruby-dev-builder/releases/latest/download/truffleruby-head-macos-latest.tar.gz

After downloading and extracting, run this to recompile the OpenSSL C extension against your system libssl:
```
$ truffleruby-head/lib/truffle/post_install_hook.sh
```

Then it should just work, but would be good to get some confirmation.
It seems to work fine for me on Linux.

**Comment by deepj** [comment]
Yeah, yes. I have already installed this build(`truffleruby 20.1.0-dev-9e0b0468, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]`) from https://github.com/ruby/truffleruby-dev-builder on my machine. It seems everything works

**Comment by deepj** [comment]
@eregon Is it possible to add nightlies to `ruby-build`/`rvm`. I use the above linked nightly builds and no issue so far. Let's close this issue finally :)

**Comment by eregon** [comment]
Yes, I'll work on that.

**Comment by eregon** [comment]
`ruby-build` PR merged: https://github.com/rbenv/ruby-build/pull/1405
`ruby-install` PR opened: https://github.com/postmodern/ruby-install/pull/364
`RVM` still to do (most complicated)

**Comment by eregon** [comment]
Both `ruby-build` and `RVM` PRs have been merged, so you can:
```
rvm get master
rvm install truffleruby-head

# Update to latest ruby-build
ruby-build truffleruby-dev $PREFIX
```

The `ruby-install` has been [rejected](https://github.com/postmodern/ruby-install/pull/364), because `ruby-install` considers installing `-head` versions an anti-feature. So use `ruby-build` (also works fine with `chruby`) or download, extract, post-install-hook the nightly manually if you're using `ruby-install`.

I think the only missing thing is updating documentation.

**Comment by gogainda** [comment]
@eregon thanks for that :100:

**Comment by eregon** [comment]
Documented in 536a663b71adc0739ea85b250ae6f91f05fbc771.
