### ISSUE TITLE
Update doc for Travis

### ISSUE THREAD

**Issue by MaxLap** [oracle/truffleruby#1485]
I see that truffle support has just been added to Travis (nice job!). However, this repo's documentation still describes only the manual way of doing things:

https://github.com/oracle/truffleruby/blob/master/doc/user/standalone-distribution.md#testing-truffleruby-in-travisci

I'm not sure what would be better, copying/similar content to Travis' page, or just a link?
https://docs.travis-ci.com/user/languages/ruby/#truffleruby

**Comment by nirvdrum** [comment]
Thanks for filing this. Getting proper support in Travis CI is something that's taken months and we weren't sure exactly when they'd merge PRs for us. We'll definitely get this updated.

**Comment by eregon** [comment]
I (finally) updated the docs in https://github.com/oracle/truffleruby/commit/b5e583a35c15a64b45395d1d098b24cefddca143.
@MaxLap Thank you for the report!
