### ISSUE TITLE
#raise without argument shouldn't have a message

### ISSUE THREAD

**Issue by MaxLap** [oracle/truffleruby#1487]
On MRI and JRuby:
```ruby
raise rescue a = $!; a.message
 #=> ''
``` 

On truffleruby:
```ruby
raise rescue a = $!; a.message
 #=> "No current exception"
``` 

My initial thought is that the message should just be removed here:
https://github.com/oracle/truffleruby/blob/c4cda962fa9f84d524a6216218cf59fbf7bd77be/src/main/ruby/core/truffle/kernel_operations.rb#L118

**Comment by nirvdrum** [comment]
This was fixed by 648d728, but unfortunately I couldn't get the fix before 1.0.0 RC 12 was released. The fix will be available in the next release.
