### ISSUE TITLE
Support :chdir in #spawn

### ISSUE THREAD

**Issue by MaxLap** [oracle/truffleruby#1492]
Right now, `spawn('echo hi', chdir: '/home')` is plain refused in TruffleRuby.

truffleruby 1.0.0-rc9, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]

**Comment by nirvdrum** [comment]
Thanks for the report! This is unfortunately a known limitation in TruffleRuby. Incidentally, we were just discussing what we can do about it a few days back. The core issue is we don't support `fork`. The `posix_spawnp` call doesn't provide a mechanism to change directories when executing a call, so MRI forks, changes the directory, then execs.

Unfortunately, approaches like changing the directory, performing the spawn, and then changing back to the previous directory suffer from race conditions in the presence of multiple running threads.

Anyway, it's something for us to sort out and we're aware we need to. I'm hopeful we'll work out a solution soon.

**Comment by MaxLap** [comment]
I understand, I just didn't see any mention of it in the doc so I thought I'd report it. It's not obvious that not supporting fork means no :chdir.

I wish I could help, but other than providing a random workaround that you guys probably already thought of and discarded, I got nothing. (Can't you `#spawn` a binary/non-ruby script which receives the information, does the chdir, and then`exec` the real target?)

**Comment by nirvdrum** [comment]
Your suggestion is what we've converged on. One of us will try that approach out next week. Not shipping an extra binary would be preferable, but we were unable to come up with a reasonable solution otherwise. "Reasonable" here means not incurring a bunch of overhead.

**Comment by eregon** [comment]
I'll try to take a look at this this week.

**Comment by eregon** [comment]
FWIW JRuby uses `cd workdir && ...` but that invokes the shell (can be slow) and if arguments are passed as an Array they would need to be escaped into a flat command line.

I think the best approach here is having a small executable doing `chdir` + `execve`, much like Java does in some cases for `ProcessBuilder`.

It seems `posix_spawn_file_actions_addchdir_np` was added in glibc 2.29: https://sourceware.org/ml/libc-announce/2019/msg00000.html
But that might take a while until all OS have a recent enough glibc.
We could still check if it is available and use it as an optimization, though.

**Comment by eregon** [comment]
I fixed this in d39f45e6fc1d50354fa2ed237883e5a798996bd3 and it will be in the next release.
@MaxLap Thank you for reporting the bug, and sorry it took so long to actually fix it.

**Comment by eregon** [comment]
FYI, TruffleRuby 19.3.0 was released and should fix this.
