### ISSUE TITLE
String literal difference between MRI and TruffleRuby

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1495]
The following described issue it's actually the same such this in JRuby https://github.com/jruby/jruby/issues/5052

MRI (2.5.3)

```
irb(main):001:0> "#@"
=> "\#@"
```

TruffleRuby (1.0.0-rc9)

```
irb(main):001:0> "#@"
=> "@"
```

**Comment by chrisseaton** [comment]
Yes our parser comes from the same origin so we've probably just inherited this issue.

**Comment by eregon** [comment]
We should apply the same fix as JRuby here: https://github.com/jruby/jruby/commit/05e415ccc92d7e680a0317b066aefadf4ce40dfa

**Comment by bjfish** [comment]
This is fixed at: https://github.com/oracle/truffleruby/commit/d4cfcaba8984de6857b825d07019eada822a11fe.
