### ISSUE TITLE
TracePoint.trace is not supported

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1497]
It's available since Ruby 2.0. See https://ruby-doc.org/core-2.0.0/TracePoint.html#method-c-trace

To reproduce:

```ruby
TracePoint.trace(:call) { puts 'Hi' }
```

Error:

```
NoMethodError: undefined method `trace' for TracePoint:Class
```

**Comment by chrisseaton** [comment]
Thanks - I can't remember how much of `TracePoint` is specified or implemented, so we can easily implement this method, but hopefully it won't just reveal the rest of it isn't implemented yet.

**Comment by eregon** [comment]
There is `TracePoint.trace` defined since a while now.
