### ISSUE TITLE
#require should ignore files which are not .rb or native extensions

### ISSUE THREAD

**Issue by MaxLap** [oracle/truffleruby#1499]
`#require` accepts loading any files, no matter the extension. This is unlike the behavior of JRuby and MRI.

```ruby
require 'tmpdir'
require 'fileutils'

def make_ruby_file(dir, path)
  File.write("#{dir}/#{path}", <<-RUBY)
    puts "in " + #{path.inspect}
  RUBY
end

# #require should ignore non .rb files
Dir.mktmpdir('truffleruby_test') do |dir|
  make_ruby_file(dir, 'test')

  $LOAD_PATH << dir

  require 'test'
end
```

In MRI: `cannot load such file -- test (LoadError)`
In JRuby: `LoadError: no such file to load -- test`
In TruffleRuby: `in test`

**Comment by chrisseaton** [comment]
Like #1500 I was sure TruffleRuby was working as per standard Ruby, but we'll fix this.

**Comment by MaxLap** [comment]
Note: Accepting any file is the correct behavior for `#load`, but not of `#require`.

**Comment by bjfish** [comment]
This appears to work now with the following error:
`/Users/bfish/Documents/truffleruby-ws/truffleruby/mxbuild/truffleruby-native/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `raise_load_error': cannot load such file -- test (LoadError)`

 and was probably fixed here: https://github.com/oracle/truffleruby/commit/3cac492c9ec19f34ea4de2a03425f59cb459fbfd

Also, `load 'test'` appears correct for this example.
