### ISSUE TITLE
#require should prioritize any .rb over any native extension, no matter LOAD_PATH order

### ISSUE THREAD

**Issue by MaxLap** [oracle/truffleruby#1500]
MRI and JRuby search for .rb files, and if that fails, they go for a native extension.

```ruby
require 'tmpdir'
require 'fileutils'
require 'rbconfig'

NATIVE_EXT = RbConfig::CONFIG['DLEXT']

def make_ruby_file(dir, path)
  File.write("#{dir}/#{path}", <<-RUBY)
    puts "in " + #{path.inspect}
  RUBY
end

# #prioritize .rb files of a later $LOAD_PATH instead of a .su of an earlier path
Dir.mktmpdir('truffleruby_test') do |dir|
  FileUtils.mkpath("#{dir}/one")
  FileUtils.mkpath("#{dir}/two")
  puts "Using .#{NATIVE_EXT} as extension for the native"
  File.write("#{dir}/one/test.#{NATIVE_EXT}", '')
  make_ruby_file(dir, 'two/test.rb')

  $LOAD_PATH << "#{dir}/one"
  $LOAD_PATH << "#{dir}/two"

  require 'test'
end
```

In MRI: `in two/test.rb`
In JRuby: `in two/test.rb`
In TruffleRuby: `Init_test() not found (LoadError)` => Which means it tried to load the fake native extension

**Comment by chrisseaton** [comment]
Hmmm I was sure Ruby loaded files without an extension. We'll have to add some more specs to explore this a bit more.

**Comment by bjfish** [comment]
This is now fixed at https://github.com/oracle/truffleruby/commit/8fa5648f3cb0f3618f4cb3b54d180cc79798fd24.
