### ISSUE TITLE
#require should return false if any $LOADED_FEATURES + any $LOAD_PATH already matches the target

### ISSUE THREAD

**Issue by MaxLap** [oracle/truffleruby#1501]
If a file that was already required matches the the required path, `#require` should return false, even if another file exist on the path which is earlier.

Note, the script just unshifts the path, but this is also for cases where a later file is loaded absolutely.

```ruby
require 'tmpdir'
require 'fileutils'

def make_ruby_file(dir, path)
  File.write("#{dir}/#{path}", <<-RUBY)
    puts "in " + #{path.inspect}
  RUBY
end

# #require should skip if any existing $LOADED_FEATURES already match $LOAD_PATH + path.
Dir.mktmpdir('truffleruby_test') do |dir|
  FileUtils.mkpath("#{dir}/one")
  FileUtils.mkpath("#{dir}/prepended")
  make_ruby_file(dir, 'one/test.rb')
  make_ruby_file(dir, 'prepended/test.rb')

  $LOAD_PATH << "#{dir}/one"
  require 'test'
  $LOAD_PATH.unshift "#{dir}/prepended"
  require 'test'
end
```

In MRI: `in one/test.rb`
In JRuby: `in one/test.rb`
In TruffleRuby: 
```
in one/test.rb
in prepended/test.rb
```

**Comment by chrisseaton** [comment]
Thanks, great issue to fix.

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/5cfbbd05100df7e176be28c3cd6b847ba6a71e36. Thanks.
