### ISSUE TITLE
Enumerable::Lazy#uniq is hanging up

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1516]
To reproduce:

```ruby
(1..Float::INFINITY).lazy.uniq.first(10)
```

After that, I needed to use `Ctrl` + `C` to stop the hanging up for a while.

Under MRI, the result is returned very quickly.

**Comment by deepj** [comment]
Still reproducible in RC11

**Comment by chrisseaton** [comment]
The problem is there's a whitelist of methods that work with `lazy`. `uniq` is listed in one place in the documentation, but not in another. I'll spec this out. The fix should be easy.

**Comment by chrisseaton** [comment]
Fix on the way.

**Comment by chrisseaton** [comment]
Fixed in 0778fcc84c6b7cf45244323e853504f49781eb0c.
