### ISSUE TITLE
BigDecimal#to_r is not supported

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1521]
I'm quite surprised by this since `BigDecimal#to_r` is available in Ruby for ages

To reproduce:

```ruby
require 'bigdecimal'

BigDecimal('1.5').to_r
```

Error:

```
NoMethodError: undefined method `to_r' for 0.15e1:BigDecimal
Did you mean?  to_i
               to_f
               to_c
               to_s
	from (irb):2
	from ~/.rubies/truffleruby-1.0.0-rc10/bin/irb:29:in `<main>'
```

**Comment by nirvdrum** [comment]
I've added support for `BigDecimal#to_r` in e3a61d54126c04d0a58fee659a38960039f6f2ac. This should be available in the TruffleRuby 1.0.0 RC 12 release. NB: there are other `BigDecimal` methods not yet implemented. I'll work through the list of them, but I wanted to get a fix out for your immediate problem.
