### ISSUE TITLE
Wrong usage of dlopen prevents graalvm to start properly

### ISSUE THREAD

**Issue by Mikiya** [oracle/truffleruby#1537]
On my Gentoo Linux system, the vm doesn't start properly like below.
```
shell$ gu -c install org.graalvm.ruby
... snip ...
shell$ ~/opt/graalvm/1.0.0/bin/gem list
ERROR:  Loading command: list (RuntimeError)
        /usr/lib64/libz.so: invalid ELF header
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```
This happens because /usr/lib64/libz.so isn't a real library on Gentoo Linux, but it's a linker script like below.
```
shell$ cat /usr/lib64/libz.so
/* GNU ld script
   Since Gentoo has critical dynamic libraries in /lib, and the static versions
   in /usr/lib, we need to have a "fake" dynamic lib in /usr/lib, otherwise we
   run into linking problems.  This "fake" dynamic lib is a linker script that
   redirects the linker to the real lib.  And yes, this works in the cross-
   compiling scenario as the sysroot-ed linker will prepend the real path.

   See bug https://bugs.gentoo.org/4411 for more info.
 */
OUTPUT_FORMAT ( elf64-x86-64 )
GROUP ( /lib64/libz.so.1 )
```
dlopen cannot handle this type of GNU ld script.

In the first place, calling dlopen without specifying ABI version isn't a correct usage. ABI version, a number specified after .so, represents compatibility of the library. If no ABI version is specified, dlopen will pick the latest version available in the system. It may cause problems when ABI version is not expected one. ABI version specification is mandatory for software which needs robustness, IMHO. I assume that GraalVM is designed to use the latest version of libraries, but ABI version specification will be required in the future. (BTW, none of .so files including ABI version isn't GNU ld script. All of their file types are either of a symbolic link or a real ELF library file. So, if ABI version number is specified, this problem will not happen on my box. It just let me notice this problem.)

So, I insist that it is required to specify ABI version when calling dlopen. To achieve that, I suggest to add an integer variable to org.graalvm.nativeimage.c.function.CLibrary, and modify related codes accordingly.

**Comment by eregon** [comment]
This is fixed on master and will be in the next release, 19.3.0.
The new approach uses a native linker which links against the correct library.
