### ISSUE TITLE
Multithread support in polyglot with Ruby and R

### ISSUE THREAD

**Issue by rbotafogo** [oracle/truffleruby#1538]
When running Ruby and R Graalvm goes into single threaded mode.  This will have serious impact when running Ruby apps.  Here is a use case I'd like to see working:

let's say I'm building a Web Application that at some point might needs to develop a data model for the user.  In this case:
    • I don't want my web application to be single threaded just because eventually I'll need to interface with R to build a data model;
    • Since building a data model is usually time consuming, then the best would be to have a worker thread take care of this model while not impacting user's interaction;
    • Since different users might request different models, it would be ideal if I could "instantiate" a new R for every users and run that on there own threads.

Thanks

**Comment by eregon** [comment]
Closing in favor of #2035.
