### ISSUE TITLE
attr_accessor inside a refinement

### ISSUE THREAD

**Issue by english** [oracle/truffleruby#1540]
MRI 2.1.0+ supports using `attr_accessor` within a `refine` block. `truffleruby-1.0.0-rc10`, however, doesn't appear to support this. The following example should illustrate the disparity:

```rb
# test.rb
class Foo
end

using Module.new {
  refine Foo do
    attr_accessor :bar
  end
}

foo = Foo.new
puts foo.bar.inspect
foo.bar = 'bar'
puts foo.bar.inspect
```

```
$ rbenv shell 2.1.0 && ruby ./test.rb
nil
"bar"
$ rbenv shell truffleruby-1.0.0-rc10 && ruby ./test.rb
./test.rb:11:in `<main>': undefined method `bar' for #<Foo:0x84>:Foo (NoMethodError)
```

**Comment by ssnickolay** [comment]
I've tested and this issue fixed in https://github.com/oracle/truffleruby/pull/2033 and can be closed after merging. //cc @eregon
