### ISSUE TITLE
Thread#backtrace_locations is not supported

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1556]
This method is available since Ruby 2.2

To reproduce

```ruby
Thread.current.backtrace_locations
```

Error:

```
NoMethodError: undefined method `backtrace_locations' for Thread:Class
	from (irb):1
	from ~/.rubies/truffleruby-1.0.0-rc11/bin/irb:29:in `<main>'
```

**Comment by chrisseaton** [comment]
"Returns any backtrace associated with the exception. This method is similar to #backtrace, but the backtrace is an array of Thread::Backtrace::Location."

**Comment by deepj** [comment]
@eregon this is already implemented so it can be closed
