### ISSUE TITLE
TruffleRuby sets `ruby_cext` in polyglot bindings

### ISSUE THREAD

**Issue by fniephaus** [oracle/truffleruby#1561]
TruffleRuby uses `ruby_cext` in the polyglot bindings to communicate with Sulong when a C-based Ruby library such as nokogiri is used. This communication should not leak into the polyglot bindings object (imagine someone happens to override `ruby_cext` for some reason). I think @chumer knows how to avoid that.

**Comment by chumer** [comment]
The polyglot bindings should remain empty, if possible. @chrisseaton could you elaborate why you need it there?

**Comment by chrisseaton** [comment]
For example, when someone uses the constant `Qnil` in a Ruby C extension, we need to get the `nil` object from the Ruby context. This is effectively done by:

```c
polyglot_invoke(polyglot_import("ruby_cext"), "Qnil");
```

On the Ruby side we effectively do

```ruby
module Truffle::CExt
  def Qnil
    nil
  end
end

Truffle::Interop.export(:ruby_cext, Truffle::CExt)
```

`ruby_cext` is the exported object @fniephaus is talking about. It's our way to communicate between C and Ruby. Is there better way?

**Comment by eregon** [comment]
No longer an issue anymore, now we have `void rb_tr_init(void *ruby_cext) {` and that sets it in C code.
