### ISSUE TITLE
protected method and respond_to? would return false

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1568]
This one of big changes in Ruby 2.0 beside Ruby 1.9.3.

See https://tenderlovemaking.com/2012/09/07/protected-methods-and-ruby-2-0.html

To reproduce

```ruby
class Dummy
  def public_method; end

  protected
  def protected_method; end

  private
  def private_method; end
end

dummy = Dummy.new

puts 'public_method:'
puts dummy.respond_to?(:public_method)

puts 'protected_method:'
puts dummy.respond_to?(:protected_method)

puts 'private_method:'
puts dummy.respond_to?(:private_method)
```

Actual:

```
public_method:
true
protected_method:
true
private_method:
false
```

Expected:

```
public_method:
true
protected_method:
false
private_method:
false
```

This issue causes failing this dry-initializer spec https://github.com/dry-rb/dry-initializer/blob/master/spec/public_attributes_utility_spec.rb

See also https://github.com/dry-rb/dry-initializer/blob/master/lib/dry/initializer/config.rb#L80

**Comment by flash-gordon** [comment]
@deepj glad you narrowed down, dry-initializer is highly optimized and, frankly speaking, quite hard for debugging. It even crashed CRuby once, it took me a while to come up with a reproducible snippet for a bug report.

**Comment by deepj** [comment]
@eregon @chrisseaton Please, make this to RC13. It helps dry/rom stuffs. And this was one of big changes between 1.x and 2.x versions.

**Comment by chrisseaton** [comment]
This is covered by specs.

The behaviour of `respond_to?` doesn't change inside an object of the same class does it?

**Comment by deepj** [comment]
@chrisseaton try the example above. `respond_to?` would return `false` for protected methods.

**Comment by chrisseaton** [comment]
I don't see an example above covering the case where the call is inside a method of the same class? They're all top-level?

**Comment by deepj** [comment]
Yes, try

```ruby
class Dummy
  def public_method; end

  protected
  def protected_method; end

  private
  def private_method; end
end

dummy = Dummy.new

puts 'public_method:'
puts dummy.respond_to?(:public_method)

puts 'protected_method:'
puts dummy.respond_to?(:protected_method)

puts 'private_method:'
puts dummy.respond_to?(:private_method)
```

**Comment by chrisseaton** [comment]
I think we're talking at cross purposes.

I'm talking about a call to `respond_to?` with a method of `Dummy`, that is made inside a method of `Dummy`. You aren't making any calls inside methods of `Dummy`.

But don't worry I was only thinking aloud and I'll work it out myself.

**Comment by eregon** [comment]
I think `respond_to?` is not context-sensitive (changing based on where it's called), just like the rest of reflection and metaprogramming in Ruby (there are some exceptions for refinements though).

**Comment by deepj** [comment]
No, it's not context-sensitive. As it is said in docs:

```
Returns true if obj responds to the given method. Private and protected methods are included in the search only if the optional second parameter evaluates to true.
```

@chrisseaton I got it this morning what you'd meant.

**Comment by aardvark179** [comment]
I think I see the problem, and we do have specs that cover this which are currently tagged as failing.

**Comment by aardvark179** [comment]
The fix for this has now been merged.

**Comment by deepj** [comment]
@aardvark179 Hm, it seems this doesn't help at all to pass this dry-initializer test

**Comment by deepj** [comment]
@aardvark179 @chrisseaton this looks this is not fixed in RC13, but in RC14-dev yes.
