### ISSUE TITLE
JSON.parse parses an invalid JSON like a valid one

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1570]
To reproduce:

```ruby
require 'json'

JSON.parse("{")
```

Actual:

```
=> {}
```

Expected:

```
JSON::ParserError: source is not valid JSON!
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/json/lib/json/pure/parser.rb:117:in `parse'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/json/lib/json/common.rb:156:in `parse'
	from (irb):3
	from ~/.rubies/truffleruby-1.0.0-rc12/bin/irb:29:in `<main>'
```

**Comment by deepj** [comment]
There is some bug for `JSON.parse("[")`

**Comment by deepj** [comment]
@chrisseaton Hello, can you check if this has been solved by your commit https://github.com/oracle/truffleruby/commit/b9d5779ffba78842999e247cb33ef11bbb8a156d, please?

**Comment by bjfish** [comment]
I just tried `ruby -e 'require "json";JSON.parse("{")'` and this still appears to be an issue.

**Comment by eregon** [comment]
This is an issue of the pure-Ruby implementation of JSON, it also happens on MRI with `json/pure`:
```
$ ruby -v -rjson/pure -e 'p JSON.parse("{")'
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
{}

$ ruby -v -rjson -e 'p JSON.parse("{")' 
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from /home/eregon/.rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse': 785: unexpected token at '{' (JSON::ParserError)
```

@deepj or @bjfish could you report the bug to https://github.com/flori/json ?

**Comment by bjfish** [comment]
@eregon I've reported the issue here: https://github.com/flori/json/issues/394

**Comment by gogainda** [comment]
@eregon I think it's fixed

**Comment by eregon** [comment]
@gogainda It's fixed upstream but we use the version of JSON that 2.7.2 includes, which is older than that.
It's still an issue on a fresh truffleruby installation.
Installing the `json` gem fixes it because `json` is a default gem and then it will pick the newer version.
