### ISSUE TITLE
Pushing a gem crashes

### ISSUE THREAD

**Issue by rbotafogo** [oracle/truffleruby#1586]
gem push galaaz-0.4.6.gem
Pushing gem to https://rubygems.org...
ERROR:  While executing gem ... (RuntimeError)
    rb_io_wait_writable wait case not implemented

**Comment by aardvark179** [comment]
This doesn't look like it will be too hard to fix, but testing it maybe slightly more tricky as there are tests for this, and they do seem to pass consistently.

**Comment by aardvark179** [comment]
The fix for this has been merged.
