### ISSUE TITLE
OpenSSL::Digest.digest doesn't support two arguments

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1587]
See https://ruby-doc.org/stdlib-1.9.3/libdoc/openssl/rdoc/OpenSSL/Digest.html#method-c-digest

To reproduce:

```
require 'openssl'
OpenSSL::Digest.digest('SHA256', 'abc')
```

Error:

```
ArgumentError: wrong number of arguments (given 2, expected 1)
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/digest.rb:141:in `digest'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/mri/openssl/digest.rb:38:in `digest'
	from (irb):3
	from ~/.rubies/truffleruby-1.0.0-rc12/bin/irb:29:in `<main>'
```

The equivalent of the above code is this method which works `OpenSSL::Digest::SHA256.digest('abc')`

`net-ssh` uses this method for instance

**Comment by deepj** [comment]
The same problem is with `OpenSSL::Digest.hexdigest`. But I couldn't find it in the documentation.

But it uses `net-ssh` gem. See https://github.com/net-ssh/net-ssh/blob/dd13dd44d68b7fa82d4ca9a3bbe18e30c855f1d2/lib/net/ssh/authentication/pub_key_fingerprint.rb#L34

**Comment by deepj** [comment]
@eregon this is already fixed I guess. At least in my nightly build the code above works

**Comment by eregon** [comment]
Yes, this was fixed by https://github.com/oracle/truffleruby/pull/1889.
Thanks for checking!
