### ISSUE TITLE
Eventmachine failing to install due to missing iostream header

### ISSUE THREAD

**Issue by ivoanjo** [oracle/truffleruby#1597]
Hello there! 👋

I'm running `truffleruby 1.0.0-rc13, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]` on `Ubuntu 18.10` installed via `rvm 1.29.7-next (master)`.

While trying to `gem install eventmachine` I'm getting this error:

```
$ gem install eventmachine
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
        ERROR: Failed to build gem native extension.

    current directory: /home/knuckles/.rvm/gems/truffleruby-1.0.0-rc13/gems/eventmachine-1.2.7/ext
/home/knuckles/.rvm/rubies/truffleruby-1.0.0-rc13/bin/truffleruby -r ./siteconf20190305-14502-1wek6i7.rb extconf.rb
checking for -lcrypto... yes
checking for -lssl... yes
checking for openssl/ssl.h... yes
checking for openssl/err.h... yes
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for pipe2() in unistd.h... yes
checking for accept4() in sys/socket.h... yes
checking for SOCK_CLOEXEC in sys/socket.h... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
checking for clock_gettime()... yes
checking for CLOCK_MONOTONIC_RAW in time.h... yes
checking for CLOCK_MONOTONIC in time.h... yes
CXXFLAGS=-Xclang -disable-O0-optnone -g -Wimplicit-function-declaration -Wno-unknown-warning-option -Wno-int-conversion -Wno-int-to-pointer-cast -Wno-unused-value -Wno-incompatible-pointer-types -ferror-limit=500 -c -emit-llvm -stdlib=libc++ -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-result -Wno-address
creating Makefile

current directory: /home/knuckles/.rvm/gems/truffleruby-1.0.0-rc13/gems/eventmachine-1.2.7/ext
make "DESTDIR=" clean

current directory: /home/knuckles/.rvm/gems/truffleruby-1.0.0-rc13/gems/eventmachine-1.2.7/ext
make "DESTDIR="
compiling binder.cpp
In file included from binder.cpp:20:
./project.h:25:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
make: *** [Makefile:204: binder.bc] Error 1

make failed, exit code 2

Gem files will remain installed in /home/knuckles/.rvm/gems/truffleruby-1.0.0-rc13/gems/eventmachine-1.2.7 for inspection.
Results logged to /home/knuckles/.rvm/gems/truffleruby-1.0.0-rc13/extensions/x86_64-linux/2.4.0/eventmachine-1.2.7/gem_make.out
```

I'm not sure why this is failing, as I've checked that a simple C++ hello world compiled using both `g++` and `clang++` on the same machine works and does not complain about not finding the header.

Let me know if I can provide any more info! 🙏

**Comment by eregon** [comment]
Hello and thank you for the report.

I have a PR open on `eventmachine` to make it compile on TruffleRuby, but it's not yet merged:
https://github.com/eventmachine/eventmachine/pull/878

However, without that patch, I get a different error (on 1.0.0-rc13), basically the same as in #1541:
```
rubymain.cpp:1220:8: error: assigning to 'VALUE' (aka 'void *') from incompatible type 'int'
        arg = (NIL_P(arg)) ? -1 : NUM2INT (arg);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rubymain.cpp:1221:18: error: no matching function for call to 'evma_set_rlimit_nofile'
        return INT2NUM (evma_set_rlimit_nofile (arg));
                        ^~~~~~~~~~~~~~~~~~~~~~
/home/eregon/.rubies/truffleruby-1.0.0-rc13/lib/cext/include/ruby/ruby.h:1461:31: note: expanded from macro 'INT2NUM'
#define INT2NUM(x) RB_INT2NUM(x)
                              ^
/home/eregon/.rubies/truffleruby-1.0.0-rc13/lib/cext/include/ruby/ruby.h:1438:41: note: expanded from macro 'RB_INT2NUM'
# define RB_INT2NUM(v) RB_INT2FIX((int)(v))
                                        ^
./eventmachine.h:131:6: note: candidate function not viable: cannot convert argument of incomplete type 'VALUE' (aka 'void *') to 'int' for 1st argument
        int evma_set_rlimit_nofile (int n_files);
            ^
2 warnings and 2 errors generated.
make: *** [Makefile:204: rubymain.bc] Error 1

make failed, exit code 2
```

So I would guess this is somehow related to your platform or setup.
Is `clang++` the installed system clang? Which version is it?
And `clang++ hello.cc` works?

It would be useful if you can share the `Makefile` and `mkmf.log` files under `/home/knuckles/.rvm/gems/truffleruby-1.0.0-rc13/gems/eventmachine-1.2.7`.
The `mkmf.log` is normally produced when running the `extconf.rb` but for some reason it's not present for me with `eventmachine`, but it could be for you as it fails earlier.

**Comment by eregon** [comment]
Please also make sure you have all required packages installed, see https://github.com/oracle/truffleruby/blob/master/doc/user/installing-llvm.md#ubuntu

**Comment by ivoanjo** [comment]
Ah! Derp :man_facepalming: I was indeed missing both `libc++-dev` and `libc++abi-dev`.

Since rvm even asks sometimes to install dependencies via `apt`, I didn't even think to check the documentation to see if I was missing anything.

Do you think it'd make sense to report this issue on the rvm side?

Other than that, feel free to close this ticket! :+1:

**Comment by eregon** [comment]
@ivoanjo Great to hear that fixed the compilation error!

I'm generally not a huge fan in hardcoding dependencies in Ruby installers, since dependencies tend to change and can vary in subtle ways between OS and TruffleRuby versions.
A good way to solve this would be to improve the error message in such a case.
Unfortunately, it seems quite difficult in this case, as it's a message from `clang` from a generated `Makefile`. I think `clang` should have a better error message if `-stdlib=libc++` is passed but it's not installed, but that's less tractable.

Since RVM already installs a bunch of packages, I think it would make sense if it installs these extra packages for C++ support on Ubuntu too. So yes, please create an issue or PR to RVM :)

I'll close this issue since I don't think we can do much better currently in TruffleRuby, unfortunately.
