### ISSUE TITLE
Error running Ruby polyglot in native mode

### ISSUE THREAD

**Issue by zaknuces** [oracle/truffleruby#1602]
Is it possible to run Ruby polyglot native? It is not apparent from the reference manual. I am getting the following error:

ERROR: Could not find class 'org.truffleruby.launcher.RubyLauncher'.
You might need to rebuild the polyglot launcher with 'gu rebuild-images polyglot'.

Is this expected?

**Comment by chrisseaton** [comment]
Yes it’s usable from a polyglot context.

Which part of the reference wasn’t as clear as you needed on that?

Did you try running the command the error message gives you? Did it work? You should have seen the same advice when installing Ruby initially.

**Comment by zaknuces** [comment]
Thanks, it worked. After rebuilding polyglot image.

**Comment by chrisseaton** [comment]
Great - but do we need to improve that error message or any other documentation to make it more clear, if it wasn't immediately obvious what you needed to do?

**Comment by zaknuces** [comment]
The error message was clear. I was doing it in a container and rebuild image failed for me. After trying it again, it worked. 

Thanks

**Comment by chrisseaton** [comment]
Yeah it probably needs more memory to rebuild images than most containers are configured for - that's usually the issue. About 8 GB I think.
