### ISSUE TITLE
Endless ranges are not supported

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1606]
Available since Ruby 2.6.

Version:
```
truffleruby 1.0.0-rc14-dev-f6b387c4, like ruby 2.6.1, Interpreted [x86_64-darwin]
```

To reproduce:

```
(2..)
```

Error:

```
SyntaxError ((irb):1: syntax error, unexpected tRPAREN)
```

Where I can use Ruby 2.6 I use this pattern because when I need to omit some beginning of string or array and I don't care about the rest, this is more readable and handy than e.g. `(2..string.length - 1)`.

**Comment by aardvark179** [comment]
Looks like this will require some parser changes, and the correct implementation of the 2.6 enumerator subclasses. I’m part way through the latter right now, but I don’t know which RC they will get into.

**Comment by deepj** [comment]
Just for a note, one of Sequel's spec since Ruby 2.5 depends on this functionality...

**Comment by deepj** [comment]
@aardvark179 Hello, is it possible to pass this to the recent following release, please? This is the last "missing feature" to pass all Sequel's specs.

**Comment by norswap** [comment]
Fixed by https://github.com/oracle/truffleruby/commit/c4ee0e28b4323c6fb176d0d1d852b8c545f9a2a7
