### ISSUE TITLE
String deduplication is not supported

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1608]
This is a feature of Ruby 2.5

Version:

```
truffleruby 1.0.0-rc14-dev-f6b387c4, like ruby 2.6.1, Interpreted [x86_64-darwin]
```

To reproduce:

```ruby
a = 'hello'
b = 'hello'
puts ((-a).object_id == (-b).object_id)
```

It would return `true` but I got `false`.

This causes an issue in Sequel specs

```
$ ruby -Ispec spec/core/schema_spec.rb
Run options: --seed 56164

# Running:

...........F..........................................................................................................................................................................................

Finished in 4.132054s, 47.9181 runs/s, 82.5255 assertions/s.

  1) Failure:
Schema Parser#test_0009_should dedup :db_type strings [spec/core/schema_spec.rb:1681]:
Expected # encoding: US-ASCII
"x" (oid=9272) to be the same as # encoding: US-ASCII
"x" (oid=9280).

198 runs, 341 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by chrisseaton** [comment]
This spec seems to be excluded for JRuby - `&& !defined?(JRUBY_VERSION)` I wonder why.

**Comment by deepj** [comment]
@chrisseaton sorry, I mislead the description. I updated it. This is a new feature of Ruby 2.5. More on https://samsaffron.com/archive/2018/02/16/reducing-string-duplication-in-ruby

**Comment by chrisseaton** [comment]
Yeah this is the `String#@-` method.

**Comment by chrisseaton** [comment]
https://github.com/jeremyevans/sequel/commit/263f98006269f59425c02e5d0a2b841f0a67ec8f

**Comment by deepj** [comment]
How hard is this to support in TruffleRuby?

**Comment by chrisseaton** [comment]
Should be trivial. Do you want to prioritise it?

**Comment by deepj** [comment]
@chrisseaton it would be fine to be fixed at least in RC17 together with https://github.com/oracle/truffleruby/issues/1606. Then all Sequel specs will pass.

**Comment by aardvark179** [comment]
The fix for this has now been merged.
