### ISSUE TITLE
binding.irb is not enabled by default

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1611]
I use this feature heavily and on daily basics since Ruby 2.5 together with #1609 . I'd appreciate to bring this to TruffleRuby 1.0.0 RC14 if possible.

From Ruby 2.5 NEWS

- IRB
  - Print backtrace and error message in reverse order [Feature #8661] [experimental]
  - `binding.irb` automatically requires irb and runs [Bug #13099] [experimental]
  - `binding.irb` on its start shows source around the line where it was called

Version:

```
truffleruby 1.0.0-rc14-dev-f6b387c4, like ruby 2.6.1, Interpreted [x86_64-darwin]
```

**Comment by nirvdrum** [comment]
Thanks for the report! This issue was fixed in d845846a5ca802301cddad998133135bda6b1890 and will appear in the next TruffleRuby release (1.0.0-rc14).
