### ISSUE TITLE
Unmarshaled hash with non-ascii keys is corrupted

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1624]
This issue is similar to https://github.com/jruby/jruby/issues/5523 reported by @larskanis. But it behaves a bit differently in TruffleRuby. There was the same issue with arrays already fixed in TruffleRuby https://github.com/oracle/truffleruby/issues/1530

The used code is from @larskanis

TruffleRuby 1.0.0-RC13

```
irb(main):001:0> h={:€a=>nil, :€c=>nil, :€h=>nil}
=> {:€a=>nil, :€c=>nil, :€h=>nil}
irb(main):002:0> Marshal.load(Marshal.dump(h))
=> {:"€a"=>nil, :"\xE2\x82\xACc"=>nil, :"\xE2\x82\xACh"=>nil}
irb(main):003:0> Marshal.load(Marshal.dump(h)) == h
=> false
```

Ruby 2.5.3

```
irb(main):001:0> h={:€a=>nil, :€c=>nil, :€h=>nil}
=> {:€a=>nil, :€c=>nil, :€h=>nil}
irb(main):002:0> Marshal.load(Marshal.dump(h))
=> {:€a=>nil, :€c=>nil, :€h=>nil}
irb(main):003:0> Marshal.load(Marshal.dump(h)) == h
=> true
```

**Comment by deepj** [comment]
Closed due to I'm not welcome anymore in Ruby community

**Comment by dentarg** [comment]
Seems to happen when using truffleruby-head-ubuntu-18.04 with Addressable (build ran 2 days ago): https://github.com/sporkmonger/addressable/runs/2977469877?check_suite_focus=true#step:7:87

The Marshal dump is from 2012: https://github.com/sporkmonger/addressable/commit/1eb715d16c93987f5feb5507ad88f6a7cd708b61

truffleruby-21.1.0-ubuntu-18.04 works fine though: https://github.com/sporkmonger/addressable/runs/2988483622?check_suite_focus=true#step:5:13

**Comment by eregon** [comment]
Thanks for the report! We'll look into that.

**Comment by eregon** [comment]
The problem in the original example is that some of the Symbols get a BINARY encoding when reloaded:
```ruby
v = {:€a=>nil, :€c=>nil, :€h=>nil}
p v
r = Marshal.load(Marshal.dump(v))
p r
p r == v

p v.keys.map(&:encoding)
p r.keys.map(&:encoding)
```

```
{:"€a"=>nil, :"€c"=>nil, :"€h"=>nil}
{:"€a"=>nil, :"\xE2\x82\xACc"=>nil, :"\xE2\x82\xACh"=>nil}
false
[#<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>]
[#<Encoding:UTF-8>, #<Encoding:ASCII-8BIT>, #<Encoding:ASCII-8BIT>]
```

**Comment by eregon** [comment]
@dentarg I tried to reproduce but the addressable specs pass for me locally.
Unclear why they failed in that CI run.
