### ISSUE TITLE
stringex: tests are running very slow

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1625]
It takes almost 25 minutes (beside ~5 minutes in MRI 2.5.5) to pass all tests in TruffleRuby 1.0.0-rc13. I don't think there would be a reason being so slow.

To reproduce:

```
git clone https://github.com/rsl/stringex.git
cd stringex
bundle
bundle exec rake
```

**Comment by nirvdrum** [comment]
As an initial observation, I ran the tests with TruffleRuby 1.0.0-rc13 and 1.0.0-rc14. Both take ~12 minutes to run the tests on my machine. In contrast, MRI 2.6.2 takes ~7 seconds. Both versions of TruffleRuby also experienced a compiler error while JITting. So, there's certainly some interesting going on here.

**Comment by deepj** [comment]
@nirvdrum any news in this? I'm just curious what you found out :)

**Comment by nirvdrum** [comment]
There were some issues with the JIT trying to compile too much code. One fix landed in Graal, but we probably need another one in TruffleRuby. I got sidetracked from this issue to prepare for and attend RubyKaigi. I'll take a look at it again shortly.

**Comment by deepj** [comment]
@nirvdrum thanks! I'm just curious about this :) The fix in Graal is in RC16 or it will occur in the next release?

**Comment by nirvdrum** [comment]
I'm looking at this again. Here are updated numbers I'm seeing on a Ryzen 3700X\* with Ubuntu 20.04:

| Runtime | Time |
|-------------|-------------|
| MRI 2.6.6 | 5.7s |
| TruffleRuby CE Native - 20.2.0-dev-17701a09 | 2m 45.7s |
| TruffleRuby CE JVM - v20.2.0-dev-17701a09 | 3m 45.2s |

MRI is clearly faster still, but the execution time on TruffleRuby has improved markedly over the course of the past year. I'll have to profile to see where the time is currently being allocated.


\* Please note that when I ran the numbers a year ago, I was running with a Ryzen 2700X and probably Ubuntu 18.10, but given both CPUs are in the same microarchitecture, I'm attributing nearly all of the gains to improvements in TruffleRuby and Graal.

**Comment by petenorth** [comment]
@nirvdrum If you are looking at performance can you try with `--experimental-options --engine.Mode=latency --engine.LanguageAgnosticInlining=false` . It would be interesting to have independent check on using these flags.

**Comment by nirvdrum** [comment]
@petenorth 

Here's what I measured on truffleruby-native 20.2.0-dev-17701a09 (same as [my comment from two days ago](https://github.com/oracle/truffleruby/issues/1625#issuecomment-644467845)):

| Options | Time|
|------------|--------|
| --experimental-options --engine.LanguageAgnosticInlining=false | 2m 1.8s |
| --experimental-options --engine.Mode=latency | 3m 37.1s |
| --experimental-options --engine.Mode=latency --engine.LanguageAgnosticInlining=false | 60.7s |

**Comment by eregon** [comment]
It's surprising that `--engine.Mode=latency` with the default inlining isn't faster.
It looks like the new default inlining doesn't respect `--engine.Mode=latency` and still inlines.

**Comment by gogainda** [comment]
> @petenorth
> 
> Here's what I measured on truffleruby-native 20.2.0-dev-17701a09 (same as [my comment from two days ago](https://github.com/oracle/truffleruby/issues/1625#issuecomment-644467845)):
> Options 	Time
> --experimental-options --engine.LanguageAgnosticInlining=false 	2m 1.8s
> --experimental-options --engine.Mode=latency 	3m 37.1s
> --experimental-options --engine.Mode=latency --engine.LanguageAgnosticInlining=false 	60.7s

My results are:
| Options | DescTimeription |
| --- | --- |
| default | 222 seconds |
| --experimental-options --engine.Mode=latency | 80 seconds|
| --experimental-options --engine.Mode=latency --engine.LanguageAgnosticInlining=false | 77 seconds|

Overall results are quite impressive performance wise

**Comment by gogainda** [comment]
Latest results:
```
Finished in 36.501179 seconds.
```

**Comment by eregon** [comment]
@gogainda That's with no special flags and using the nightly builds, right?
Thank for the update.

I think 36 seconds is good enough, at least for this use case, and we improved ~40x since the first report here, so I think we can close this.

**Comment by gogainda** [comment]
@eregon no extra args, yes
