### ISSUE TITLE
gem install rugged failed {linking shared-object rugged/rugged.su}

### ISSUE THREAD

**Issue by TisonKun** [oracle/truffleruby#1642]
[gem_make.txt](https://github.com/oracle/truffleruby/files/3032397/gem_make.txt)

```
linking shared-object rugged/rugged.su
Could not find a search path for git2 -- passing libgit2.dylib on to Sulong
/Users/tison/.sdkman/candidates/java/1.0.0-rc-13-grl/jre/languages/ruby/lib/cext/linker.rb:67:in `process_args': Unknown argument: -framework (RuntimeError)
	from /Users/tison/.sdkman/candidates/java/1.0.0-rc-13-grl/jre/languages/ruby/lib/cext/linker.rb:21:in `main'
	from /Users/tison/.sdkman/candidates/java/1.0.0-rc-13-grl/jre/languages/ruby/lib/cext/linker.rb:150:in `<main>'
make: *** [rugged.su] Error 1
```

**Comment by TisonKun** [comment]
ref #1400 #1088 
cc @eregon

**Comment by TisonKun** [comment]
a workaround is welcome too

**Comment by eregon** [comment]
Thank you for the report.
This is a current limitation of the linker we plan to address by using the native linker.
I don't see where `-framework` is passed or `have_framework` is used in `rugged` though.

Could you share your command to install rugged? Did you system libraries?

**Comment by TisonKun** [comment]
`gem install rugged` I don't use a bundle `libgit2`

**Comment by eregon** [comment]
`gem install rugged` succeeds on master:
```
$ gem i rugged          
Building native extensions. This could take a while...
Successfully installed rugged-0.28.3.1
1 gem installed
```

**Comment by TisonKun** [comment]
Thanks for your update!

**Comment by eregon** [comment]
@TisonKun FYI, TruffleRuby 19.3.0 was releases and fixes this.

**Comment by TisonKun** [comment]
@eregon Thanks for your working~
