### ISSUE TITLE
Hash#merge doesn't keep order when value of given key is changed

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1650]
This different behaviour causes some troubles in `Hanami::Controller` specs.

TruffleRuby 1.0.0 RC15:

```ruby
{ id: 21, foo: true, bar: false }.merge(id: 23)
# => {:foo=>true, :bar=>false, :id=>23}

{ id: 21, foo: true, bar: false }.merge(id: 23, foo: false)
# => {:bar=>false, :id=>23, :foo=>false}
```

MRI 2.6.2

```ruby
{ id: 21, foo: true, bar: false }.merge(id: 23)
# => {:id=>23, :foo=>true, :bar=>false}

{ id: 21, foo: true, bar: false }.merge(id: 23, foo: false)
# => {:id=>23, :foo=>false, :bar=>false}
```

**Comment by deepj** [comment]
@nirvdrum Hello, would this be possible "fix" into RC16, please? 😸

**Comment by aardvark179** [comment]
I've now got a fix for this that I'm testing in CI.

**Comment by nirvdrum** [comment]
@deepj Sorry for not getting back to you sooner. I was traveling for a conference when you pinged me. It looks like @aardvark179 has taken care of this. We should get the fix into master soon.

**Comment by aardvark179** [comment]
The fix for this has now been merged.
