### ISSUE TITLE
refrigerator tests are running 50x slower than in MRI

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1658]
> Refrigerator offers an easy way to freeze all ruby core classes and modules.

To reproduce

```
git clone https://github.com/jeremyevans/ruby-refrigerator.git
cd ruby-refrigerator
rake
```

TruffleRuby 1.0.0 RC16 nightly (9cda04fc)

```
Run options: --seed 14103

# Running:

.....

Finished in 54.748976s, 0.0913 runs/s, 0.1827 assertions/s.

5 runs, 10 assertions, 0 failures, 0 errors, 0 skips
```

MRI 2.6.2

```
Run options: --seed 59354

# Running:

.....

Finished in 1.100139s, 4.5449 runs/s, 9.0898 assertions/s.

5 runs, 10 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by chrisseaton** [comment]
The performance of the build I gave you will have different performance characteristics to normal - I'll close this but can you re-open if you see it in the actual RC?

**Comment by deepj** [comment]
@chrisseaton OK.

RC15

```
Run options: --seed 62158

# Running:

.....

Finished in 14.071152s, 0.3553 runs/s, 0.7107 assertions/s.

5 runs, 10 assertions, 0 failures, 0 errors, 0 skips
```

True, it's faster in RC15 over the nightly build. Still significantly slower over MRI

**Comment by chrisseaton** [comment]
Yes, tests in general work against the whole idea of how people optimise Ruby. For example it applies to JRuby as well, but TruffleRuby is an improvement.

* MRI 0.983689s
* JRuby 20.214842s
* TruffleRuby 10.069473s
