### ISSUE TITLE
Roda#define_roda_method and problem with arity

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1669]
Honestly, I don't get into this metaprograminng much https://github.com/jeremyevans/roda/blob/master/lib/roda.rb#L173

Due to some "difference" in TruffleRuby this [spec](https://github.com/jeremyevans/roda/blob/master/spec/define_roda_method_spec.rb#L198) fails on `ArgumentError: wrong number of arguments (given 1, expected 0)`

To reproduce:

```
git clone https://github.com/jeremyevans/roda.git
cd roda
bundle
ruby -Ilib -Itest spec/define_roda_method_spec.rb
```

Error:

```
Run options: --seed 15104

# Running:

....E...........

Finished in 0.661358s, 24.1926 runs/s, 219.2459 assertions/s.

  1) Error:
Roda.define_roda_method#test_0015_should ignore keyword arguments for expected_arity 1:
ArgumentError: wrong number of arguments (given 1, expected 0)
    (eval):1:in `_roda_x_10'
    spec/define_roda_method_spec.rb:198:in `test_0015_should ignore keyword arguments for expected_arity 1'

16 runs, 145 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by deepj** [comment]
@eregon is it possible to take a look at this in near future? :)

**Comment by bjfish** [comment]
A smaller example which I think reproduces this failure:
```
def a(&block)
    p block.arity
end
a {|b:2| [b, 1]}
```
Expected
```
0
```
Actual
```
1
```

**Comment by deepj** [comment]
Closed due to I'm not welcome anymore in Ruby community

**Comment by gogainda** [comment]
Roda gem is [supported](https://github.com/jeremyevans/roda/pull/196) now

**Comment by ssnickolay** [comment]
Thanks @gogainda !
