### ISSUE TITLE
mathn: RuntimeError (External function @nurat_canonicalization cannot be found. (LLVMLinkerException)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1670]
To reproduce:

```
$ gem install mathn

require 'mathn'
```

Error:

```
Traceback (most recent call last):
        7: from ~/.rubies/truffleruby-1.0.0-nightly/bin/irb:31:in `<main>'
        6: from (irb):1
        5: from ~/.rubies/truffleruby-1.0.0-nightly/lib/mri/rubygems/core_ext/kernel_require.rb:130:in `require'
        4: from ~/.rubies/truffleruby-1.0.0-nightly/lib/mri/rubygems/core_ext/kernel_require.rb:130:in `require'
        3: from ~/.gem/truffleruby/2.6.2/gems/mathn-0.1.0/lib/mathn.rb:49:in `<top (required)>'
        2: from ~/.rubies/truffleruby-1.0.0-nightly/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require'
        1: from ~/.rubies/truffleruby-1.0.0-nightly/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require'
RuntimeError (External function @nurat_canonicalization cannot be found. (LLVMLinkerException))
Translated to internal error
```

**Comment by eregon** [comment]
Thanks for the report.
Could you explain in which context the `mathn` gem is installed?
It's a stdlib traditionally, so it doesn't need to be gem installed (but it can and we should probably support it).

**Comment by deepj** [comment]
This is a part deprecated `sass` gem, in this context of their specs. I'm chasing why I can't load any page in Rails app in TruffleRuby. Instead of that it starts handing up while processing assets.

**Comment by eregon** [comment]
FWIW, `sassc` should run now, and all specs except 1 pass for me locally.

**Comment by deepj** [comment]
Yes, I know about that. I still think it'd be "fixed".

**Comment by eregon** [comment]
Actually this is a special case, `mathn` was removed as a stdlib since Ruby 2.5.
I thought it was the general issues than default gems can also be installed manually, but it's not.
I didn't know you could still install mathn it as a gem.

I'm not sure what's the priority of fixing this. It will depend on what uses it I think.
I guess if it only happens in specs of a deprecated gem (sass), and since the `mathn` gem itself [is deprecated](https://github.com/ruby/mathn),  it would be rather not urgent and low priority.

**Comment by eregon** [comment]
> I'm chasing why I can't load any page in Rails app in TruffleRuby. Instead of that it starts handing up while processing assets. So I wanted to run `sass` specs and get if I'll something find out.

In the case you could share that Rails app or a reproduction (in a different issue), that would be very useful.

It's definitely more exciting than trying to support a monkey-patching library that has been deprecated for many years now (`mathn`). As a current workaround to run other specs, you could try just removing the `require 'mathn'` in `sass`'s specs and in their Gemfile.

**Comment by deepj** [comment]
@eregon I see. I'll try something later the next week. Unfortunately, the most apps are under NDA. This concrete app is in field of a film industry.

**Comment by deepj** [comment]
@eregon I can give an access to one application (it's just a torso, any of NDA apps). It's easy demonstrate the issues which ones I'm facing. I can be more specific via DM on Twitter.

**Comment by deepj** [comment]
Closed due to I'm not welcome anymore in Ruby community

**Comment by eregon** [comment]
We have no plan to support `mathn` currently, unless it becomes used in real non-deprecated code.
Also mathn no longer works on CRuby 3.1.3, so we're "compatible" now:
```
$ gem i mathn
Fetching mathn-0.1.0.gem
Building native extensions. This could take a while...
Successfully installed mathn-0.1.0
1 gem installed
$ ruby -rmathn -e0
<internal:/home/eregon/.rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- cmath.rb (LoadError)
	from <internal:/home/eregon/.rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/eregon/.rubies/ruby-3.1.3/lib/ruby/gems/3.1.0/gems/mathn-0.1.0/lib/mathn.rb:45:in `<top (required)>'
	from <internal:/home/eregon/.rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/home/eregon/.rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/home/eregon/.rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
<internal:/home/eregon/.rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- mathn (LoadError)
	from <internal:/home/eregon/.rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
```
