### ISSUE TITLE
rom-sql specs have abnormal usage of memory

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1674]
Yes, the most specs fail.

![Screenshot 2019-04-19 at 15 51 37](https://user-images.githubusercontent.com/33736/56427339-025ba180-62ab-11e9-9342-ecc3dd645ef2.png)

To reproduce:

```
git clone https://github.com/rom-rb/rom-sql.git
cd rom-sql
git checkout truffleruby
bundle exec rake spec
```

This requires PostgreSQL and MySQL running +

```
psql -c 'create database rom_sql;' -U postgres
mysql -u root -e 'create database rom_sql;'
```

**Comment by deepj** [comment]
@eregon I guess this can be closed. Now the memory is 1 GB and below. But another problem with these specs they are very very slow. TruffeRuby-dev (25 minutes) vs MRI 2.7. (4m 30s)

**Comment by eregon** [comment]
Let's close this then. If that's too slow to e.g. add TruffleRuby in CI then please open another issue.
