### ISSUE TITLE
Some BigDecimal constants are still missing

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1684]
There are many BigDecimal constants missing in TruffleRuby. E.g. `BigDecimal::INFINITY` or `BigDecimal::NAN` See the recent constants available https://ruby-doc.org/stdlib-2.6.3/libdoc/bigdecimal/rdoc/BigDecimal.html

**Comment by nirvdrum** [comment]
I could only find 3 that are missing:

* `BigDecimal::NaN`
* `BigDecimal::INFINITY`
* `BigDecimal::VERSION`

Are there others you've found are missing as well? You wrote that many are missing, so I want to make sure I'm not overlooking anything.

**Comment by deepj** [comment]
@nirvdrum sorry, `some` would be more proper word to be used here :)

**Comment by nirvdrum** [comment]
@deepj I've added the missing constants and added specs to ensure that they're both defined and have the proper value. You can find the fix in fdea7b265b1a4fc42258a1c9ba56f798c92ba160. This will be part of the 20-beta1 release.
