### ISSUE TITLE
Infinity#to_d causes ArgumentError (java.lang.NumberFormatException)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1685]
This causes several failing tests in Rails 6 ActiveModel tests https://github.com/rails/rails/blob/6-0-stable/activemodel/test/cases/validations/numericality_validation_test.rb#L27

This would returns `Infinity` instead of the exception.

To reproduce:

```ruby
require 'bigdecimal/util'
(1.0 / 0.0).to_d
```

Error:

```
Traceback (most recent call last):
        4: from ~/.rubies/truffleruby-1.0.0-rc16/bin/irb:31:in `<main>'
        3: from (irb):3
        2: from ~/.rubies/truffleruby-1.0.0-rc16/lib/mri/bigdecimal/util.rb:48:in `to_d'
        1: from ~/.rubies/truffleruby-1.0.0-rc16/lib/truffle/bigdecimal.rb:314:in `BigDecimal'
ArgumentError (java.lang.NumberFormatException)
```

**Comment by nirvdrum** [comment]
Thanks for the report! I've fixed the issue in 93a4054853268324ef46da2de5e16934faaf877c. Unfortunately I didn't pick up this issue until the next release was already in code freeze, so you won't see it until the release after that one.
