### ISSUE TITLE
Proc#>> and << are not supported

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1688]
This is a new feature in Ruby 2.6. The proc's function composition is used in `dry-monads` spec when 2.6 is available. See https://github.com/dry-rb/dry-monads/blob/6ca973c87c65e1526bfd4b671a8229319ce00bb1/spec/unit/maybe_spec.rb#L53

This causes some troubles to run some specs in TruffleRuby "supporting Ruby 2.6"

**Comment by aardvark179** [comment]
Yes, spotted that one. :smile:

There's a couple of other small issues that need fixing as well.

**Comment by deepj** [comment]
@aardvark179 yeah, I know about them. I don't report everything :) This issue is reported after ~2 months what I know about it.

**Comment by deepj** [comment]
@eregon @chrisseaton Hello, can you make this priority since this uses a lot of specs in dry-types/dry-schemas, please?

**Comment by chrisseaton** [comment]
Fix on the way.

**Comment by chrisseaton** [comment]
Fixed in 70722f6784cd1ac6ec9714bba2fbe44d22db3141.
