### ISSUE TITLE
Ripper.new(code) - `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)

### ISSUE THREAD

**Issue by Mogztter** [oracle/truffleruby#1692]
Maybe it's related to https://github.com/oracle/truffleruby/issues/1585 but the following code throws an exception in TruffleRuby 19:

```rb
require 'ripper'

p Ripper.new("print 'hello world'")
```

```console
$ rvm use truffleruby-19.0.0
Using /Users/guillaumegrossetie/.rvm/gems/truffleruby-19.0.0
$ ruby test.rb
test.rb:3:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from test.rb:3:in `new'
	from test.rb:3:in `<main>'
```

```console
$ rvm use ruby-2.6@asciidoctor
Using /Users/guillaumegrossetie/.rvm/gems/ruby-2.6.3
$ ruby test.rb
#<Ripper:0x00007fdc1b12fc38>
```

Ripper is used in [Temple](https://github.com/judofyr/temple) which is used in [Haml](https://github.com/haml/haml) which is used in [Asciidoctor](https://github.com/asciidoctor/asciidoctor) 😉 

https://github.com/judofyr/temple/blob/7987ab67af00a598eb3d83192415371498a0f125/lib/temple/static_analyzer.rb#L58

**Comment by chrisseaton** [comment]
Yes unfortunately ripper is currently unsupported.

https://github.com/oracle/truffleruby/blob/vm-19.0.0/doc/user/compatibility.md#standard-libraries

**Comment by Mogztter** [comment]
Thanks for the blazing fast response.

Would you be willing to add a no-op constructor and a no-op method `parse` in https://github.com/oracle/truffleruby/blob/master/lib/truffle/ripper.rb ? (similar to what's done with `Ripper::Filter`)

**Comment by chrisseaton** [comment]
Yes we can more no-ops. Until we properly support ripper we aim to just work as if you were passing an empty source file.
