### ISSUE TITLE
Failing async-io specs

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1702]
From https://github.com/oracle/truffleruby/issues/1646
cc @ioquatix 

First issue is `rb_enc_sprintf` not yet implemented, I have a trivial fix for that.
With that fixed, specs no longer hang and I get
```
111 examples, 20 failures
```

Some of these issues were already mentioned by @aardvark179 in https://github.com/oracle/truffleruby/issues/1646#issuecomment-483231395

**Comment by ioquatix** [comment]
Nice, I look forward to trying this out.

**Comment by eregon** [comment]
`rb_enc_sprintf` merged in a986766980f6ce8860de337953196854ea6a8436.

**Comment by eregon** [comment]
I removed extra public methods on IO in 1a6aa8d9c89cbde180d13460d86519967230d666.
Still needs some Socket fixes to handle `exception: false`, going through CI.

**Comment by eregon** [comment]
And Socket APIs now support `exception: false` in fa9863de004da4b982ec9c0ce58924e6ee08a111.
That's all that's required to pass all `async-io`'s specs when running on my machine.
When 20.0.0-beta2 is released, we can remove TruffleRuby from allowed failures in TravisCI.
@ioquatix Thanks for the help getting them passing.

**Comment by ioquatix** [comment]
Awesome!

**Comment by ioquatix** [comment]
When can you release `20.0.0-beta2`?

**Comment by eregon** [comment]
@ioquatix Not sure yet, I'll ping you here when it's released.
