### ISSUE TITLE
ArgumentErrors when interacting with other languages in `irb`

### ISSUE THREAD

**Issue by fniephaus** [oracle/truffleruby#1709]
```
$ irb --jvm --polyglot
irb(main):001:0> Polyglot.eval('python', 'a + b')
Traceback (most recent call last):
        3: from $GRAALVM_HOME/jre/languages/ruby/bin/irb:31:in `<main>'
        2: from (irb):1
        1: from (irb):1:in `eval'
ArgumentError (Current context is not yet initialized or already disposed.)
irb(main):002:0> Polyglot.eval('js', '1 + 2')
Traceback (most recent call last):
        3: from $GRAALVM_HOME/jre/languages/ruby/bin/irb:31:in `<main>'
        2: from (irb):4
        1: from (irb):4:in `eval'
ArgumentError (Multi threaded access requested by thread Thread[Ruby Thread id=18 from Ruby-reference-processor,5,main] but is not allowed for language(s) js.)
irb(main):003:0> Polyglot.eval('regex', '1 + 2')
=> #<Foreign:0x4f169009 proc>
```

For some reason, interacting with `regex` seems to work fine, but I'm not sure that's actually allowed (isn't `regex` an internal language?).

*Tested with GraalVM CE 19.0.0 and TruffleRuby 2.6.2 on macOS.*

**Comment by eregon** [comment]
Thank you for the report, these are 2 separate issues:

> ArgumentError (Current context is not yet initialized or already disposed.)

Seems an exception specific to using GraalPython. We should investigate, but I'd guess it's something to fix on the Python side.

> ArgumentError (Multi threaded access requested by thread Thread[Ruby Thread id=18 from Ruby-reference-processor,5,main] but is not allowed for language(s) js.)

Is specific to languages which disallow multithreading, and JS is one of them. This happens when there is more than one Ruby thread, which is the case in IRB. The second thread here is the finalizer thread, we might be able to fix that. A workaround here is to use
`ruby --jvm --polyglot --single-threaded -S irb`.

**Comment by eregon** [comment]
This seems to just work in 19.1.0:
```
$ ruby -v
truffleruby 19.1.0, like ruby 2.6.2, GraalVM CE Native [x86_64-linux]
$ irb --jvm --polyglot
irb(main):001:0> Polyglot.eval('python', '1 + 2')
=> 3
irb(main):002:0> Polyglot.eval('js', '1 + 2')
=> 3
irb(main):003:0> Thread.list
=> [#<Thread:0x1ea8@main run>]
```

So I'll close this, but feel free to reopen if there are still issues.

The fact that JS work is because there is only a single Ruby thread.
The workaround above is the more reliable solution for now when doing interop with JS (using `--single-threaded`).

**Comment by eregon** [comment]
I also improved the error message when interacting with single-threaded languages like JS in 3b698b1a4bf9b168891f1f795858eb550c258bc7.
