### ISSUE TITLE
report Thread#status incompatible with MRI

### ISSUE THREAD

**Issue by wangyin-git** [oracle/truffleruby#1718]
```ruby
threads = []
20.times do
    threads << Thread.new do
      gets     #no input all the time
    end
end

sleep 5

pp threads.map{|th| th.status}
```
in MRI 2.6.3 all thread.status returns 'sleep'
in Truffleruby-19.1.0 or Truffleruby-1.0.0-rc16 only one thread.status returns 'sleep', others return 'run'

**Comment by eregon** [comment]
I can reproduce.
The process also doesn't finish correctly with that program (threads are stuck in `monitorEnter`).

Note that with threads just calling `sleep`, the output is the same as MRI:
```ruby
threads = []
20.times do
    threads << Thread.new do
      sleep # gets     #no input all the time
    end
end

sleep 5

pp threads.map{|th| th.status}
```

So this seems specific to `gets`.

**Comment by wangyin-git** [comment]
Thanks for your reply. And I find another minor difference from MRI:  Thread.report_on_exception is false in Truffleruby by default, but since MRI 2.5 the default is true

**Comment by eregon** [comment]
I fixed `Thread.report_on_exception` to now be true by default in 32740381ca2f0bb015264a51eaf45903d83f407d, thanks for the comment.

**Comment by andrykonchin** [comment]
Cannot reproduce the issue on master, so close for now:

```
jt -q ruby -v test.rb
truffleruby 24.1.0-dev-2651959c*, like ruby 3.2.2, Interpreted JVM [x86_64-darwin]
["sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep",
 "sleep"]
```
