### ISSUE TITLE
msgpack: Global variable rb_tr_true is declared but not defined

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1729]
See https://travis-ci.com/socketry/falcon/jobs/217858985

**Comment by eregon** [comment]
@deepj Thanks for the report.
This is a duplicate of #1715, which will be fixed in the next release, and can be worked around until then by removing the cache in TravisCI.

**Comment by eregon** [comment]
@ioquatix Could you clear the cache on TravisCI for `falcon`?

**Comment by ioquatix** [comment]
Sure

**Comment by ioquatix** [comment]
Cleared cache and running it again: https://travis-ci.com/socketry/falcon/jobs/218052935

**Comment by eregon** [comment]
TruffleRuby 19.2.0 was release and fixes this bug, please try it.
