### ISSUE TITLE
Installation failure ruby-build with macOS

### ISSUE THREAD

**Issue by hsbt** [oracle/truffleruby#1733]
I'm going to add 19.1.1 definition to ruby-build. But I couldn't install truffleruby-19.1.1(and 19.1.0) to my macOS 10.14.6 environment.

It fails openssl build with `./lib/truffle/post_install_hook.sh`. I'm not sure why it failed because I could install it a few weeks ago.

mkmf.log is here: https://gist.github.com/hsbt/482726643f45e92b48304ad85956ffbe

What's do I next step for investigation? /cc @eregon

**Comment by eregon** [comment]
Please do not add 19.1.1 to `ruby-build`, there is no difference with 19.1.0 for the TruffleRuby standalone (see https://github.com/rvm/rvm/pull/4740#issuecomment-513757515).

```
/private/var/folders/jl/zgy9fk353nd6zn0xznlsdzvc6gxzs5/T/ruby-build.20190803171558.7572/truffleruby-19.1.1/lib/cext/include/truffleruby/truffleruby-pre.h:29:10:
 fatal error: 'ctype.h' file not found
#include <ctype.h> // isdigit
```

This looks like the missing C headers on macOS.
@chrisseaton @lukasstadler @rschatz What's the solution for this on the latest macOS?

**Comment by eregon** [comment]
@hsbt Do the instructions for installing system headers at https://github.com/oracle/truffleruby/blob/master/doc/user/installing-llvm.md#development-tools-and-system-headers work for you?

**Comment by hsbt** [comment]
@eregon After the following instruction, I could install truffleruby.

```
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

I wonder why I need it because I already install it ago. Can we invoke above command each updating `CommandLineTools` on macOS?

**Comment by eregon** [comment]
It seems unfortunately that every macOS update removes the system headers, and so they need to be re-installed again after every update. We're looking at finding a more permanent solution to this issue.

**Comment by hsbt** [comment]
I see. I try to re-install them the next minor upgrade of macOS.

Thanks!

**Comment by lukasstadler** [comment]
FWIW, I fixed this problem (header files not being in standard locations any more in Mojave) by defining `SDK_ROOT`:
```
export SDKROOT=`xcrun --show-sdk-path
```

**Comment by brodock** [comment]
> FWIW, I fixed this problem (header files not being in standard locations any more in Mojave) by defining `SDK_ROOT`:
> 
> ```
> export SDKROOT=`xcrun --show-sdk-path
> ```

didn't work for me... xcrun seems to not be doing what we expect it to do:

```
xcrun --show-sdk-path                                                                                                                          
xcodebuild: error: SDK "`xcrun" cannot be located.
xcodebuild: error: SDK "`xcrun" cannot be located.
xcrun: error: unable to lookup item 'Path' in SDK '`xcrun'
```

**Comment by eregon** [comment]
@brodock There was a missing final backquote above, I edited the command.
BTW, the next TruffleRuby release (on Nov 19) will use `xcrun` automatically, so it's less error-prone.
