### ISSUE TITLE
RuntimeError: rb_io_set_nonblock not implemented

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1741]
How about 'rb_io_set_nonblock'.  I got a #<RuntimeError: rb_io_set_nonblock not implemented>

ruby version:
truffleruby 19.1.0, like ruby 2.6.2, GraalVM CE Native [x86_64-linux]

_Originally posted by @wangyin-git in https://github.com/oracle/truffleruby/issues/1730#issuecomment-519807723_

**Comment by bjfish** [comment]
This is now implemented at eca449347e2e011bd36565be01a81d6d86a69fed.
