### ISSUE TITLE
Lots of WARNING: negative line number warnings not supported in #class/module_eval

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1742]
For example, in AsciiDoctor's CI: https://travis-ci.org/asciidoctor/asciidoctor/jobs/576533763:
```
[ruby] WARNING: negative line number (__TEMPLATE__):-8 not supported in #class/module_eval - will be reported as starting at 1
...
```

We should try to figure what uses negative line numbers and how to make this work, so there is no need to warn.

**Comment by deepj** [comment]
This issue is a duplicate of https://github.com/oracle/truffleruby/issues/1481 and then https://github.com/oracle/truffleruby/issues/1482

**Comment by eregon** [comment]
@deepj Thanks for the links, I forgot about them when filing this issue.
ERB itself should work fine, but indeed with `tilt` or other cases setting the line number to a negative value it's still a problem.

I'll close this in favor of #1482.
