### ISSUE TITLE
Not all specs are configured properly to run on a release build

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#1746]
I'm trying to run all specs on a proper release artefact.

It turns out this isn't possible - for example `spec/truffle/launcher_spec.rb` has specs that try to use the `--options-log`, which isn't allowed in a release build unless you also use `--experimental-options`.

We haven't noticed this problem yet as so far the only place we have been running all specs is a development build. The Docker test for releases only runs fast specs, which hides the issue as specs with options need to run a sub-Ruby and so also happen to be tagged as slow.

```
$ graalvm-ce-19.2.0/Contents/Home/bin/ruby --log.level=CONFIG --options-log -e 14
ERROR: Option '--options-log' is experimental and must be enabled via '--experimental-options'
Do not use experimental options in production environments.
```

```
$ jt ruby --log.level=CONFIG --options-log -e 14
Using Interpreted TruffleRuby: mxbuild/truffleruby-jvm
$ ...../mxbuild/truffleruby-jvm/jre/languages/ruby/bin/ruby \
  --experimental-options \
  --core-load-path=..../src/main/ruby/truffleruby \
  --log.level=CONFIG \
  --options-log \
  -e \
  14
[ruby] CONFIG: option load-paths=
[ruby] CONFIG: option required-libraries=
[ruby] CONFIG: option working-directory=
[ruby] CONFIG: option debug=false
[ruby] CONFIG: option verbose=FALSE
[ruby] CONFIG: option source-encoding=
[ruby] CONFIG: option internal-encoding=
...
```

The solution is possibly to modify specs to have all the required flags, but I get a _lot_ of failures and it's a lot to work through.

**Comment by chrisseaton** [comment]
> How do you run the specs?

With binary tarballs, with our `ruby` on `$PATH` and then

```
ruby spec/mspec/bin/mspec --config spec/truffle.mspec --excl-tag fails --excl-tag graalvm --excl-tag aot --excl-tag slow
```

I'll use the workaround and I'll send a PR in to fix the specs at some point.

**Comment by eregon** [comment]
@chrisseaton Is this fixed with https://github.com/oracle/truffleruby/pull/1782 ?

**Comment by chrisseaton** [comment]
Yes. 

There's some weird GitHub or browser bug going on here which caused me to mention #1749 instead.

![ezgif-1-3fd122adde1f](https://user-images.githubusercontent.com/341094/70948862-51352300-2054-11ea-9a6d-3311aa065b78.gif)
