### ISSUE TITLE
hamlit: performance degraded due to missing Ripper.lex

### ISSUE THREAD

**Issue by k0kubun** [oracle/truffleruby#1747]
I added truffleruby support of Hamlit in https://github.com/k0kubun/hamlit/pull/145, but it disabled various optimizations because `Ripper.lex` is not available in truffleruby.

It also complicated its implementation to guard against missing `Ripper.lex`. I really want truffleruby to support `Ripper.lex`, to make it easier to maintain the truffleruby support. Is there any plan to support `Ripper.lex`?

related to: https://github.com/oracle/truffleruby/issues/1712

**Comment by eregon** [comment]
Thank you again for adding TruffleRuby support in Hamlit.

We'll try to support `Ripper.lex`, it's one of the few missing stdlibs remaining: https://github.com/oracle/truffleruby/blob/master/doc/user/compatibility.md#standard-libraries

I expect there are no major issues to implement it, we can probably use a similar approach to JRuby as we share basically the same lexer and parser.

**Comment by eregon** [comment]
Relates to https://github.com/oracle/truffleruby/issues/1585

**Comment by bjfish** [comment]
@k0kubun `Ripper` has now been implemented and `Ripper.lex` is supported. Please let us know if you have any issues.
