### ISSUE TITLE
AOT tags don't seem to be needed any more

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#1748]
I test against a tarball AOT image, and I can run all specs not marked as `fails`, including those tagged as `aot` - I think this tag could be removed.

After working around #1746, the only spec I now can't run on a binary tarball is 'Requiring C extensions concurrently is thread-safe'. I've tagged that as a failure and now run without any tags set apart from `fails`.

**Comment by eregon** [comment]
`spec/truffle/nfi_spec` still seems to fail for `spec/truffle/nfi_spec.rb` (trying with 19.2.0.1 and master), it hard exits:
```
$ mspec -t ruby spec/truffle/nfi_spec.rb
$ ruby /home/eregon/code/mspec/bin/mspec-run spec/truffle/nfi_spec.rb
truffleruby 19.2.0.1, like ruby 2.6.2, GraalVM CE Native [x86_64-linux]
[- |                   0%                     | 00:00:00]      0F      0E org.truffleruby.language.control.RaiseException: error in callback from native code! (RuntimeError)
zsh: exit 99    mspec -t ruby spec/truffle/nfi_spec.rb
```

**Comment by chrisseaton** [comment]
Ah, sorry I figured out that `truffle.mspec` sets to exclude `aot` automatically for native. So you don't need to set the exclude - it's always set in native mode - but you still need the specs tagged.

**Comment by eregon** [comment]
Yes, all tags should be automatic with `truffle.mspec` except `fails`.

**Comment by eregon** [comment]
I removed all tags except that one in https://github.com/oracle/truffleruby/commit/622abfce0718cb93face31d7c19970f033ecd0c8 and did a bit more cleanup related to tags.
