### ISSUE TITLE
Slack/Discourse for Truffleruby community (?)

### ISSUE THREAD

**Issue by tomajask** [oracle/truffleruby#1752]
I was looking for a slack or discourse where Truffleruby users could discuss their topics. Is there anything like this available? 

It could help to popularize Truffleruby faster amongs the developers community, I think.

**Comment by eregon** [comment]
There is a Gitter room currently:
https://gitter.im/graalvm/truffleruby

We are working on a better communication platform and will introduce it soon.

**Comment by tomajask** [comment]
Thanks @eregon for letting know 🙂 I'm looking forward to see this new platform then 🤞

**Comment by eregon** [comment]
A Slack is now available for GraalVM in general and there is a `#truffleruby` channel.

> Hi everyone. Due to popular demand we’re moving GraalVM channels to a GraalVM community Slack workspace.
> It has been set up and has the same channels as here (and more). To join the workspace, use this link: https://join.slack.com/t/graalvm/shared_invite/enQtNzk0NTc5MzUyNzg5LTAwY2YyODQ4MzJjMGJjZGQzMWY2ZDA3NWI3YzEzNDRlNGQ1MTZkYzkzM2JkYjIxMTY2NGQzNjUxOGQzZGExZmU
> We hope this transition wouldn’t be too much trouble and will help to make our communication easier.

We still need to update links in the README about it.

**Comment by deepj** [comment]
@eregon What to consider Discord? E.g. artichoke uses it for their community https://github.com/artichoke/artichoke#discussion

For me it has multiple pros over Slack (better native client for main platforms including for iOS or Android)

**Comment by eregon** [comment]
> We still need to update links in the README about it.

The link is in the README and it's been publicly announced now, so I think we can close this issue.

> @eregon What to consider Discord? E.g. artichoke uses it for their community https://github.com/artichoke/artichoke#discussion

Slack is what we use at work, so it's a lot more convenient for us to use it for community too.
I find the Slack client on Android quite good (and so much better than Gitter).

**Comment by chrisseaton** [comment]
Slack is what quite a lot of the community seems to already use internally - Oracle, Shopify, AdoptOpenJDK, etc. So in terms of apps open, it's much more convenient for these people.
