### ISSUE TITLE
jt docker build with --source flag fails 

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#1758]
I tried to build a new Docker image to pick up some fixes  but the the `jt docker build truffleruby-latest --source` command fails with

```
Step 24/36 : RUN cd graal-jvmci-8 && JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac)))) mx build
 ---> Running in 0e7aae326d49
/bin/sh: which: command not found
readlink: missing operand
Try 'readlink --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
Could not find a JDK >=1.8.0_141 and <1.9
The following JDKs are available:
  /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-1.el7_7.x86_64
Specify one with the --java-home or --extra-java-homes option or with the JAVA_HOME or EXTRA_JAVA_HOMES environment variable.
Or run `/test/mx/select_jdk.py -p /test/graal-jvmci-8` to set and persist these variables in /test/graal-jvmci-8/mx.jvmci/env.
The command '/bin/sh -c cd graal-jvmci-8 && JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac)))) mx build' returned a non-zero code: 1
```
The offending line is

https://github.com/oracle/truffleruby/blob/master/tool/jt.rb#L2347

Fundamentally the slim linux base image doesn't have the `which` command installed.

```
FROM oraclelinux:7-slim
RUN which anything
```

**Comment by eregon** [comment]
Thank you for the report.

We don't use the `--source` Dockerfile frequently, at least building JVMCI from source seems unusual, nowadays most people would use https://github.com/graalvm/openjdk8-jvmci-builder/releases.
We should fix it.

Do you specifically want to build TruffleRuby in a Docker image, or building TruffleRuby on your host system would be fine for you? We definitely support the latter better.

**Comment by petenorth** [comment]
I think it will be easier enough to work around (using the `print` option and then manually working with the  Dockerfile).

Thanks.

**Comment by petenorth** [comment]
I no longer have a need to build from source within a Dockerfile since nightly builds are now made available

https://github.com/ruby/truffleruby-dev-builder/releases

Here are some example `Dockerfile` using these nightly builds

`https://github.com/petenorth/bundle-install-memory/blob/master/Dockerfile-rails-truffleruby`

or

`https://github.com/petenorth/schools-experience/blob/master/Dockerfile-truffleruby-head`

**Comment by eregon** [comment]
Thanks for updating this issue. I removed the `--source` flag in https://github.com/oracle/truffleruby/commit/700154a8dfc1bbed34bd211508374e202e198602 since it was not working.
In the future we can add a development Dockerfile if there is demand for it, but I would recommend to indeed use nightly builds or build on the host machine as those are more convenient.
