### ISSUE TITLE
`jt dis` is defunct

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#1762]
Use `jt mx llvm-dis` instead.

**Comment by eregon** [comment]
Do you think we should document this anywhere or just remove the method in `jt`?

**Comment by chrisseaton** [comment]
Just removing would be fine I think - we don't want to proxy every `mx` command into `jt`.

**Comment by eregon** [comment]
I fixed this in 56610ec48ded517e6f63717949a9ecee63a18362 along with documentation updates for the toolchain.
