### ISSUE TITLE
New LLVM toolchain produces code not supported by Sulong

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#1763]
I know the team are already aware of this as discussed on other channels, but I'll open it for the record.

We used to compile `-O0` and `opt -mem2reg`. The new toolchain does `-O1`. This produces different bitcode - for example a chain of `if` becoming a `switch` with bitcode that Sulong does not support.

@eregon already reduces to a minimal test case `gem install json + jt ruby -e 'gem "json"; require "json"; puts $"; p JSON.dump(a: 1)'`.

```
...../cext_ruby.rb:20:in `generate': Truffle doesn't have a case for the com.oracle.truffle.llvm.runtime.nodes.op.LLVMCompareNodeFactory$LLVMEqNodeGen node with values of type  java.lang.Long=4 com.oracle.truffle.llvm.runtime.pointer.LLVMPointerImpl (TypeError)
    from com.oracle.truffle.llvm.runtime.nodes.op.LLVMCompareNodeFactory$LLVMEqNodeGen.executeAndSpecialize(LLVMCompareNodeFactory.java:680)
    from com.oracle.truffle.llvm.runtime.nodes.op.LLVMCompareNodeFactory$LLVMEqNodeGen.executeCompare(LLVMCompareNodeFactory.java:150)
    from com.oracle.truffle.llvm.runtime.nodes.control.LLVMSwitchNode$LLVMSwitchNodeImpl.executeIsCase(LLVMSwitchNode.java:100)
```

**Comment by rschatz** [comment]
Should be fixed on `graal` master (https://github.com/oracle/graal/commit/c5164fbd9a4c5ffca043294aa95065d1cd13c9f6). The fix will be in 19.3.0.

**Comment by chrisseaton** [comment]
Thank you very much.

**Comment by eregon** [comment]
Regression test added in dc1d6807f930e9b57ba0ddf06751bb00706bb194
