### ISSUE TITLE
Cannot load more than one byte from RSTRING_PTR

### ISSUE THREAD

**Issue by XrXr** [oracle/truffleruby#1772]
I'm trying to run [google-protobuf](https://rubygems.org/gems/google-protobuf) on TruffleRuby. The gem contains a C extension that computes a hash code off of Ruby strings, and TruffleRuby does not execute the hash function correctly.

I have reduced the code down to a simple demo extension here that you can play with: https://gist.github.com/XrXr/d7a07623330c244cb3b13bcae5f9530e.
As you can see in the output, TruffleRuby reads out a single byte instead of the expected four.
The hash function in protobuf is here: https://github.com/protocolbuffers/protobuf/blob/c08b7512cf9d65899e8e84edd02d4335a64b11b0/ruby/ext/google/protobuf_c/upb.c#L2007

Digging into the code RSTRING_PTR returns a polyglot object, which only supports single byte loads:
https://github.com/oracle/truffleruby/blob/3541dcec2f50e0fc3fa93c3c09fd83b0f294314d/lib/truffle/truffle/cext.rb#L164
https://github.com/oracle/truffleruby/blob/25e3533e699021b51b264efa12b9d5fe901a65be/src/main/java/org/truffleruby/cext/CExtNodes.java#L1063

Related, Sulong computes the index into the polyglot object in an undesirable way: 
https://github.com/oracle/graal/blob/cbee70bd6f3e0c487e1340ace299eb3813596922/sulong/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/interop/access/LLVMInteropReadNode.java#L72
The division makes it so that the byte being read out in a multiple-byte load isn't necessarily the byte at that address.

**Comment by eregon** [comment]
Thank you for this excellent bug report and investigation.

I guess we need to tell Sulong that our `RStringPtr` object needs to be addressed byte-wise.

**Comment by eregon** [comment]
Filed as a Sulong bug internally as GR-19473.

**Comment by eregon** [comment]
This is fixed with 9a22abd0844caae6ce1329dd39c08707235c96ba and 1bf2f6ac641454dae8498adb49bae15dc6b804db, by always returning a native pointer for `RSTRING_PTR`. It will be in the 20.0 release. Thank you for the bug report!
