### ISSUE TITLE
Having a problem while installing gems: (NullPointerException)

### ISSUE THREAD

**Issue by dixpac** [oracle/truffleruby#1806]
I've just started with `truffleruby`. I managed to install GraalVM and truffleruby with rbenv. But when I want to install a gem I got this error:

<img width="1258" alt="Screenshot 2019-11-08 at 10 58 58" src="https://user-images.githubusercontent.com/7427365/68467604-cbcd8000-0216-11ea-9f7d-151b33110cac.png">

<img width="900" alt="Screenshot 2019-11-08 at 11 00 33" src="https://user-images.githubusercontent.com/7427365/68467728-07684a00-0217-11ea-98e8-ba210c1160c9.png">

I'm running on macOS Mojave

llvm is installed with brew: `llvm: stable 9.0.0 (bottled)`

Probably I've set-up something wrong, but if anyone can help it would be much appreciated :)

**Comment by eregon** [comment]
This is very likely due to using a too recent LLVM.
For TruffleRuby 19.2.x we recommend `llvm@4` from Homebrew.

The coming 19.3 release will fix this by shipping its own LLVM so it's always the right version.

**Comment by eregon** [comment]
@dixpac TruffleRuby 19.3.0 was released and should fix this.

**Comment by dixpac** [comment]
Thanks @eregon! Works like a charm now
