### ISSUE TITLE
rb_check_symbol_cstr is not yet implemented

### ISSUE THREAD

**Issue by larskanis** [oracle/truffleruby#1814]
pg-1.2.0 will probably introduce field names deliverable as symbols. In MRI there are two types of symbols: dynamic and static symbols. PG will primary use dynamic symbols per [`rb_check_symbol_cstr()`](https://github.com/ged/ruby-pg/pull/306/files#diff-631a3ecabfa0db95985789711f6ded8bR417-R422) , to allow GC'ing of field names. Static symbols on the other hand can lead to memory bloat if field names are dynamically generated.

Unfortunately Truffleruby [doesn't implement](https://github.com/oracle/truffleruby/blob/master/src/main/c/cext/ruby.c#L3286) `rb_check_symbol_cstr` so that [tests fail](https://travis-ci.org/larskanis/ruby-pg/jobs/612928577#L781) currently.

However the tests run fine on Truffleruby with static symbols allocated by [ID2SYM()](https://github.com/ged/ruby-pg/pull/306/files#diff-631a3ecabfa0db95985789711f6ded8bR425). 

So my questions are:
1. Does Truffleruby distinguish between static and dynamic symbols like MRI does?
2. Can I use `ID2SYM()` to allocate symbols on Truffleruby?
3. Will you support `rb_check_symbol_cstr()` to make pg-1.2.0 work?

**Comment by eregon** [comment]
Thanks for the bug report!

1. No, all Symbols are the same and GC'd.
2. Yes.
3. We will, but that will need to wait for the next release (20.0), so it would be helpful if pg can use ID2SYM() on TruffleRuby.

**Comment by larskanis** [comment]
Thank you @eregon ! I switched symbol allocation to `ID2SYM` in https://github.com/ged/ruby-pg/pull/306 on Truffleruby and it works great. So you could drop the "priority" flag from this issue.

**Comment by eregon** [comment]
@larskanis Thanks!
Using `rb_str_intern` always would work on both MRI and TruffleRuby, but that requires to allocate a temporary String so I guess that's why `rb_check_symbol_cstr` is used?

`rb_check_symbol_cstr` is mentioned in `extension.rdoc` and it seems useful for your case, so we'll implement it soon for compatibility.

**Comment by larskanis** [comment]
> requires to allocate a temporary String so I guess that's why rb_check_symbol_cstr is used?

Exactly! Most of the time the symbols are already allocated, so that we allocate strings only when necessary.

**Comment by eregon** [comment]
I implemented `rb_check_symbol_cstr` in 2aafcec9a83894d83100b202e358967be075c13c, it will be in the next release.

**Comment by larskanis** [comment]
Thank you @eregon ! Good to know it's in ruby spec now.
