### ISSUE TITLE
Method#>> and Method#<< are not supported

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1821]
This is supported in MRI 2.6 when proc composition was added.

```
truffleruby 19.3.0, like ruby 2.6.2, GraalVM CE Native [x86_64-darwin]
```

To reproduce:

```
$ ruby -e 'p = ->(x) { x }; def a(x); x; end; method(:a) >> p'
```

Error:

```
-e:1:in `<main>': undefined method `>>' for #<Method: Object(Object)#a -e:1>:Method (NoMethodError)
```

**Comment by bjfish** [comment]
Thanks for the bug report @deepj . This has been resolved at https://github.com/oracle/truffleruby/commit/192c776d1160343f8757bfbb8fe05dcc73c56678.
