### ISSUE TITLE
[interop] 'Internal error occured' instead of 'Unknown identifier' error

### ISSUE THREAD

**Issue by fniephaus** [oracle/truffleruby#1831]
For some reason, `invokeMember` exposes `PolyglotException`s when sending not-existing identifiers to Python objects. This may be a problem in GraalPython, but I've decided to open this here as the interaction between Javascript and Python seems to work fine.

#### Repro session

```
$ polyglot --shell --jvm
GraalVM MultiLanguage Shell 19.3.0
Copyright (c) 2013-2019, Oracle and/or its affiliates
  Python version 3.7.4
  Ruby version 2.6.2
ruby> Polyglot.eval("js", "[]").foo
Unknown identifier: foo (NoMethodError)
        at <ruby> <top (required)>(resource:/truffleruby/core/truffle/boot.rb:16:15-43)
        at <ruby> parsing-request(Unknown)
ruby> Polyglot.eval("python", "[]").foo
Internal error occured: org.graalvm.polyglot.PolyglotException: org.truffleruby.language.control.RaiseException: AttributeError: 'list' object has no attribute 'foo' (PException)
Translated to internal error (RuntimeError)
Run with --verbose to see the full stack trace.
ruby> js>
js> Polyglot.eval("python", "[]").foo == undefined
true
```

**Comment by eregon** [comment]
`Polyglot.eval("python", "[]").foo` is the same as `Polyglot.eval("python", "[]").foo()`.

You probably meant:
```
js> Polyglot.eval("python", "[]").foo
js> print(Polyglot.eval("python", "[]").foo)
undefined
ruby> Polyglot.eval("python", "[]")[:foo]
Unknown identifier: foo (NameError)
        at <ruby> <top (required)>(resource:/truffleruby/core/truffle/boot.rb:16:15-49)
        at <ruby> parsing-request(Unknown)
```

Which seems to work as expected.

OTOH, when calling the method foo():
```
js> Polyglot.eval("python", "[]").foo()
AttributeError: 'list' object has no attribute 'foo'

ruby> Polyglot.eval("python", "[]").foo()
Internal error occured: org.graalvm.polyglot.PolyglotException: org.truffleruby.language.control.RaiseException: AttributeError: 'list' object has no attribute 'foo' (PException)
Translated to internal error (RuntimeError)
Run with --verbose to see the full stack trace.
```
It seems the same for JS and Ruby, just that Ruby wraps the Python AttributeError in a RaiseException (= A Ruby exception).
The wrapping is a bug (we already know about it), but the real cause here is Python throwing `AttributeError` and not `UnknownIdentifierException` on `invokeMember()`.

**Comment by eregon** [comment]
@fniephaus I can't transfer this issue to https://github.com/graalvm/graalpython, so could you reopen it there?

I'll close this as I think the Ruby side is correct for this case.
Sorry for moving the issue around.

**Comment by fniephaus** [comment]
No worries, thanks for looking into this!
