### ISSUE TITLE
Active Record error in Blog 5 test

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#1832]
When I try and run the `test/truffle/ecosystem/blog5` application I get an exception when trying to add a post. 

```
I, [2019-11-27T10:33:30.561000 #58]  INFO -- : [ca3070a9-3f64-4931-9418-bafe75d64f92] Started POST "/posts" for 172.17.0.1 at 2019-11-27 10:33:30 +0000
I, [2019-11-27T10:33:30.581000 #58]  INFO -- : [ca3070a9-3f64-4931-9418-bafe75d64f92] Processing by PostsController#create as HTML
I, [2019-11-27T10:33:30.588000 #58]  INFO -- : [ca3070a9-3f64-4931-9418-bafe75d64f92]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"ETG4Y/77E5yJ54VWJ4L4E7qA/4P1UeYQc3Jg6ooQOxwy58az88nIIxeCu7lPTheGFtAfCgthlBrvjJ2A7tFq2A==", "body"=>"asd"}
D, [2019-11-27T10:33:30.627000 #58] DEBUG -- : [ca3070a9-3f64-4931-9418-bafe75d64f92]    (3.8ms)  begin transaction
D, [2019-11-27T10:33:30.664000 #58] DEBUG -- : [ca3070a9-3f64-4931-9418-bafe75d64f92]    (5.4ms)  rollback transaction
I, [2019-11-27T10:33:30.669000 #58]  INFO -- : [ca3070a9-3f64-4931-9418-bafe75d64f92] Completed 500 Internal Server Error in 78ms (ActiveRecord: 9.2ms)
F, [2019-11-27T10:33:30.698000 #58] FATAL -- : [ca3070a9-3f64-4931-9418-bafe75d64f92]   
F, [2019-11-27T10:33:30.699000 #58] FATAL -- : [ca3070a9-3f64-4931-9418-bafe75d64f92] ActiveRecord::StatementInvalid (ActiveRecord::Rollback: ActiveRecord::Rollback: rollback transaction):
F, [2019-11-27T10:33:30.700000 #58] FATAL -- : [ca3070a9-3f64-4931-9418-bafe75d64f92]   
F, [2019-11-27T10:33:30.702000 #58] FATAL -- : [ca3070a9-3f64-4931-9418-bafe75d64f92] app/controllers/posts_controller.rb:22:in `create'
```
I am testing via a Dockerfile

https://github.com/petenorth/truffleruby/blob/master/test/truffle/ecosystem/blog5/Dockerfile-5-truffleruby

To build and test

```
docker build -f Dockerfile-5-truffleruby -t blog-5:truffleruby . 
docker run -p 3000:3000 -e SECRET_KEY_BASE=stubbed blog-5:truffleruby
```

Prior to this error there is a failure to serve an image which seems to be to do with the assets pipeline but I do not believe it is impacting the error above.

```
F, [2019-11-27T10:33:23.594000 #58] FATAL -- : [da1d51f6-9f15-46de-8748-506b7c337410]   
F, [2019-11-27T10:33:23.596000 #58] FATAL -- : [da1d51f6-9f15-46de-8748-506b7c337410] ActionController::RoutingError (No route matches [GET] "/assets/github/li-chevron.png"):
F, [2019-11-27T10:33:23.597000 #58] FATAL -- : [da1d51f6-9f15-46de-8748-506b7c337410]   
F, [2019-11-27T10:33:23.600000 #58] FATAL -- : [da1d51f6-9f15-46de-8748-506b7c337410] actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
```

**Comment by petenorth** [comment]
So it looks as if the new post screen isn't rendering fields for title and author (or have I missed something). I have added a MRI version of  the Dockerfile to compare to in the my fork.

Would be nice if there was a working blog app to smoke test Rails in a truffleruby environment.

**Comment by eregon** [comment]
Thank you for the report.
The application is tested in our CI and seems to work fine there.

What's your `startup.sh` script?

**Comment by eregon** [comment]
There is no separate title and author fields, those are extracted from the main field, like such:
```
= Blog post
Author <email>

Body
```

I agree that's not intuitive, we should at least provide a default value for the main field.

**Comment by eregon** [comment]
Here is a screenshot of it working with `jt test ecosystem blog5` + `cd test/truffle/ecosystem/blog5 && bundle exec rails s`:
![Screenshot from 2019-11-28 18-07-25](https://user-images.githubusercontent.com/168854/69823704-f7d29480-1209-11ea-97c4-a8c1209bf351.png)

**Comment by petenorth** [comment]
@eregon Thanks that has sorted it - I'll try and get some timings out for the various Docker build stages vs MRI. Bundle installs are (as reported separately) much slower compared to MRI and running the assets pipeline is significantly slower.

An existing app works with TruffleRuby but full functional testing (via the suite of Cucumber tests) is currently not possible I think because of the memory demands of running the app via TruffleRuby and running the Cucumber tests via TruffleRuby.

**Comment by petenorth** [comment]
@eregon Here are the outputs from GNU Time using the docker files

https://github.com/petenorth/truffleruby/blob/master/test/truffle/ecosystem/blog5/Dockerfile-5-mri
https://github.com/petenorth/truffleruby/blob/master/test/truffle/ecosystem/blog5/Dockerfile-5-truffleruby

Both the elapsed time and resident memory are significantly larger for TruffleRuby. 

**time bundle install --without development**

MRI

46.50user 6.48system 1:16.09elapsed 69%CPU (0avgtext+0avgdata 304704maxresident)k
90232inputs+874224outputs (298major+4646566minor)pagefaults 0swaps

TruffleRuby

847.68user 190.48system 9:50.43elapsed 175%CPU (0avgtext+0avgdata 2112016maxresident)k
18056inputs+231408outputs (176major+56526711minor)pagefaults 0swaps

**time bundle exec rake assets:precompile SECRET_KEY_BASE=stubbed --trace**

MRI

8.76user 0.98system 0:08.45elapsed 115%CPU (0avgtext+0avgdata 104328maxresident)k
5968inputs+11872outputs (22major+171969minor)pagefaults 0swaps

TruffleRuby

319.12user 40.63system 2:33.58elapsed 234%CPU (0avgtext+0avgdata 2404748maxresident)k
872inputs+16392outputs (5major+11146840minor)pagefaults 0swaps
