### ISSUE TITLE
[interop] Array-like object do not implement `length` and other Array methods

### ISSUE THREAD

**Issue by fniephaus** [oracle/truffleruby#1844]
According to [the polyglot docs](https://github.com/oracle/truffleruby/blob/master/doc/user/polyglot.md#using-foreign-objects-from-ruby), foreign objects understand `size`, which is [an alias for `length`](https://docs.ruby-lang.org/en/2.4.0/Array.html#method-i-size). In fact, foreign arrays should appear as Ruby `Array`s and hence should also understand all other messages of [`Array`](https://docs.ruby-lang.org/en/2.4.0/Array.html). That would significantly improve portability of foreign code and it would be in line with what @chumer told me.

**Comment by eregon** [comment]
Agreed, this would make sense but will probably be quite some effort to make it work, especially considering `Array.public_instance_methods(false).size # => 104` and quite a few of these currently work on the internal Array representation directly.
Maybe we need a separate implementation of these methods for foreign arrays, which only support the array elements interop.

**Comment by eregon** [comment]
This is done now (https://github.com/oracle/truffleruby/issues/2149#issuecomment-899763303).
