### ISSUE TITLE
Enumerator::Chain.new(1..3, [4, 5]) causes TypeError

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1858]
This is a direct example from Ruby 2.6 documentation to `Enumerator::Chain` (https://ruby-doc.org/core-2.6/Enumerator/Chain.html). There is no issue under MRI. 

To reproduce:

```
ruby -e "Enumerator::Chain.new(1..3, [4, 5])"
```

Error:

```
-e:1:in `coerce_to_failed': Coercion error: [4, 5].to_sym => Symbol failed (TypeError)
	from -e:1:in `execute_coerce_to'
	from -e:1:in `coerce_to'
	from -e:1:in `initialize'
	from -e:1:in `new'
	from -e:1:in `<main>'
```

**Comment by bjfish** [comment]
Thanks, this is fixed at: 3b756ceddba635edb4a5673ab999a26f427074de.
