### ISSUE TITLE
Enumerator#+ is not supported

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1859]
Available since Ruby 2.6 (https://ruby-doc.org/core-2.6/Enumerator.html#method-i-2B)

To reproduce

```
ruby -e "e = (1..3).each + [4, 5]; puts e.to_a"
```

Error:

```
-e:1:in `<main>': undefined method `+' for #<Enumerator: 1..3:each>:Enumerator (NoMethodError)
```

**Comment by bjfish** [comment]
Thanks, this is fixed at: 3b756ceddba635edb4a5673ab999a26f427074de.
