### ISSUE TITLE
If the context cannot be patched we search for home twice

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#1878]
In `RubyContext#patch` and then in `RubyContext#<init>`.

The reason this is an issue is that warnings about the home get printed twice.

```
[ruby] WARNING: Truffle-reported home foo does not look like TruffleRuby's home
[ruby] WARNING: home foo guessed from executable foo/bin/ruby does not look like TruffleRuby's home
[ruby] WARNING: could not determine TruffleRuby's home - the standard library will not be available - set --home= or use --log.level=CONFIG to see details
[ruby] WARNING: Truffle-reported home foo does not look like TruffleRuby's home
[ruby] WARNING: home foo guessed from executable foo/bin/ruby does not look like TruffleRuby's home
[ruby] WARNING: could not determine TruffleRuby's home - the standard library will not be available - set --home= or use --log.level=CONFIG to see details
```

**Comment by eregon** [comment]
Right, I'm not sure what's a good way to avoid the warnings twice.
I would kind of expect them twice, since it's searched twice in two different RubyContext instances.

Is `--no-home-provided` a good enough workaround for these warnings?

**Comment by chrisseaton** [comment]
The fact that home can't be found is a bug in this case (the one I mentioned on Slack), so the warnings are correct and I don't want to work around them.

**Comment by eregon** [comment]
I think we can't reasonably fix this, doing the search in multiple context could potentially have different results.
If the home is not found, there is large problem, so that needs fixing anyway.

BTW, I recently cleaned up the home search in 19f457aea1cc324bde151b7a3465025573316376, it only ever tries the Truffle-reported home now, and always warn if not found.
