### ISSUE TITLE
The Rack test suite does not pass on TruffleRuby

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1898]
See https://github.com/rack/rack/issues/1579 and https://github.com/rack/rack/pull/1568#issuecomment-583856763.
Found by @ioquatix

**Comment by eregon** [comment]
OK, one issue is:
```
ruby -e 's=StringIO.new; p s.external_encoding; s.binmode; p s.external_encoding'
```
gives 
```
#<Encoding:UTF-8>
#<Encoding:ASCII-8BIT>
```
on MRI but
```
#<Encoding:UTF-8>
#<Encoding:UTF-8>
```
on TruffleRuby.

That's what causes `Rack::Lint#test_0005_notice error errors` to fail.

**Comment by ioquatix** [comment]
Is UTF-8 considered binary? I don't get it?

**Comment by eregon** [comment]
No it's not. It was a bug that `StringIO#binmode` didn't change the external encoding (and did nothing but return `self`):
https://github.com/oracle/truffleruby/blob/9e0b0468590ff77cb62e80e185b0474541dc6774/lib/truffle/stringio.rb#L201-L203

**Comment by ioquatix** [comment]
Haha, that's actually pretty funny :p

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/d5d3d0727ede8d5d899b42ebde6a9e0bfc993afe, waiting for a nightly to build, and then I'll make a PR to add truffleruby-head in rack's CI.
