### ISSUE TITLE
[interop] foreign null objects not handled correctly as falsy values

### ISSUE THREAD

**Issue by fniephaus** [oracle/truffleruby#1902]
# Repro:

```
$ polyglot --jvm --shell
GraalVM MultiLanguage Shell 19.3.0
  Python version 3.7.4
  Ruby version 2.6.2
ruby> if nil; puts "No!!" end
nil
ruby> if Polyglot.eval('python', 'None'); puts "No!!!" end
No!!! # not expected!
nil
ruby> Polyglot.eval('python', 'None').nil?
true
```

**Comment by eregon** [comment]
Should isNull() imply "false when converted to boolean"?

I agree for `None`, but unsure, e.g., for a pointer object which has an address of 0 and also implements isNull() for some reason, such as NFI `NativePointer`.

**Comment by fniephaus** [comment]
Intuitively, I would have expected a null pointer to behave as `false` in conditions. It would also return `true` for `nil?`, right?

**Comment by eregon** [comment]
Right, we handle `foreign.nil?` by sending `isNull()`.

Do you know if any other language does this?
Maybe we should add this in the JavaDoc of isNull()? cc @boris-spas @chumer

**Comment by fniephaus** [comment]
In GraalSqueak, we map `ForeignObject>>isNil` to `isNull()`. However, it's more common to use `ifNil:ifNotNil:`. That's also why the Squeak parser optimizes these cases by replacing `ifNil:` with a `nil` identity check, which is unfortunate because `nil` != Ruby's `nil` or Python's `None`.
