### ISSUE TITLE
How exactly I can install latest nightly builds on my local machine?

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#1903]
Before I was using rvm, but are nightly build available there?

**Comment by eregon** [comment]
I plan to integrate the nightlies in RVM, as mentioned in https://github.com/oracle/truffleruby/issues/1483#issuecomment-583606306.

Please follow that issue.
I'll close this one since it's basically a duplicate.

**Comment by gogainda** [comment]
Until it's implemented in rvm is there a way to install it locally?

**Comment by eregon** [comment]
`rvm mount` maybe: https://github.com/rvm/rvm/blob/master/help/mount.md
(in other managers, a simple `mv` would be enough, but not for RVM)

**Comment by eregon** [comment]
PR to RVM adding truffleruby-head: https://github.com/oracle/truffleruby/issues/1903
