### ISSUE TITLE
cppjieba_rb fails to install

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1911]
Reported by @samsaffron in https://twitter.com/samsaffron/status/1228476364388352001

Error:
```
$ gem install cppjieba_rb

internal.cc:48:5: error: cannot initialize a member subobject of type 'VALUE' (aka 'void *') with an rvalue of type 'int'
    RUBY_TYPED_FREE_IMMEDIATELY,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eregon/code/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/cext/include/ruby/ruby.h:1214:38: note: expanded from macro 'RUBY_TYPED_FREE_IMMEDIATELY'
#define RUBY_TYPED_FREE_IMMEDIATELY  1 /* TYPE field */
                                     ^
8 warnings and 1 error generated.
make: *** [Makefile:182: internal.o] Error 1
```

Code:
https://github.com/fantasticfears/cppjieba_rb/blob/5b3f0f210529fa5418b093c0a56ed7549e381057/ext/cppjieba_rb/internal.cc#L48

**Comment by eregon** [comment]
Interesting, this error seems to happen only in C++ code where it doesn't allow converting `1` to `void*`.
In C it seems to just convert it, since the same pattern is used in OpenSSL and that works fine:
https://github.com/oracle/truffleruby/blob/c24c4074a20b16b2e1968662cf7e62c55460231a/src/main/c/openssl/ossl_x509store.c#L114-L120

**Comment by eregon** [comment]
It's trivial to fix: https://github.com/eregon/truffleruby/commit/4cfea0bc10657b16617774a0070dc4fe70a98cde
After that, `gem install cppjieba_rb` works.

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/daa9b86594a597c767078df389147d01e187f84d

**Comment by SamSaffron** [comment]
btw... was about to test this @eregon  and I got

```
sam@arch discourse % ruby-install truffleruby-dev
*** Unknown truffleruby version dev. Proceeding anyways ...
>>> Installing truffleruby dev into /home/sam/.rubies/truffleruby-dev ...
>>> Installing dependencies for truffleruby dev ...
>>> Downloading https://github.com/oracle/truffleruby/releases/download/vm-dev/truffleruby-dev-linux-amd64.tar.gz into /home/sam/src ...
--2020-02-18 11:17:46--  https://github.com/oracle/truffleruby/releases/download/vm-dev/truffleruby-dev-linux-amd64.tar.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving github.com (github.com)... 13.236.229.21
Connecting to github.com (github.com)|13.236.229.21|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-18 11:17:46 ERROR 404: Not Found.

!!! Download of https://github.com/oracle/truffleruby/releases/download/vm-dev/truffleruby-dev-linux-amd64.tar.gz failed!

```

**Comment by eregon** [comment]
`ruby-install` doesn't support installing truffleruby nightly builds, see https://github.com/oracle/truffleruby/issues/1483#issuecomment-587009669
I'd suggest to use `ruby-build`, which works fine with `chruby` too.
