### ISSUE TITLE
Performance regression in bundle install

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#1918]
I think a performance regression has been introduced between

builds-20200217-190341

and 

builds-20200218-190334

A rails bundle install for the former takes 1 min 54 secs 

https://github.com/petenorth/bundle-install-memory/actions/runs/41924274 

and the latter takes 2 mins and 9 secs

https://github.com/petenorth/bundle-install-memory/actions/runs/41942419

The timings are pretty consistent (I noticed the timings had changed from previous runs)

From the date time stamps I think it might be this commit

https://github.com/oracle/truffleruby/commit/e8ccba872a3c3924cb51f4f59e417fa4fc0958d9

but I am not sure.

**Comment by eregon** [comment]
`ruby -v` shows the revisions, it's daa9b865...e8ccba87, so indeed only one PR is the difference: e8ccba87.

**Comment by eregon** [comment]
If I `bundle install` with an existing Gemfile.lock, I can't reproduce any meaningful difference locally:
```
$ /usr/bin/time -a .../truffleruby-head/bin/ruby --vm.XX:+PrintGCSummary -S bundle install
```

Feb17:
```
110.40user 5.28system 0:56.45elapsed 204%CPU (0avgtext+0avgdata 2647532maxresident)k
0inputs+172336outputs (34major+2460432minor)pagefaults 0swaps
/usr/bin/time -a  --vm.XX:+PrintGCSummary -S bundle install  110.41s user 5.29s system 204% cpu 56.454 total

111.83user 5.24system 0:57.02elapsed 205%CPU (0avgtext+0avgdata 2518260maxresident)k
0inputs+172336outputs (34major+2440391minor)pagefaults 0swaps
/usr/bin/time -a  --vm.XX:+PrintGCSummary -S bundle install  111.84s user 5.24s system 205% cpu 57.031 total

112.09user 5.31system 0:57.03elapsed 205%CPU (0avgtext+0avgdata 2509768maxresident)k
8inputs+172336outputs (34major+2444827minor)pagefaults 0swaps
/usr/bin/time -a  --vm.XX:+PrintGCSummary -S bundle install  112.10s user 5.31s system 205% cpu 57.038 total
```

Feb18:
```
113.66user 5.19system 0:58.60elapsed 202%CPU (0avgtext+0avgdata 2774916maxresident)k
0inputs+172336outputs (34major+2445212minor)pagefaults 0swaps
/usr/bin/time -a  --vm.XX:+PrintGCSummary -S bundle install  113.67s user 5.20s system 202% cpu 58.608 total

113.93user 5.22system 0:58.33elapsed 204%CPU (0avgtext+0avgdata 2801832maxresident)k
0inputs+172336outputs (34major+2414722minor)pagefaults 0swaps
/usr/bin/time -a  --vm.XX:+PrintGCSummary -S bundle install  113.94s user 5.22s system 204% cpu 58.335 total

111.69user 5.07system 0:57.41elapsed 203%CPU (0avgtext+0avgdata 2509836maxresident)k
0inputs+172336outputs (34major+2441092minor)pagefaults 0swaps
/usr/bin/time -a  --vm.XX:+PrintGCSummary -S bundle install  111.69s user 5.08s system 203% cpu 57.414 total
```

**Comment by eregon** [comment]
Similar, no significant difference if I also remove the `Gemfile.lock` everytime:
Feb17:
```
122.95user 5.22system 1:02.28elapsed 205%CPU (0avgtext+0avgdata 2819400maxresident)k
0inputs+172344outputs (34major+2430275minor)pagefaults 0swaps
/usr/bin/time -a  --vm.XX:+PrintGCSummary -S bundle install  122.96s user 5.23s system 205% cpu 1:02.29 total

122.28user 5.27system 1:02.06elapsed 205%CPU (0avgtext+0avgdata 2687380maxresident)k
8inputs+172344outputs (34major+2447271minor)pagefaults 0swaps
/usr/bin/time -a  --vm.XX:+PrintGCSummary -S bundle install  122.29s user 5.28s system 205% cpu 1:02.07 total
```
Feb18:
```
122.35user 5.11system 1:01.73elapsed 206%CPU (0avgtext+0avgdata 2472776maxresident)k
0inputs+172344outputs (34major+2461753minor)pagefaults 0swaps
/usr/bin/time -a  --vm.XX:+PrintGCSummary -S bundle install  122.35s user 5.12s system 206% cpu 1:01.74 total

121.49user 5.26system 1:02.50elapsed 202%CPU (0avgtext+0avgdata 2544964maxresident)k
0inputs+172344outputs (34major+2468245minor)pagefaults 0swaps
/usr/bin/time -a  --vm.XX:+PrintGCSummary -S bundle install  121.50s user 5.27s system 202% cpu 1:02.50 total
```

**Comment by eregon** [comment]
So this might be simply fluctuations from the GitHub Action runners, which most likely have no performance guarantees, being in the cloud and all.

Could you try to reproduce locally?
FWIW I ran this outside Docker, but I don't think it should matter.

If you want to reproduce on GitHub Actions, it would be better to run with both releases multiple times (e.g. 3) in the same job run, so at least it's the same machine.

I pushed https://github.com/ruby/truffleruby-dev-builder/commit/8d027bd526f77afd27820c2c66f2701fb4c6e2a7 so those builds should be available for at least a week.

**Comment by eregon** [comment]
One thing we should do at least is add a `bundle install` benchmark in our benchmark server to keep track of it over time.

**Comment by petenorth** [comment]
I have been re-running with and without the Gemfile.lock file on GitHub (and locally) and I think these are just fluctuations as you say.

Feel free to close but a benchmark would be useful as you say.

**Comment by petenorth** [comment]
Another suggestion for the benchmarking, split it into two (but run sequentially)

    env time bundle lock
    env time bundle install

I think that a regression might have occurred against a `bundle lock` benchmark but not `bundle install`

They do very different things (I think the lock does lots of yaml parsing?) and `bundle install` retrieves resources over the network.

**Comment by petenorth** [comment]
Looking at recent runs of of bundle install for rails the performance seems to have improved and is comparable if not better than the performance prior to https://github.com/oracle/truffleruby/commit/e8ccba872a3c3924cb51f4f59e417fa4fc0958d9

**Comment by eregon** [comment]
Thanks, I'll create an internal issue to track adding a benchmark for `bundle install`.

**Comment by eregon** [comment]
We now track the performance of `bundle install` on the https://github.com/oracle/truffleruby/tree/master/test/truffle/ecosystem/blog6 app (from `.gem` files to avoid network variance).
