### ISSUE TITLE
ArtiyException on C-extension

### ISSUE THREAD

**Issue by yosiat** [oracle/truffleruby#1925]
Hi!

I am the mainer of panko-serializer (https://github.com/yosiat/panko_serializer) and I am checking out truffleruby.

I am trying to get it passing the tests and they fail on ArtityExcpetion.

Here are the reproduction steps:
1. Install truffleruby (`truffleruby 20.0.0, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
`) using RVM
2. Clone https://github.com/yosiat/panko_serializer
3. Use `truffleruby` branch (https://github.com/yosiat/panko_serializer/tree/truffleruby) - this branch have commented gems (used for profiling) and code (oniguruma for example) which don't work in TruffleRuby but let's ignore that for now.
4. Run the following commands:
```
# This is how i implemented multiple rails testing and it's required
export RAILS_VERSION=6.0.0
bundle install
bundle exec rake
```
5. It should compile successfully and when the starts to run you will get this error: https://gist.github.com/yosiat/ea559d2b2fff83955263eeca36e5a43f

The error comes from Ruby which tries to set a value on C-backed struct.
Ruby code: https://github.com/yosiat/panko_serializer/blob/truffleruby/lib/panko/serialization_descriptor.rb#L28 
C method definition: https://github.com/yosiat/panko_serializer/blob/truffleruby/ext/panko_serializer/serialization_descriptor/serialization_descriptor.c#L175
C method: https://github.com/yosiat/panko_serializer/blob/truffleruby/ext/panko_serializer/serialization_descriptor/serialization_descriptor.c#L119

If more information/changes on my side needed, let me know.

**Comment by eregon** [comment]
Thank you for the nice issue report, we'll take a look.

**Comment by bjfish** [comment]
@yosiat I believe there is an extra unused parameter `type` for `sd_type_aref`:
https://github.com/panko-serializer/panko_serializer/blob/d1afc3607b6f6bbb29eb95b73a9ac89791170ae5/ext/panko_serializer/serialization_descriptor/serialization_descriptor.c#L125

So, the arity is not matching:
https://github.com/panko-serializer/panko_serializer/blob/d1afc3607b6f6bbb29eb95b73a9ac89791170ae5/ext/panko_serializer/serialization_descriptor/serialization_descriptor.c#L176

I think removing the `type` parameter should resolve this issue. Please re-open if there is still an issue.
