### ISSUE TITLE
Too deep inlining error when running ActionPack tests (Regexp.escape builtin)

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#1927]
The reproducer is summarized by the following workflow

https://github.com/petenorth/rails/blob/5-2-stable/.github/workflows/ruby.yml

I am not sure whether the test directory environment variable TEST_DIR is being respected since `dispatch` is not `journey` but still something is going wrong in a test.

Failure (truncated stack trace):
```
JsonParamsParsingTest#test_occurring_a_parse_error_if_parsing_unsuccessful [/home/runner/work/rails/rails/actionpack/test/dispatch/request/json_params_parsing_test.rb:83]:
Expected: JSON::ParserError
  Actual: NilClass

bin/rails test home/runner/work/rails/rails/actionpack/test/dispatch/request/json_params_parsing_test.rb:75

[truffle] opt fail         Regexp.escape (builtin)                                     |ASTSize            14 |Reason org.graalvm.compiler.core.common.PermanentBailoutException: Too deep inlining, probably caused by recursive inlining.
== Inlined methods ordered by inlining frequency:
org.truffleruby.core.regexp.RegexpNodes$QuoteNode.quote(VirtualFrame, Object) [491]
org.truffleruby.core.regexp.RegexpNodesFactory$QuoteNodeFactory$QuoteNodeGen.executeQuote(VirtualFrame, Object) [491]
org.truffleruby.core.string.StringNodesFactory$MakeStringNodeGen.executeMake(Object, Object, Object) [2]
org.truffleruby.language.objects.AllocateObjectNode.allocate(DynamicObject, Object[]) [1]
org.truffleruby.core.string.StringNodes$MakeStringNode.makeStringFromString(String, Encoding, CodeRange) [1]
com.oracle.truffle.object.ShapeImpl$DynamicObjectFactoryImpl.newInstance(Object[]) [1]
com.oracle.truffle.object.ShapeImpl.newInstance() [1]
org.truffleruby.language.objects.AllocateObjectNode.allocate(AllocationReporter, DynamicObjectFactory, Object[]) [1]
com.oracle.truffle.object.DynamicObjectImpl.<init>(Shape) [1]
com.oracle.truffle.object.ShapeImpl.getRoot() [1]

...
```

**Comment by eregon** [comment]
The too deep inlining compilation failure should be easy to fix.

Not sure about the test failing, that might possibly be due to using the pure-Ruby `json` stdlib.

**Comment by norswap** [comment]
The inlining failure was fixed in 83dd6abcbe5e9fb52ace355ad342b3009f4ead99
But as Benoit pointed out, that's probably not why the test fails.

**Comment by petenorth** [comment]
Well I will test the nightly build on the repo anyway and hopefully confirm that the inlining issue has gone away. 

Might be better to open a separate issue for the actual test failure.

**Comment by norswap** [comment]
Appreciate it!

I'll probably take a look at this next week, though it would be easier if you can point at some function behaving differently on MRI vs TruffleRuby rather than a whole Rails workflow.

**Comment by petenorth** [comment]
Have verified the inlining issue fix.

**Comment by petenorth** [comment]
@aardvark179 The issue as described in the issue title is resolved so think this issue can be resolved.
