### ISSUE TITLE
symbol matching not quite working

### ISSUE THREAD

**Issue by DamienRobert** [oracle/truffleruby#1933]
This is on truffleruby 20.0.0.

Doing `:foobar.match(/foobar/) { |m| puts "hello" }` does not execute the block.
Adding a `to_s` after `:foobar` does work.

**Comment by bjfish** [comment]
This is fixed at https://github.com/oracle/truffleruby/commit/5aff36289241ef132febeb10c26a39eccae50e4b. Thank you.
