### ISSUE TITLE
Float ArgumentError exception has different message but in MRI

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1945]
To reproduce:

```ruby
Float('foo')
```

TruffleRuby: `#<ArgumentError: invalid value for Float()>`
MRI: `#<ArgumentError: invalid value for Float(): "foo">`

Due to this difference some specs fail in `hanami-model`.

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/a19f208a4cfaaea6f6e3af90df470ce70fec98f8.
