### ISSUE TITLE
ruby2d: `ruby2d_window_ext_show': External LLVMFunction S2D_CreateWindow cannot be found. (LLVMLinkerException)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1947]
To reproduce:

```
gem install ruby2d
ruby -rruby2d -e 'show'
```

Error:

```
~/.gem/truffleruby/2.6.5/gems/ruby2d-0.9.4/ext/ruby2d/ruby2d.c:1057:in `ruby2d_window_ext_show': External LLVMFunction S2D_CreateWindow cannot be found. (LLVMLinkerException) (RuntimeError)
Translated to internal error
	from ~/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `ext_show'
	from ~/.gem/truffleruby/2.6.5/gems/ruby2d-0.9.4/lib/ruby2d/window.rb:392:in `show'
	from ~/.gem/truffleruby/2.6.5/gems/ruby2d-0.9.4/lib/ruby2d/window.rb:153:in `show'
	from ~/.gem/truffleruby/2.6.5/gems/ruby2d-0.9.4/lib/ruby2d/dsl.rb:32:in `show'
	from -e:1:in `<main>'
```

**Comment by deepj** [comment]
Closed due to I'm not welcome anymore in Ruby community

**Comment by eregon** [comment]
It works now!
![Screenshot from 2021-03-01 13-27-29](https://user-images.githubusercontent.com/168854/109497219-01444f80-7a92-11eb-948b-230e47d11206.png)
I believe due to 5f3339321c6bf3f30e7993101b2f2abce7f1b0f4.

**Comment by deepj** [comment]
I can't test it myself until solving https://github.com/oracle/truffleruby/issues/2181 :)

**Comment by eregon** [comment]
@deepj Wouldn't using Rosetta 2 work?
Maybe it's inconvenient because you would need to install the SDL2 libs in a amd64 Homebrew prefix?

**Comment by deepj** [comment]
@eregon I don't want to keep two versions of Homebrew. It's complicate and breaking many things from my experience. So I need to wait on a native version.

It seems Apple ARM64 port of JDK is near https://github.com/openjdk/jdk/pull/2200

BTW: Rosetta may be removed in the next version of macOS https://www.macrumors.com/2021/03/02/rosetta-macos-11-3-strings/
