### ISSUE TITLE
NoMethodError in case of calling private method has a slighly different message

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1957]
Due to this difference some `Hanami::Model` specs fail. It mainly expects `#<User:....`

TruffleRuby: 
```
private method `attributes' called for User (NoMethodError)
```
MRI:
```
private method `attributes' called for #<User:0x00007faf660934c8 @attributes={}> (NoMethodError)
```

To reproduce:

```ruby
class User
  def initialize(**params)
    @attributes = params
  end

  private

  attr_reader :attributes
end

p User.new.attributes
```

**Comment by eregon** [comment]
Thanks for the report, we should fix it.
Seriously though, gem tests shouldn't hardcode error messages from the Ruby implementation, which might change even between MRI versions.

**Comment by bjfish** [comment]
This is now fixed at https://github.com/oracle/truffleruby/commit/afa606312bfae442ca510c05daa27a8770de9e37
