### ISSUE TITLE
Frozen string literal modification error in place MRI doesn't

### ISSUE THREAD

**Issue by nateberkopec** [oracle/truffleruby#1964]
https://travis-ci.org/puma/puma/jobs/659981141#L432

We run all our CI jobs with --enable-frozen-string-literal. This [doesnt blow up](https://github.com/puma/puma/runs/494216825#step:6:16) when running Rubocop for us on MRI.

**Comment by eregon** [comment]
Thanks for the report.
This should be easier to iterate on now that we have nightly builds.

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/93a7fa3f0482d40a2ff7f97620aeec0c8f6f1a11. Thanks.

**Comment by eregon** [comment]
RuboCop passes now for Puma:
https://travis-ci.org/eregon/puma/jobs/660689923

But the tests not quite, part of it being related to `--enable-frozen-string-literal`
