### ISSUE TITLE
FrozenError when creating StringIO

### ISSUE THREAD

**Issue by nateberkopec** [oracle/truffleruby#1969]
https://travis-ci.org/github/puma/puma/jobs/662501844#L459

Bit of a weird one - we're blowing up just by calling `StringIO.new`?

**Comment by eregon** [comment]
Indeed:
https://github.com/oracle/truffleruby/blob/1237af4bea89465298d4225615750dbc3d0a5cc6/lib/truffle/stringio.rb#L74

That empty string literal becomes frozen with `--enable-frozen-string-literal`.

We need to add a magic frozen literal comment, either disabled, or enabled and look at all String literals in that file.

**Comment by eregon** [comment]
Run on TravisCI with this fix: https://travis-ci.org/github/eregon/puma/jobs/663021831

**Comment by eregon** [comment]
```
302 runs, 633 assertions, 3 failures, 5 errors, 23 skips
```
Not bad :)
