### ISSUE TITLE
This should consider Renaming to graalruby

### ISSUE THREAD

**Issue by frank-dspeed** [oracle/truffleruby#1970]
At present there is an ongoing effort to create graalphp there exists graaljs, graalpython

i think this should get named graalruby so it is more clear what this is truffle is a part of the GraalVM framework but I think it makes overall adoption more easy.

i raise a similar issue in fastr

**Comment by claudiug** [comment]
truffleruby is much nicer, and give also personality.

**Comment by eregon** [comment]
I believe most people know this project by the name TruffleRuby, so we are not going to rename the project at this time.

FWIW, we did consider a rename many years ago but even then it was already clear the name TruffleRuby was too established to change it.

It's also clear many Truffle/GraalVM languages don't follow the graal-language naming:
https://github.com/oracle/graal/blob/master/truffle/docs/Languages.md
https://gist.github.com/smarr/d1f8f2101b5cc8e14e12

Besides, this is a *Truffle* language implementation, part of GraalVM, so logically it would be `TruffleRuby` or `GraalVM Ruby` (too long).

**Comment by frank-dspeed** [comment]
you are some sense of right I feel mad about this.
