### ISSUE TITLE
gprc extconf.rb fails due to needing RbConfig::CONFIG['AR']

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1973]
On `gem install gproc`, the grpc `extconf.rb` fails with:
```
extconf.rb:28:in `<main>': undefined method `+' for nil:NilClass (NoMethodError)
```
code:
```ruby
if ENV['AR'].nil? || ENV['AR'].size == 0
    ENV['AR'] = RbConfig::CONFIG['AR'] + ' rcs'
end
```
Looks like we need a value for `RbConfig::CONFIG['AR']`.
I'll split that to a different issue.

_Originally posted by @eregon in https://github.com/oracle/truffleruby/issues/1917#issuecomment-601288437_

**Comment by shidel-dev** [comment]
@eregon I believe that it maybe missing `RbConfig::CONFIG['STRIP']` as well. I run into an issue related to this when I run `AR='ar rcs' bundle install` which gets past this AR issue.

It is related to this line https://github.com/grpc/grpc/blob/8b5b1755ec0adeca6d8d1473b95cd8840ed02d8c/src/ruby/ext/grpc/extconf.rb#L104

strip_tool is nil in the case of truffleruby

I get the following 
```
Stripping grpc_c.so
make: grpc_c.so: Command not found
Makefile:612: recipe for target 'strip' failed
make: *** [strip] Error 127
```

**Comment by bjfish** [comment]
`RbConfig::CONFIG['AR']` and `RbConfig::CONFIG['STRIP']` have now been added here: https://github.com/oracle/truffleruby/commit/b09f04ee890b6f7cf541bd30f3566bad4b23a0c5
