### ISSUE TITLE
Support the bigdecimal gem and its C extension

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1975]
This would ensure much better compatibility for BigDecimal, and avoid having to maintain our own BigDecimal implementation which is not fully compatible.

The trade-off is BigDecimal wouldn't work without enabling C extension support, but that doesn't seem a big concern currently.

**Comment by eregon** [comment]
The large number of issues regarding BigDecimal make it clear this would be a good move for compatibility: https://github.com/oracle/truffleruby/issues?q=is%3Aissue+bigdecimal

Right now `gem install bigdecimal` fails to compile, so we need to look at why.

**Comment by nirvdrum** [comment]
I know peak performance outweighs interpreter performance, but do you have a sense for how big a hit that would be?

**Comment by eregon** [comment]
Hard to know until we can actually compare.
With @aardvark179's work I think C extensions got decent peak performance, around MRI's speed for C extensions, and we can likely improve it further.
I would think BigDecimal isn't used that much during application startup, so maybe interpreter doesn't matter as much there.

**Comment by eregon** [comment]
Getting it to install is easy, getting `BigDecimal("3.14")` to work needed some work on RTypedData.
With my fixes this works:
```
gem install bigdecimal
ruby -rrubygems -e 'gem "bigdecimal", "2.0.0"; require "bigdecimal"; p BigDecimal("3.14")'
```

**Comment by bjfish** [comment]
`BigDecimal` is now implemented using the C extension at https://github.com/oracle/truffleruby/commit/aa11d31adb031302a3b9e04d95c0376858c86b72.
