### ISSUE TITLE
Puma CI fails when using Bundler 2

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1984]
See https://github.com/puma/puma/runs/553627450

```
/home/runner/.rubies/truffleruby-head/lib/mri/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version': You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)
	from /home/runner/.rubies/truffleruby-head/lib/mri/bundler/lockfile_parser.rb:95:in `initialize'
	from /home/runner/.rubies/truffleruby-head/lib/mri/bundler/definition.rb:83:in `new'
	from /home/runner/.rubies/truffleruby-head/lib/mri/bundler/definition.rb:83:in `initialize'
	from /home/runner/.rubies/truffleruby-head/lib/mri/bundler/dsl.rb:234:in `new'
	from /home/runner/.rubies/truffleruby-head/lib/mri/bundler/dsl.rb:234:in `to_definition'
	from /home/runner/.rubies/truffleruby-head/lib/mri/bundler/dsl.rb:13:in `evaluate'
	from /home/runner/.rubies/truffleruby-head/lib/mri/bundler/definition.rb:34:in `build'
	from /home/runner/.rubies/truffleruby-head/lib/mri/bundler.rb:135:in `definition'
	from /home/runner/.rubies/truffleruby-head/lib/mri/bundler.rb:101:in `setup'
	from /home/runner/.rubies/truffleruby-head/lib/mri/bundler/setup.rb:20:in `<top (required)>'
	from bin/puma:1:in `require'
	from bin/puma:1:in `<main>'
```
Which looks like the shipped bundler (which is Bundler 1) gets required instead of Bundler 2, when the `bundle install` before was done with Bundler 2.

It most likely happens since `ruby/setup-ruby` installs Ruby 2 by default if there is no `Gemfile.lock`:
https://github.com/ruby/setup-ruby/issues/38#issuecomment-606869460

cc @nateberkopec

**Comment by eregon** [comment]
I cannot reproduce the failure locally (with `truffleruby-jvm`).
For now let's use Bundler 1 in Puma's CI, there are other issues notably on Ruby 2.3 with Bundler 2:
https://github.com/puma/puma/pull/2214

**Comment by bjfish** [comment]
This may be related to #1987

**Comment by eregon** [comment]
FWIW, the failure on MRI 2.3 with Bundler 2 is most likely due to https://github.com/rubygems/rubygems/issues/3570#issuecomment-624348235

**Comment by eregon** [comment]
TruffleRuby now works fine with Bundler 2 when running in Puma's CI: https://github.com/eregon/puma/runs/647762836

#1987 and #1956 fixed this.

I'll make a PR to Puma to use the latest Bundler once the Ruby 2.3 bug is resolved (https://github.com/ruby/setup-ruby/issues/51).
