### ISSUE TITLE
BigDecimal(..., exception: false) doesn't work as intended

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#2002]
You can see the basic problem with this:

```ruby
require 'bigdecimal'
p BigDecimal('invalid', exception: false)
```

That'll return `nil` on MRI and `0.0` on TruffleRuby.

I tried to fix this, but it quickly started to look like a pretty bad rabbit hole. There's this whole code path in TruffleRuby for *strict*, which is set set when you set `exception: false` but it's not tested, and in MRI *strict* seems to be at some point a different option to *e*, meaning the `exception:` keyword argument.

Perhaps the better option is to go ahead and use the C extension as in https://github.com/oracle/truffleruby/issues/1975? But I'm not positive that we can make `BigDecimal` fully external as other specialisations refer to it.

This bug is a problem on real production code - for example https://github.com/Shopify/money/commit/1e1748d38b2e6289614585a3f2d3c80e23983f62#diff-e3a3ec1d1042d492e86d2e74c633e6a1R27.

**Comment by eregon** [comment]
Using the `bigdecimal` gem (with `truffleruby-dev`) seems to work for this case:
```
$ ruby -v
truffleruby 20.2.0-dev-af4c22ac, like ruby 2.6.5, GraalVM CE Native [x86_64-linux]

$ gem install bigdecimal
Fetching bigdecimal-2.0.0.gem
Building native extensions. This could take a while...
Successfully installed bigdecimal-2.0.0
1 gem installed

# Using the gem
$ ruby -rbigdecimal -e "p BigDecimal('invalid', exception: false)"
nil

# Not using the gem
$ ruby --disable-gems -rbigdecimal -e "p BigDecimal('invalid', exception: false)"
0.0
```

I'll try to run the bigdecimal specs & MRI tests with the gem and see if that works.

You can also try locally if `gem install bigdecimal` works for your use cases (it will get used by default as it's an upgraded default gem, doesn't even seem to need to be in the Gemfile).

**Comment by chrisseaton** [comment]
> I'll try to run the bigdecimal specs

I see 62 failures. Examples include things like `corrupt handle 0x2a` and `Missing LLVM builtin: llvm.usub.sat.i32`.

> it will get used by default as it's an upgraded default gem

This doesn't seem to be the case when you use `bundle exec` unfortunately.

But general functionality works and quite a lot of our CI passes.

**Comment by aardvark179** [comment]
The missing intrinsics are quite easy to implement, they are just saturating addition and substraction. However that still leaves over 20 failures from corrupt handles and other issues. The handles do seem genuinely broken, so either there is a code path that is failing to correctly shift and tag a value, or someting is directly manipulating those values and getting something wrong. The problem seems to show up well when raising to a power so I'll look at debugging that case

**Comment by bjfish** [comment]
`BigDecimal` is now implemented using the C extension and the example now works at https://github.com/oracle/truffleruby/commit/aa11d31adb031302a3b9e04d95c0376858c86b72
