### ISSUE TITLE
SyntaxError: unexpected tIDENTIFIER with RHS or-equal assignment

### ISSUE THREAD

**Issue by paddor** [oracle/truffleruby#2015]
This method runs in MRI, but fails with a `SyntaxError` on TruffleRuby:

```
def update_object(obj)
  parent = obj.parent ||= fetch_object_by_path obj.parent_path          # <-- unexpected tIDENTIFIER
  obj.resolve

  parent.set_component obj
end
```

**Comment by eregon** [comment]
JRuby 9.2.8.0 doesn't have that issue so we should look what we're missing in the parser or lexer to accept this code.

**Comment by eregon** [comment]
I've updated our parser to be based on JRuby 9.2.8.0, and this parses now since 723b4fa2c86e41a5b9176f43e5bb803f99550dfc.

**Comment by paddor** [comment]
@eregon dankä
