### ISSUE TITLE
`Enumerator::Yielder#yield` with multiple arguments issue

### ISSUE THREAD

**Issue by andrykonchin** [oracle/truffleruby#2016]
Looks like `Enumerator::Yielder#yield` with multiple arguments doesn't play well with `Enumerator#first` method. `Enumerator#first` returns only the first argument.

TBH I haven't found any related documentation and it isn't covered in the RubySpec tests suit but at least it breaks compatibility with MRI.

Expected behavior
```ruby
# ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin18]

enum = Enumerator.new { |y| y.yield(1, 2) }
enum.first
# => [1, 2]
```

Actual behavior
```ruby
# truffleruby 20.1.0, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]

enum = Enumerator.new { |y| y.yield(1, 2) }
enum.first
# => 1
```

**Comment by eregon** [comment]
Thanks for the report!

It would be helpful if you can write a spec for this in https://github.com/ruby/spec if you have time :)
Then I should be able to implement it based on that.

**Comment by andrykonchin** [comment]
Done

**Comment by LillianZ** [comment]
fixed by https://github.com/oracle/truffleruby/pull/2056
