### ISSUE TITLE
[interop] No parsing happening in RubyLanguage#parse(ParsingRequest request)

### ISSUE THREAD

**Issue by fniephaus** [oracle/truffleruby#2025]
`RubyLanguage#parse(ParsingRequest request)` does not actually parse Ruby source code. Instead, it returns a `RubyParsingRequestNode` and runs the parser as part of an evaluation request:

https://github.com/oracle/truffleruby/blob/c6b381257de8adb48658f68166c69d7bd82d5bba/src/main/java/org/truffleruby/RubyLanguage.java#L180-L184

This probably requires quite some refactoring, but it's necessary to support the instrumentation API and therefore tools built on top of it correctly.

**Comment by eregon** [comment]
Since currently RubyLanguage has ContextPolicy.EXCLUSIVE, probably we can just getCurrentContext(RubyLanguage.class) in `parse()`.
I'll try that.

**Comment by eregon** [comment]
This should be fixed with afc0f55.

Methods are translated lazily to Truffle nodes, but LazyRubyNode implement `materializeInstrumentableNodes()` which should help: https://github.com/oracle/truffleruby/blob/master/src/main/java/org/truffleruby/language/LazyRubyNode.java#L56
