### ISSUE TITLE
include within refine doesn't work

### ISSUE THREAD

**Issue by palkan** [oracle/truffleruby#2026]
Here is an example:

```ruby
module A
  def test
    "testo"
  end
end

class B
end

using(Module.new do
  refine B do
    include A
  end
end)

B.new.test #=> private method `test' called for ...
```

Reproduction is available here: https://github.com/palkan/ruby-compatibility-examples (see tests here https://github.com/palkan/ruby-compatibility-examples/actions).

Possible related to #1540.

**Comment by ssnickolay** [comment]
i'll take a look at it

**Comment by eregon** [comment]
Interesting case, I didn't know you could `include` inside `refine`.
There is probably no ruby/spec for it, would be good to add one.
It seems the way it behaves (would be good to check in MRI source code) is not adding anything to ancestors, but rather just taking every method of `A` and adding it in the refinement.

**Comment by palkan** [comment]
> There is probably no ruby/spec for it

Looks like this one:
https://github.com/ruby/spec/blob/d282303a2ab863df38fd16d6ba94ca9ab459c7f0/core/module/refine_spec.rb#L256-L270

**Comment by eregon** [comment]
Interesting, and it seems we "pass" that spec when running the whole file, but not when running it in isolation:
```
$ jt -u ruby test -e "looks in included modules from the refinement then" spec/ruby/core/module/refine_spec.rb

1)
Module#refine method lookup looks in included modules from the refinement then FAILED
Expected "foo" == "foo from included module"
to be truthy but was false
/home/eregon/code/truffleruby-ws/truffleruby/spec/ruby/core/module/refine_spec.rb:294:in `block (3 levels) in <top (required)>'
/home/eregon/code/truffleruby-ws/truffleruby/spec/ruby/core/module/refine_spec.rb:4:in `<top (required)>'
```

Probably best to define anonymous class & module for that example, to avoid any global state.

**Comment by ssnickolay** [comment]
Yeah, I'm surprised how tests for refinements are written. I think we should create anonymous class & module for _each_ of examples of this scope.

**Comment by eregon** [comment]
Note it's perfectly fine to modify specs directly in this repo (I sync the changes from/back to ruby/spec).
But yeah for bigger refactoring of specs better to be its own PR, or PR to ruby/spec directly.
We'll just need to modify this spec so we can reliably test this failing case.

**Comment by ssnickolay** [comment]
I agree, it looks like independent steps:
1) Fix the error in this repo & add small test to prove the fix; Merge 
2) Modify `ruby/spec` tests; Merge
3) At the next synchronization, remove the redundant test (from the current repo) from step 1

**Comment by eregon** [comment]
Sounds good. My thinking was to just modify this specific spec example in PR 1, and then apply the same change in PR 2 + for other specs. Then there is no step 3.

**Comment by ssnickolay** [comment]
Ah, in your case, synchronization will not be needed. Perfect :+1:

**Comment by eregon** [comment]
I believe #2033 fixes this, thanks @ssnickolay!
