### ISSUE TITLE
CI failures for async-container

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2045]
See https://github.com/socketry/async-container/pull/12 and
https://github.com/socketry/async-container/runs/852715495

On issue is:
```
ArgumentError: wrong number of arguments (given 1, expected 0)
  /home/runner/work/async-container/async-container/lib/async/container/error.rb:34:in `initialize'
  /home/runner/work/async-container/async-container/lib/async/container/thread.rb:171:in `new'
  /home/runner/work/async-container/async-container/lib/async/container/thread.rb:171:in `raise'
```
seems to be caused by TruffleRuby passing an argument to [the exception constructor](https://github.com/socketry/async-container/blob/643d889af4b027a0189b8fb11579b8ade467bd58/lib/async/container/error.rb#L34) for Thread#raise (Kernel#raise is fine).
The caller is https://github.com/socketry/async-container/blob/643d889af4b027a0189b8fb11579b8ade467bd58/lib/async/container/thread.rb#L171

Can be reproduced with `ruby -e 'class E<Exception; def initialize(); end; end; Thread.current.raise E'`.

cc @ioquatix

**Comment by ioquatix** [comment]
Thanks for taking a look at this.

**Comment by eregon** [comment]
The `Thread#raise` issue is fixed in d8f759e6dd3ccb17b63becbc133bc5f81eca316d.

@ioquatix Could you switch to `truffleruby-head` in CI to see if it's fixed now and whether there are other issues?

**Comment by ioquatix** [comment]
Made a PR here: https://github.com/socketry/async-container/pull/19

**Comment by eregon** [comment]
The [only failure left](https://github.com/socketry/async-container/pull/19#issuecomment-660469759) seems some missing handling of SIGHUP in async-container for threaded containers, so I think we can close this issue.

**Comment by ioquatix** [comment]
This seems to fix the HUP issue, at least locally.

https://github.com/socketry/async-container/commit/74cc92b5fc64019b6e6b0ab547caf8f980d760ec

Not sure why it should be necessary though?

**Comment by eregon** [comment]
You're right, that's a difference:
```
MRI 2.6.6:
$ ruby -e 'Thread.new { sleep 1; `kill -HUP #{$$}` }; begin; sleep; rescue Exception => e; p e; end'
#<SignalException: SIGHUP>

TruffleRuby-dev:
$ ruby -e 'Thread.new { sleep 1; `kill -HUP #{$$}` }; begin; sleep; rescue Exception => e; p e; end' 
zsh: hangup     ruby -e 
```
Similar for e.g., SIGUSR2.

So it seems CRuby has signal handlers for all (?) signals and transforms them in SignalException, and if they bubble up to the main thread, then re-sends the signal (after disabling the custom signal handlers?).
We do the second part in https://github.com/oracle/truffleruby/blob/9f03f3c84387257dee80c1fa74b7a52deed2007c/src/main/java/org/truffleruby/language/exceptions/TopLevelRaiseHandler.java#L64 but not the first part, [except for SIGINT](https://github.com/oracle/truffleruby/blob/9f03f3c84387257dee80c1fa74b7a52deed2007c/src/main/ruby/truffleruby/core/main.rb#L72-L79) (which is special, it's an `Interupt` and not `SignalException`)

If the signal is not caught, there is no difference:
```
MRI 2.6.6 and TruffleRuby-dev:
$ ruby -e 'Thread.new { sleep 1; `kill -HUP #{$$}` }; sleep'                                        
zsh: hangup     ruby -e 'Thread.new { sleep 1; `kill -HUP #{$$}` }; sleep'
```

Capturing all signals seems pretty bad for embedding or polyglot scenarios (Embeddings or other languages might want to use those signals).

I think explicit handling as you did in https://github.com/socketry/async-container/commit/74cc92b5fc64019b6e6b0ab547caf8f980d760ec is better and *de facto* more portable (JRuby seems to also not have a handler by default for such signals).
Do you think it's something worth supporting in TruffleRuby? I can extract this comment to an issue if so.

**Comment by eregon** [comment]
Extracted to https://github.com/oracle/truffleruby/issues/2051 as in general any behavior difference is something worth tracking as an issue: https://github.com/oracle/truffleruby/issues/2051

**Comment by ioquatix** [comment]
I don't personally have an issue with it, now that I wrapped the issue for consistency. However

- Other users may run into the same issue.
- The documentation is lacking.
- The list of signals which are safe to use across implementations is not clear.

Thanks for extracting a new issue to sort out these points.
