### ISSUE TITLE
JSON.pretty_generate generates different output to MRI for at least an empty hash

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#2053]
```ruby
require 'json'
puts JSON.pretty_generate({})
```

```
% chruby 2.6.5
% ruby -v test.rb
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
{
}
% chruby truffleruby-20.1.0
% ruby -v test.rb
truffleruby 20.1.0, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
{

}
```

So does JRuby https://github.com/jruby/jruby/issues/6338

**Comment by eregon** [comment]
It's an issue of `json/pure`, it also happens on MRI:
```
$ ruby -v -e 'require "json/pure"; puts JSON.pretty_generate({})'
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
{

}
```

Could you file an issue or make a PR to https://github.com/flori/json ?

**Comment by chrisseaton** [comment]
Fixed by https://github.com/flori/json/pull/449.

**Comment by chrisseaton** [comment]
That's merged now. I'll close on anticipation you'll pick up the new version soon enough.

**Comment by eregon** [comment]
I'll watch (= enable notifications for) the `json` repo for releases.
We should probably use the json version that MRI uses for the stdlib though.
So if this fix is important, we could manually cherry-pick it on top of the stdlib version.
Do you think that's worth it? Are some tests failing without it?

We might also consider switching to the C extension for maximum compatibility, the main question there is what's the impact on performance.

**Comment by chrisseaton** [comment]
It caused a spec to fail in practice.

But it's not actually a problem - minor workaround to allow for it. I wouldn't cherry-pick it.
