### ISSUE TITLE
deep_clone: Polyglot object DeepClone cannot be converted to i32 (LLVMPolyglotException)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#2073]
```
truffleruby 20.3.0-dev-f610a725, like ruby 2.6.6, GraalVM CE Native [x86_64-darwin]
```

To reproduce:

```
gem install ruby_deep_clone
ruby -rdeep_clone -e 'DeepClone.clone({})'
```

Error:

```
~/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `clone': Polyglot object DeepClone cannot be converted to i32 (LLVMPolyglotException) (RuntimeError)
Translated to internal error
	from -e:1:in `<main>'
```

**Comment by eregon** [comment]
The gem is from https://github.com/gmodarelli/ruby-deepclone

It seems an issue upstream, because
https://github.com/gmodarelli/ruby-deepclone/blob/465162df3f89c816badec1a1a473e5b2da4c8ec8/ext/deep_clone/deep_clone.c#L34
https://github.com/gmodarelli/ruby-deepclone/blob/465162df3f89c816badec1a1a473e5b2da4c8ec8/ext/deep_clone/deep_clone.c#L176

So the signature of the function `deep_clone` doesn't match the arity given to `rb_define_module_function`.
It should be `VALUE deep_clone(VALUE self, VALUE arg)`.

**Comment by eregon** [comment]
With that signature fixed it goes further:
```
$ ruby -Ilib -rdeep_clone -e 'p DeepClone.clone({})'
/home/eregon/code/ruby-deepclone/ext/deep_clone/deep_clone.c:71:in `clone_object': External LLVMFunction rb_hash_tbl cannot be found. (LLVMLinkerException) (RuntimeError)
Translated to internal error
	from /home/eregon/code/ruby-deepclone/ext/deep_clone/deep_clone.c:180:in `deep_clone'
	from /home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `clone'
	from -e:1:in `<main>'
```

But https://github.com/gmodarelli/ruby-deepclone/blob/master/ext/deep_clone/deep_clone.h is accessing too much internals, it doesn't seem reasonable to support it as-is.
In fact it even accesses internals of MRI by duplicating struct definitions, which is extremely brittle (there is a reason those structs are newer versions of MRI).

Also, we could probably do a far more efficient version of it directly in TruffleRuby, which I think makes sense in the context of [Ractor](https://bugs.ruby-lang.org/issues/17100#note-8) and is also generally useful.

**Comment by eregon** [comment]
I filed an issue: https://github.com/gmodarelli/ruby-deepclone/issues/19

Does some dependency you use depend on `ruby_deep_clone`? Could you tell which gem?

**Comment by deepj** [comment]
https://github.com/lyptt/struct

**Comment by eregon** [comment]
I see, then I think the best would be for https://github.com/gmodarelli/ruby-deepclone to have a fallback on `Marshal.load Marshal.dump(obj)` on non-MRI.

**Comment by eregon** [comment]
I filed an issue with this idea here: https://github.com/gmodarelli/ruby-deepclone/issues/20

Since there seems to be nothing we can reasonably do in TruffleRuby for this issue, but rather we need that gem to be more portable, I will close this issue.
