### ISSUE TITLE
Couldn't install truffleruby 20.2.0 with ruby-build on macOS

### ISSUE THREAD

**Issue by hsbt** [oracle/truffleruby#2075]
@eregon I try to install 20.2.0 on macOS today. But it was failed. 20.1.0 is works fine with same environment.

see https://gist.github.com/hsbt/82d9eae64ccbc3a4cc648ad973ab00a6

**Comment by eregon** [comment]
Fixed in 80abcaa07ac2f81633275c8356b1e9f99a0c8de3.
