### ISSUE TITLE
Test coverage report numbers are inconsistant with Ruby MRI

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2078]
Taken from [here](https://travis-ci.org/github/namusyaka/gammo/builds/720937433)
Ruby MRI 2.7.0
```
--------------------------------------------------------------------------------

1710 tests, 1821 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications

100% passed

--------------------------------------------------------------------------------

1352.88 tests/s, 1440.70 assertions/s

Coverage report generated for Unit Tests to /home/travis/build/namusyaka/gammo/.coverage. 3104 / 3204 LOC (96.88%) covered.
```

Truffleruby head
```
1710 tests, 1821 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications

100% passed

--------------------------------------------------------------------------------

70.29 tests/s, 74.86 assertions/s

Coverage report generated for Unit Tests to /home/travis/build/namusyaka/gammo/.coverage. 2983 / 3179 LOC (93.83%) covered.

Line coverage (93.83%) is below the expected minimum coverage (95.00%).

SimpleCov failed with exit 2

rake aborted!
```

**Comment by eregon** [comment]
Thanks for the report.
It would probably be useful to compare the SimpleCov HTML reports to find what are the differences.

**Comment by gogainda** [comment]
Happens again for https://github.com/omniauth/omniauth/pull/1008

**Comment by bjfish** [comment]
@gogainda A fix for coverage was added here which should would to get enough coverage for omniauth. I see  (96.9%) covered locally.
https://github.com/oracle/truffleruby/commit/e68afb35db3922a1877af966f2c4652e952f4def

**Comment by gogainda** [comment]
@bjfish thanks for fixing it , I will double check the results

**Comment by gogainda** [comment]
https://travis-ci.org/github/omniauth/omniauth/builds/729730701 tests are passing and coverage is correct
