### ISSUE TITLE
Dynamic constant assignment using non-ascii variable

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2079]
From one of our libraries we have this:
```
def variance
  μ = mean
  reduce(0) { |m, i| m + (i - μ).square } / (length - 1)
end
```

In TruffleRuby, this results in: `SyntaxError: dynamic constant assignment`

**Comment by eregon** [comment]
Thanks for the report, this sounds like a bug in the lexer when considering the kind of identifier `μ` is.
