### ISSUE TITLE
Error uninitialized constant Truffle::FFI::Library

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2094]
truffleruby 20.2.0, like ruby 2.6.6, GraalVM CE Native [x86_64-darwin]

Just testing one of my ffi libs with TruffleRuby and I hit this:

```
require 'ffi'

class File::Temp < File
  extend FFI::Library # boom
end
```

Result:

```
test.rb:4:in `const_missing': uninitialized constant Truffle::FFI::Library (NameError)
	from test.rb:4:in `Temp'
	from test.rb:3:in `<main>'
```

**Comment by eregon** [comment]
Interesting bug, thanks for the report. I think this is because File::FFI is set (for convenience I guess) but it should not.

**Comment by bjfish** [comment]
Thank you for reporting this issue. This is now fixed at https://github.com/oracle/truffleruby/commit/950d2afec730b34460dfd6a46e9b9aea9e1bd694.
