### ISSUE TITLE
Can't built head

### ISSUE THREAD

**Issue by marcandre** [oracle/truffleruby#2106]
`rvm install truffleruby-head` gives me
"Error running 'run_gem_wrappers regenerate'"

log is:

```sh
[2020-09-28 21:07:36] /Users/work/.rvm/rubies/truffleruby-head/lib/truffle/post_install_hook.sh
current path: /Users/work/.rvm/rubies/truffleruby-head
GEM_PATH=/Users/work/.rvm/gems/ruby-2.7.1:/Users/work/.rvm/gems/ruby-2.7.1@global
GEM_HOME=/Users/work/.rvm/gems/ruby-2.7.1
PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/work/.rvm/gems/ruby-2.7.1/bin:/Users/work/.rvm/gems/ruby-2.7.1@global/bin:/Users/work/.rvm/rubies/ruby-2.7.1/bin:/usr/local/opt/postgresql@9.6/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/git/bin:/Users/work/.ec2/api/bin:/Users/work/ruby/dev/spec/mspec/bin:/Users/work/.bin:/usr/local/Cellar/node/6.8.1/bin:/usr/local/bin:/Users/work/.rvm/bin
command(1): /Users/work/.rvm/rubies/truffleruby-head/lib/truffle/post_install_hook.sh
Recompiling the OpenSSL C extension (against the installed libssl)
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/work/.rvm/rubies/truffleruby-head/bin/truffleruby (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/work/.rvm/rubies/truffleruby-head/bin/truffleruby (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

/Users/work/.rvm/rubies/truffleruby-head/lib/truffle/post_install_hook.sh: line 18: 25249 Abort trap: 6           truffleruby -w extconf.rb
```

**Comment by marcandre** [comment]
Nevermind, OS X 10.3 is not supported and I don't have the video card needed to upgrade.

**Comment by chrisseaton** [comment]
Yeah sorry about that - we'd love to support multiple versions of macOS, but it's extremely difficult (for everyone) to do that because keeping an old box running with modern versions of everything else is hard.

**Comment by eregon** [comment]
The TruffleRuby releases are built on slightly older macOS, maybe `rvm install truffleruby` works for you?

I guess you mean macOS 10.13? (10.3 would be OS X Panther from 2004)

**Comment by marcandre** [comment]
> The TruffleRuby releases are built on slightly older macOS, maybe `rvm install truffleruby` works for you?

I wanted to check [a failure I get only on `head`](https://github.com/rubocop-hq/rubocop-ast/runs/1179896566?check_suite_focus=true). Installed it on my macbook and can't reproduce it 🤷‍♂️

> I guess you mean macOS 10.13? (10.3 would be OS X Panther from 2004)

Yes, indeed 😅

**Comment by eregon** [comment]
Sorry about that, maybe it is a transient failure. Feel free to file an issue about the failure.
