### ISSUE TITLE
Overriding Warning.warn leads to Stackoverflow

### ISSUE THREAD

**Issue by deivid-rodriguez** [oracle/truffleruby#2109]
The following script prints "Foo Bar" to standard error on CRuby, but crashes with StackOverflow on truffleruby.

```ruby
module Warning
  def warn(str)
    # some custom pre-processing of the warning message
    super
  end
end

warn 'Foo Bar'
```

The problem is related to https://github.com/rubygems/rubygems/issues/2588, but I can reproduce the above behaviour using the `--disable-gems` flag too.

Also, note that ruby introduced [this patch](https://github.com/ruby/ruby/commit/8a2a882e53ade974494dbf7c968a85bad0393dcd) to fix apparently this same problem, so maybe truffleruby needs to do something similar.

**Comment by eregon** [comment]
Thanks for report, I'll investigate.

**Comment by eregon** [comment]
The [workaround in CRuby](https://github.com/ruby/ruby/commit/8a2a882e53ade974494dbf7c968a85bad0393dcd) is to not call `Warning.warn` from `Kernel#warn` if `self` is `Warning`.
We should do the same.

It does feel like a hack to me (i.e., overriding Warning#warn is the bug, overriding Warning.warn or `prepend`'ing is OK), but we need to be compatible. Let's add some specs for it.
