### ISSUE TITLE
Globbing with `FNM_DOTMATCH` misses some hidden files

### ISSUE THREAD

**Issue by deivid-rodriguez** [oracle/truffleruby#2116]
The following script prints `bar/.baz/qux` on CRuby, but nothing on truffleruby.

```ruby
require 'tmpdir'

Dir.mktmpdir("foo") do |tmpdir|
  Dir.chdir(tmpdir) do
    Dir.mkdir("bar")
    Dir.mkdir("bar/.baz")
    FileUtils.touch("bar/.baz/qux")
    puts Dir.glob(File.join("**", "*"), File::FNM_DOTMATCH).reject{|f| File.directory?(f)}
  end
end
```

**Comment by eregon** [comment]
Indeed, thanks for the report.
@bjfish Could you take a look?

**Comment by eregon** [comment]
I filed an issue on the CRuby tracker: https://bugs.ruby-lang.org/issues/17280

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/72d1f415e0472bc86a85b662d5539f96c8c92153
