### ISSUE TITLE
Some Truffle::Interop methods have inconsistent names

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2139]
For instance, https://github.com/oracle/truffleruby/blob/516b3ee9d51d79ccd9c2820c11f6531a9b177e97/doc/contributor/interop.md#how-to-explicitly-send-interoplibrary-messages-from-ruby---explicit-polyglot-api says

> Few examples: isString becomes string?

But actually currently it's `Truffle::Interop.is_string?` and not `Truffle::Interop.string?`.
We should rename in `InteropNodes` it to match the docs (no leading `is_`, there are a few cases).

Noticed by @fniephaus

**Comment by fniephaus** [comment]
Also, several new Interop APIs are not yet exposed, for example `date?`or `has_identity?`.

**Comment by eregon** [comment]
I think
> For every message in the InteropLibrary there is a Ruby method in the Truffle::Interop module.

is a bit optimistic.

We would need to add a test that lists all InteropLibrary methods and verify they are defined on `Truffle::Interop`.
Probably feasible by using reflection in a static initializer.

**Comment by eregon** [comment]
We'll add a test and make sure all InteropLibrary messages are exposed as methods on `Truffle::Interop`.

**Comment by eregon** [comment]
Fixed in bdf0785e65c28ec565c03be381c2a0a7f3200b18, now all `InteropLibrary` messages are exposed as methods on `Truffle::Interop` with names consistent with the docs, and there is an automated test for it.

**Comment by fniephaus** [comment]
Excellent, thank you @eregon!
