### ISSUE TITLE
String#unpack('w*') does not return all values

### ISSUE THREAD

**Issue by zofrex** [oracle/truffleruby#2143]
Calling `unpack` on a string with the format string `w*` gives incorrect results:

```
> packed = [1,2,3,4].pack("w*")
=> "\x01\x02\x03\x04"
> packed.unpack('w*')
=> [1, 2, 4]
```

As you can see it's unpack that is dropping the data here, not pack.

It seems like it's possibly only returning values with an index that's a power of two, perhaps?

```
> (1..40).to_a.pack('w*').unpack('w*')
=> [1, 2, 4, 8, 16, 32]
```

**Comment by eregon** [comment]
Thanks for the report, it seems a clear bug.

```
$ ri pack
  w             | Integer | BER-compressed integer
```

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/430460473e189a7588f3b667ff4094f0e72b3ff4

**Comment by zofrex** [comment]
Thank you! I can confirm that fix is working for my code.
