### ISSUE TITLE
gem commands fails on macOS Big Sur due to Library "/usr/lib/libSystem.B.dylib" does not exist

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#2158]
Hello,
I've switched to Big Sur 11.0.1 recently. I removed old gems (`rm -rf ~/.gem/truffleruby`) and installed newly `truffleruby-ruby` via `ruby-build` (after switching to Big Sur). It fails on any gem command, even on `-v` to get a version of rubygems.

```
$ gem -v
<internal:core> core/kernel.rb:234:in `gem_original_require': Library "/usr/lib/libSystem.B.dylib" does not exist. (RuntimeError)
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:92:in `require'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/config_file.rb:71:in `<class:ConfigFile>'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/config_file.rb:39:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:92:in `require'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/gem_runner.rb:10:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:92:in `require'
	from ~/.rubies/truffleruby-dev/bin/gem:28:in `<main>'
```

My TruffleRuby version
```
$ ruby -v
truffleruby 21.0.0-dev-9304b9e2, like ruby 2.7.2, GraalVM CE Native [x86_64-darwin]
```

**Comment by eregon** [comment]
That seems to indicate that Big Sir is not backward compatible and cannot run some programs built on Catalina then.

This line means it failed to load the `etc.bundle` extension.
Could you show what `otool -L ~/.rubies/truffleruby-dev/lib/mri/etc.bundle` prints?

**Comment by deepj** [comment]
@eregon 

```
@rpath/libtruffleruby.dylib (compatibility version 0.0.0, current version 0.0.0)
@rpath/libgraalvm-llvm.1.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

**Comment by eregon** [comment]
Could you also post `otool -L path/to/etc.bundle` for CRuby to compare?
BTW, does a CRuby installation form before Big Sur still works after the upgrade?

And I guess `/usr/lib/libSystem.B.dylib` does not exist?

Under https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes#Kernel
> New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

So Big Sur doesn't even have a libc on disk anymore, that might be the breaking change.

**Comment by deepj** [comment]
@eregon 
1. CRuby 2.7.2 was compiled on Mojave (I skipped Catalina entirely) and it seems everything works
2. Indeed, `/usr/lib/libSystem.B.dylib` does not exist

```
~/.rubies/ruby-2.7.2/lib/libruby.2.7.dylib (compatibility version 2.7.0, current version 2.7.2)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```

**Comment by eregon** [comment]
Thanks. I found an internal issue for this (GR-26569), changes in Sulong or Truffle NFI might help to fix this, let's see.

**Comment by eregon** [comment]
@deepj This should be fixed now, thank you for the report.

**Comment by deepj** [comment]
@eregon Thanks. I can confirm it was fixed!

**Comment by djberg96** [comment]
I've noticed a similar error happening with macos-latest with github actions: https://github.com/djberg96/sys-proctable/runs/4572088661?check_suite_focus=true
