### ISSUE TITLE
Kernel.rand in native mode massively slower than in jvm mode + MRI

### ISSUE THREAD

**Issue by ivoanjo** [oracle/truffleruby#2176]
Hello there! :wave: 

I was doing a few monte carlo toy experiments, and thought of checking out the performance with truffleruby and was really surprised to see it was slower than MRI even. I managed to isolate it to the performance of `Kernel.rand` being really bad in native mode.

Benchmark:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'benchmark-ips'
end

require 'benchmark/ips'

Benchmark.ips do |x|
  # Configure the number of seconds used during
  # the warmup phase (default 2) and calculation phase (default 5)
  x.config(:time => 30, :warmup => 30)

  # Typical mode, runs the block as many times as it can
  x.report(RUBY_DESCRIPTION) { Kernel.rand }

  # Compare the iterations per second of the various reports!
  x.save! 'benchmark-results-v4'
  x.compare!
end
```

(P.s.: Due to [a bug](https://github.com/evanphx/benchmark-ips/pull/107) an empty `benchmark-results-v4` file needs to be created prior to running it).

Results of running with a few different Ruby configurations on my `Intel i5-8250U` laptop using `Ubuntu 20.04.1 LTS`:

```
Comparison:
truffleruby 20.3.0, like ruby 2.6.6, GraalVM CE JVM [x86_64-linux]: 50467500.0 i/s
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) +JIT [x86_64-linux]: 14287448.3 i/s - 3.53x  (± 0.00) slower
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]: 14025769.7 i/s - 3.60x  (± 0.00) slower
truffleruby 20.3.0, like ruby 2.6.6, GraalVM CE Native [x86_64-linux]:  8018421.0 i/s - 6.29x  (± 0.00) slower
```

**Comment by eregon** [comment]
I think @chrisseaton noticed this at some point too.
Probably it comes from the cost of the `synchronized` statement here:
https://github.com/oracle/truffleruby/blob/ab54d2d06f52036c11b977dc07e091a231024640/src/main/java/org/truffleruby/algorithms/Randomizer.java#L90-L96

`synchronized` is always a full lock on Native CE.

For usages like `Kernel.rand`, there is no need to lock (it's a thread-local instance of a Truffle::Randomizer), but for `Random` instances it's required to lock.
So a way to fix that would be to pass a boolean to the `Randomizer` whether to lock (and ideally ConditionProfile it), or maybe use subclasses or Truffle libraries.

Probably using explicit `Random` instances is rare, so we could also speculate on that with an Assumption or so, but there is `Random::DEFAULT = Random.new` we'd need to account for.

**Comment by eregon** [comment]
I ran it locally with `jt benchmark`, and I see:
```
jt -u ruby benchmark -e 'benchmark { Kernel.rand }'
16867761.19965056

jt -u jvm-ce benchmark -e 'benchmark { Kernel.rand }'
40416472.69294497

jt -u native benchmark -e 'benchmark { Kernel.rand }'
11056599.023788081

# If I remove the synchronized
jt -u native benchmark -e 'benchmark { Kernel.rand }'
53160150.51845292
```

So it is indeed very clearly the `synchronized` mentioned above.

**Comment by eregon** [comment]
@ivoanjo If you want to give this a try, I'd suggest to add a boolean to `Randomizer` for whether to synchronize. That should be fairly straightforward and get most of the benefits.
I mentioned ConditionProfile above, but it's not relevant because all this code is anyway behind a `@TruffleBoundary` anyway (so it's not partially evaluated, and there is no gain to profile it with ConditionProfile).

**Comment by ivoanjo** [comment]
Sounds good, I'll take a stab at it!
