### ISSUE TITLE
Regexp.last_match(Symbol) is not supported

### ISSUE THREAD

**Issue by amyspark** [oracle/truffleruby#2179]
The `Regexp` class does not parse or accept queries for named captures. This is a feature introduced in [MRI 1.9](https://github.com/ruby/ruby/commit/e56e8c758d8effb54144df0b61ca9d5f6b98a0cd).

This currently breaks Jekyll 4.1.1 in truffleruby.

MWE (from `irb`):
```
irb(main):006:0> /(?:<test>[A-Z]+.*)/.match? "TEST123"
=> false
irb(main):007:0> /(?:[A-Z]+.*)/.match? "TEST123"
=> true
irb(main):008:0> Regexp.last_match :test
Traceback (most recent call last):
       12: from /home/amalia/.rbenv/versions/truffleruby-20.3.0/bin/irb:37:in `<main>'
       11: from <internal:core> core/kernel.rb:401:in `load'
       10: from <internal:core> core/kernel.rb:401:in `load'
        9: from /home/amalia/.rbenv/versions/truffleruby-20.3.0/lib/gems/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        8: from <internal:core> core/throw_catch.rb:36:in `catch'
        7: from <internal:core> core/throw_catch.rb:36:in `catch'
        6: from <internal:core> core/kernel.rb:438:in `loop'
        5: from <internal:core> core/kernel.rb:325:in `eval'
        4: from (irb):8
        3: from <internal:core> core/regexp.rb:83:in `last_match'
        2: from <internal:core> core/type.rb:186:in `rb_to_int_fallback'
        1: from <internal:core> core/type.rb:277:in `convert_type'
TypeError (no implicit conversion of Symbol into Integer)
```

Using truffleruby 20.3.0 from rbenv.

**Comment by eregon** [comment]
I think this only applies to `Regexp.last_match` with a Symbol argument, otherwise named captures work fine:
```
$ ruby -e '/(?<test>[A-Z]+.*)/.match "TEST123"; p $~[:test]; p Regexp.last_match :test'
"TEST123"
<internal:core> core/type.rb:277:in `convert_type': no implicit conversion of Symbol into Integer (TypeError)
	from <internal:core> core/type.rb:186:in `rb_to_int_fallback'
	from <internal:core> core/regexp.rb:83:in `last_match'
	from -e:1:in `<main>'
```

There are several issues in the example above, `match?` won't set `$?` and the group are non-capturing (`(?:`).

**Comment by amyspark** [comment]
> I think this only applies to `Regexp.last_match` with a Symbol argument, otherwise named captures work fine:
> 
> ```
> $ ruby -e '/(?<test>[A-Z]+.*)/.match "TEST123"; p $~[:test]; p Regexp.last_match :test'
> "TEST123"
> <internal:core> core/type.rb:277:in `convert_type': no implicit conversion of Symbol into Integer (TypeError)
> 	from <internal:core> core/type.rb:186:in `rb_to_int_fallback'
> 	from <internal:core> core/regexp.rb:83:in `last_match'
> 	from -e:1:in `<main>'
> ```
> 
> There are several issues in the example above, `match?` won't set `$?` and the groups are non-capturing (`(?:`).

Apologies, I just wanted a minimal test case to show you the stacktrace from Regexp. The actual one came from Jekyll and was way bigger.

**Comment by bjfish** [comment]
This is fixed at: https://github.com/oracle/truffleruby/commit/cda1364e72a03dcf3b00147a9726eb266c728376
