### ISSUE TITLE
TypeError: no case for org.truffleruby.core.cast.ToFNodeGen org.truffleruby.core.numeric.RubyBignum

### ISSUE THREAD

**Issue by rickhull** [oracle/truffleruby#2184]
Here is the full error text: `TypeError: TruffleRuby doesn't have a case for the org.truffleruby.core.cast.ToFNodeGen node with values of type org.truffleruby.core.numeric.RubyBignum`

I encountered this error as part of a testing matrix for my GitHub Action CI on a project of mine.  This failure occurs for truffleruby and truffleruby-head but not for jruby or any MRI I tested.  Here is the CI ouput: https://github.com/rickhull/compsci/runs/1520388175?check_suite_focus=true#logs

**Comment by eregon** [comment]
Full log (GitHub Actions logs disappear after some time):
```
  1) Error:
CompSci::Fit::Fit.power#test_0001_must accept power data:
TypeError: TruffleRuby doesn't have a case for the org.truffleruby.core.cast.ToFNodeGen node with values of type org.truffleruby.core.numeric.RubyBignum
	from org.truffleruby.core.cast.ToFNodeGen.executeAndSpecialize(ToFNodeGen.java:107)
	from org.truffleruby.core.cast.ToFNodeGen.executeToDouble(ToFNodeGen.java:49)
	from org.truffleruby.core.MathNodes$LogNode.function(MathNodes.java:477)
	from org.truffleruby.core.MathNodesFactory$LogNodeFactory$LogNodeGen.execute(MathNodesFactory.java:3231)
	from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:61)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:559)
    /home/runner/work/compsci/compsci/lib/compsci/fit.rb:146:in `log'
    /home/runner/work/compsci/compsci/lib/compsci/fit.rb:146:in `block in power'
    /home/runner/work/compsci/compsci/lib/compsci/fit.rb:48:in `map'
    /home/runner/work/compsci/compsci/lib/compsci/fit.rb:48:in `sigma'
    /home/runner/work/compsci/compsci/lib/compsci/fit.rb:146:in `power'
    /home/runner/work/compsci/compsci/test/fit.rb:134:in `block (5 levels) in <top (required)>'
    /home/runner/work/compsci/compsci/test/fit.rb:132:in `each'
    /home/runner/work/compsci/compsci/test/fit.rb:132:in `block (4 levels) in <top (required)>'
    /home/runner/work/compsci/compsci/test/fit.rb:131:in `each'
    /home/runner/work/compsci/compsci/test/fit.rb:131:in `test_0001_must accept power data'
```

**Comment by eregon** [comment]
Looks like we need negated guards for https://github.com/oracle/truffleruby/blob/8ed19c0814ea020b8d896dc6be26a53201f252f0/src/main/java/org/truffleruby/core/MathNodes.java#L471
There is already a specialization handling `RubyBignum` but it isn't taken (because the Object specialization was activated first).

Also `ToFNode` independently should try to convert any Object too, not just RubyDynamicObject.

@bjfish Could you do that?

**Comment by rickhull** [comment]
I am looking at the test case in my codebase.  I do have a conditional guard on certain values, noting: ` Fit.error warning: Bignum out of Float range`

Depending on platform and implementation details, it seems "legitimate" that certain Bignum's cannot be represented accurately by a float.  It's possible this failure has to do with Github's platform moreso than TruffleRuby itself.  I'm trying to put together a testcase that doesn't depend on my codebase.

**Comment by eregon** [comment]
@rickhull This case is a clear bug, at least in the LogNode, there is already handling for RubyBignum due to some missing check in the generic case.

This is enough to reproduce the bug:
`ruby -e 'class C<Numeric; def to_f; 1.0; end; end; obj=C.new; [obj, (1<<65)].each { |e| p Math.log(e) }'`

**Comment by rickhull** [comment]
Glad I could help!

**Comment by bjfish** [comment]
@rickhull This is fixed at https://github.com/oracle/truffleruby/commit/f3b1e5c17dcd3bca73e03b1767907d23b35baac2. Thanks for reporting this.
