### ISSUE TITLE
Thread-local random number generation behavior in TruffleRuby does not match MRI

### ISSUE THREAD

**Issue by ivoanjo** [oracle/truffleruby#2185]
Hello! While I was digging through the TruffleRuby sources and Ruby docs trying to see if I could take a stab at fixing #2176 I ran into a divergence from the MRI behavior.

In the docs for [`Kernel::srand`](https://ruby-doc.org/core-3.0.0.preview1/Kernel.html#method-i-srand) it's stated that 

> Seeds the system pseudo-random number generator, Random::DEFAULT, with number.
> [...]
> srand may be used to ensure repeatable sequences of pseudo-random numbers between different runs of the program. By setting the seed to a known value, programs can be made deterministic during testing.

And this example is included:

```ruby
srand 1234               # => 268519324636777531569100071560086917274
[ rand, rand ]           # => [0.1915194503788923, 0.6221087710398319]
[ rand(10), rand(1000) ] # => [4, 664]
srand 1234               # => 1234
[ rand, rand ]           # => [0.1915194503788923, 0.6221087710398319]
```

This seems to state quite strongly that `Random::DEFAULT` should be where `rand` gets stuff from.

Which means that TruffleRuby's current `rand` implementation [using thread-local randoms](https://github.com/oracle/truffleruby/blob/master/src/main/ruby/truffleruby/core/kernel.rb#L487) diverges from MRI's behavior in the presence of multithreading. This can be observed using a modified version of the example from [the `Kernel::srand` docs](https://ruby-doc.org/core-3.0.0.preview1/Kernel.html#method-i-rand):

```ruby
puts RUBY_DESCRIPTION
srand 1234
Thread.new { puts [ rand, rand ].inspect }.join
puts [ rand(10), rand(1000) ].inspect
```

Output from MRI:

```
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
[0.1915194503788923, 0.6221087710398319]
[4, 664]
```

Output from TruffleRuby:

```
truffleruby 20.3.0, like ruby 2.6.6, GraalVM CE Native [x86_64-linux]
[0.34989367684452877, 0.11392725147474025]
[3, 294]
```

(Out of curiosity, output from JRuby:)

```
jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc OpenJDK 64-Bit Server VM 25.265-b01 on 1.8.0_265-b01 [linux-x86_64]
[0.1915194503788923, 0.6221087710398319]
[4, 664]
```

The easiest way to fix this would of course to drop the thread-local behavior, but I wonder if there's a better way:

* maybe start with thread-local randoms, but switch back to single global random if a seed is manually set?
* maybe work with upstream to decouple `Kernel::rand` and `Kernel::srand` from `Random::DEFAULT`? (I'm guessing this can surprise some users, so there'd be a trade-off on this one)
* propose a new `ThreadLocalRandom` class [similar to its Java counterpart](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadLocalRandom.html), so that advanced users may still opt-in into a faster random implementation that avoids extra synchronization?

Any opinions on how to tackle this?

Also, let me know if would make sense for me to submit the above testcase to https://github.com/ruby/spec

---

Bonus: It seems like in the current prototype, random is ractor-local: 
```
3.0.0-preview2 :001 > srand 1234
 => 31363227390919466820722897978257363053 
3.0.0-preview2 :002 > Ractor.new { [ rand, rand ] }.take
<internal:ractor>:38: warning: Ractor is experimental, and the behavior may change in future versions of Ruby! Also there are many implementation issues.
 => [0.8142820513046246, 0.8160629365109611] 
3.0.0-preview2 :004 > [rand, rand]
 => [0.1915194503788923, 0.6221087710398319] 
3.0.0-preview2 :005 > [ rand(10), rand(1000) ]
 => [4, 664] 
```

**Comment by eregon** [comment]
See https://bugs.ruby-lang.org/issues/17322 and https://bugs.ruby-lang.org/issues/17351
In short, `Random::DEFAULT` has always been a mistake, it doesn't scale, Ruby 3 won't use it anymore, and it will be deprecated.

So I think we can close this.
Does it cause any compatibility issue in practice?

Setting `srand` only makes `rand` deterministic when not using threads. When using threads (which actually interleave execution and not always wait for each other), it's non-deterministic anyway, Random::DEFAULT or not. Actually thread-local Random is more deterministic, if `srand` is called in each thread.

**Comment by ivoanjo** [comment]
Thanks for clarifying it! I checked the truffleruby issues for any mentioning random but completely forgot to check the upstream Ruby bugtracker as well. :facepalm: 

> So I think we can close this, and keep the existing logic.

:+1: sounds good

> Does it cause any compatibility issue in practice?

I would imagine in some test suites there may be a corner-case here and there, but if upstream is also happy with moving away from this, I think the gain for the common case outweighs the gain in the corner case (and if someone really really wants their test suite to have the single random, I imagine they could always monkey patch it).

> Setting srand only makes rand deterministic when not using threads. When using threads (which actually interleave execution and not always wait for each other), it's non-deterministic anyway, Random::DEFAULT or not.

I claim that in examples such as mine where there are threads but no concurrency in random generation -- e.g. if you know at which points the generation would happen, and per the program structure know that there's no concurrency on those bits -- it's still deterministic.

BUT those assumptions seem mega dangerous and brittle anyway (seems like it's something ripe to break), so yeah, please ignore :)
