### ISSUE TITLE
Unify the representations of a block argument

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2206]
Unify the 4 representations (null/nil/NotProvided/RubyProc) of a block argument to be just 2 (nil/RubyProc).
That way, there is no need to convert from nil=>null or null=>nil and less checks are needed.

This would also clean up the extra `IsNull` + `Guard` nodes in IGV for every Ruby method:
![Screenshot from 2021-01-02 13-16-19](https://user-images.githubusercontent.com/168854/103457133-b8c01e00-4cfc-11eb-8c9f-7a3821278503.png)
from https://chrisseaton.com/truffleruby/basic-truffle-graphs/
The null check comes from https://github.com/oracle/truffleruby/blob/5ab35083f1cebd44b05ad5e8706196118184c328/src/main/java/org/truffleruby/language/arguments/ReadBlockFromCurrentFrameArgumentsNode.java#L30

cc @chrisseaton

**Comment by tomstuart** [comment]
@eregon I’m taking a look at this. Is it important that we use `nil` as the canonical representation of a missing block, or would `null` also suffice?

**Comment by eregon** [comment]
@tomstuart There is no choice, at the Ruby-level it must be `nil | Proc`.
`null` in general cannot be used in Truffle interpreters as a value (e.g. in a Ruby local variable).
Everywhere else we're quite flexible, `nil` should work in all places.

**Comment by tomstuart** [comment]
Understood, thank you!

**Comment by chrisseaton** [comment]
Something Tom and I discussed today was the importance of negotiating into a common format in the *caller*, not the *callee* where it currently is, since the *caller* has all the information about the type of the object being passed.

**Comment by eregon** [comment]
Good point, indeed.
If we manage to get rid of all conversations, then there won't be any conversion logic left in caller or callee.

Saving the passed block to the frame should result in no node/code, as long as the frame is virtual.
The frame might be materialized due to some block capturing it and not being inlined though.
So we might want to consider other ways to find out how deep is the closest method (= not block)'s frame.
I think the most important first step is to avoid conversations between the different representations for "no block", i.e., this issue.

**Comment by eregon** [comment]
First part merged!
Now I think the only remaining part is `@CoreMethod` currently using `NotProvided` instead of `Nil`: https://github.com/oracle/truffleruby/pull/2232#discussion_r562619610

@tomstuart Are you interested to do that part too?

**Comment by tomstuart** [comment]
Great, thanks for the merge! Sure, I’ll pick up the rest of it.
