### ISSUE TITLE
UDPSocket#recvfrom_nonblock: wrong number of arguments (given 3, expected 1)

### ISSUE THREAD

**Issue by HoneyryderChuck** [oracle/truffleruby#2209]
Running latest truffleruby (2.20.3), which targets ruby 2.6 .

I'm getting this error [running httpx tests](https://gitlab.com/honeyryderchuck/httpx/-/jobs/946733460). This is due to truffleruby implementing the old `UDPSocket#recvfrom_nonblock` signature, which has changed since ruby 2.4 (it has since accepted a buffer and `exception: ` kwarg) .

**UPDATE**: `UDPSocket#send` seems to be broken as well:

```
TypeError: TruffleRuby doesn't have a case for the org.truffleruby.extra.ffi.PointerNodesFactory$PointerWriteBytesNodeFactory$PointerWriteBytesNodeGen node with values of type java.lang.Long=164333584 HTT
PX::Buffer(org.truffleruby.core.basicobject.RubyBasicObject) java.lang.Integer=0 java.lang.Integer=25
        from org.truffleruby.extra.ffi.PointerNodesFactory$PointerWriteBytesNodeFactory$PointerWriteBytesNodeGen.executeAndSpecialize(PointerNodesFactory.java:1652)
        from org.truffleruby.extra.ffi.PointerNodesFactory$PointerWriteBytesNodeFactory$PointerWriteBytesNodeGen.execute(PointerNodesFactory.java:1618)
        from org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:77)
        from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:33)
        from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
        from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
        from org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:42)
        from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
        from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:64)
        from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:557)
    <internal:core> core/truffle/ffi/pointer.rb:221:in `put_bytes'
    <internal:core> core/truffle/ffi/pointer.rb:243:in `write_bytes'
    /usr/local/lib/truffle/socket/basic_socket.rb:132:in `block in send'
    <internal:core> core/truffle/ffi/pointer.rb:314:in `new'
    /usr/local/lib/truffle/socket/truffle/foreign.rb:349:in `memory_pointer'
    /usr/local/lib/truffle/socket/truffle/foreign.rb:345:in `char_pointer'
    /usr/local/lib/truffle/socket/basic_socket.rb:131:in `send'
    /usr/local/lib/truffle/socket/udp_socket.rb:73:in `send'
    /home/lib/httpx/io/udp.rb:43:in `write'
```

this seems to happen because it expects a String as the first argument, instead of an object that can be coerced into a String (i.e. implementing `to_str`). 

I've tested "patching" these two flaws, and I get a non-SSL HTTP request afterwards.

**Comment by eregon** [comment]
Thank you for the report.

Would you be interested in writing [specs](https://github.com/ruby/spec/tree/master/library/socket) for this if there isn't already to make the issue clearer?
Or even maybe a PR to TruffleRuby? (see [CONTRIBUTING.md](https://github.com/oracle/truffleruby/blob/master/CONTRIBUTING.md))
All of that socket code is pure Ruby, using FFI.

**Comment by HoneyryderChuck** [comment]
Probably not in the next 2 days, but I'll see what I can do 👍

**Comment by eregon** [comment]
Ref: specs for `recv_nonblock` and `recvfrom_nonblock` added in https://github.com/ruby/spec/pull/825

**Comment by eregon** [comment]
I think the report issues above should all be fixed now, thank you for the PRs!
