### ISSUE TITLE
OpenSSL: certificate verify failed (CA signature digest algorithm too weak)

### ISSUE THREAD

**Issue by HoneyryderChuck** [oracle/truffleruby#2210]
I'm getting the following error when performing https requests via `httpx`:

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (CA signature digest algorithm too weak)
  /usr/local/lib/truffle/truffle/cext.rb:1063:in `rb_exc_raise'
    exception.c:19:in `rb_exc_raise'
    /usr/local/src/main/c/openssl/ossl.c:300:in `ossl_raise'
    /usr/local/src/main/c/openssl/ossl_ssl.c:1697:in `ossl_start_ssl'
    /usr/local/src/main/c/openssl/ossl_ssl.c:1755:in `ossl_ssl_connect_nonblock'
    /usr/local/lib/truffle/truffle/cext_ruby.rb:39:in `connect_nonblock'
    /home/lib/httpx/io/ssl.rb:65:in `connect'
```

I'm using a local CA store for my tests. Can I assume that this has to do with the truffleruby openssl defaults not being on-par with ruby's, or is it a new default from openssl itself?

**Comment by eregon** [comment]
> Can I assume that this has to do with the truffleruby openssl defaults not being on-par with ruby's

AFAIK TruffleRuby doesn't touch any openssl default.
The only thing is TruffleRuby will always use a system libssl.

> or is it a new default from openssl itself?

Could you try with CRuby, and make sure CRuby is also built against the system libssl?

Is there a way for us to reproduce that error?

**Comment by HoneyryderChuck** [comment]
> Is there a way for us to reproduce that error?

The easiest way is using docker. In order to reproduce my tests you'd have to:

1. Download `httpx` repo from https://gitlab.com/honeyryderchuck/httpx;
2. build the necessary images and open a shell to a running container (`docker-compose -f docker-compose.yml -f docker-compose-truffleruby.yml run --entrypoint bash httpx`);
3. [Copy all the necessary information from the build script](https://gitlab.com/honeyryderchuck/httpx/-/blob/master/test/support/ci/build.sh) in order to have all the system deps, env vars and gems installed;
4. run the simplest HTTPS test (`bundle exec ruby -Itest test/https_test.rb --name /http_get/`)

**Comment by HoneyryderChuck** [comment]
FYI I fixed this. The issue was [the digest algorithm being setup as sha1 for the ca.cnf](https://gitlab.com/honeyryderchuck/httpx/-/blob/master/test/support/ci/certs/build_certs.sh#L91), which probably some systems or openssl's set a warning for nowadays. I'm not sure whether you want to dig this further (would be interesting to at least know why in truffleruby that's different), but from side everything's cleared. And safer :)

**Comment by Rogchen** [comment]
add config: tls-cipher "DEFAULT:@SECLEVEL=0" to *.ovpn
