### ISSUE TITLE
Derive hash value of struct instances not only from the instance's values, but also its class

### ISSUE THREAD

**Issue by janlelis** [oracle/truffleruby#2214]
`Struct.new(:x).new.hash` on TruffleRuby always creates the same hash, while on MRI/JRuby it creates a different hash for different struct classes.

> @eregon: Actually Struct.new(:y).new.hash also has the same hash, the hash is only based on Struct values currently, which seems suboptimal.

**Comment by eregon** [comment]
Thanks for the report.

I think we should use something like `val = Primitive.vm_hash_start(Truffle::Type.object_class(self).hash)`
in
https://github.com/oracle/truffleruby/blob/0dc999f7a82d744ff4315fb4db073eb1f676c561/src/main/ruby/truffleruby/core/struct.rb#L309
and also in
https://github.com/oracle/truffleruby/blob/0dc999f7a82d744ff4315fb4db073eb1f676c561/src/main/ruby/truffleruby/core/struct.rb#L440
@bjfish Could you do that?

It seems a good idea to add a ruby/spec that `Struct.new(:x).new(1).hash != Struct.new(:y).new(1).hash`.

**Comment by eregon** [comment]
Fixed in d9235b8b2fd7294b7aa215e1bb05f55f31bee60a by @bjfish, thanks for the report.
