### ISSUE TITLE
Webrick gem test failure: ArgumentError: unknown mask signature

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2219]
Example failure (one of many similar):
```
TestWEBrickUtils#test_nested_timeout_inner_custom_exception:
ArgumentError: unknown mask signature
    <internal:core> core/thread.rb:88:in `handle_interrupt'
    /Users/novoi/tmp/webrick/test/webrick/test_utils.rb:12:in `assert_expired'
    /Users/novoi/tmp/webrick/test/webrick/test_utils.rb:70:in `test_nested_timeout_inner_custom_exception'
    <internal:core> core/thread.rb:388:in `block in <top (required)>'
    /Users/novoi/tmp/webrick/test/lib/test/unit.rb:1172:in `run_test'
```

```
ruby -v: truffleruby 21.1.0-dev-0dc999f7, like ruby 2.7.2, GraalVM CE Native [x86_64-darwin]
```

To reproduce:
```
git clone git@github.com:ruby/webrick.git
cd webrick && bundle install
bundle exec rake
```

**Comment by eregon** [comment]
Is that when running MRI tests with `jt test mri`, or when running the tests of https://github.com/ruby/webrick ?

**Comment by gogainda** [comment]
Running webrick tests

**Comment by gogainda** [comment]
@eregon I can try to handle it

**Comment by gogainda** [comment]
I am having problem with creating of working example for MRI Ruby

**Comment by eregon** [comment]
The error comes from https://github.com/oracle/truffleruby/blob/a5afb7a164e3318284e9c76d3448d3ab4baf1a7e/src/main/ruby/truffleruby/core/thread.rb#L87-L89
which called from
https://github.com/ruby/webrick/blob/9279dd8c61d4fa1d76f1c448cd2c60bbd7413a6a/test/webrick/test_utils.rb#L12-L14

`EX` is https://github.com/ruby/webrick/blob/9279dd8c61d4fa1d76f1c448cd2c60bbd7413a6a/test/webrick/test_utils.rb#L23

I didn't know `Thread.handle_interrupt` can take multiple exception classes.

Currently TruffleRuby ignores those exception classes:
https://github.com/oracle/truffleruby/blob/a5afb7a164e3318284e9c76d3448d3ab4baf1a7e/src/main/java/org/truffleruby/core/thread/ThreadNodes.java#L265

So you could try to relax the check in core/thread.rb, and see if that's enough, or if we need to handle those exception classes and not just disable all interrupts while in the block.

**Comment by gogainda** [comment]
this is the problem, it's clear to me how to fix it, but before doing that I wanted to write a test or working example for MRI Ruby to see expected behaviour

**Comment by gogainda** [comment]
```
class BarException < StandardError
end

def raises_exception
	raise BarException.new
end

def execute
	Thread.handle_interrupt(BarException => :never) {
		
		raises_exception
		
		puts "exception was ignored"
	}
end

execute
```
This execution is still interrupted and I dont see "exception was ignored" message. Is this correct understanding how this feature should work?

**Comment by eregon** [comment]
`handle_interrupt` only delays interrupts, and also `Kernel#raise` is not an interrupt (it's on the same thread), but `Thread#raise` (and signals, etc) are.
It seems quite tricky to test.
There is actually a pretty good MRI test for the basic functionality:
https://github.com/oracle/truffleruby/blob/2378f646a3c0e96884273fc1a0f5f7d597d7a3bd/test/mri/tests/ruby/test_thread.rb#L719-L755

You can try to run that one by removing the exclude in `test/mri/excludes/TestThread.rb` or running `jt retag test/mri/tests/ruby/test_thread.rb`.

**Comment by gogainda** [comment]
unfortunately, fixing issue with > 1 arguments is not enough here. That example fails even with one :never argument:
```
def make_handle_interrupt_test_thread1 flag
    r = []
    ready_q = Queue.new
    done_q = Queue.new
    th = Thread.new{
      begin
        Thread.handle_interrupt(RuntimeError => flag){
          begin
            ready_q << true
            done_q.pop
          rescue
            r << :c1
          end
        }
      rescue
        r << :c2
      end
    }
    ready_q.pop
    th.raise
    begin
      done_q << true
      th.join
    rescue
      r << :c3
    end
    r
  end

make_handle_interrupt_test_thread1 :never
```

**Comment by eregon** [comment]
Interesting, I'll investigate that one.
The result of running that is:
```
Dumping stacktraces of all threads:
DRIVER: Thread[main,5,main]
java.lang.Thread.dumpThreads(Native Method)
java.lang.Thread.getAllStackTraces(Thread.java:1610)
org.truffleruby.language.SafepointManager.printStacktracesOfBlockedThreads(SafepointManager.java:224)
org.truffleruby.language.SafepointManager.driveArrivalAtPhaser(SafepointManager.java:200)
...
BLOCKED: Thread[Ruby Thread id=21 from handle_interrupt.rb:5,5,main]
java.lang.Throwable.fillInStackTrace(Native Method)
java.lang.Throwable.fillInStackTrace(Throwable.java:784)
java.lang.Throwable.<init>(Throwable.java:251)
java.lang.Exception.<init>(Exception.java:54)
java.lang.InterruptedException.<init>(InterruptedException.java:57)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2034)
org.truffleruby.core.queue.UnsizedQueue.take(UnsizedQueue.java:78)
org.truffleruby.core.queue.QueueNodes$PopNode$$Lambda$693/1881419576.block(Unknown Source)
org.truffleruby.core.thread.ThreadManager.runUntilResult(ThreadManager.java:511)
org.truffleruby.core.queue.QueueNodes$PopNode.doPop(QueueNodes.java:94)
org.truffleruby.core.queue.QueueNodes$PopNode.popBlocking(QueueNodes.java:82)
```

i.e. the blocked thread is in `Queue#pop` (`done_q.pop` above), and that seems to consistently interrupt or never get out of `done_q.pop`).

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/b7090ac62afa87d6dc8c1b464d4a88c908b055b4, also the original example with multiple pairs should work fine now.
