### ISSUE TITLE
rubocop fails with rubocop-rspec matcher

### ISSUE THREAD

**Issue by avdv** [oracle/truffleruby#2222]
Hi.

```console
$ ruby --version

truffleruby 21.1.0-dev-4f309b51, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]
```

Error:
```
An error occurred while RSpec/PredicateMatcher cop was inspecting /home/travis/build/athityakumar/colorls/spec/color_ls/yaml_spec.rb:20:8.

To see the complete backtrace run rubocop -d.

.....

23 files inspected, no offenses detected

1 error occurred:

An error occurred while RSpec/PredicateMatcher cop was inspecting /home/travis/build/athityakumar/colorls/spec/color_ls/yaml_spec.rb:20:8.
```

Rubocop ran fine on MRI Ruby 2.{5,6,7}.

Code:
```yaml_spec.rb
16    describe filename do
17      let(:checker) { YamlSortChecker.new("#{base_directory}/#{filename}.yaml") }
18
19      it 'is sorted correctly' do
20        expect(checker.sorted?(sort_type)).to eq true
21      end
22    end
```
https://github.com/avdv/colorls/blob/refactor-fix-233/spec/color_ls/yaml_spec.rb#L20

CI job: https://travis-ci.org/github/athityakumar/colorls/jobs/754544334

I'll try to re-run with `-d` and post the results here.

**Comment by bjfish** [comment]
This error also occurs during the specs for the gem: https://github.com/rubocop-hq/rubocop-rspec

**Comment by bjfish** [comment]
I had trouble tracing exactly how rubocop all works but this example probably recreates the issue:
```
module A
  module Runners
    def self.all
      puts "all"
    end
  end
  private_constant :Runners
end
module B 
  include A
  def self.try
    Runners.all
  end
end
B.try

```
Expected
```
all
```
Actual
```
../../notes/rubocop-rspec.rb:12:in `try': private constant B::Runners referenced (NameError)
	from ../../notes/rubocop-rspec.rb:15:in `<main>'
```

**Comment by eregon** [comment]
I'm not sure what the rule for private constants is in such a case.
Maybe the first constant looked up is like calls with implicit receiver, i.e., they ignore visibility?
This seems to show it's the case:
```ruby
module A
  module Runners
  end
  private_constant :Runners
end

module B 
  include A
  
  p Runners # OK
  p self::Runners # fails
  p B::Runners # fails
end
```

**Comment by bjfish** [comment]
It appears that constant lookup when the lookup is not scoped to a particular class ignores the visibility:
https://github.com/ruby/ruby/blob/d0693391103672b7fc3976e5ae8ae414059b3e97/vm_insnhelper.c#L953-L967
https://github.com/ruby/ruby/blob/d0693391103672b7fc3976e5ae8ae414059b3e97/variable.c#L2391-L2406
https://github.com/ruby/ruby/blob/d0693391103672b7fc3976e5ae8ae414059b3e97/variable.c#L2340-L2343

Another example:
```
module B 
    module Runners
    end
    private_constant :Runners
    p Runners # OK
    p self::Runners # FAILS
end
```

**Comment by eregon** [comment]
Yes, that makes sense and it's consistent with how visibility is handled for method calls (except that `self.some_method` is treated specially, but not for constants). 
Let's write/find a few specs for that and implement those changes.
I guess `const_get/rb_const_get` ignore visibility, which is typically the case for metaprogramming, except if there is `public_` in the method name of course.

**Comment by bjfish** [comment]
Thanks for reporting this issue @avdv. This is now fixed at https://github.com/oracle/truffleruby/commit/8f469826db794d599d1a490e1ed490fd4157a0aa.

**Comment by avdv** [comment]
Thank you @bjfish :+1: , I'll check the CI jobs in the next few days...

**Comment by avdv** [comment]
Once again, thank you! I confirm that CI builds with truffleruby-head are good again :green_heart:
