### ISSUE TITLE
Integer#digits should returns integer values > 9 when base is above 10

### ISSUE THREAD

**Issue by janlelis** [oracle/truffleruby#2224]
```ruby
it "returns integer values > 9 when base is above 10" do
  1234.digits(16).should == [2, 13, 4]
end
```

Current implementation returns 0 instead of 13

**Comment by eregon** [comment]
The current implementation relies on Integer#to_s(base), so that explains this issue and #2225:
https://github.com/oracle/truffleruby/blob/70c024bb7a20d63caafee2c68a4057a8db13e0a4/src/main/ruby/truffleruby/core/integer.rb#L318

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/f1e6d6bcae4aa099c03e3107caad8de44bb91549
