### ISSUE TITLE
not supporting sequel rollback transactions

### ISSUE THREAD

**Issue by HoneyryderChuck** [oracle/truffleruby#2227]
Coming from https://gitlab.com/honeyryderchuck/rodauth-select-account/-/jobs/967366339

This comes from a test around filter using sequel (latest version, 5.40.0) and a common transaction with auto-rollback strategy:

```ruby
DB.transaction(rollback: :always, savepoint: true, auto_savepoint: true) do
     # pre steps
     super
     # post steps
   end
```

When testing in truffleruby, the rollback exception is bubbling up, instead of being rescued within sequel.

**Comment by eregon** [comment]
Thanks for the report, I found the example usage in https://gitlab.com/honeyryderchuck/rodauth-select-account/-/blob/e0f112696bfff2daf95b2aeae39f1c29d086c5db/test/test_helper.rb#L142-152.

A small standalone reproducer would be helpful.
@bjfish Could you investigate?

**Comment by bjfish** [comment]
Here's a smaller case to reproduce:
```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'sequel', '~> 5.40'
  gem 'sqlite3', '~> 1.3', '>= 1.3.11'
end

require "sequel"
DB = Sequel.sqlite

DB.transaction do
  raise Sequel::Rollback
end 
puts "Done, no error"
```
Expected
```
Done, no error
```
Actual
```
../../notes/sequel.rb:15:in `block in <main>': Sequel::Rollback (Sequel::Rollback)
	from /Users/bfish/Documents/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/gems/gems/sequel-5.40.0/lib/sequel/database/transactions.rb:258:in `_transaction'
	from /Users/bfish/Documents/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/gems/gems/sequel-5.40.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
	from /Users/bfish/Documents/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/gems/gems/sequel-5.40.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
	from /Users/bfish/Documents/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/gems/gems/sequel-5.40.0/lib/sequel/database/connecting.rb:269:in `synchronize'
	from /Users/bfish/Documents/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/gems/gems/sequel-5.40.0/lib/sequel/database/transactions.rb:195:in `transaction'
	from ../../notes/sequel.rb:14:in `<main>'
```

**Comment by bjfish** [comment]
If we run something like:
```
require "sqlite3"
db = SQLite3::Database.new "test.db"
db.execute <<-SQL
  create table students (
    name varchar(50),
    email varchar(50),
    grade varchar(5),
    blog varchar(50)
  );
SQL
begin
  1 / 0
rescue => e
  p db.execute( "select * from students" )
end
```
The `rb_errinfo()` has a value here (ZeroDivisionError) in TruffleRuby but not MRI:
https://github.com/sparklemotion/sqlite3-ruby/blob/d94c42b0b8e5005ee28cde75a58e15ea5670d1c4/ext/sqlite3/statement.c#L128

**Comment by bjfish** [comment]
This should now be fixed at https://github.com/oracle/truffleruby/commit/19f0e6af33651e177691a5ecb5a7a8b1dc3e8409 by @aardvark179 . Thank you for reporting @HoneyryderChuck , please let us know if you have any trouble with this.

**Comment by eregon** [comment]
@bjfish Could you check if it also fixes the 2 issues I just linked above?

**Comment by bjfish** [comment]
@eregon #2245 is a separate but related issue, I'll also check #2231
