### ISSUE TITLE
Zlib::MemError: insufficient memory

### ISSUE THREAD

**Issue by HoneyryderChuck** [oracle/truffleruby#2243]
I'm getting this error predictably [in CI, when testing httpx deflate compression plugin](https://gitlab.com/honeyryderchuck/httpx/-/jobs/997829373). This error doesn't happen if I run the test individually, only when running all the tests at the same time:

```
HTTPSTest#test_plugin_compression_deflate_post:
Zlib::MemError: insufficient memory
    /usr/local/lib/truffle/truffle/cext.rb:1049:in `rb_exc_raise'
    exception.c:19:in `rb_exc_raise'
    zlib.c:345:in `raise_zlib_error'
    zlib.c:1564:in `rb_deflate_initialize'
    /usr/local/lib/truffle/truffle/cext_ruby.rb:39:in `initialize'
    /home/lib/httpx/plugins/compression/deflate.rb:21:in `deflate'
    /home/lib/httpx/plugins/compression.rb:143:in `deflate'
    /home/lib/httpx/plugins/compression.rb:133:in `bytesize'
    /home/lib/httpx/plugins/compression.rb:57:in `initialize'
```

The deflater is initialized [here](https://gitlab.com/honeyryderchuck/httpx/-/blob/master/lib/httpx/plugins/compression/deflate.rb#L21-24). I suspect this has to do with the `Zlib::MAX_MEM_LEVEL` statement, though. Is this a big issue in truffleruby, given that has been a non-issue in CRuby and JRuby sofar?

**Comment by eregon** [comment]
This might be solved by a PR @norswap is working on.

**Comment by norswap** [comment]
Most likely a duplicate issue for https://github.com/oracle/truffleruby/issues/1704, fixed by ec62fae.

I'm closing the issue as this is most likely resolved, but @HoneyryderChuck, could you confirm with the latest nightly build?

**Comment by HoneyryderChuck** [comment]
given that my tests run under docker, I'll have to wait for a release :/

**Comment by norswap** [comment]
You could install the nightly in docker by using a ruby manager: https://github.com/oracle/truffleruby/blob/master/doc/user/ruby-managers.md - of course it's more setup. Let us know when you get to it anyhow :)

**Comment by eregon** [comment]
There are nightly builds documented here, that you can use in Docker: https://github.com/oracle/truffleruby/blob/master/doc/user/standalone-distribution.md#latest-nightly-build

There are also nightly Docker images at https://hub.docker.com/r/flavorjones/truffleruby.

**Comment by HoneyryderChuck** [comment]
> There are also nightly Docker images at https://hub.docker.com/r/flavorjones/truffleruby.

Didn't know it was shipping nightlies already, thank you for the tip!

**Comment by HoneyryderChuck** [comment]
https://gitlab.com/honeyryderchuck/httpx/-/jobs/1009278087

This build ran with nightly, and I'm still seeing the same Zlib::MemError's @norswap

**Comment by norswap** [comment]
I checked locally, naively running `bundle install && bundle exec rake test` using a recent native build of truffleruby (not the exact nightly, but it shouldn't matter).

I am getting a lot of errors (25 errors, 12 failures), so not quite the same as the CI, but none of the are Zlib-related, and `HTTPSTest#test_plugin_compression_deflate_post` (which has the zlib failure on CI) doesn't fail.

Is there a better way I can try to reproduce the issue?

**Comment by HoneyryderChuck** [comment]
@norswap I've written [here](https://github.com/oracle/truffleruby/issues/2210#issuecomment-755364941) how to set up the environment to run the tests. Let me know if you need more.

**Comment by norswap** [comment]
I'm able to run the tests. Had to increase the memory to 4G because bundler would run out of memory with 2G. 
I do not get any Zlib failure — how much memory does your container have?

I'm running the tests through `build.sh`, but if I try to run just the OOM test from `/home` with 
`bundle exec ruby -Itest test/https_test.rb --name /plugin_compression_deflate_post/` then I get
`OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)`. Any idea how I can avoid that?

Oh, and you might want to change the hashbang on `build.sh` to `#!/bin/bash`, since it uses some bash syntax.

**Comment by HoneyryderChuck** [comment]
Running the test in isolation didn't yield it for me as well.

In order to reproduce it, youll have to enable parallel mode and set the SSL_CERT_FILE env var. It's all inside build.sh.
I also don't have access to gitlab-ci parameters, so can't say how much memory is thrown at the container. But it bundles, so I guess it's enough?

If I had to guess, it's due to contention, so make sure you run all test with PARALLEL=1

**Comment by norswap** [comment]
I'm not sure we're dealing with "buggy" memory consumption here. TruffleRuby does have a relatively high footprint to begin with, and running in parallel is not going to help. Can't reproduce using 4G (even with parallel test execution).

@eregon what do you think?

Is it an option to bump the memory? (I'm guessing not) What about not running test in parallel?

**Comment by eregon** [comment]
According to https://forum.gitlab.com/t/what-are-resource-limits-for-ci-jobs-on-gitlab-com-ram-cpus/29821, GitLab CI has about 4GB.
One could check by running `free -m` in the CI job, @HoneyryderChuck could you do that?

Could we try to isolate some code (e.g., that Zlib example in the first post, together with some String to deflate) that uses much more memory on TruffleRuby? We should compare to how much CRuby or JRuby uses.
This can be checked with `/usr/bin/time -v original_command args`, which shows max RSS.

We could also try to take a heap dump (manually, or with `-XX:+HeapDumpOnOutOfMemoryError`) and look for what's in the heap.

**Comment by HoneyryderChuck** [comment]
> One could check by running free -m in the CI job, @HoneyryderChuck could you do that?

https://gitlab.com/honeyryderchuck/httpx/-/jobs/1026259623#L118

**Comment by eregon** [comment]
```
              total        used        free      shared  buff/cache   available
Mem:           3693         604        1664         199        1425        2728
Swap:          2047           0        2047
```

So that's about 2728MB available / 2.66GB in that run.

**Comment by HoneyryderChuck** [comment]
Fixed this by [removing initializer parameters](https://gitlab.com/honeyryderchuck/httpx/-/commit/0ca144becc06fc30ce65c33350247241c0da73f5). I'm not entirely sure why, because those were supposed to be the default initializer parameters, but they seemed to have caused it. 

First green build in truffleruby [here](https://gitlab.com/honeyryderchuck/httpx/-/jobs/1045031305).

**Comment by eregon** [comment]
The defaults seem to differ:
From the docs:
```ruby
Zlib::Deflate.new(level=DEFAULT_COMPRESSION, window_bits=MAX_WBITS, mem_level=DEF_MEM_LEVEL, strategy=DEFAULT_STRATEGY)
```
and that usage:
```ruby
Zlib::Deflate.new(Zlib::BEST_COMPRESSION, Zlib::MAX_WBITS, Zlib::MAX_MEM_LEVEL, Zlib::HUFFMAN_ONLY)
```
For instance at least DEFAULT_COMPRESSION and BEST_COMPRESSION have different values (-1 and 9 respectively for me).

Great to hear it works now.
