### ISSUE TITLE
Implement missing standard tags

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#2253]
We're missing a few standard tags, like `RootBodyTag`, `CallTag`, `TryBlockTag`, and so on. Should we implement all of them?

No particular need in mind though.

**Comment by eregon** [comment]
I think it would be fine, but we should avoid making footprint worse for that (e.g., no extra nodes if possible).
I'd rather we do it based on some use case though, there are always more things to do and if nothing uses then it seems low priority.

**Comment by eregon** [comment]
We need a use case for those, they seem optional
