### ISSUE TITLE
Fix Hash#rehash

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#2263]
`Hash#rehash` is tagged.

https://github.com/oracle/truffleruby/blob/634c0ae2517d04261b05e357b79da009eeac62ff/spec/tags/core/hash/rehash_tags.txt#L1

@mattalp at Shopify has already been looking at this and has found some more interesting issues not shown by the specs.

**Comment by chrisseaton** [comment]
@eregon can you assign @MattAlp?

**Comment by eregon** [comment]
I cannot, Matt would need to reply here, then I or you could assign (GitHub requirement).

**Comment by MattAlp** [comment]
Replying

**Comment by eregon** [comment]
Fixed by https://github.com/oracle/truffleruby/pull/2310
