### ISSUE TITLE
Kernel.format does not truncate strings that are too long

### ISSUE THREAD

**Issue by reidmorrison** [oracle/truffleruby#2281]
Using the nightly build version of Truffle Ruby:

Expected results:
~~~ruby
2.5.8 001:0> size = 10
10
2.5.8 002:0> value = "Hello World. Truncate this please."
"Hello World. Truncate this please."
2.5.8 003:0> format("%-#{size}.#{size}s", value)
"Hello Worl"

~~~

Actual Result:
~~~ruby
irb(main):001:0> size = 10
=> 10
irb(main):002:0> value = "Hello World. Truncate this please."
=> "Hello World. Truncate this please."
irb(main):003:0> format("%-#{size}.#{size}s", value)
=> "Hello World. Truncate this please."
~~~

**Comment by eregon** [comment]
Thanks for the report, @bjfish could you take a look?

**Comment by chrisseaton** [comment]
This seems like unusually low-hanging fruit - can we see if we can find a beginner to work on it? @MattAlp for example?

**Comment by eregon** [comment]
Sounds fine to me.
@MattAlp if you are interested to work on this one, could you reply here?

**Comment by MattAlp** [comment]
Sure thing. I'll pick it up on Sunday.

**Comment by chrisseaton** [comment]
We figured out this was completely missing support for precision for strings. We started work on it today.

**Comment by chrisseaton** [comment]
Did you make any progress on this, @MattAlp?

**Comment by kirs** [comment]
Found a few more bugs while working on this:

* https://github.com/oracle/truffleruby/issues/2314
* https://github.com/oracle/truffleruby/issues/2313
