### ISSUE TITLE
Reusing precompiled gems between different development builds of TruffleRuby

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2284]
Reinstalling gems with native extensions can take a while, so we should ideally only change the ABI version (= `RbConfig::CONFIG['ruby_version']`) when needed.
I think we should probably update the ABI version manually (can be a simple number we increment) + have a CI check that if any of the headers, mkmf.rb or rbconfig.rb change then ensure the ABI version has been bumped.
That check is also similar to the Makefile check we have for "should we recompile core C extensions" in https://github.com/oracle/truffleruby/blob/3ac8cc47598c079d7ce30de0e02b20768b64005a/src/main/c/Makefile#L27
and that seems to work reasonably well.

I think nowadays it's rather infrequent to change the ABI, we almost never touch headers.
For releases, the release version would be the ABI version. (maybe keeping an extra digit with the ABI version, but might be confusing)

We could also try to use a C ABI checking tool (https://lvc.github.io/abi-compliance-checker/) but I guess that's a lot more involved to setup and might be inaccurate.

**Comment by eregon** [comment]
FWIW I've tried https://github.com/lvc/abi-dumper which works kind of OK, but the output does not always have the right ordering and is platform-dependent. It also kept giving warnings. Also installing this tool might not always be easy.
The old mode https://github.com/lvc/abi-compliance-checker for did not work at all for me, and comparing 2 abi-dumper dumps actually failed to notice a new function.

So let's do the manual review of ABI whenever one the files susceptible to change ABI is modified, and check that in CI by having a manually-updated "ABI version" and "check version" (which indicates it was reviewed and there is no ABI change).

**Comment by chrisseaton** [comment]
Can we have a debug flag right now to change the gem installation path and mix ABIs at our own risk?

**Comment by eregon** [comment]
I have a PR that implements the check in CI and only increasing the ABI version when needed, it should merge soon.

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/34c7477027c5eec77f40a0b6e6f327bc3a45f4be, now the ABI should only change when required.
