### ISSUE TITLE
Time::at with a Rational argument doesn't return seconds to the correct decimal place

### ISSUE THREAD

**Issue by wildmaples** [oracle/truffleruby#2286]
# Background

When a `Time` is created using [`Time::at`](https://ruby-doc.org/core-2.6.3/Time.html#method-c-at) which a `Rational` object, the decimal points are off by a few. However, it isn't an issue when the Rational number gets smaller. Alternatively, if we use `Time::at(seconds, microseconds_with_frac)` everything is ok. 

Here are some ✨ ~code snippets ~ ✨  to demonstrate the issue. 

# Examples 

This is a reproduction of the original issue we found on SFR. The decimal places is off by 3 places in the time produced by TruffleRuby. 

#### MRI 

```
➜  ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

➜  irb
> rat = Rational(1_486_570_508_539_759, 1_000_000)
=> (1486570508539759/1000000)
> time = Time.at(rat)
=> 2017-02-08 11:15:08.539759 -0500
```

#### TruffleRuby

```
➜  ruby -v
truffleruby 21.1.0-dev-464297e8, like ruby 2.7.2, GraalVM CE JVM [x86_64-darwin]

➜  irb
> rat = Rational(1_486_570_508_539_759, 1_000_000)
=> (1486570508539759/1000000) 
> time = Time.at(rat)
=> 2017-02-08 11:15:08.539758921 -0500 ❌ # off by 3 
```

---------------------------

This is to show that a smaller Rational number actually does matches up with MRI decimal points. 

#### MRI  
```

> small_rat = Rational(1_486_570, 1_000_000_000)
=> (148657/100000000)
> time = Time.at(small_rat)
=> 1969-12-31 19:00:00.00148657 -0500
```

#### TruffleRuby

```
> small_rat = Rational(1_486_570, 1_000_000_000)
=> (148657/100000000)
> time = Time.at(small_rat)
=> 1969-12-31 19:00:00.00148657 -0500 ✅
```

---------------------------

And here, we see that if we simply used `Time::at(seconds, microseconds_with_frac)`, which is an alternate way of getting the same `Time` object. TruffleRuby has no problem with it. 

#### MRI 
```
> time = Time.at(1_486_570_508, 539_759)
=> 2017-02-08 11:15:08.539759 -0500 
```

#### TruffleRuby

```
> time = Time.at(1_486_570_508, 539_759)
=> 2017-02-08 11:15:08.539759 -0500 ✅
```

# Issue

We think that TruffleRuby's decimal points don't match with MRIs is because TruffleRuby uses an intermediate floating point number when creating a Time from a Rational. Floating points get less precise the larger the number, which is the behaviour we're seeing right now. 

# Solution

Again, haven't looked into any code, but I can write a spec that covers this case. 

Do you have any lead/insight for the solution? Would it be easy to fix this? 

What is an alternate object to `Float` we can use to ensure precision when creating the `Time`?

**Comment by chrisseaton** [comment]
Looks like it does try to handle `Rational`?

https://github.com/Shopify/truffleruby/blob/ffeea5619fa8a123da947379ae038c9dcac1205d/src/main/ruby/truffleruby/core/type.rb#L468

**Comment by wildmaples** [comment]
It never reaches the else block, it stops at the first if-block:  https://github.com/Shopify/truffleruby/blob/ffeea5619fa8a123da947379ae038c9dcac1205d/src/main/ruby/truffleruby/core/type.rb#L461

The object passed in seems to be an `Integer`.

**Comment by wildmaples** [comment]
I think I found the issue: the [`sec` argument in the `Time::at` method](https://github.com/Shopify/truffleruby/blob/ffeea5619fa8a123da947379ae038c9dcac1205d/src/main/ruby/truffleruby/core/time.rb#L303) in time.rb [doesn't have a case to handle the `Rational` type](https://github.com/Shopify/truffleruby/blob/ffeea5619fa8a123da947379ae038c9dcac1205d/src/main/ruby/truffleruby/core/time.rb#L312).

**Comment by eregon** [comment]
I remember doing an optimization for `Time.at(Float)`, but I think it doesn't affect `Time.at(Rational)`.

I think `Time.at(Rational)` should work by going to the second part of the method (the first part is the fast path for simple cases, Rational is not really a simple case).
Maybe these computations are losing precision by converting to a Float at some point:
https://github.com/Shopify/truffleruby/blob/ffeea5619fa8a123da947379ae038c9dcac1205d/src/main/ruby/truffleruby/core/time.rb#L344-L351

**Comment by eregon** [comment]
This is something that probably makes a lot of sense to debug with `--inspect` or VS Code.
