### ISSUE TITLE
require '/absolute/path/' is much slower than $LOADED_FEATURES.include?

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2312]
Found by @fxn in https://github.com/fxn/zeitwerk/pull/157#issuecomment-813988837

```ruby
require "benchmark/ips"

ME = File.expand_path(__FILE__, __dir__)
$LOADED_FEATURES.clear
$LOADED_FEATURES << ME

Benchmark.ips do |x|
  x.report("lookup") do
    $LOADED_FEATURES.include?(ME)
  end

  x.report("require") do
    require ME
  end

  x.compare!
end
```

**Comment by eregon** [comment]
@bjfish Could you take a look and profile this with `--cpusampler`?

**Comment by eregon** [comment]
I get different results with:
```
$ ruby -v
truffleruby 21.1.0-dev-8deb9b1f, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]
$ ruby bench_require_absolute.rb             
Warming up --------------------------------------
              lookup   924.146k i/100ms
             require    40.170k i/100ms
Calculating -------------------------------------
              lookup      9.185M (± 0.7%) i/s -     46.207M in   5.031227s
             require    814.710k (± 0.8%) i/s -      4.097M in   5.029540s

Comparison:
              lookup:  9184577.2 i/s
             require:   814709.9 i/s - 11.27x  (± 0.00) slower
```

I wonder if maybe it's due to running on macOS or some other environment-specific thing like maybe the pwd having a symlink in it?

**Comment by eregon** [comment]
Very similar with 972a0521 which the same version you used:
```
$ ruby -v
truffleruby 21.1.0-dev-972a0521, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]
$ ruby bench_require_absolute.rb
Warming up --------------------------------------
              lookup     1.050M i/100ms
             require    40.892k i/100ms
Calculating -------------------------------------
              lookup     10.586M (± 1.5%) i/s -     53.573M in   5.061713s
             require    832.544k (± 0.7%) i/s -      4.171M in   5.010191s

Comparison:
              lookup: 10586420.9 i/s
             require:   832543.8 i/s - 12.72x  (± 0.00) slower
```

**Comment by eregon** [comment]
Ah, I think I found why, it's because I was benchmarking with `export RUBYLIB=$HOME/code/benchmark-ips/lib` for convenience, but that means RubyGems isn't loaded.

If I don't do that and `gem i benchmark-ips` instead, then I have a much larger difference:
```
$ ruby -v
truffleruby 21.1.0-dev-972a0521, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]
$ ruby bench_require_absolute.rb
Warming up --------------------------------------
              lookup   876.011k i/100ms
             require     3.799k i/100ms
Calculating -------------------------------------
              lookup      9.241M (± 1.7%) i/s -     46.429M in   5.025546s
             require     63.880k (± 3.0%) i/s -    322.915k in   5.059515s

Comparison:
              lookup:  9241074.4 i/s
             require:    63879.6 i/s - 144.66x  (± 0.00) slower
```

**Comment by fxn** [comment]
Interesting. Yes, I ran the benchmark on macOS.

In a string that exists as is in `$LOADED_FEATURES` do you think symlinks matter? Is there disk access involved if the string is found?

**Comment by eregon** [comment]
I guess the overhead (12x=>144x) is mostly due to all the extra logic in RubyGems' `require`.
That monitor usage is probably quite expensive, and since 2.7 CRuby uses a native extension for `monitor`, which might be faster than the pure-ruby version.
There is likely also quite a lot of disk accesses & extra computation by RubyGems before it calls the original `require`.

If I follow https://github.com/oracle/truffleruby/blob/972a0521668532c070bdf9915e2524d3fefadb44/src/main/ruby/truffleruby/core/truffle/feature_loader.rb#L81 correctly, the original require does not seem to do any disk access when the cache is valid and the required path ends in `.rb` or has no extension.

**Comment by eregon** [comment]
In RubyGems 3.1.4 shipped with Ruby 2.7.2 there is pretty heavy logic doing File.expand_path in a double loop of $LOAD_PATH and Gem.suffixes (= `["", ".rb", ".so"]`):
https://github.com/oracle/truffleruby/blob/972a0521668532c070bdf9915e2524d3fefadb44/lib/mri/rubygems/core_ext/kernel_require.rb#L44-L67

The actual time spent in the original require is only ~10% of the time spent in RubyGems' require.

**Comment by eregon** [comment]
So this seems almost entirely a RubyGems issue, and newer RubyGems seems faster.

RubyGems 3.2.3 shipped with CRuby 3.0.0:
```
Calculating -------------------------------------
              lookup     17.290M (± 0.8%) i/s -     87.626M in   5.068328s
             require    725.701k (± 1.6%) i/s -      3.652M in   5.033374s

Comparison:
              lookup: 17290026.2 i/s
             require:   725701.3 i/s - 23.83x  (± 0.00) slower
```

RubyGems 3.1.4 shipped with CRuby 2.7.2:
```
Calculating -------------------------------------
              lookup     15.191M (± 0.5%) i/s -     77.328M in   5.090371s
             require     89.705k (± 0.4%) i/s -    454.104k in   5.062292s

Comparison:
              lookup: 15191334.7 i/s
             require:    89704.9 i/s - 169.35x  (± 0.00) slower
```

So when we update to a newer RubyGems (probably when migrating to 3.0) it should be similar to CRuby 3.0.0 results.

**Comment by fxn** [comment]
@eregon This can be closed perhaps after your discovery? I left a summary in https://github.com/fxn/zeitwerk/pull/157#issuecomment-814063956.

**Comment by eregon** [comment]
Yeah I think we can close this, it'll be naturally solved when updating RubyGems.
If there are performance issues in practice with RubyGems 3.2.3 we might consider updating it before updating to 3.0.0.
