### ISSUE TITLE
String#inspect and encodings

### ISSUE THREAD

**Issue by kirs** [oracle/truffleruby#2313]
(discovered this while pairing with @chrisseaton on https://github.com/oracle/truffleruby/pull/2308)

```ruby
puts RUBY_DESCRIPTION
source = 'foobar'.encode('utf-16le')
puts source
puts source.inspect
```

On MRI this prints:

```
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
foobar
"foobar"
```

And on TruffleRuby:

```
truffleruby 21.1.0-dev-70fe61f3, like ruby 2.7.2, GraalVM CE JVM [x86_64-darwin]
foobar
"\u0066\u006F\u006F\u0062\u0061\u0072"
```

I think this one would benefit from consistency with MRI because developers might be surprised by `"\u0066\u006F\u006F\u0062\u0061\u0072"` while it's a legit string.

**Comment by eregon** [comment]
Yes, that would be good to fix.

**Comment by kirs** [comment]
👍 I can see what I can do once https://github.com/oracle/truffleruby/pull/2308 is merged

**Comment by kirs** [comment]
Let me braindump what I discovered and maybe you'll share some ideas.

```ruby
puts RUBY_DESCRIPTION

puts 'foobar ね'.encode("utf-16le").inspect

puts 'foobar'.encode("windows-1251").inspect

puts 'привет foobar?!'.encode("windows-1251").inspect
```

```
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
"foobar \u306D"
"foobar"
"\xEF\xF0\xE8\xE2\xE5\xF2 foobar?!"
```

No matter the encoding, MRI prints ASCII-compatible chars in the human readable on `inspect`.

Here's the implementation: https://github.com/ruby/ruby/blob/master/string.c#L6156-L6247 - I'm having hard time following that.

So I'm guessing that in TruffleRuby we'd need some way to determine if a character from another encoding is ASCII-compatible, and if it is, print it.

**Comment by chrisseaton** [comment]
Also check what JRuby does. We use the same encodings library as them, so if they can do it correctly we should be able to connect it up to the library we both use in the same way.

**Comment by eregon** [comment]
> some way to determine if a character from another encoding is ASCII-compatible,

That can be checked by `Encoding#isAsciiCompatible() && Encoding.isAscii(byte/int)`.

We should probably try to follow the MRI logic as much as possible here since it seems quite complicated with lots of corner cases.
