### ISSUE TITLE
RbConfig::CONFIG["mandir"] should be set

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2315]
It might be a good idea in general to check which other keys we might be missing in RbConfig compared to CRuby.

See https://github.com/rubygems/rubygems/pull/4209#issuecomment-756967502

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/efb16331c2ab4787492e7901a4a915ba732ac4b7
