### ISSUE TITLE
CI Native Image step seems broken

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#2319]
```
Building graalvm-native-ld.image... [dependency GRAALVM_17E9D1B1CF_JAVA11_STAGE1 updated]
Error: Could not find or load main class com.oracle.svm.driver.NativeImage
Caused by: java.lang.ClassNotFoundException: com.oracle.svm.driver.NativeImage
Building graalvm-native-ld.image failed
1 build tasks failed
```

https://github.com/oracle/truffleruby/pull/2318/checks?check_run_id=2291296400#step:9:27

Seems on all branches, unrelated to changes in the branch.

**Comment by eregon** [comment]
Internal issue: GR-30713
There is a PR from @olpaw fixing this that should be merged soon.

**Comment by olpaw** [comment]
The fix is on master https://github.com/oracle/graal/commit/d866b4ab387bd461e8681a462956839def26c752

**Comment by eregon** [comment]
I'll update the graal import in truffleruby to get that fix.

**Comment by olpaw** [comment]
> I'll update the graal import in truffleruby to get that fix.

Thanks!

**Comment by eregon** [comment]
Import update done, the CI on GitHub Actions is fixed, and truffleruby-dev builds are running again.
