### ISSUE TITLE
Mass fiber creation is slow

### ISSUE THREAD

**Issue by LillianZ** [oracle/truffleruby#2325]
While looking at a random benchmark, it was unexpectedly slow on TR. It seems that this is because fiber creation is slow:

``` ruby
puts RUBY_DESCRIPTION
require 'benchmark/ips'

Benchmark.ips do |x|
  x.report('Fiber') do
    f = Fiber.new do
      x = Kernel.rand(100) * Kernel.rand(100) 
    end
  end
end
```

```
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
Warming up --------------------------------------
               Fiber   130.120k i/100ms
Calculating -------------------------------------
               Fiber      1.399M (± 3.9%) i/s -      7.026M in   5.032245s

truffleruby 21.1.0-dev-972a0521, like ruby 2.7.2, GraalVM CE JVM [x86_64-darwin]
Warming up --------------------------------------
               Fiber   189.000  i/100ms
Calculating -------------------------------------
               Fiber    469.824  (±23.2%) i/s -      2.457k in   5.495864s
```

Relative TR performance gets worse as more fibers are created (ie when I increase warmup time).

Unclear how important this issue is since fibers are usually not created in the thousands.

**Comment by eregon** [comment]
That's kind of expected and documented: https://github.com/oracle/truffleruby/blob/master/doc/user/compatibility.md#fibers-do-not-have-the-same-performance-characteristics-as-in-mri

The benchmark doesn't actually run the code in the Fiber, you would need `f.resume` for that.
Could you rerun the benchmark with that?

TruffleRuby does use a thread pool for Fibers so it shouldn't be too bad but still.
I think here what's visible is that in TruffleRuby we wait for the Fiber to be initialized, and it's also created on Fiber#initialize (so on `Fiber.new`).
Maybe we could avoid that.
Also potentially when we merge support for TruffleSafepoint it might be a bit better as we need to disable & reenable safepoints when switching between Fibers to avoid triggering multithreading.

For curiosity, could you compare to JRuby too?

**Comment by hanabi1224** [comment]
Reporting another case here, below program is ported from the concurrent-prime-sieve example from [golang homepage](https://golang.org/), it creates another coroutine for every prime number found, thus can be used to demonstrate / benchmark performance of massive coroutine scheduling and communication, it runs ok with ruby but is very slow with truffleruby today.

```ruby
def get_n()
    n = 100
    if ARGV.size > 0
        n= Integer(ARGV[0])
    end
    n
end

def generate()
    return Fiber.new do
        i = 2
        while true do
            Fiber.yield i
            i += 1
        end
    end
end

def filter(fiber_in, prime)
    return Fiber.new do 
        while true do
            i = fiber_in.resume
            if i % prime != 0
                Fiber.yield i
            end
        end
    end
end

n = get_n()
ch = generate
(0...n).each do
    prime = ch.resume
    puts prime
    ch = filter(ch, prime)
end
```

**Comment by eregon** [comment]
> Relative TR performance gets worse as more fibers are created (ie when I increase warmup time).

That's because the benchmark leaks Fibers essentially, since they are never run or terminated.
And leaking Fibers means many more alive threads, much bigger heap, longer GCs, no Fiber pool reuse, etc.
In summary, it's no better than a big memory leak.

Here is a Fiber creation benchmark which does not leak Fibers:
```ruby
benchmark 'fiber-create' do
  Fiber.new { nil }.resume
end
```

Results:
* CRuby 2.7: 882,599
* JVM CE: 44,622
* JVM CE `--fiber-leave-context=false`: ~43,949, but some iterations as fast as 98,432

The difference is I expect mostly the cost of thread switching vs coroutine switching in this case, and potentially the cost of initializing the Fiber (the same Java Thread is reused for all Fibers so that's not a concern in this benchmark).

**Comment by eregon** [comment]
This will be addressed once Fibers are based on Loom. Until then it's documented, so I think we can close this issue.
I added a micro benchmark to measure Fiber creation time.
