### ISSUE TITLE
`define_method` in `self << class` block creates private method instead of public one

### ISSUE THREAD

**Issue by ojab** [oracle/truffleruby#2334]
Found in [`king_konf`](https://github.com/dasch/king_konf) gem, minified testcase:

```ruby
class Config
  class << self
    define_method(:integer) do |name|
      define_method(name) { nil }
    end

    private
  end
end

klass = Class.new(Config) { integer :value }
klass.new.value
```
Works fine on MRI, on `truffleruby 21.0.0, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]` installed via `rbenv` there is
```
$ ruby /tmp/2.rb
/tmp/2.rb:16:in `<main>': private method `value' called for #<#<Class:0x418>:0x428> (NoMethodError)
```

The error goes away if `private` is removed.

**Comment by eregon** [comment]
Thanks for the report.

That's interesting, so the `private` is not visible to the nested `define_method` in CRuby, even though `define_method` inside a block would normally inherit the visibility outside the block:
```ruby
class C
  later = -> do
    define_method(:foo) { :foo }
  end

  private
  later.call
end
p C.new.foo # => private method `foo' called for #<C:0x000055de497e4a28> (NoMethodError)
```

I think this might be quite tricky to fix unfortunately.
In this case, could I suggest using `public def desc` or `public :desc` in https://github.com/dasch/king_konf/blob/1f7e912300474ed338d811463f44aa1749a3f0b4/lib/king_konf/config.rb#L66-L68?
That seems much more robust, given that `private` normally affects methods in blocks too.

**Comment by eregon** [comment]
The logic in CRuby seems to be:
https://github.com/ruby/ruby/blob/3c8a67e8a5f51f337cf95b4038ed97bf8ca8b696/proc.c#L2197-L2198
https://github.com/ruby/ruby/blob/3c8a67e8a5f51f337cf95b4038ed97bf8ca8b696/vm.c#L1644

Notably if the module to define on is different than `self` in the caller frame, then the visibility of the new method is simply `public`.

**Comment by ojab** [comment]
While I'm pretty sure that your analysis is correct, I _think_ you're overthinking/misread the reported issue :) 

In the example above `Config.integer` is public and `private` shouldn't actually change anything.

**Comment by eregon** [comment]
I've got a fix now. `Config.integer` is public on both CRuby and TruffleRuby, the difference is for `Config#value`.
`define_method` itself sets up a visibility inside the new method the same as outside (both CRuby and TruffleRuby), the tricky part is when deciding the visibility of the new method: it is decided not only based on the surrounding visibility but also based on the new method name, caller self and caller default definee.
