### ISSUE TITLE
`File.mtime` doesn't return milliseconds

### ISSUE THREAD

**Issue by AlexWayfer** [oracle/truffleruby#2337]
```
truffleruby 21.1.0, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]
```

Related:
* https://github.com/jruby/jruby/issues/4520
* https://github.com/ruby/spec/pull/386

**Comment by eregon** [comment]
Thank you for the report, I can reproduce:
```
ruby -e 'p File.mtime("README.md").to_f'   
1619184907.0575614
truffleruby -e 'p File.mtime("README.md").to_f'
1619184907.0
```

**Comment by AlexWayfer** [comment]
Yep, sorry for a lack of example, I didn't know how to make it laconically.

**Comment by eregon** [comment]
We use `struct stat`.`st_mtime` and that's a number of seconds, but some platforms have `struct stat`.`st_mtim` which is a `struct timespec`.
https://github.com/oracle/truffleruby/blob/1d46891ebbfb1df28319b8e0e7819e21d4511bcf/src/main/c/truffleposix/truffleposix.c#L397
If we store both seconds and nanonseconds into a `uint64_t`, then it would work until:
```
> Time.at((2 ** 64) / 1e9)
=> 2554-07-22 01:34:33 186005/262144 +0200
```
but not after.
So it's probably best to use an extra field for the nanoseconds.

**Comment by bjfish** [comment]
This is fixed at: https://github.com/oracle/truffleruby/commit/fde89ae07d4e2cb66397f9bde6c2eaf83d58a7eb.
