### ISSUE TITLE
Implement Fiber#raise

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2338]
It's part of the new 2.7 methods: https://github.com/oracle/truffleruby/issues/2004
And it's used notably by https://github.com/socketry/event/issues/2
cc @ioquatix

**Comment by ioquatix** [comment]
Thanks, and also allow `Fiber#transfer` and `Fiber#resume/yield` interleaved.

**Comment by eregon** [comment]
The change for Fiber#transfer allowed in more cases is only in Ruby 3.0+ though, right?

**Comment by ioquatix** [comment]
> The change for Fiber#transfer allowed in more cases is only in Ruby 3.0+ though, right?

It is purely additive, it won't break Ruby 2.x

**Comment by eregon** [comment]
Looking at Fiber specs, it seems there would be specs that break if we change the behavior of `Fiber#transfer` while reporting RUBY_VERSION as 2.7:
https://github.com/oracle/truffleruby/blob/master/spec/ruby/library/fiber/transfer_spec.rb
https://github.com/oracle/truffleruby/blob/master/spec/ruby/library/fiber/resume_spec.rb

Is it needed by https://github.com/socketry/event ?

**Comment by ioquatix** [comment]
The event library needs the following:

- Fiber#raise (for cancellation)
- Fiber#transfer (for non-blocking operation)

For new version of async which depends on `event`, `Fiber#resume` and `Fiber#yield` is not used. It's purely for user code.

**Comment by eregon** [comment]
Fiber#raise was implemented in https://github.com/oracle/truffleruby/commit/52f7d8bbcee0bda019620d7b8189b60cbedcf760 by @bjfish.
If we need to allow more cases for `transfer` to pass tests/specs of `event` or `async`, could you create a separate issue?

**Comment by eregon** [comment]
Looks like the `event` specs need Fiber#raise to be allowed after Fiber#transfer: https://github.com/socketry/event/pull/5#issuecomment-831210501
That's a change of Ruby 3 as well: https://github.com/ruby/ruby/pull/3795/files#diff-f5e06781d15d3a6c16eef4cb49eebc310820bead3672ed84608c84958ae5da14R2341-R2343

**Comment by ioquatix** [comment]
Yes, `Fiber#raise` must do the right thing in order to transfer back to the fiber.
