### ISSUE TITLE
File.basename returns frozen String

### ISSUE THREAD

**Issue by jeremyevans** [oracle/truffleruby#2343]
A few of Roda's tests are failing on TruffleRuby because `File.basename` is returning a frozen string, while CRuby and JRuby return a new unfrozen string: https://github.com/jeremyevans/roda/runs/2492967121?check_suite_focus=true#step:4:17

Code in question:

```ruby
            param_filename = File.basename(filename)
            encoding = param_filename.encoding

            needs_encoding = param_filename.gsub!(/[^ 0-9a-zA-Z!\#$&\+\.\^_`\|~]+/, '-') # FrozenError raised here
```

**Comment by eregon** [comment]
Thank you for the report!
It's probably a case where the argument is returned, and the argument is a frozen String.

@bjfish Could you fix it?

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/d2c863850e9824f4fc8322ec904c43e867161536
