### ISSUE TITLE
DateTime::new doesn't return the correct sec_fraction

### ISSUE THREAD

**Issue by wildmaples** [oracle/truffleruby#2344]
_I wrote this issue in our private repo a while back when we were looking at getting SFR tests running on TR. This issue impacts two tests in SFR. The team is prioritizing something else right now so I'm creating an issue here so everyone is aware._

# Issue 

The TruffleRuby implementation does not return the correct `DateTime` fractional seconds as MRI. 

# Investigation

Take this code example `foo.rb`:

```ruby
require 'date'

value = DateTime.new(2017, 2, 8, 11, 25, 12.571685, "EST") # seconds with fractions
puts "datetime: " + value.inspect
puts "second: " + value.second.inspect
puts "sec_fraction: " + value.sec_fraction.inspect
puts "offset: " + value.offset.inspect

puts

value = DateTime.new(2017, 2, 8, 11, 25, 12, "EST") # seconds without fractions
puts "datetime: " + value.inspect
puts "second: " + value.second.inspect
puts "sec_fraction: " + value.sec_fraction.inspect
puts "offset: " + value.offset.inspect
```

# Output 

### MRI 

```ruby
datetime: #<DateTime: 2017-02-08T11:25:12-05:00 ((2457793j,59112s,571685000n),-18000s,2299161j)>
second: 12
sec_fraction: (114337/200000)
offset: (-5/24)

datetime: #<DateTime: 2017-02-08T11:25:12-05:00 ((2457793j,59112s,0n),-18000s,2299161j)>
second: 12
sec_fraction: (0/1)
offset: (-5/24)
```

### TR

```ruby
datetime: #<DateTime: 2017-02-08T11:25:12-05:00 (1459280979720247490449/593736278999040,-5/24,2299161)>
second: 12
sec_fraction: (19642947029/34359738368) ❌
offset: (-5/24)

datetime: #<DateTime: 2017-02-08T11:25:12-05:00 (2949351821/1200,-5/24,2299161)>
second: 12
sec_fraction: (0/1) 👌
offset: (-5/24)
```

# Questions 

Aside from the obvious difference, there are some curious differences between the two DateTime inspect output. 

1. In the TruffleRuby output, it seems like the `offset` value is correctly returned but it does not align with DateTime's inspect in MRI: 

MRI: datetime: #<DateTime: 2017-02-08T11:25:12-05:00 ((2457793j,59112s,571685000n),**-18000s**,2299161j)>
vs
TR: datetime: #<DateTime: 2017-02-08T11:25:12-05:00 (1459280979720247490449/593736278999040,**-5/24**,2299161)>

2. MRI's version of the `DateTime` output seems to be an array of array containing what I'm assuming to be, (fraction seconds, offset, Julian Day).
 
```
((2457793j,59112s,571685000n),-18000s,2299161j)
```

Why is the fractional seconds broken down into an array of 3 numbers? TruffleRuby's fraction second has it as a Rational number, which seems... rational 🤪

**Comment by bjfish** [comment]
This may be related to internal issue GR-27260 "Invalid datetime day_fraction":
```
% jt ruby -rdate -e 'p DateTime.civil(2005, 2, 1, 15, 15, 10.7).day_fraction'
(50312460949433/79164837199872)
% ruby -rdate -e 'p DateTime.civil(2005, 2, 1, 15, 15, 10.7).day_fraction' 
(549107/864000)
```

**Comment by bjfish** [comment]
This is now fixed at https://github.com/oracle/truffleruby/commit/1efa5322390773fa6a4028dba3849d5ba871b30a
