### ISSUE TITLE
official docker images: no yum

### ISSUE THREAD

**Issue by HoneyryderChuck** [oracle/truffleruby#2349]
I'm experimenting with the recently released docker images. However, I can't seem to find a package manager. Being it oraclelinux, I'd expect at least `yum` to be there. How am I supposed to  install packages there?

**Comment by eregon** [comment]
I can reproduce, indeed, there seems to be no yum:
```
$ docker run --rm -it --entrypoint bash ghcr.io/graalvm/truffleruby:latest 
bash-4.4# yum --version
bash: yum: command not found
```

**Comment by ezzarghili** [comment]
Please use microdnf, the latest image is based on OracleLinux 8 slim image

**Comment by eregon** [comment]
Currently https://github.com/orgs/graalvm/packages/container/package/truffleruby doesn't point to the documentation at https://github.com/graalvm/container/blob/master/truffleruby/README.md, but that's being worked on.

I think the best is to document about `microdnf` in the common README for docker images (https://github.com/graalvm/container/blob/master/README.md, does not yet exist).
Maybe a `yum` or `dnf` alias would make sense?

There is also something not so intuitive with the ENTRYPOINT, I think we should have no ENTRYPOINT and `CMD [ "irb" ]`, just like https://github.com/docker-library/ruby/blob/57fbb486ad5a793c83a47a4c1ef36160f7abd28e/3.0/buster/Dockerfile#L88, tracked as https://github.com/graalvm/container/issues/14

**Comment by eregon** [comment]
This is documented in https://github.com/graalvm/container/blob/master/truffleruby/README.md now, and that's linked from the TruffleRuby README.
