### ISSUE TITLE
Enumerator::Lazy missing `filter_map` and `with_index` methods

### ISSUE THREAD

**Issue by ivoanjo** [oracle/truffleruby#2356]
Hello, hello 👋 

I'm again spending a few minutes trying to get @Datadog's [ddtrace](https://github.com/DataDog/dd-trace-rb) gem specs going with TruffleRuby and I've noticed that `Enumerator::Lazy` is missing a few more methods (beyond those fixed in #2273), which forces lazy enumerators to become eager (non-lazy). The impact can be that, of course, if you do that with an infinite enumerator, the app will break (and in general it breaks the expected semantics).

In particular, the following are still not lazy on TruffleRuby:

* `filter_map`

```ruby
# truffleruby 21.1.0, like ruby 2.7.2, GraalVM CE Native [x86_64-darwin]
[10] pry(main)> [1].lazy.filter_map(&:zero?)
=> []
# ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin19]
[7] pry(main)> [1].lazy.filter_map(&:zero?)
=> #<Enumerator::Lazy: ...>
```

* `with_index`

```ruby
# truffleruby 21.1.0, like ruby 2.7.2, GraalVM CE Native [x86_64-darwin]
[19] pry(main)> [1].lazy.with_index(&:+)
=> [1]
# ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin19]
[14] pry(main)> [1].lazy.with_index(&:+)
=> #<Enumerator::Lazy: ...>
```

**Comment by eregon** [comment]
Thank you for the report. @bjfish Could you look at this?

**Comment by eregon** [comment]
As a note, it seems both of these methods are new as of Ruby 2.7.

**Comment by bjfish** [comment]
These methods have been implemented at:
https://github.com/oracle/truffleruby/commit/3c681607abb7d85e0103ee4495a3b8fdc50bfa85
https://github.com/oracle/truffleruby/commit/e6e7a0eb493a0f4562f0ea3084dfc7ec983a8e3e

**Comment by ivoanjo** [comment]
Thanks @bjfish for looking into this 🙇
