### ISSUE TITLE
Implement Process::Status.wait

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2378]
Requested by @ioquatix, to fix https://github.com/socketry/event/pull/6/checks?check_run_id=2807838780

This is a new Ruby 3 method, it's the same as `Process.wait` but without setting `$?`, so it should be fairly straightforward to add.

There are no specs currently, we should add some basic specs for it.

**Comment by bjfish** [comment]
This has been implemented at https://github.com/oracle/truffleruby/commit/2b88831b97a183db6ab7059dd5875333629e4304.

**Comment by ioquatix** [comment]
Thanks!!!
