### ISSUE TITLE
Native extension ABI version check failing for some gems

### ISSUE THREAD

**Issue by tomstuart** [oracle/truffleruby#2382]
As [discussed](https://github.com/oracle/truffleruby/commit/d497bae73fdc60585b66cd183768a16563b2886b#r52492762), the native extension ABI version check in d497bae73fdc60585b66cd183768a16563b2886b is causing failures when loading some gems on Linux (Ubuntu 20.04.2 LTS).

My current example is the [`semian`](https://rubygems.org/gems/semian) gem:

```
LoadError: The native extension at truffleruby/2.7.3.4/gems/semian-0.11.4/lib/semian/semian.so has a different ABI version: "TRUFFLERUBY_ABI_VERSION" than the running TruffleRuby: "2.7.3.4"
```

@nirvdrum reported a similar problem with the [`google-protobuf`](https://rubygems.org/gems/google-protobuf) gem. I’ll add more examples as I find them.

**Comment by eregon** [comment]
`google-protobuf` is a different case, I already have a PR to fix that (it showed `nil` due the the symbol being hidden).

What happens here most likely is that `TRUFFLERUBY_ABI_VERSION` is not defined somehow, and in that case `STRINGIZE(TRUFFLERUBY_ABI_VERSION);` is replaced by `"TRUFFLERUBY_ABI_VERSION"`.
Probably best to make it a compile/preprocessor-time error if TRUFFLERUBY_ABI_VERSION is not defined for clarity.

**Comment by eregon** [comment]
https://github.com/Shopify/semian/blob/6ff4b8292038fe3f6fc785884129039d5cf3e05f/ext/semian/extconf.rb#L26 is most likely what overrides the CFLAGS and causes the error.

**Comment by tomstuart** [comment]
Makes sense. Is the suggestion that this must be fixed in the gem? Do we have no way of supporting what it’s currently doing?

**Comment by eregon** [comment]
I'll try to find a way that's more reliably to pass the define, but overriding `$CFLAGS` seems problematic in general and might be worth fixing in the gem anyway (appending to `$CFLAGS` is fine, replacing much less).

**Comment by eregon** [comment]
I found a way, I moved the define from debugflags (part of CFLAGS), to DEFS, part of CPPFLAGS (= C preprocessor flags, `CPPFLAGS="cppflags_hardcoded $(DEFS) $(cppflags)"`) which seems better suited.
Here is to hoping nobody overrides `cppflags` or `$CPPFLAGS`.

**Comment by tomstuart** [comment]
FWIW I couldn’t find any other gems with this specific problem. All of the other failures I saw were the `nil` case like `google-protobuf`.

**Comment by eregon** [comment]
FWIW RubyInline includes CFLAGS but not CPPFLAGS when it compiles, but that's probably a bug of RubyInline, so doesn't matter too much.

**Comment by eregon** [comment]
Fixed by https://github.com/oracle/truffleruby/commit/3252693c341d9db8f9ba3065fd891d4c602bf439
