### ISSUE TITLE
`rb_str_modify` seems to fill strings with null bytes.

### ISSUE THREAD

**Issue by ioquatix** [oracle/truffleruby#2392]
My understanding is this method is supposed to blow up if the string is frozen. But existing content should be preserved. However, my test shows otherwise.

https://github.com/oracle/truffleruby/blob/3219bdbd62abd0bb79605320b12e6b2f3355919b/src/main/c/cext/string.c#L176-L178

This is my implementation:

```c
char* Event_Backend_resize_to_capacity(VALUE string, size_t offset, size_t length) {
	size_t current_length = RSTRING_LEN(string);
	long difference = (long)(offset + length) - (long)current_length;
	difference += 1;
	if (difference > 0) {
		rb_str_modify_expand(string, difference);
	} else {
		rb_str_modify(string);
	}
	return RSTRING_PTR(string);
}
```

In this test, we call this method twice, and the following results:

```
  1) Event::Backend::EPoll behaves like Event::Selector #io_read can handle partial reads
     Failure/Error: expect(buffer).to be == message
       expected: == "Hello World"
            got:    "\x00\x00\x00\x00\x00 World"
```

**Comment by eregon** [comment]
rb_str_modify on CRuby 2.7 is:
```c
void
rb_str_modify(VALUE str)
{
    if (!str_independent(str))
	str_make_independent(str);
    ENC_CODERANGE_CLEAR(str);
}
```
Interestingly it's `str_independent` which raises if frozen, ENC_CODERANGE_CLEAR or str_make_independent do not (on CRuby).

Docs:
```
rb_str_modify(VALUE str) ::

  Prepares a Ruby string to modify.  If str is not modifiable, this
  function raises an exception, or if the buffer of str is shared,
  this function allocates new buffer to make it unshared.  Always
  you MUST call this function before modifying the contents using
  RSTRING_PTR and/or rb_str_set_len.
```

rb_str_modify_expand() also calls `str_independent` so also checks if frozen.
We should add a frozen check for both and add C-API specs for that.

Regarding the `\x00` that's less clear, @bjfish could you investigate?
It's from this spec: https://github.com/socketry/event/blob/4ef1dfa1dc9b0ed4909dc444d51148c15e2a03e4/spec/event/selector_examples.rb#L216

The `"Hello World"` in that example does not seem frozen BTW, but I guess it shouldn't be mutated. Would be good to make sure it's also not mutated on MRI.

**Comment by ioquatix** [comment]
I guess my feeling is, Ruby IO using Strings is finally coming to a point where we actually need something a bit better.

So, I'm going to propose `IO::Buffer`. We still need to fix this issue though.

**Comment by nirvdrum** [comment]
> So, I'm going to propose `IO::Buffer`. We still need to fix this issue though.

I'd be happy to add support to such a proposal. You may want to look at a previous feature request for a [byte array type](https://bugs.ruby-lang.org/issues/13166). It has comments from several Ruby core members.

**Comment by eregon** [comment]
https://github.com/ruby/ruby/pull/4621 is the PR by @ioquatix to add `IO::Buffer`.

**Comment by bjfish** [comment]
Both of these issues have been fixed at:
- https://github.com/oracle/truffleruby/commit/00283ee9b7162b1467d9213f7db1606002d3ce0f
- https://github.com/oracle/truffleruby/commit/000482099abb95ffe33eb852b5c1fb5cab57ed65

**Comment by ioquatix** [comment]
Awesome, nice work!
