### ISSUE TITLE
Maybe missing `rb_fiber_current`?

### ISSUE THREAD

**Issue by ioquatix** [oracle/truffleruby#2402]
It compiles, but fails:

https://github.com/socketry/event/runs/3063384404#step:5:63

```
1) Event::Selector::EPoll behaves like queue #push defers push during push to next iteration
		Failure/Error: subject.yield

		RuntimeError:
			External LLVMFunction rb_fiber_current cannot be found. (com.oracle.truffle.llvm.runtime.except.LLVMLinkerException)
			Translated to internal error
		Shared Example Group: "queue" called from ./spec/event/selector/queue_spec.rb:
		# ./ext/event/selector/selector.c:153:in `Event_Selector_wait_and_transfer'
		# ./ext/event/selector/selector.h:117:in `Event_Selector_yield'
		# ./ext/event/selector/epoll.c:130:in `Event_Selector_EPoll_yield'
		# /home/runner/.rubies/truffleruby-head/lib/truffle/truffle/cext_ruby.rb:41:in `yield'
		# ./spec/event/selector/queue_spec.rb:52:in `block (4 levels) in <top (required)>'
```

**Comment by ioquatix** [comment]
It seems like we have it?

https://github.com/oracle/truffleruby/blob/5f4a46271351c5b8e22b078620d826824d6adb7f/lib/cext/include/ruby/intern.h#L250

**Comment by eregon** [comment]
https://github.com/oracle/truffleruby/blob/5f4a46271351c5b8e22b078620d826824d6adb7f/lib/cext/include/ruby/intern.h#L250
is just the prototype, this error means there is no actual definition of the `rb_fiber_current()` function.

So we should add it, @bjfish could you do that?

**Comment by eregon** [comment]
Note that if you use `have_func('rb_fiber_current')` it should correctly find out that it's not available on TruffleRuby (until we add it).

**Comment by ioquatix** [comment]
Thanks, sorry, I didn't realise this was needed. I can add it.

**Comment by eregon** [comment]
> Thanks, sorry, I didn't realise this was needed. I can add it.

It's just a good way to workaround if the function is not available, but we'll add it soon anyway (if you use `truffleruby-head`).

We noticed other `rb_fiber_*` functions are also not defined currently on TruffleRuby and will add those too.

**Comment by bjfish** [comment]
This is now implemented at: https://github.com/oracle/truffleruby/commit/06bc34f55d238747b832581a71ce2cd413e0d0d0. Thank you for reporting this.
