### ISSUE TITLE
TRegex matches aren't counted with `--regexp-instrument-match` flag

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#2416]
One of the instrumentation options is to see how frequently regular expressions are matched against via the `--regexp-instrument-match` flag. Only regular expressions that are processed by Joni get counted at the moment because the only instrumentation is in `TruffleRegexpNodes.MatchNode`. TRegex matches will go through `TruffleRegexpNodes.MatchInRegionTRegexNode` and will need to be instrumented as well, deferring such instrumentation until after it's been determined that the match won't fall back to Joni (otherwise, we'll double-count matches for those cases).

**Comment by nirvdrum** [comment]
It might be worth rolling `--warn-truffle-regex-match-fallback` up into the other `REGEXP_INSTRUMENT_` options. I would find it helpful to see the regex creation and match data split up by the regex engine.

**Comment by eregon** [comment]
Indeed, PR welcome :)
Sounds fine to separate in the output of `--regexp-instrument-match`, could be done easily with a boolean in `MatchInfo`.

**Comment by nirvdrum** [comment]
Sounds good. I have a local patch that I'll clean up for next week.
