### ISSUE TITLE
require "strscan.so" uses the strscan gem and does not work

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2420]
```
$ gem i strscan
Fetching strscan-3.0.0.gem
Building native extensions. This could take a while...
Successfully installed strscan-3.0.0
1 gem installed

$ ruby -e 'require "strscan.so"; puts $".grep(/strscan/); p StringScanner.new("")'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/strscan-3.0.0/lib/strscan.so
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/strscan-3.0.0/ext/strscan/strscan.c:214:in `strscan_s_allocate': External LLVMFunction onig_region_init cannot be found. (com.oracle.truffle.llvm.runtime.except.LLVMLinkerException) (RuntimeError)
Translated to internal error
	from /home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1240:in `__allocate__'
	from -e:1:in `<main>'
```

However `require "strscan"` picks the stdlib and works fine:
```
$ ruby -e 'require "strscan"; puts $".grep(/strscan/); p StringScanner.new("")'
/home/eregon/.rubies/truffleruby-dev/lib/truffle/strscan.rb
#<StringScanner fin>
```

Even `bundle exec` picks the stdlib:
```
$ cat Gemfile
gem "strscan"
$ bundle exec ruby -e 'require "strscan"; puts $".grep(/strscan/); p StringScanner.new("")' 
/home/eregon/.rubies/truffleruby-dev/lib/truffle/strscan.rb
#<StringScanner fin>
```

Found by @noahgibbs in https://github.com/Shopify/yjit-bench/pull/32#issuecomment-892590349

[strscan gem](https://github.com/ruby/strscan)

**Comment by eregon** [comment]
It's surprising that the strscan.so is even used in that case, maybe it was a bug of 21.1.0.
I don't see any `require "strscan.so"` from a quick look.

Anyway we should probably make a PR to the strscan gem so it just does nothing on TruffleRuby since the strscan stdlib is a lot faster (no need to move every String to native or emulate the Onigmo C API) and with much less indirections.

**Comment by noahgibbs** [comment]
Makes sense. It's a dependency of one of the (removed in 3.1) net-* gems, so you're likely to see this more frequently going forward. When 3.1 is released properly, there's going to be a lot more code that just installs those gems unconditionally, as our yjit-bench version of Railsbench had been doing.

There are definitely a lot of weird issues with having duplicates of the default CRuby built-in gems that then depend on other external-but-duplicate-a-builtin gems. Bundler's not dealing well with them either.

**Comment by eregon** [comment]
https://github.com/ruby/strscan/pull/35 will fix this.

**Comment by eregon** [comment]
Fixed by https://github.com/ruby/strscan/pull/35
