### ISSUE TITLE
"%2s" does not add left-padding when given a unicode character

### ISSUE THREAD

**Issue by postmodern** [oracle/truffleruby#2426]
It appears that when formatting a unicode characters within a `%2s` format string, the raw byte length of the unicode String is used instead of the character length.

### Expected Behavior

```ruby
("%2s" % "☃").length
# => 2
```

### Actual Behavior

```ruby
("%2s" % "☃").length
# => 1
```

### Version Info

```
$ truffleruby -v
truffleruby 21.2.0.1, like ruby 2.7.3, GraalVM CE Native [x86_64-linux]
```

**Comment by eregon** [comment]
@aardvark179 Could you take a look at this one (can be after the rb_sprintf changes)?

**Comment by aardvark179** [comment]
This was actually fixed as part of the `rb_sprintf` work I believe. It certainly appears to be producing the correct results now.
