### ISSUE TITLE
Upgrade Bundler to 2.2.23+

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#2434]
Bundler 2.2.x now records the source of each gem that was installed, plugging a security issue for Gemfiles with multiple sources. It's hard to point at a single release that includes the functionality as there were several issues detected that were fixed in subsequent point releases. MRI 3.0.2 ships with Bundler 2.2.22, which includes many of the aforementioned fixes. TruffleRuby still currently ships with Bundler 2.1.4, matching what MRI 2.7.4 uses, but that version that is susceptible to gems installing from the wrong source.

I think it would be best if we shipped with the most secure version of Bundler that we can. Moreover, by shipping with an old version and knowing that end users are encouraged to upgrade, we're making them jump through an extra hoop. If we do upgrade, I think it'd make sense to break with MRI a bit and install at least 2.2.23, as that version includes a fix for [an issue on TruffleRuby](https://github.com/rubygems/rubygems/pull/4625).

Full Ruby 3 support is still a little ways off, so I'm asking we consider an upgrade in advance of a full Ruby 3 compatible release. Upgrading Bundler may require an upgrade to RubyGems as well (I haven't attempted a local upgrade yet to tell).

**Comment by eregon** [comment]
I think pragmatically it would be easier to do this when doing the update to Ruby 3, to minimize risks and surprises.
Indeed, we'll need 2.2.23, or to backport that fix individually (but that would probably be confusing as it would still report as 2.2.22).

21.3 will be released on Oct 19, and feature freeze will be earlier than that. After the feature freeze I think we can start work to migrate to Ruby 3 (for the 22.0 release).

**Comment by eregon** [comment]
We updated to Ruby 3 and currently ship Bundler 2.2.22 like CRuby 3.0.2.

That has the issue with `sorbet-static` (https://github.com/rubygems/rubygems/issues/4588).
So either we patch Bundler to include [that one-line fix](https://github.com/rubygems/rubygems/pull/4625/files#diff-3ada38090bec028614dcf46678cd1dbf7ef8918a69f00b2f0a1c18ebe0b48fc3R198) or we ship a newer Bundler.

Newer Bundler might have additional bugs or incompatibilities with the default Bundler of CRuby 3.0.2, so I think it's safest to just apply the patch in this case.

**Comment by eregon** [comment]
Fixed in 8fa22dca3336e970bacf116861515ab41fd22027 by adding a patch which includes the fix for `sorbet-static` and similar.

If you need a minimum Bundler version I would advise to have some dynamic check e.g. in the Gemfile or application that the minimum version is met.
