### ISSUE TITLE
conditional operations sometimes failing with multithreading

### ISSUE THREAD

**Issue by HoneyryderChuck** [oracle/truffleruby#2437]
Here's another wickedly hard to reproduce bug from `httpx` :)

A [recent MR](https://gitlab.com/honeyryderchuck/httpx/-/merge_requests/162) caused the truffleruby build to start failing "consistently" (always the "expect-100" plugin tests) but "randomly" (never the same test failing).

I've started a "truffleruby-bug" branch to reproduce it, and added [this commit](https://gitlab.com/honeyryderchuck/httpx/-/commit/9f3db913c53137e39fb4ec44c9c5c8bf0b49a950) to enable debugging output only for that subset of tests, and provide extra information on what's happening.

The issue seems to come from [this line](https://gitlab.com/honeyryderchuck/httpx/-/commit/9f3db913c53137e39fb4ec44c9c5c8bf0b49a950#4937659c2f42a445b835e4904826aa3c9bcd8a90_100_104), where the extra check was added in the MR mentioned above. Somehow, although the debug statement immediately above shows that both conditionals evaluate to "true", it never enters the if body, thereby not enabling the `@informational_status` flag.

You can have [this CI log](https://gitlab.com/honeyryderchuck/httpx/-/jobs/1556316453) as example of what I'm talking about, namely this bit:

```
(374584-375928) <- HEADLINE: "POST /post HTTP/1.1"
<- HEADER: User-Agent: httpx.rb/0.17.0
<- HEADER: Accept: */*
<- HEADER: Content-Type: application/octet-stream
<- HEADER: Content-Length: 5
<- HEADER: Expect: 100-continue
<- HEADER: Connection: close
<- HEADER: Host: nghttp2
(375928) <- 
WRITE: 180 bytes...
READ: 25 bytes...
(375928) -> HEADLINE: 100 HTTP/1.1
(374584-375928) here: true, true
# it should print: 375928-375928) it's info: 100
# but it didn't
# although both conditionals evaluated to true, as per https://gitlab.com/honeyryderchuck/httpx/-/commit/9f3db913c53137e39fb4ec44c9c5c8bf0b49a950#4937659c2f42a445b835e4904826aa3c9bcd8a90_100_102
(374584-375928): here 2: 100-continue, , false
```

I suspect `truffleruby` has issues in the `is_a?` implementation when performed on dynamic classes (`Class.new(HTTPX::Response){...}.new(...)`), and somehow that only manifests itself under multithreading, however this is pretty much a wild guess at this point.

**Comment by eregon** [comment]
Thank you for the report!
Maybe it is some race in some part of the Ruby code, or it could indeed be a TruffleRuby bug.
We will try to reproduce.

Which command line did you use to reproduce that failure, and which TruffleRuby version (`ruby -v`)?

**Comment by HoneyryderChuck** [comment]
Hi @eregon ,

The failure can be reproduced by [following the same instructions](https://github.com/oracle/truffleruby/issues/2210#issuecomment-755364941) from a previous issue report, the main differences being:

* you must do it in the `truffleruby-bug` branch;
* You ran the tests like this: `PARALLEL=1 bundle exec ruby -Itest test/http_test.rb`

I can only reliably reproduce this using minitest's parallel runner, and under a sufficently high test load (which should be covered by running `http_test.rb`.

> which TruffleRuby version (ruby -v)?
