### ISSUE TITLE
rdoc : SOURCE_DATE_EPOCH is empty

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2443]
Noticed that this env variable is not set for Truffleruby

`clone`, `bundle install` rdoc gem and then
epoch.rb:
```
puts ENV['SOURCE_DATE_EPOCH']
```
MRI Ruby 2.7.1
```
> rdoc % bundle exec ruby epoch.rb 
1631827957
```
Truffleruby head:
```
> rdoc % export PATH=~/.rubies/truffleruby-dev/bin:$PATH
> rdoc % bundle exec ruby epoch.rb                      

```

**Comment by bjfish** [comment]
@gogainda I was unable to recreate this yet. Could you report the TruffleRuby version `ruby -v`, bundler version `bundler --version` and rdoc project commit `git log -n` so I could try to reproduce this again?

**Comment by gogainda** [comment]
sure, here you go:
```
bundler --version
Bundler version 2.1.4

commit 7c0f81d741be34d597830057e462135d3844cb7f

ruby -v 
truffleruby 21.3.0-dev-a52bd0fc, like ruby 2.7.4, GraalVM CE Native [x86_64-darwin]
```
```

**Comment by eregon** [comment]
It looks like RubyGems sets that variable, but probably only some versions of RubyGems: https://github.com/rubygems/rubygems/issues/3081
Do you need that env var for anything or does it cause any failure?

**Comment by gogainda** [comment]
Nothing in particular, just noticed the difference

**Comment by gogainda** [comment]
@bjfish it is `"3.1.6"`

**Comment by eregon** [comment]
It's not set on CRuby 3.0.2 either, let's close this as it doesn't seem to cause any incompatibility in practice, and rather seems a side effect of using a specific non-default RubyGems version.
