### ISSUE TITLE
defined?(yield) should behave like block_given?

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2446]
Noticed by @jeremyevans in https://github.com/jeremyevans/roda/runs/3668526326?check_suite_focus=true

**Comment by bjfish** [comment]
Here is a minimal case to reproduce:
```
def y
  yield
end

def test
  y { p defined?(yield) }
end

test() { }
```

**Comment by eregon** [comment]
Fixed by https://github.com/oracle/truffleruby/commit/7e369102a2880c8ae9c49aea0cf021fae5190301, cc @jeremyevans
