### ISSUE TITLE
File.utime strips nanoseconds from mtime

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2448]
touch orig.rb
touch dest.rb

```
require 'pathname'
require 'fileutils'

puts "orig mtime", Pathname("./orig.rb").mtime.inspect
st = File.stat("orig.rb")
dest = File.path("dest.rb")
File.utime st.atime, st.mtime, dest
puts "copied mtime", Pathname("./dest.rb").mtime.inspect
```

**Comment by eregon** [comment]
Related to https://github.com/oracle/truffleruby/issues/2337.
I guess the issue here is `utime` not preserving the nanoseconds.

**Comment by bjfish** [comment]
This is now fixed at https://github.com/oracle/truffleruby/commit/605d5b84cf222e6592050c410f6e47895f07b1da.
