### ISSUE TITLE
The result of defined?(code) should be frozen

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2450]
`defined?` returns `nil` or a String, I consider only when it returns a String here.
It seems on CRuby since a very long time/the start the returned String is frozen:
```
$ ruby -ve 'p defined?(String).frozen?'
ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-linux]
true
```
On TruffleRuby it's not currently:
```
ruby -ve 'p defined?(String).frozen?'
truffleruby 21.3.0-dev-fd0f34e7, like ruby 2.7.3, GraalVM CE Native [x86_64-linux]
false
```

We should add specs for this and change the behavior (e.g., return a cached ImmutableRubyString from the CoreString, or maybe not use CoreString for `defined?` altogether and replace it with FrozenStrings, a new class with final ImmutableRubyString fields).
That will then avoid allocations in the interpreter and potentially some allocations in the compiled code too.

@bjfish Could you take care of it?

**Comment by bjfish** [comment]
This is fixed at https://github.com/oracle/truffleruby/commit/fdbe239a2f753eabfda89e8f389638066560d822
