### ISSUE TITLE
Array#pack('h') discrepancy

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2503]
Given `[0].pack('h')`, Ruby and JRuby raise an error:

`<internal:pack>:134:in 'pack': no implicit conversion of Integer into String (TypeError)`

While TruffleRuby 21.2.0 returns "\x00"

**Comment by aardvark179** [comment]
Sorry for the slow reply on his. It looks like a very easy fix, but we also seem to be lacking a lot of tests for `Array#pack` error case, so I think should add those while we're at it.

**Comment by aardvark179** [comment]
Fixed in commit `39d740bd3eb8abafe737656055850fc7b3a4d1dc`.
