### ISSUE TITLE
Incorrect exception message for exceptions that inherit from Errno exceptions

### ISSUE THREAD

**Issue by postmodern** [oracle/truffleruby#2521]
I noticed that TruffleRuby deviates from CRuby when an exception inherits from an Errno exception. The inherited Errno message (ex: `No such file or directory`) becomes lost.

## Example

```ruby
class CustomError < Errno::ENOENT
end

raise(CustomError,"custom message")
```

### CRuby (3.0.2)

```
(irb):4:in `<main>': No such file or directory - custom message (CustomError)
```

### TruffleRuby (21.3.0)

```
(irb):4:in `<top (required)>': unknown error - custom message (CustomError)
```

**Comment by eregon** [comment]
Thanks for the report.

@bjfish Could you look into this?
I think this condition is problematic: `if error && error.class.equal?(self)` and I guess we need to pass the `self` (the exception class) to `SystemCallError.errno_error`. The other usage of `SystemCallError.errno_error` doesn't know the correct class so we should probably split the logic to map errno->class to a separate Primitive.

**Comment by eregon** [comment]
Actually it might already work by changing `error.class.equal?(self)` to something like `Primitive.object_kind_of?(error, self)` since there is a `super(*args)` call which might deal fine with such cases.

**Comment by bjfish** [comment]
This is now fixed at https://github.com/oracle/truffleruby/commit/5776ef65c7fa5c2edbddc6c49593de3f507c8637.
