### ISSUE TITLE
Kernel#print doesn't print $_ when no arguments are given

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2531]
```
seq 100 | ruby -ne 'print'
```
per manual it should work as -p but currently it doesn't work

**Comment by eregon** [comment]
It works with `seq 100 | ruby -ne 'print $_'`.
So it seems `print` with no args prints `$_` in CRuby?

Ruby without `-n` has the same behavior:
```
$ ruby -e '$_ = "abc"; print'
abc
```

Note that `$_` is nil by default and `print nil` prints nothing, so I guess it doesn't matter whether `$_` is set or not, if `print` has no arguments, then pretend the argument was `$_`.

**Comment by bjfish** [comment]
@gogainda This is now fixed at https://github.com/oracle/truffleruby/commit/82c9521e06f758a9f1064ddacde71f83727d4cca.
