### ISSUE TITLE
GC.stat({}) doesn't work

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2535]
From https://github.com/Shopify/gctime/pull/1#issuecomment-974125795, found by @casperisfine
@bjfish Can you fix it?

**Comment by eregon** [comment]
Let's also implement `GC.total_time` and `GC.measure_total_time/=` (does nothing) while we're at it, so https://github.com/Shopify/gctime needs to do nothing then.

**Comment by casperisfine** [comment]
❤️

**Comment by eregon** [comment]
@bjfish Spec added in https://github.com/ruby/spec/pull/900 :)
(you can just copy the file for the truffleruby PR and it'll just noop when upstreaming)

**Comment by bjfish** [comment]
These issues are now fixed at https://github.com/oracle/truffleruby/commit/91546e7a81599a9d7d1c50248f10cbbb10e8290e.
