### ISSUE TITLE
Remove Hash#index and make Hash#__store__ private

### ISSUE THREAD

**Issue by jeremyevans** [oracle/truffleruby#2546]
Looks like `Hash#__store__` and `Hash#index` are public in TruffleRuby.  CRuby dropped `Hash#index` in 3.0, so I assume TruffleRuby should do the same now that you target CRuby 3.0.  I'm guessing it's a bug that `Hash#__store__` was ever public?  I noticed this due to a CI failure: https://github.com/jeremyevans/ruby-cicphash/runs/4487049153?check_suite_focus=true#step:4:15.

**Comment by bjfish** [comment]
@jeremyevans Yes, this is a bug. I'll look into removing these methods.

**Comment by bjfish** [comment]
@jeremyevans This is now fixed at https://github.com/oracle/truffleruby/commit/4b4c2521cb206bca1bff0c3ea2b57263043c8a11. Thanks!
