### ISSUE TITLE
[Minor problem] Slightly peculiar message when re-compiling openssl

### ISSUE THREAD

**Issue by rubyFeedback** [oracle/truffleruby#2554]
So I am installing graalvm right now. Well actually truffleruby, but from the context of graalvm so I had
to install the latter first.

truffleruby shows this:

"IMPORTANT NOTE:
---------------
The Ruby openssl C extension needs to be recompiled on your system to work with the installed libssl.
First, make sure TruffleRuby's dependencies are installed, which are described at:
  https://github.com/oracle/truffleruby/blob/master/README.md#dependencies
Then run the following command:
        /home/Programs/Graalvm/21.3.0/languages/ruby/lib/truffle/post_install_hook.sh

"

Ok, so I understand I have to compile openssl.

I run the command and things seem to work:

[...]

"compiling ossl_x509revoked.c
compiling ossl_x509store.c
linking shared-object openssl.so
TruffleRuby was successfully installed in /home/Programs/Graalvm/21.3.0/languages/ruby"

The thing that confuses me is the last sentence:

"TruffleRuby was successfully installed in /home/Programs/Graalvm/21.3.0/languages/ruby"

I believe, technically, that sentence is not correct, because it would imply that the PRIOR
installation of truffleruby would not work. But I think it works. What I did above was merely
get graalvm to compile the openssl bindings, yes? So I think the sentence should indicate
this, perhaps via "Openssl bindings were successfully installed", rather than the
"TruffleRuby was successfully installed". I am not sure if I am able to explain my confusion,
but I was using the above command to compile openssl, so I am not sure why I then get
the message "TruffleRuby was successfully installed" - that would mean that it was not
installed PRIOR to that which seems... incorrect. So the sentence should be re-worded
a bit. Is a tiny issue but tiny issues are easy to change, so ... :)

**Comment by eregon** [comment]
> I believe, technically, that sentence is not correct, because it would imply that the PRIOR installation of truffleruby would not work.

TruffleRuby typically does not work properly before that step, e.g., `gem/bundle ...` will fail.

I get your point, but I think "Openssl bindings were successfully installed" is even more confusing, and I have no idea how to make it clearer.

What I intend by this sentence is to mean "now you completed the installation of truffleruby and everything is ready" (before it indeed was not).

BTW, I would recommend to install via `ruby-build`, you can install either truffleruby either standalone or the full graalvm, and it runs that script automatically for you: https://github.com/oracle/truffleruby/blob/master/README.md#getting-started
