### ISSUE TITLE
`rb_io_wait` is declared but not implemented

### ISSUE THREAD

**Issue by larskanis** [oracle/truffleruby#2564]
Truffleruby on the master branch declares [`rb_io_wait`](https://github.com/oracle/truffleruby/blob/0345f913981d115434f84b3efb3b4ccc6da10e2c/lib/cext/include/ruby/io.h#L166) but doesn't implement it. It also defines [`RUBY_IO_READABLE`](https://github.com/oracle/truffleruby/blob/0345f913981d115434f84b3efb3b4ccc6da10e2c/lib/cext/include/ruby/io.h#L45) without using it.

This issue leads to a build error in ruby-pg [here](https://github.com/ged/ruby-pg/runs/4752866844?check_suite_focus=true#step:10:131). The `extconf.rb` tests for `rb_io_wait` and doesn't detect it, so that it enables a polyfill instead. This polyfill usually works on truffleruby, but conflicts on the definition of the function and the enum.

Truffleruby-head is currently [disabled in ruby-pg](https://github.com/ged/ruby-pg/commit/3519d2ab0f5a5780d54b8cf0cfd05c9c6c6f11e1), but the latest truffleruby release [runs successfully](https://github.com/ged/ruby-pg/runs/4752866832?check_suite_focus=true).

**Comment by eregon** [comment]
@aardvark179 is working on implementing `rb_io_wait`.

The current conflict is unfortunate but expected: we import headers from CRuby, changed as little as possible to keep it maintainable.
`have_func` correctly detects it's not implemented, so the only issue here is those conflicts.

**Comment by larskanis** [comment]
OK, so the next release will implement `rb_io_wait` and the current inconsistent state is just temporary.

The polyfill in ruby-pg is [here](https://github.com/ged/ruby-pg/blob/master/ext/pg_connection.c#L2211-L2235), just in case it's interesting. But sure, a complete implementation needs proper integration into `Fiber.scheduler`, far beyond the simple polyfill.

**Comment by eregon** [comment]
Maybe a simple workaround here is to do some renames/prefix for the polyfill?
I think that would be the fastest to solve this specific issue.

(We're also working on the Fiber scheduler, not merged yet)

**Comment by larskanis** [comment]
`rb_io_wait` has been implemented in commit https://github.com/oracle/truffleruby/commit/58aea0198762de15659cd1680fbe03c6fb829aec
