### ISSUE TITLE
Difference in String#split behavior

### ISSUE THREAD

**Issue by dazuma** [oracle/truffleruby#2565]
`String#split` behaves differently from MRI in certain cases.

```ruby
" ".split(" ")  # or equivalently, " ".split
```

In TruffleRuby 21.3.0, this yields `[" "]`.
In MRI (both 2.7.5 and 3.1.0 tested), this yields `[]`.

**Comment by eregon** [comment]
Indeed, thanks for the report.
@bjfish Could you fix it?

**Comment by bjfish** [comment]
@dazuma This is now fixed at https://github.com/oracle/truffleruby/commit/6dd971c7ef070259ee7a414ad59a6597be0ed8aa. Thanks!
