### ISSUE TITLE
Rescue through Set of errors not working

### ISSUE THREAD

**Issue by brauliobo** [oracle/truffleruby#2572]
The following code:
```ruby
RETRIABLE_ERRORS = Set.new([
  ::Mechanize::ResponseCodeError,
  ::Mechanize::ResponseReadError,
])

def call method, url, *args
  mechanize.send method, url, *args                                                                                                                                                                        
rescue *RETRIABLE_ERRORS => e
end
```

Returns the error `TypeError: class or module required for rescue clause` on truffleruby but works on MRI

**Comment by eregon** [comment]
Thanks for the report, simpler repro with no dependencies:
```ruby
require 'set'

RETRIABLE_ERRORS = Set.new([
  RuntimeError,
  ArgumentError,
])

def call
  raise "oops"
rescue *RETRIABLE_ERRORS => e
  p e
end

call
```

It works fine if an Array is used instead of the `Set`.
A `Set` of exceptions like here seems rather inefficient since it will cause to iterate the set on every exception.

**Comment by brauliobo** [comment]
thanks eregon, I'll switch to array

**Comment by eregon** [comment]
I have a fix coming BTW, it's literally changing a `true` to `false` to use `to_a` instead of `to_ary` for coercion.
