### ISSUE TITLE
Some files have invalid filenames on Windows

### ISSUE THREAD

**Issue by Speak2Erase** [oracle/truffleruby#2590]
Hi! I would like to integrate truffleruby in one of my projects that makes heavy use of the Ruby C API, and truffleruby is the only distribution out there besides MRI that has support for it. (And good support too.)

I'm still not sure if it will work, since it's set up to embed ruby rather than act as a C extension.

Unfortunately because of the way I have my project set up as well to make a Windows build I also need to build truffleruby on Windows, and I can't do that because some of the files have invalid characters in them (: namely), so cloning the repository or untarring a release will either crash or replace the invalid characters, which causes even more problems.

What should I do about this? Is windows just not supported at all? 
Or do I have to use a subsystem like msys2 or wsl?

**Comment by Speak2Erase** [comment]
Well, I just noticed windows isn't listed in system compatibility, darn that's kind of disappointing.
That's entirely my fault for not noticing though.

Are there any plans to support windows?

**Comment by Speak2Erase** [comment]
Huh, I'm confused now. You can get GraalVM on windows which let's you get truffleruby.

**Comment by eregon** [comment]
> Is windows just not supported at all?

Windows is not supported for TruffleRuby and there is currently no plan for it (huge effort and many easy workarounds, including WSL).

Not all GraalVM components support Windows: https://www.graalvm.org/22.0/docs/introduction/#features-support

Regarding the files with `:` in it, it's just a few:
```
$ git ls-files | grep ':'
spec/truffle/methods/Digest::Base.singleton_class.txt
spec/truffle/methods/Digest::Base.txt
spec/truffle/methods/Digest::Class.singleton_class.txt
spec/truffle/methods/Digest::Class.txt
spec/truffle/methods/Digest::Instance.singleton_class.txt
spec/truffle/methods/Digest::Instance.txt
spec/truffle/methods/Digest::MD5.singleton_class.txt
spec/truffle/methods/Digest::MD5.txt
spec/truffle/methods/Digest::SHA1.singleton_class.txt
spec/truffle/methods/Digest::SHA1.txt
spec/truffle/methods/Enumerator::Lazy.txt
spec/truffle/methods/Random::Formatter.txt
spec/truffle/methods/Socket::AncillaryData.txt
spec/truffle/methods/Socket::Constants.txt
spec/truffle/methods/Socket::Ifaddr.txt
spec/truffle/methods/Socket::Option.txt
spec/truffle/methods/Socket::UDPSource.txt
```
That could be changed in https://github.com/oracle/truffleruby/blob/master/spec/truffle/methods_spec.rb (e.g., replacing `::` by `_`).

**Comment by chrisseaton** [comment]
@Speak2Erase TruffleRuby is currently built on POSIX APIs that Windows doesn't support - that's the issue.

**Comment by eregon** [comment]
That's hardly the only issue for Windows support, there are a lot of complications for supporting C extensions on Windows and other things (not LP64, etc). Truffle POSIX is being worked on and that will eventually address the NFI calls to POSIX functions we currently use, but that's not enough for Windows support.

**Comment by Speak2Erase** [comment]
Darn. Yeah, I understand. Multi platform sucks to support. I wouldn't necessarily agree that WSL is an easy workaround, since I've had issues with it indefinitely hanging on build.
Plus, it's not a native binary, so it doesn't make it as easy for the end user to use, and wsl isn't supported or easy to get working on all systems. I had to fiddle with it quite a bit to get it to work for me.
I think I am going to push ahead testing out Linux integration and see if it is possible first. If further down the line this project ever gets windows support I will come back to this then.
Please do let me know if it is ever worked on or considered in the future. Thanks!
