### ISSUE TITLE
TruffleRuby doesn't print warnings for ininitialized  variables

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2595]
test.rb:
```
def undef
  puts "undef", $undefined
end
send(:undef)
```
Run: `ruby -w test.rb`

Expected output:
```
warning: global variable `$undefined' not initialized
```

**Comment by eregon** [comment]
Does it cause any compatibility issue in practice?
This is probably not worth the implementation effort otherwise.

**Comment by eregon** [comment]
Actually we already track if they are defined/have been assigned, so it seems easier than I thought.

**Comment by eregon** [comment]
It seems used in RSpec tests

**Comment by andrykonchin** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/9b535010fc8983217b3cb4fb9aa8bb75d22caa49, thank you for the report.
