### ISSUE TITLE
Add `asdf-ruby` to README

### ISSUE THREAD

**Issue by pboling** [oracle/truffleruby#2600]
`asdf` seems to be coalescing as the [one version manager to rule them all](https://asdf-vm.com/), and the `asdf-ruby` project is gaining a lot of traction.  I have had some trouble getting truffleruby (and only truffleruby) working with it though.

Would like to see asdf-ruby install instructions added to the readme.  Ideally it would work in all cases where ruby-build works, since it literally just runs ruby-build, but [reality doesn't seem to match my expectations](https://github.com/oracle/truffleruby/issues/1389#issuecomment-1042320212) there.

ref: https://github.com/asdf-vm/asdf-ruby

**Comment by eregon** [comment]
Upstream issue: https://github.com/asdf-vm/asdf-ruby/issues/247

**Comment by eregon** [comment]
Done in https://github.com/oracle/truffleruby/commit/c95144afe737f2072efc40966e4f4daee8e1cf8e.
Would be helpful if you can test that it works as documented, as I don't have asdf and I don't plan to setup a Docker image just to test it.
Any tweaks to the docs is also welcome of course e.g. if some part is unclear.
