### ISSUE TITLE
contracts.ruby gem test failure: wrong number of arguments

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2602]
Example 
```
113) Contracts: method called with blocks should enforce return value inside block with no other parameter
       Failure/Error: expect { obj.foo(&:to_s) }.to raise_error ReturnContractError

         expected ReturnContractError, got #<ArgumentError: wrong number of arguments (given 1, expected 0)> with backtrace:
           # ./spec/methods_spec.rb:8:in `foo'
           # ./lib/contracts/method_reference.rb:47:in `send_to'
           # ./lib/contracts/call_with.rb:98:in `call_with_inner'
           # ./lib/contracts/method_handler.rb:140:in `block (2 levels) in redefine_method'
           # ./lib/contracts/method_handler.rb:136:in `each'
           # ./lib/contracts/method_handler.rb:136:in `foo'
           # ./spec/methods_spec.rb:39:in `block (4 levels) in <top (required)>'
           # ./spec/methods_spec.rb:39:in `block (3 levels) in <top (required)>'
       # ./spec/methods_spec.rb:39:in `block (3 levels) in <top (required)>'
```
was trying to track down the root cause but didn't find a way to debug such issues. 

https://github.com/egonSchiele/contracts.ruby

**Comment by eregon** [comment]
It's seems kwargs-related, the 2nd caller is:
https://github.com/egonSchiele/contracts.ruby/blob/36b055b80544a58464f83602e5b98d38c0084d28/lib/contracts/method_reference.rb#L44-L46

Which is correct for Ruby 3+ kwargs but broken for Ruby 2 kwargs, and TruffleRuby currently still has Ruby 2 kwargs.

Given the gem [requires Ruby 3+](https://github.com/egonSchiele/contracts.ruby/blob/master/contracts.gemspec#L15), it's not an issue upstream but just an issue of TruffleRuby, which will be solved when we implemented Ruby 3 kwargs semantics.

**Comment by bjfish** [comment]
These spec failures now pass after the kwargs implementation was merged: https://github.com/oracle/truffleruby/commit/b8086afe6ecc64a78e1f80f42d4ae9c05cf56605.
