### ISSUE TITLE
String#split(false) should raise error

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2606]
MRI 3.0.2:

`"hello".split(false) # => wrong argument type false (expected Regexp) (TypeError)`

TruffleRuby 22.0.0.2:

`"hello".split(false) # => ["hello"]`

**Comment by bjfish** [comment]
This is now fixed at 
https://github.com/oracle/truffleruby/commit/62f0cc4093c8e99f39ffe675859aa9b8cece586b.
