### ISSUE TITLE
String#lstrip should strip leading nulls

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2607]
MRI 3.0.2:

`"\u0000\u0000\u0000hello".lstrip # => "hello"`

TruffleRuby 22.0.0.2:

`"\u0000\u0000\u0000hello".lstrip # => "\u0000\u0000\u0000hello"`

**Comment by bjfish** [comment]
This is now fixed at https://github.com/oracle/truffleruby/commit/2dd02626b98bd3a0fdd330d55b0bef77d4b3931d.
