### ISSUE TITLE
String#rindex should raise error on invalid type

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2608]
Ruby 3.0.2:

`"hello".rindex(1) # => no implicit conversion of Integer into String (TypeError)`

TruffleRuby 20.0.0.2:

`"hello".rindex(1) # => nil`

**Comment by bjfish** [comment]
This is now fixed at https://github.com/oracle/truffleruby/commit/f4ab861fe96d2d8a47b08c29970c95512c4ab5a7.
