### ISSUE TITLE
String#<< should require an argument

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2609]
Ruby 3.0.2:

`"hello".send(:<<) # => wrong number of arguments (given 0, expected 1) (ArgumentError)`

TruffleRuby 20.0.0.2:

`"hello".send(:<<) # => "hello"`

**Comment by eregon** [comment]
Thank you for the report, I'm curious, how did you find this out?

**Comment by eregon** [comment]
Ah yes, I thought it might be that, but I couldn't find it anymore, found it now: https://github.com/djberg96/berger_spec

Ideally it'd be great to integrate that test suite in ruby/spec or in CRuby tests one day for the extra behaviors which are not already tested, but I guess that's a significant amount of work so probably unrealistic.
We'll add specs to ruby/spec for the issues you reported, so at least those will be covered.
Thanks for the testing and reports.

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/6d7998f372785479f5478cd14e4e6ea0fa6cb079.
