### ISSUE TITLE
Compatibility with Rails 7

### ISSUE THREAD

**Issue by wxw-matt** [oracle/truffleruby#2610]
## How to reproduce
Using Docker image:
```bash
docker run --rm -it ghcr.io/flavorjones/truffleruby:nightly-slim bash
# In the shell inside the container:
apt-get update
apt-get install xz-utils git libpq-dev libsqlite3-dev -y
gem install nokogiri --platform=ruby
gem install rails
rails new blog 
rails g scaffold comment2 title:string content:string
```
You will get the error:
```
      invoke  active_record
      create    db/migrate/20220302010737_create_comment2s.rb
      create    app/models/comment2.rb
      invoke    test_unit
      create      test/models/comment2_test.rb
      create      test/fixtures/comment2s.yml
      invoke  resource_route
       route    resources :comment2s
      invoke  scaffold_controller
/usr/local/bundle/gems/jbuilder-2.11.5/lib/generators/rails/templates/controller.rb:11:in `block (3 levels) in <unused>': undefined method `all' for ActiveModel:Module (NoMethodError)
```

**Comment by eregon** [comment]
Thanks for the report, Rails 5 & 6 work (tested [here](https://github.com/oracle/truffleruby/tree/master/test/truffle/ecosystem)), but we didn't test Rails 7 yet.

`gem install nokogiri --platform=ruby` should be unnecessary (it'll be installed by `bundler` later on if needed), why is that done?

@bjfish Could you investigate?
I would try to repro outside Docker for convenience.

**Comment by bjfish** [comment]
I think this is a smaller reproduction case:
```
module ActiveRecord
end
module Generators
end
module ActiveModel
end

p Object.const_get("ActiveRecord::Generators::ActiveModel")
```
Actual
```
ActiveModel
```
Expected
```
in `const_get': uninitialized constant ActiveRecord::Generators (NameError)
```

**Comment by bjfish** [comment]
@wxw-matt This issue is now fixed at https://github.com/oracle/truffleruby/commit/1c888c9e77def6dd7bc40488590a2a6e813a87de. Thanks.

**Comment by wxw-matt** [comment]
@bjfish Thank you all very much. Just wondering if the patch is available in the nightly built Docker image?
Will have a tutorial about Truffleruby and latest Rails 7.

**Comment by eregon** [comment]
@wxw-matt As long as the build at https://github.com/flavorjones/truffleruby/pkgs/container/truffleruby is after 1c888c9e77def6dd7bc40488590a2a6e813a87de it should be fine (not the case yet, needs ~4 hours more).

**Comment by wxw-matt** [comment]
Thanks @eregon. Yeah, the current image does not have this patch. Waiting for the latest Docker image built with this fix.
