### ISSUE TITLE
Hash constructor with true/false keys causes FrozenError with to_s

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2613]
Ruby 3.0.2:

`Hash[true, 1].to_s # => "{true=>1}"`
`Hash[false, 1].to_s # => "{false=>1}"`

TruffleRuby 22.0.0.2:

`Hash[true, 1].to_s #=> FrozenError`
`Hash[false, 1].to_s #=> FrozenError`

**Comment by eregon** [comment]
Thanks for the report, seems a trivial fix.

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/cde4cfae0883e5225ba80993ac668eb5cb386cd7
