### ISSUE TITLE
File.utime returning wrong value

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2616]
Assuming you've done `touch temp.txt` locally...

Ruby 3.0.2:

`File.utime(0, 0, "temp.txt") # => 1`

Truffleruby 22.0.0.2:

`File.utime(0, 0, "temp.txt") # => ["temp.txt"]`

Docs say it should return the number of filenames in the argument list.

**Comment by bjfish** [comment]
This is fixed at https://github.com/oracle/truffleruby/commit/8947d2bc4f33a920c12363733dcb30e5aaffb92c.
