### ISSUE TITLE
Math.sqrt(-1) should raise error

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2621]
Ruby 3.0.2:

`Math.sqrt(-1) # => Math::DomainError`

TruffleRuby 22.0.0.2

`Math.sqrt(-1) # => NaN`

Not really "wrong" so much as a philosophical difference I think, but that's how MRI behaves.

**Comment by bjfish** [comment]
This is fixed at https://github.com/oracle/truffleruby/commit/a5b5504487844d0ca51fcf15fb23495f954a2e91.
