### ISSUE TITLE
Crash on CI by `bundle install`

### ISSUE THREAD

**Issue by okuramasafumi** [oracle/truffleruby#2646]
I saw my CI failing only with TruffleRuby, it seems it crashes when it executes `bundle install`.
https://github.com/okuramasafumi/alba/runs/6169615428?check_suite_focus=true
This is the first time I see this kind of crash of TruffleRuby. It uses `truffleruby-22.0.0.2` so there might be a bug only in this version?

**Comment by eregon** [comment]
This is a segfault reported by SubstrateVM/Native Image.
It's hard to tell from that the actual issue.
I guess it's transient and rarely occurring? Or did it happen multiple times?

It could also be an issue of sharing native-compiled code due to the bundler cache, but that seems unlikely.

**Comment by okuramasafumi** [comment]
Oh, after re-running it passes. Thank you for pointing out!

**Comment by eregon** [comment]
I copied the output in https://gist.github.com/eregon/20b715929396b9a499a2777afeb51da0 since GitHub Actions logs disappear after some time.
