### ISSUE TITLE
Module#class_variables should accept an inherit argument

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2653]
The `Module.class_variables` method should accept an optional `inherit` argument.

Trying this in Truffleruby 22.1.0 results in `'class_variables': wrong number of arguments (given 1, expected 0) (ArgumentError)`

**Comment by bjfish** [comment]
This is fixed at https://github.com/oracle/truffleruby/commit/9d4c2bcb18363e54a7d3ab39219c2be16eca7b9f.
