### ISSUE TITLE
RBS gen doesn't work with Truffleruby

### ISSUE THREAD

**Issue by MrWormHole** [oracle/truffleruby#2691]
**Ruby Version**
truffleruby 22.3.0-dev-3dfcaa03, like ruby 3.0.3, GraalVM CE Native [x86_64-linux]

**RBS gem version**
2.6.0

Error message I am getting when I run the command
```ruby
class Dog
  def bark
    "woof,woof"
  end
end
```

```sh
rbs prototype rb dog.rb
Not supported on this interpreter (truffleruby).
```

**Notes**
It works on other ruby versions

**Comment by eregon** [comment]
As it says, `rbs prototype` doesn't support anything but CRuby, because it depends on RubyVM, an unstable experimetal CRuby-specific API: https://github.com/ruby/rbs/issues/348
The rest of `rbs` should work.
