### ISSUE TITLE
Installing the latest bundler causes google-protobuf to be installed as a different platform and failed to be resolved at runtime

### ISSUE THREAD

**Issue by ntkme** [oracle/truffleruby#2695]
Log from GitHub Actions that with truffleruby-head it is using bundled bundler from truffleruby and everything was fine:

```
  /Users/runner/.rubies/truffleruby-head/bin/ruby --version
  truffleruby 22.2.0-dev-07df635e, like ruby 3.0.3, GraalVM CE Native [x86_64-darwin]

  Using Bundler 2 shipped with truffleruby-head (head versions do not always support the latest Bundler release)

  /home/runner/.rubies/truffleruby-head/bin/bundle install --jobs 4
......
  Fetching google-protobuf 3.21.3
  Installing google-protobuf 3.21.3 with native extensions
```

When using truffleruby stable release ruby/setup-ruby action will install the latest bundler version and it causes a strange problem. At first, instead of treating truffleruby as `platform: ruby`, it now `platform: x86_64-linux`, this behavior itself is already very problematic, as native extension may have been compiled with SSE3, and such native extension will just crash and need to be re-compiled from source using `platform: ruby`.

```
  /home/runner/.rubies/truffleruby-22.2.0/bin/ruby --version
  truffleruby 22.2.0, like ruby 3.0.3, GraalVM CE Native [x86_64-linux]

  /home/runner/.rubies/truffleruby-22.2.0/bin/gem install bundler -v ~> 2.0
  Successfully installed bundler-2.3.18

  /home/runner/.rubies/truffleruby-22.2.0/bin/bundle install --jobs 4
  Fetching google-protobuf 3.21.3 (x86_64-linux)
  Installing google-protobuf 3.21.3 (x86_64-linux)
```

After gems are installed, as a side effect of being treated as a different platform, running the following code also gives an unexpected error due to inconsistent platforms:

``` ruby
Gem::Dependency.new('google-protobuf').to_spec
```

```
Gem::MissingSpecVersionError: Could not find 'google-protobuf' (>= 0) - did find: [google-protobuf-3.21.3-x86_64-linux]
```

**Comment by ntkme** [comment]
Also https://github.com/ruby/setup-ruby/issues/358

**Comment by eregon** [comment]
It's https://github.com/rubygems/rubygems/issues/5691 it should be fixed in the upcoming Bundler 2.3.19: https://github.com/rubygems/rubygems/issues/5691#issuecomment-1193725643

**Comment by ntkme** [comment]
Thanks. I will lock it to 2.3.16 for now.

**Comment by eregon** [comment]
I'll fix https://github.com/ruby/setup-ruby/issues/358 ASAP so users run less into this.

**Comment by eregon** [comment]
Thanks for the report!

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby/issues/358 fixed, so at least setup-ruby users should not run into this with the default `bundler` input.
