### ISSUE TITLE
grpc doesn't build on M1 Mac (aarch64) with 22.2.0

### ISSUE THREAD

**Issue by ollym** [oracle/truffleruby#2697]
```
gem install grpc
Building native extensions. This could take a while...
ERROR:  Error installing grpc:
	ERROR: Failed to build gem native extension.
```

Followed by long list of errors, ending with:

```
29 warnings generated.
linking shared-object grpc/grpc_c.bundle
Stripping grpc_c.bundle
/Users/ollym/.rbenv/versions/truffleruby-22.2.0/lib/llvm-toolchain/bin/llvm-strip: error: option not supported by llvm-objcopy for MachO
make: *** [strip] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/ollym/.rbenv/versions/truffleruby-22.2.0/lib/gems/gems/grpc-1.48.0 for inspection.
Results logged to /Users/ollym/.rbenv/versions/truffleruby-22.2.0/lib/gems/extensions/aarch64-darwin/3.0.3.22.2.0/grpc-1.48.0/gem_make.out
```

**Comment by eregon** [comment]
Thanks for the report.
grpc 1.48.0 should install fine, since it includes the fixes: https://github.com/grpc/grpc/releases/tag/v1.48.0
But apparently it does not work yet for you.

Could you share the gem_make.out and the mkmf.log (somewhere under `/Users/ollym/.rbenv/versions/truffleruby-22.2.0/lib/gems/gems/grpc-1.48.0`)?

I wonder which option is it which is `not supported by llvm-objcopy for MachO`.

**Comment by eregon** [comment]
I wonder if that option is `--keep-section=.llvmbc`:
https://github.com/oracle/truffleruby/blob/c37d6aeb1b1159ce28d2c50dd310b3000a771511/lib/truffle/rbconfig.rb#L191
Because https://github.com/grpc/grpc/blob/dd77c67217b10ffeaf766e25eb8b46d2d59de4ff/src/ruby/ext/grpc/extconf.rb#L159 does not seem to add strip options.

**Comment by eregon** [comment]
I have a fix and a test for it, it should merge soon. We simply need to not pass `--keep-section=.llvmbc` on macOS because it is not supported on macOS, but yet macOS keeps the bitcode by default (unlike Linux where the flag is needed).

**Comment by ollym** [comment]
*gem_make.out*
https://gist.github.com/ollym/343869d0573e870d0bceba5dfd8c19b9

I couldn't find mkmf.log

**Comment by eregon** [comment]
Fixed in 4a027648c1e699cbb00bc2f7e74080bb0f24d1f3. You can try `truffleruby-dev` and it will be in the next release.

**Comment by ollym** [comment]
@eregon I'm still struggling installing grpc with `truffleruby-dev` (installed via rbenv) also

```
$ gem install grpc
Building native extensions. This could take a while...
ERROR:  Error installing grpc:
	ERROR: Failed to build gem native extension.

...many errors...

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [/Users/ollym/.rbenv/versions/truffleruby-dev/lib/gems/gems/grpc-1.48.0/src/ruby/ext/grpc/objs/opt/src/core/ext/filters/client_channel/lb_policy/ring_hash/ring_hash.o] Error 1
make: *** Waiting for unfinished jobs....
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/ollym/.rbenv/versions/truffleruby-dev/bin/ruby
log file does not exist

extconf failed, exit code 1

Gem files will remain installed in /Users/ollym/.rbenv/versions/truffleruby-dev/lib/gems/gems/grpc-1.48.0 for inspection.
Results logged to /Users/ollym/.rbenv/versions/truffleruby-dev/lib/gems/extensions/aarch64-darwin/3.0.3.7/grpc-1.48.0/gem_make.out
```

The contents of gem_make.out are here: https://gist.github.com/ollym/992c273ab98331c5ee1fd2e6652f1ace

**Comment by eregon** [comment]
The problem is likely already solved, except that https://github.com/ruby/truffleruby-dev-builder/actions hasn't produced a build recently due to an issue on macOS builders, which should be fixed soon (i.e. I'd guess fixed by Wednesday).

**Comment by eregon** [comment]
Correction, the latest dev build even though it is old has that fix, so please follow on https://github.com/oracle/graal/issues/4726
