### ISSUE TITLE
Report NullPointerException

### ISSUE THREAD

**Issue by ShalokShalom** [oracle/truffleruby#2713]
[ruby] WARNING: truffleruby starts IRB when stdin is a TTY instead of reading from stdin, use '-' to read from stdin

truffleruby: an internal exception escaped out of the interpreter,
please report it to https://github.com/oracle/truffleruby/issues.

```
<no message> (java.lang.NullPointerException)
        from java.util.Objects.requireNonNull(Objects.java:208)
        from sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
        from java.nio.file.Path.of(Path.java:147)
        from java.nio.file.Paths.get(Paths.java:69)
        from com.oracle.truffle.polyglot.FileSystems$NIOFileSystem.parsePath(FileSystems.java:767)
        from com.oracle.truffle.polyglot.FileSystems$PreInitializeContextFileSystem.parsePath(FileSystems.java:310)
        from com.oracle.truffle.api.TruffleLanguage$Env.getInternalTruffleFile(TruffleLanguage.java:2636)
        from com.oracle.truffle.llvm.runtime.ToolchainImpl.getSysroot(ToolchainImpl.java:149)
        from com.oracle.truffle.llvm.runtime.ToolchainImpl.getWrappersRoot(ToolchainImpl.java:140)
        from com.oracle.truffle.llvm.runtime.ToolchainImpl.getToolPathImpl(ToolchainImpl.java:86)
        from com.oracle.truffle.llvm.runtime.ToolchainImpl.getToolPath(ToolchainImpl.java:54)
        from org.truffleruby.language.TruffleBootNodes$ToolchainExecutableNode.toolchainExecutable(TruffleBootNodes.java:397)
        from org.truffleruby.language.TruffleBootNodesFactory$ToolchainExecutableNodeFactory$ToolchainExecutableNodeGen.executeAndSpecialize(TruffleBootNodesFactory.java:981)
        from org.truffleruby.language.TruffleBootNodesFactory$ToolchainExecutableNodeFactory$ToolchainExecutableNodeGen.execute(TruffleBootNodesFactory.java:966)
        from org.truffleruby.language.RubyCoreMethodRootNode.execute(RubyCoreMethodRootNode.java:48)
/usr/lib/jvm/java-17-graalvm/languages/ruby/lib/truffle/rbconfig.rb:65:in `toolchain_executable'
        from /usr/lib/jvm/java-17-graalvm/languages/ruby/lib/truffle/rbconfig.rb:65:in `<module:RbConfig>'
        from /usr/lib/jvm/java-17-graalvm/languages/ruby/lib/truffle/rbconfig.rb:37:in `<top (required)>'
        from <internal:core> core/kernel.rb:260:in `require'
        from /usr/lib/jvm/java-17-graalvm/languages/ruby/lib/mri/rubygems.rb:8:in `<top (required)>'
        from <internal:core> core/kernel.rb:260:in `require'
        from /usr/lib/jvm/java-17-graalvm/languages/ruby/lib/patches/rubygems.rb:8:in `<top (required)>'
        from <internal:core> core/kernel.rb:260:in `require'
        from /usr/lib/jvm/java-17-graalvm/languages/ruby/bin/irb:28:in `<main>'
```

P.S: I love that you include Backticks into your output XD

Running on Linux
Any more facts needed?

**Comment by eregon** [comment]
How did you install GraalVM?
I think this likely means the LLVM toolchain is not installed.

**Comment by ShalokShalom** [comment]
From the AUR. I reported this issue to the maintainer. More specifically, it needs 
https://aur.archlinux.org/packages/graal-llvm-jdk17-bin

**Comment by eregon** [comment]
Right, installing the ruby component should include both sulong and the llvm toolchain components which are dependencies (and `gu install` does that):
https://github.com/oracle/truffleruby/blob/ea16721f7f9ce953a0a5e50197d327bc776a9904/mx.truffleruby/mx_truffleruby.py#L239

**Comment by eregon** [comment]
@rschatz Is it expected Sulong fails like that when the llvm toolchain is missing? I would expect a clearer message.

Kind of related, we might need to handle this case gracefully for https://github.com/graalvm/container/blob/master/truffleruby/README.md#multi-stage-build-for-the-no-toolchain-images so `require 'rbconfig'` still works for that case.
I think the expectation is the `Toolchain` still works and the wrapper error when they are executed.

**Comment by ShalokShalom** [comment]
I added a comment:
https://aur.archlinux.org/packages/truffleruby-jdk17-bin

**Comment by rschatz** [comment]
The problem isn't that the LLVM toolchain is missing. This is handled gracefully by the toolchain launchers. The problem is that the LLVM *runtime* component is missing.

I guess this is kind of unexpected from the point of view of the code running. After all, the code that's throwing the exception is part of the LLVM runtime ;)

What's happening here is that the code from the LLVM runtime component gets baked into the Ruby native-image at build time. That results in a binary that has code from the LLVM runtime component in there. So it fails if the rest of the LLVM runtime component (in particular it's language home) is missing.

I guess we could handle the error better. Just wondering where else we might have this problem.

**Comment by rschatz** [comment]
No. My comment was just a clarification what's wrong here.

The original issue was a packaging issue, caused by a missing dependency. It has been fixed in the meantime. I don't think there is anything left to fix on the GraalVM side, right?

**Comment by ShalokShalom** [comment]
I dont know. If you are fine, I am fine. 👍🏼
