### ISSUE TITLE
truffle/truffle/fiddle_backend.rb may raise `Polyglot::ForeignException`

### ISSUE THREAD

**Issue by kou** [oracle/truffleruby#2714]
It should raise `Fiddle::Error` or `Fiddle::DLError` to compatible with https://github.com/ruby/fiddle .

e.g.:

https://github.com/ruby-gettext/locale/runs/8130975674?check_suite_focus=true#step:5:8

```text
/Users/runner/.rubies/truffleruby-head/lib/truffle/truffle/fiddle_backend.rb:262:in `<unknown>': dlopen(kernel32.dll, 2): image not found (Polyglot::ForeignException)
```

**Comment by eregon** [comment]
Thank you for the report, I'll take a look soon.

**Comment by eregon** [comment]
There seems to be no test in Fiddle for this case. I guess I'll test this in ruby/spec then.

**Comment by eregon** [comment]
This is a regression since 22.1, it will be fixed soon.

**Comment by eregon** [comment]
@kou Could you maybe rerun https://github.com/ruby-gettext/locale/actions/runs/2970103655/jobs/4780349285 to check it works fine now?

**Comment by kou** [comment]
Done: https://github.com/ruby-gettext/locale/actions/runs/2970103655/jobs/4905290386
It's green now. :-)
Thanks.

**Comment by eregon** [comment]
Great, thanks!
