### ISSUE TITLE
No ability to look at instance variables in VS Code debugger

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#2727]
While debugging a Rails application with the VS Code debugger, I set a breakpoint inside the `call` method of a middleware class. By convention, each middleware will have a handle to the app called `@app`. I would like to inspect that object, but I can't find access to the instance variables anywhere. They don't show up under the "Local" or either of the two "Global" sections. I thought if I expanded the `self` value in the local variable list that I might see the instance variables there. But, all I could see were the object's method list (https://github.com/oracle/truffleruby/issues/2726). I tried expanding `self -> instance_variables`, but all I could see was the set of methods associated with the `instance_variables` object.

I've set a watch expression for `instance_variables` and that will gave me the list of variable names. But, then I need to add a new watch expression for each instance variable name. Since the set changes depending on what frame I'm in, I need to keep adjusting the watch expressions. It would helpful if the values appeared somewhere in VS Code's "Variables" section.

**Comment by eregon** [comment]
Let's take care of this also in https://github.com/oracle/truffleruby/issues/2726 and close this one.

Expanding the `instance_variables` method will not work, I think that much is expected (it'll just show methods of the Ruby `Method` representing `receiver.method(:instance_variables)`).
