### ISSUE TITLE
Support for OpenBSD/adJ

### ISSUE THREAD

**Issue by vtamara** [oracle/truffleruby#2738]
Running `bin/jt build`  (improved with https://github.com/oracle/truffleruby/pull/2737) tries to download JDK-11 but it cannot compile it:
```
$ unset JAVA_HOME; \
  /home/vtamara/comp/truffle/mx/mx \
  -y \
  fetch-jdk \
  --configuration \
  /home/vtamara/comp/truffle/truffleruby/common.json \
  --java-distribution \
  labsjdk-ce-11 \
  --to \
  /home/vtamara/.mx/jdks \
  --alias \
  /home/vtamara/.mx/jdks/labsjdk-ce-11-jvmci-22.3-b04
No such file or directory - /home/vtamara/comp/truffle/mx/mx
FAILED (pid 82558 exit 1): unset JAVA_HOME; \
  /home/vtamara/comp/truffle/mx/mx \
  -y \
  fetch-jdk \
  --configuration \
  /home/vtamara/comp/truffle/truffleruby/common.json \
  --java-distribution \
  labsjdk-ce-11 \
  --to \
  /home/vtamara/.mx/jdks \
  --alias \
  /home/vtamara/.mx/jdks/labsjdk-ce-11-jvmci-22.3-b04
```

Installing the standard jdk-11 package for OpenBSD and setting JAVA_HOME produces:

```
% doas pkg_add jdk-11.0.14.9.1p0v0
% export JAVA_HOME=/usr/local/jdk11/
truffleruby jtportable % bin/jt build
Kernel version changed since last build: "" -> "7"
Error during command: build
/home/vtamara/comp/truffle/truffleruby/tool/jt.rb:596:in `find_java_home': $JAVA_HOME does not seem to point to a JVMCI-enabled JDK (`/usr/local/jdk-11/bin/java -version` does not contain 'jvmci') (RuntimeError)
        from /home/vtamara/comp/truffle/truffleruby/tool/jt.rb:607:in `mx'
        from /home/vtamara/comp/truffle/truffleruby/tool/jt.rb:877:in `mx'
        from /home/vtamara/comp/truffle/truffleruby/tool/jt.rb:2357:in `sforceimports?'
        from /home/vtamara/comp/truffle/truffleruby/tool/jt.rb:2430:in `build_graalvm'
        from /home/vtamara/comp/truffle/truffleruby/tool/jt.rb:905:in `build'
        from /home/vtamara/comp/truffle/truffleruby/tool/jt.rb:3119:in `main'
        from /home/vtamara/comp/truffle/truffleruby/tool/jt.rb:3128:in `<main>'
```

Running `/usr/local/jdk-11/bin/java -version` it produces

```
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-1)
OpenJDK 64-Bit Server VM (build 11.0.14+9-1, mixed mode)
```

**Comment by nirvdrum** [comment]
I don't think this is going to work the way you hope. You could probably run TruffleRuby on a stock JVM, but you won't get any of the JIT benefits from Graal. GraalVM doesn't have builds for any of the BSDs. You'd likely have to run in the Linux compatibility layer.

**Comment by vtamara** [comment]
There is no Linux compatibility layer in recent OpenBSD/adJ.

**Comment by nirvdrum** [comment]
Sorry, I haven't used OpenBSD in probably 10 years. I thought it had ported FreeBSD's Linux compatibility layer.

While we appreciate the interest, I don't see *BSD becoming a supported platform anytime soon. The changes needed in TruffleRuby are fairly minimal. We'd need to add new [configuration for C extensions](https://github.com/oracle/truffleruby/tree/7cc607338c2d83cb834f3f5afe0016af6e523f08/lib/cext/include/truffleruby) and a new implementation of [NativeConfiguration](https://github.com/oracle/truffleruby/blob/7cc607338c2d83cb834f3f5afe0016af6e523f08/src/main/java/org/truffleruby/platform/NativeConfiguration.java) to support any platform-specific settings and type sizes for FFI-type calls. But, without support in Graal, there's little point in running TruffleRuby. While the interpreter runs on a plain JDK, it's just too slow to be of much use. If you're looking to run Ruby on a JVM, you should probably give JRuby a look -- it supports OpenBSD.

**Comment by eregon** [comment]
> No such file or directory - /home/vtamara/comp/truffle/mx/mx

That's very likely because `mx` begins with `#!/bin/bash`, so same as for `jt`. Feel free to PR https://github.com/graalvm/mx for that.

But yes labsjdks builds are done on a number of platforms but not BSDs, see e.g. https://github.com/graalvm/labs-openjdk-11/releases
It might be possible to build them from source but it's probably not completely trivial.
Stock JDKs often don't have all the latest JVMCI updates.

GraalVM in general is supported on these platforms: https://www.graalvm.org/downloads/
If you want to request BSD support or contribute it, I suggest opening an issue at https://github.com/oracle/graal/.

**Comment by eregon** [comment]
Something that might be worth a try is to use your system Java and replace locally in tool/jt.rb:
```diff
diff --git a/tool/jt.rb b/tool/jt.rb
index 441c11c4a5..94ef329776 100755
--- a/tool/jt.rb
+++ b/tool/jt.rb
@@ -593,7 +593,8 @@ module Utilities
           warn "warning: JAVA_HOME=#{java_home} is not the same JVMCI version as in common.json (#{jvmci_version})"
           :use_env_java_home
         else
-          raise "$JAVA_HOME does not seem to point to a JVMCI-enabled JDK (`#{java_home}/bin/java -version` does not contain 'jvmci')"
+          warn "$JAVA_HOME does not seem to point to a JVMCI-enabled JDK (`#{java_home}/bin/java -version` does not contain 'jvmci')"
+          :use_env_java_home
         end
       else
         raise '$JAVA_HOME should be set in CI' if ci?
```

And see if that manages to build a GraalVM with it.
