### ISSUE TITLE
Exception during writing data to a file

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2760]
### Set up
test.rb:
```
str =  [
   236,
   53,
   124,
   0,
   0,
   0].pack('c*').force_encoding('BINARY')
   extractor = IO.popen("./file.out", "w")
   extractor.write(str)
```

`/> touch file.out`
`/> chmod 755 file.out`

### How to run

`ruby test.rb`

fails with:
```
<internal:core> core/string.rb:373:in `encode!': "\xEC" to UTF-8 in conversion from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from <internal:core> core/string.rb:417:in `encode'
	from <internal:core> core/io.rb:2365:in `write'
	from test.rb:9:in `<main>'
```

### Affected gems

[ruby-arr-pm](https://github.com/jordansissel/ruby-arr-pm)

**Comment by eregon** [comment]
Changing it to this reproduces (and is also more sensible code).
```ruby
str =  [
   236,
   53,
   124,
   0,
   0,
   0
].pack('c*').force_encoding('BINARY')

extractor = IO.popen("/usr/bin/cat", "w")
p extractor.write(str)
```

**Comment by eregon** [comment]
It sounds like we'll have to replicate the very complex logic from [`rb_io_set_encoding()`](https://github.com/ruby/ruby/blob/master/io.c) from CRuby, and probably `IO#internal_encoding` and `IO#external_encoding` as well.
BTW `enc` and `enc2` mean internal and external encodings: https://github.com/ruby/ruby/blob/5ffbb2be187681a37f2722ce1d7db4ec5c128464/include/ruby/io.h#L117-L120

Self-note: WIP branch: bd/fix-set_encoding

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/1888b298e494593581e88ca9e83789fb589c2304, thanks for the report.
