### ISSUE TITLE
Slow performance for comparing long strings for equality on aarch64

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#2762]
```ruby
require 'benchmark/ips'

def comp_strings_worst(a, b)
  a == b
end

strings_worst = 100.times.map { |n|
  s = "f#{'o' * 1_000_000}#{n}"
  s = Truffle::Debug.flatten_string(s) if defined?(Truffle::Debug.flatten_string)
  s
}

n = 0

Benchmark.ips do |x|
  puts RUBY_DESCRIPTION

  x.report 'comp_strings_worst' do
    comp_strings_worst strings_worst[n], strings_worst[n + 1]
    n = (n + 1) % 99
  end
end
```

```
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin21]
Warming up --------------------------------------
  comp_strings_worst     3.681k i/100ms
Calculating -------------------------------------
  comp_strings_worst     37.136k (± 1.1%) i/s -    187.731k in   5.055873s
```

```
truffleruby 23.0.0-dev-72aa843b, like ruby 3.0.3, GraalVM CE JVM [aarch64-darwin]
Warming up --------------------------------------
  comp_strings_worst    63.000  i/100ms
Calculating -------------------------------------
  comp_strings_worst    644.254  (± 1.2%) i/s -      3.276k in   5.085737s
```

Is it because of this loop?

```java
        for (int i = 0; i < length; i++) {
            if (readValue(arrayA, offsetA, strideA, i, isNativeA) != readValue(arrayB, offsetB, strideB, i, isNativeB)) {
                return false;
            }
            TStringConstants.truffleSafePointPoll(location, i + 1);
        }
```

We're doing a safe point poll on *every* byte?

**Comment by chrisseaton** [comment]
@nirvdrum

**Comment by chrisseaton** [comment]
That's what I mean - doesn't that branch get in the way of all vectorisation and intrinsification?

**Comment by eregon** [comment]
So it sounds like an architecture-specific thing, @djoooooe do you know why TruffleString equality is a lot slower on aarch64?

**Comment by eregon** [comment]
BTW we have a fairly similar benchmark in repo, https://github.com/oracle/truffleruby/blob/master/bench/micro/string/equal.rb, and TruffleRuby is >10x faster than CRuby/JRuby on amd64.

10000x is maybe because of an early return due to different hash codes, that's why comparing equal strings is actually better to measure byte equality.

**Comment by eregon** [comment]
It's pretty clear that [runRegionEqualsWithStride](https://github.com/oracle/graal/blob/ea1abd32662fe9f09c0effede38ef119c43c3965/truffle/src/com.oracle.truffle.api.strings/src/com/oracle/truffle/api/strings/TStringOps.java#L1040-L1043) is [intrinsified on AMD64](https://github.com/oracle/graal/blob/ea1abd32662fe9f09c0effede38ef119c43c3965/compiler/src/org.graalvm.compiler.truffle.compiler.amd64/src/org/graalvm/compiler/truffle/compiler/amd64/substitutions/AMD64TruffleInvocationPlugins.java#L294) but is not on AArch64.

**Comment by djoooooe** [comment]
I'm currently porting the AMD64 intrinsics to AArch64, that should fix the issue.

**Comment by djoooooe** [comment]
should be fixed by https://github.com/oracle/graal/commit/aebd56cd8843fc3936ef62d939e9590296dd9ca8

**Comment by djoooooe** [comment]
performance of `bench/micro/string/equal.rb`:
| benchmark | previous | with intrinsics | speedup |
|------------------|--------------|-----------------------|--------------|
| core-string-equal-10| 25194645.341864932 | 64764516.75520601 | 2.57x |
|core-string-equal-1000000 | 372.85082236600203 | 22858.086413652352 | 61.31x |

This should bring us up to expected performance levels.
