### ISSUE TITLE
IO#pos= should raise TypeError if argument is non-numeric

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2787]
truffleruby 22.3.0, like ruby 3.0.3, GraalVM CE Native [x86_64-darwin]

fh = File.new('test.txt', 'wb+')
fh.pos = 'bogus'

Expected: no implicit conversion from string (TypeError)
Got: invalid value for Integer(): bogus (ArgumentError)

**Comment by andrykonchin** [comment]
Thank you for the report! Fixed in 85a9b0e52f7a3b314e78de63e309a74659b79c73.
