### ISSUE TITLE
Enumerable#zip with invalid argument should raise TypeError

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2788]
truffleruby 22.3.0, like ruby 3.0.3, GraalVM CE Native [x86_64-darwin]

`[1, 2, 3].zip(1)`

Expected: `wrong argument type Integer (must respond to :each) (TypeError)`

Got: `'each_with_block': undefined method 'each' for 1:Integer (NoMethodError)`

**Comment by andrykonchin** [comment]
Thank you for the report. Fixed in 97ba8a91a83d0e7f951c2e26481bc4e89999c370.
