### ISSUE TITLE
Current performance with Rails

### ISSUE THREAD

**Issue by ShalokShalom** [oracle/truffleruby#2796]
The README suggests a status, that is imho not representive anymore with the current reality.

https://github.com/oracle/truffleruby#current-status

Somebody is interested to introduce TruffleRuby in their company

With the current Readme, that won't fly past the CTO, though.

Is TruffleRuby still as slow as suggested?
Thanks 🥳

**Comment by eregon** [comment]
It says:

> TruffleRuby might not be fast yet on Rails applications and large programs.

That doesn't mean it's slow, just that it may be slow for some large programs/apps.
But it's a good point, we should probably reword.
TruffleRuby is significantly faster than CRuby on multiple Rails benchmarks now.

The mention about warmup is still an important consideration so we should keep something about that in there.

**Comment by ShalokShalom** [comment]
Adding actual benchmarks could help?

There is currently a discussion going on, to make Graal the default for Mastodon.

Considering the current events and the increased pressure on the server - The main Mastodon instance just had to increase its server capacity *twice* in a row - is this a huge opportunity for TruffleRuby and Graal.

**Comment by eregon** [comment]
I'll link to https://eregon.me/blog/2022/01/06/benchmarking-cruby-mjit-yjit-jruby-truffleruby.html for benchmarks.

> There is currently a discussion going on, to make Graal the default for Mastodon.

Could you give a link to that, is it a public discussion? Obviously the TruffleRuby team is interested in that.

**Comment by ShalokShalom** [comment]
https://github.com/mastodon/mastodon/issues/20467
