### ISSUE TITLE
sqlite3 fails to install on WSL2

### ISSUE THREAD

**Issue by Intelliractive** [oracle/truffleruby#2803]
### SETUP:
Ubuntu 22 on WSL2
truffleruby 22.0.0.2 (rbenv)
Rails 7.0.4
---
I couldn't install rails because it requires sqlite3 (1.4+) gem, which fails to be built

**Comment by eregon** [comment]
What's the output?
Which sqlite3 version does it try to install?
Did you install the `sqlite3-dev` system package?

**Comment by eregon** [comment]
Ah also 22.0.0.2 is fairly old, please use the latest release: https://github.com/oracle/truffleruby/releases/latest (it's also in rbenv)
