### ISSUE TITLE
`Coverage.running?` not implemented

### ISSUE THREAD

**Issue by notEthan** [oracle/truffleruby#2813]
The [Simplecov](https://github.com/simplecov-ruby/simplecov) gem just put out a new version which [relies on `Coverage.running?`](https://github.com/simplecov-ruby/simplecov/pull/1035/files#diff-68c13cfe5ec28d52fddb46ef6fcc9fb653e685444b004f553c3f7acc1e736468), which errors out trying to start on truffleruby.

`Coverage.running?` was added in ruby 2.4, Ruby 3.1 also adds the [`Coverage.state`](https://ruby-doc.org/3.1.3/exts/coverage/Coverage.html#method-c-state) method.

**Comment by andrykonchin** [comment]
Thank you for reporting the issue. Fixed in 6c2da4e0db134ac400126114badd1cda8a7c2ee9.
