### ISSUE TITLE
String#casecmp? fails between ascii and utf-8

### ISSUE THREAD

**Issue by notEthan** [oracle/truffleruby#2826]
Comparing an ASCII-8BIT string with UTF-8, for both of which `#ascii_only?` is true, using `String#casecmp?` returns nil rather than a boolean e.g.

```ruby
''.b.casecmp?('')
```
It returns boolean on MRI, and the implementation to return boolean is present in truffleruby but not reached:

https://github.com/oracle/truffleruby/blob/vm-22.3.0/src/main/ruby/truffleruby/core/string.rb#L1204-L1213
The check `if ascii_only? && other.ascii_only?` is not reached after `Primitive.encoding_compatible?(encoding, other.encoding)` returns nil.

**Comment by eregon** [comment]
Thank you for the report.
We should use ` Primitive.encoding_ensure_compatible_str self, other` there I suspect.

**Comment by eregon** [comment]
@notEthan Would you be interested to submit a PR for this, or you prefer the team fixes this? (either is fine)
I'm asking because this seems like it could be an easy contribution.

**Comment by notEthan** [comment]
I had a look but getting a truffleruby development/build/test environment rolling looks to be more involved than I have time to put into this at the moment.

**Comment by eregon** [comment]
No worry, the team will fix it then.
Building from source is explained in https://github.com/oracle/truffleruby/blob/master/doc/contributor/workflow.md, it's mostly automated except setting up `jt`.

**Comment by notEthan** [comment]
Nice, thanks for fixing.
I do want to note that this applies to nonempty strings too, I just used empty strings in the example for conciseness. The code changes look like they apply to all strings, though the tests only use empty ones. (And, looking at the code changes, kinda glad I didn't try to take this on as my first easy contribution)

**Comment by eregon** [comment]
Ah yes of course. The change is to use strings for encoding negotiations (which considers code range and empty) vs only encodings of those strings.
The fix is actually just: https://github.com/oracle/truffleruby/commit/7a96f2cb94af4805a3ac45ab6d5dfc090d06347b, https://github.com/oracle/truffleruby/commit/7dd4301d134eddd3736e1e2f99e3252b075b1c69 is the merge commit and include an unrelated cleanup.
