### ISSUE TITLE
Implement Array#intersect?

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#2831]
Ruby 3.1 introduced the [Array#intersect?](https://ruby-doc.org/core-3.1.0/Array.html#method-i-intersect-3F) core library method. I'm trying to run a project that targets Ruby 3.1 and uses this method. Its absence is a blocker on TruffleRuby.

**Comment by eregon** [comment]
@andrykonchin is already working on Array#intersect? as written in https://github.com/oracle/truffleruby/issues/2733
