### ISSUE TITLE
Bug in Hash literals with invalid symbol keys

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#2848]
While looking at some IRB test failures with @st0012, we came across a case where MRI raises an `EncodingError` but TruffleRuby raises nothing. Looking quickly at the specs, I didn't see anything in the language specs to test this behavior. The code in question is a `Hash` literal with a symbol key with an invalid encoding.

```ruby
puts({"\xAE": 1}.keys)
```

Note, I didn't print the `Hash` directly because the invalid key will raise a separate exception on TruffleRuby when calling `Hash#inspect`.

On MRI:

```
> ruby -v bad_irb.rb
ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin21.5.0]
bad_irb.rb: invalid symbol in encoding UTF-8 :"\xAE" (EncodingError)
```

On TruffleRuby:

```
> jt ruby -v bad_irb.rb
truffleruby 23.0.0-dev-8bb04d8c, like ruby 3.1.3, GraalVM CE JVM [aarch64-darwin]
�
```

**Comment by andrykonchin** [comment]
Fixed in 145d23ebcae366faf11f2d270d1fc4cb22808cae
