### ISSUE TITLE
Can't install truffleruby+graalvm with asdf on AlpineLinux

### ISSUE THREAD

**Issue by yuriy-yarosh** [oracle/truffleruby#3156]
It fails during libssl compilation 
![зображення](https://github.com/asdf-vm/asdf-ruby/assets/6811933/2c73172f-15ad-4718-b645-8a7ec56f1919)

It might have to do something with ld.so LD_LIBRARY_PATH, I presume.

Posted in https://github.com/asdf-vm/asdf-ruby/issues/354 as well.

**Comment by eregon** [comment]
Alpine uses musl but GraalVM releases rely on glibc.
Alpine Linux is not supported with TruffleRuby releases currently.
It might work if you build from source, but that is untested.
