### ISSUE TITLE
truffleruby+graalvm requires graalvm/bin to be writable regardless of gem install dir

### ISSUE THREAD

**Issue by rwstauner** [oracle/truffleruby#3160]
When installed with graalvm gem installation fails if `$PREFIX/graalvm/bin` isn't writable by the user running `gem`:

With the installation at `/usr/loca/ruby`,
and a gem command of `gem install --user-install` (user-install should prefer HOME over GEM_HOME)
throws this error even though the gem installation isn't trying to write anything there (and both HOME and GEM_HOME are writable):

```
$ gem install --no-document --user-install bundler -v 2.4.13
--
  | Fetching bundler-2.4.13.gem
  | WARNING:  You don't have /app/.local/share/gem/truffleruby/3.1.3.23.0.0/bin in your PATH, gem executables will not run.
  | ERROR:  While executing gem ... (Gem::FilePermissionError)
  | You don't have write permissions for the /usr/local/ruby/graalvm/bin directory.
  | /usr/local/ruby/graalvm/languages/ruby/lib/mri/rubygems/installer.rb:962:in `ensure_writable_dir'
```

"extra_bin_dirs" is set when graalvm is included:
https://github.com/oracle/truffleruby/blob/e941116439a13372d60fa537445faba80f39896a/lib/truffle/rbconfig.rb#L63

and the hook that causes this error is one of the patches:
https://github.com/oracle/truffleruby/blob/e941116439a13372d60fa537445faba80f39896a/lib/patches/rubygems.rb#L10-L16
https://github.com/oracle/truffleruby/blob/e941116439a13372d60fa537445faba80f39896a/lib/truffle/rubygems/extra_executables_installer.rb#L13-L45

I can reproduce this on a mac with
```
sudo chown root  ~/.rubies/truffleruby-graalvm-23.0.0/graalvm/Contents/Home/bin
```
as a work around you can set a flag during gem installation which allows it to proceed.
```
TRUFFLERUBYOPT=--ruby.patching=false ./bin/gem install bundler
```

What are the scenarios where this folder will be populated?
Does it make sense to ignore the check if the installation destination is elsewhere?

**Comment by eregon** [comment]
Thanks for the report.
I think we should drop this feature, there is probably little value to have gem executables in `$GRAALVM/bin` these days.
For `truffleruby+graalvm` we always have `bin -> graalvm/languages/ruby/bin` as a symlink, so we don't care what's in `graalvm/bin`.

Also with the upcoming JVM standalones there wouldn't be a "graalvm/bin" anymore.
