### ISSUE TITLE
Segfault in `IO.select`

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#3201]
I have a Rails application that periodically segfaults. The hs_err log indicates it's stemming from the [dnsruby gem](https://github.com/alexdalitz/dnsruby/tree/v1.70.0) as it calls `IO.select`. I'm seeing this with TruffleRuby 23.0.0 on Oracle GraalVM running in JVM mode. The gem is used by an in-house gem that wraps around _ruby-kafka_. As the hs_err shows, there's a background thread that does periodic DNS checks.

I haven't yet debugged the code to see what values are flowing through the system when the error occurs. The _dnsruby_ gem uses class variables for various bits of state and I haven't yet verified the thread-safety of that code.

[hs_err.log](https://gist.github.com/nirvdrum/def238f295353b75345e1191736adea2)

**Comment by eregon** [comment]
I tried to reproduce this with:
On CRuby:
```
$ ruby -ve 'ios=2048.times.map { io=File.new("README.md"); p io.fileno; io }; p ios.last.fileno; IO.select([ios.last], nil, nil, 1.0)'
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
...
1022
1023
-e:1:in `initialize': Too many open files @ rb_sysopen - README.md (Errno::EMFILE)
```

On TruffleRuby:
```
$ ruby -ve 'ios=4096.times.map { io=File.new("README.md"); p io.fileno; io }; p ios.last.fileno; p IO.select([ios.last], nil, nil, 1.0)'
truffleruby 23.1.0-dev-b6c229a4, like ruby 3.1.3, GraalVM CE Native [x86_64-linux]
...
4095
4096
4097
4098
4099
4100
4101
4101
zsh: segmentation fault (core dumped)  ruby -ve 
```

So interestingly CRuby raises EMFILE for what would be fd 1024.
And for some unknown reason TruffleRuby goes higher.

At least what we can do is add a check in IO.select to raise if fd > FD_SETSIZE.

**Comment by eregon** [comment]
open(2) mentions:
> EMFILE The  per-process  limit  on  the  number  of  open file descriptors has been reached (see the description of RLIMIT_NOFILE in getrlimit(2)).

and getrlimit(2) mentions:
```
       RLIMIT_NOFILE
              This specifies a value one greater than the maximum file descriptor  number  that  can  be  opened  by  this
              process.  Attempts (open(2), pipe(2), dup(2), etc.)  to exceed this limit yield the error EMFILE.  (Histori‐
              cally, this limit was named RLIMIT_OFILE on BSD.)

              Since Linux 4.5, this limit also defines the maximum number of file descriptors that an unprivileged process
              (one  without  the  CAP_SYS_RESOURCE  capability)  may  have "in flight" to other processes, by being passed
              across UNIX domain sockets.  This limit applies to the sendmsg(2) system call.   For  further  details,  see
              unix(7).
```
And the default limit for me is `$ limit`: `descriptors     1024`.
So it seems the JVM/SVM increases the soft limit to the hard limit:
```
$ ruby -ve 'p Process.getrlimit Process::RLIMIT_NOFILE'
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
[1024, 524288]

$ ruby -ve 'p Process.getrlimit Process::RLIMIT_NOFILE'
truffleruby 23.1.0-dev-b6c229a4, like ruby 3.1.3, GraalVM CE Native [x86_64-linux]
[524288, 524288]
```

**Comment by eregon** [comment]
On CRuby if we set the limit then it works with higher fds:
```
$ ruby -ve 'Process.setrlimit(Process::RLIMIT_NOFILE, 524288); ios=4096.times.map { io=File.new("README.md"); p io.fileno; io }; p ios.last.fileno; p IO.select([ios.last], nil, nil, 1.0)'
...
4099
4100
4100
[[#<File:README.md>], [], []]
```

**Comment by eregon** [comment]
I have a branch reimplementing `IO.select` with `poll()` or `ppoll()` which seems a pretty good fit, removes this limit of fd < 1024 and is likely faster than select(2).
