### ISSUE TITLE
yarp CI run: an internal exception escaped out of the interpreter

### ISSUE THREAD

**Issue by froydnj** [oracle/truffleruby#3273]
I was asked to report this issue here:

https://github.com/ruby/yarp/actions/runs/6252409387/job/16975640160?pr=1569

Gist of output in case the above is not viewable or goes away for some reason:

https://gist.github.com/froydnj/2e5c50134f0e88a3699c992f612a426d

**Comment by eregon** [comment]
Thanks, this is the same as https://github.com/oracle/truffleruby/issues/3112, notably the first Ruby line in the backtrace is:
`/Users/runner/.rubies/truffleruby-23.1.0/lib/mri/rubygems/specification.rb:845:in `[]='`
So I'll close this one and track it in #3112.

**Comment by eregon** [comment]
Because it's a race condition, rerunning the job is likely to fix it.
