### ISSUE TITLE
SubstrateSegfaultHandler caught a segfault in TruffleCompilerThread

### ISSUE THREAD

**Issue by notEthan** [oracle/truffleruby#3295]
I encountered the error in the title on a github actions workflow - one-off, can't reproduce, no change to my codebase that should cause such a thing. I see some other issues that mention SubstrateSegfaultHandler but I can't tell if they are similar enough that this issue might be a duplicate.

This is the run:
https://github.com/notEthan/jsi/actions/runs/6539290317/job/17757052240?pr=326

and the same log in a gist, if that expires
https://gist.github.com/notEthan/864dbfb2a263593bda9e011f2ae8b605

**Comment by eregon** [comment]
Thank you for the report, I reported this to the Native Image/Compiler team.

**Comment by dentarg** [comment]
Got one too: https://github.com/sinatra/sinatra/actions/runs/6836683176/job/18591868425#step:6:67

Log at https://gist.github.com/dentarg/51d6a8fe6f7dc5fbf6c87c927cdd8b4e too

**Comment by eregon** [comment]
Both of these are segfaults in TruffleCompilerThread.
The internal issue is being investigated (GR-48811).
