### ISSUE TITLE
Trufflerruby image with graalvm

### ISSUE THREAD

**Issue by Izerrion** [oracle/truffleruby#3301]
Greetings.

When we launch the trufflerruby  with flags:
TRUFFLERUBYOPT='--vm.Xmx8G --vm.Xmn4G --jvm'

from the image:
ghcr.io/graalvm/truffleruby-community:debian

We receive the following error:
'--jvm' is only supported when this launcher is part of a GraalVM.

We are new to trufflerruby, so this error seems a bit unusual for the GraalVM packaged in the image.
Can someone tell us if we are downloading the wrong image or doing something wrong?
Thanks in advance.

**Comment by eregon** [comment]
This is expected, `ghcr.io/graalvm/truffleruby-community:debian` has always only contained the native truffleruby standalone, which supports only `--native` and not `--jvm` mode.

See this section of the README:
> Via Docker. For Native Standalone see [official release images](https://github.com/graalvm/container/blob/master/truffleruby-community/README.md) and [nightly images](https://github.com/flavorjones/truffleruby/pkgs/container/truffleruby). For JVM Standalone there are no Docker images yet, but you can easily [download it](https://github.com/oracle/truffleruby/blob/master/doc/user/installing-truffleruby.md) and take inspiration from the [Native Standalone Dockerfiles](https://github.com/flavorjones/truffleruby/blob/master/tool/dockerfiles/stable.dockerfile).

And https://github.com/oracle/truffleruby/blob/master/doc/user/installing-truffleruby.md#jvm-standalone

**Comment by Izerrion** [comment]
Thank you.
