### ISSUE TITLE
TruffleRuby - determine openssl config flags

### ISSUE THREAD

**Issue by MSP-Greg** [oracle/truffleruby#3303]
Good day.

With MRI Ruby, if the build used a config flag for openssl, it appears in `RbConfig::CONFIG['configure_args']`.

Related to the common situation where people have more than one OpenSSL install on macOS, we will be changing Puma's `extconf.rb` file to ignore `openssl.pc` if openssl is contained in `RbConfig::CONFIG['configure_args']`.  Not a perfect check, but it works with standard installations.

Can a similar check be done with TruffleRuby?  We had an issue where Puma was linking to the wrong OpenSSL to link to in GitHub Actions CI...

**Comment by MSP-Greg** [comment]
Looking over a few pre-built files, it seems that many vendor the openssl files, so in extconf.rb we added
```
Dir.exist?("#{RbConfig::TOPDIR}/src/main/c/openssl") # TruffleRuby
```
One can still use `--with-openssl-dir`, we're trying to avoid forcing users to do so.

Closing.

**Comment by eregon** [comment]
There is https://github.com/oracle/truffleruby/issues/3170 to track this.
Doing it breaks installing grpc, so we'd need to find a workaround so it still works for grpc.

**Comment by eregon** [comment]
@MSP-Greg https://github.com/ruby/openssl/pull/653/files is the better workaround until this is added in `configure_args`

**Comment by eregon** [comment]
This will be fixed by https://github.com/oracle/truffleruby/pull/3343.

**Comment by eregon** [comment]
https://github.com/oracle/truffleruby/pull/3343 merged.
@MSP-Greg If you used any workaround for this issue, could you revert them if the CI uses truffleruby-head? They won't be needed anymore in that case.

**Comment by eregon** [comment]
I found https://github.com/puma/puma/blob/master/ext/puma_http11/extconf.rb#L16.
However I think we need to wait for the 24.0 release to remove that because the Puma CI [tests](https://github.com/puma/puma/actions/runs/6893947120/job/18754687998) against the latest truffleruby release, not just head (which is useful), and notably on ubuntu 20.04 where there are multiple libssl installed (IIRC).

**Comment by MSP-Greg** [comment]
@eregon

Just checked the 'head' build, thanks for the fix.
```ruby
RbConfig::CONFIG['configure_args']:
  '--with-openssl-dir=/usr/local/opt/openssl@1.1'
  '--with-libyaml-dir=/usr/local/opt/libyaml'
```
