### ISSUE TITLE
Cannot import an enum using Java.type

### ISSUE THREAD

**Issue by WilliamGusmanov** [oracle/truffleruby#3306]
When using Java.type "some java module", I run into the error: "Unable to load application: TypeError: #<Polyglot::ForeignMetaObject:0x191d5e7b> is not a class/module. 

The java module, simply has the contents of the form:
ex. SomeEnums.java
public enum MyEnums
{
 ENUMA,
 ENUMB
}

The enum should be importable.

**Comment by eregon** [comment]
@WilliamGusmanov Did you get it working?

**Comment by eregon** [comment]
It works fine with enums from the JDK:
```
$ ruby -e 'p Java.type("java.lang.StackWalker$Option").RETAIN_CLASS_REFERENCE'          
#<Polyglot::ForeignObject[Java] java.lang.StackWalker$Option:0x4eb45fec>
```

And also with a custom enum:
```
// foo/MyEnum.java
package foo;

public enum MyEnum {
    FOO,
    BAR
}
```
```
javac foo/MyEnum.java
jar cf foo.jar foo/MyEnum.class
```

All these 3 work:
```
ruby --vm.cp=$PWD/foo.jar -e 'p Java.type("foo.MyEnum")'
ruby -e 'Java.add_to_classpath("#{Dir.pwd}/foo.jar"); p Java.type("foo.MyEnum")'  
uby --vm.-module-path=$PWD/foo.jar --vm.-add-modules=foo -e 'p Java.type("foo.MyEnum")'
```

**Comment by WilliamGusmanov** [comment]
Hi Benoit, yeah I got it working. The issue was due to how was accessing
the import, not the import itself. Thank you for looking into it.
