### ISSUE TITLE
Calling overloaded methods

### ISSUE THREAD

**Issue by fxposter** [oracle/truffleruby#3324]
I have two cases, which are probably related to each other and which were discussed in [this slack thread](https://graalvm.slack.com/archives/CMY63522F/p1700255062902799).

1. I'm trying to call this method https://github.com/etcd-io/jetcd/blob/9a7a98a2ba253946111425503acc6c05706ba989/jetcd-core/src/main/java/io/etcd/jetcd/ClientBuilder.java#L132
```public ClientBuilder endpoints(Iterable<URI> endpoints) {...}```
from ruby by passing it a ruby array:
```
Java.import "io.etcd.jetcd.Client"
JavaURI = Java.type "java.net.URI"
Client.builder().endpoints([JavaURI.new('...')])
```
and getting this error:
```
(irb):30:in `<main>': unsupported type [[#<Polyglot::ForeignObject[Java] java.net.URI:0x31d53d0c>]] (TypeError)
  from <internal:core> core/kernel.rb:414:in `loop'
  from <internal:core> core/throw_catch.rb:36:in `catch'
  from <internal:core> core/throw_catch.rb:36:in `catch'
  from /Users/fxposter/.rbenv/versions/truffleruby+graalvm-dev/lib/gems/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
  from <internal:core> core/kernel.rb:383:in `load'
  from /Users/fxposter/.rbenv/versions/truffleruby+graalvm-dev/bin/irb:44:in `<main>'
```
as was discussed in the slack thread - it probably is related to the fact that there are overloads for that method, but in my opinion this one should call the overload with `Iterable<URI>` parameter.

2. these code:
```
Java.import "java.util.concurrent.Executors"
executor = Executors.newFixedThreadPool(1)
executor.submit lambda { p 1 }
```
gives this error:
```
(irb):3:in `<main>': unsupported type [#<Proc:0x8208 (irb):3 (lambda)>] (TypeError)
	from <internal:core> core/kernel.rb:414:in `loop'
	from <internal:core> core/throw_catch.rb:36:in `catch'
	from <internal:core> core/throw_catch.rb:36:in `catch'
	from /Users/pavelf/.rbenv/versions/truffleruby+graalvm-dev/lib/gems/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from <internal:core> core/kernel.rb:383:in `load'
	from /Users/pavelf/.rbenv/versions/truffleruby+graalvm-dev/bin/irb:44:in `<main>'
```
which is probably due to the fact that it cannot chose between `submit(Runnable)` and `submit(Callable<T>)`, but from the error it's not clear that this is the case, cause docs say that ruby lambdas are converted to relevant interfaces automatically.

**Comment by fxposter** [comment]
As was also mentioned in slack thread - there is a workaround to explicitly select method overload:
```
Java.import "java.util.concurrent.Executors"
executor = Executors.newFixedThreadPool(1)
executor['submit(java.lang.Runnable)'].call(lambda { 1 })
```

**Comment by eregon** [comment]
Thanks for the report.
I made a fix locally to show the error message from host interop, it looks like this:

$ ruby -e 'Java.type("java.util.concurrent.Executors").newFixedThreadPool(1).submit {}'
-e:1:in 'main': Multiple applicable overloads found for method name submit (candidates: [Method[public java.util.concurrent.Future java.util.concurrent.AbstractExecutorService.submit(java.util.concurrent.Callable)], Method[public java.util.concurrent.Future java.util.concurrent.AbstractExecutorService.submit(java.lang.Runnable)]], arguments: [RubyProc@4893b344<Proc> (RubyProc)]) (TypeError)

**Comment by eregon** [comment]
Fix in https://github.com/oracle/truffleruby/pull/3334. I still need to update the docs to mention how to select the overload after that merges.
