### ISSUE TITLE
ffi_tramp_get_temp_file makes implicit declaration of open_temp_exec_file

### ISSUE THREAD

**Issue by sempervictus** [oracle/truffleruby#3327]
```make
Building Java module org.graalvm.ruby.launcher (truffleruby-launcher.jar) from TRUFFLERUBY-LAUNCHER
Building Java module org.graalvm.llvm.nfi (sulong-nfi.jar) from SULONG_NFI
Compiling com.oracle.truffle.llvm.runtime with javac-daemon(JDK 21)... [dependency TRUFFLE_DSL_PROCESSOR updated]
Compiling org.truffleruby with javac-daemon(JDK 21)... [dependency TRUFFLE_DSL_PROCESSOR updated]
MAKE libffi
../libffi-3.4.4/src/tramp.c: In function 'ffi_tramp_get_temp_file':
../libffi-3.4.4/src/tramp.c:262:22: warning: implicit declaration of function 'open_temp_exec_file' [-Wimplicit-function-declaration]
  262 |   tramp_globals.fd = open_temp_exec_file ();
      |                      ^~~~~~~~~~~~~~~~~~~
WARNING: Using incubator modules: jdk.incubator.vector
```
Arch Linux environment, so rolling-stable for the most part (except Ruby is unmaintained so migrating our packages to TruffleRuby)

**Comment by eregon** [comment]
It's a warning and shouldn't fail the build.
It comes from upstream libffi: https://github.com/libffi/libffi/issues/760.
From that issue it sounds like it should be fixed for the next libffi release, but there has not been one yet.
So I think nothing we can do, it's just a noisy warning, sorry.

> except Ruby is unmaintained so migrating our packages to TruffleRuby

Interesting, do you have a link regarding that?

**Comment by sempervictus** [comment]
@eregon - Thanks figured as much since it doesnt blow up running big rails apps :smile:. Things like this are why @brixen and folks did all that work to split Rubinius the Ruby VM from the Ruby code of standard libraries and system interfaces. Sort of wish the ecosystem would stop presuming MRI to be the only thing out there, partially why RBX didn't keep evolving - being "another VM" is a never ending race against tech debt which in some cases can never be fixed (CCs, forking, etc).

https://archlinux.org/packages/extra/x86_64/ruby/ is stuck at 3.0.x due to packager's lack of availability (though this is not in any way indicated on the official page). I have asked @segaja to bring Ruby to current on Arch for well over a year and he doesn't seem keen on it - there's a lot of work involved in dealing with the packaged gems and its not like he's paid to do this. As of right now, Rails apps on Arch need to be containerized into another userspace since Ruby is effectively stuck in 2020 on the platform.

As a result, we've implemented our own packaging for the graalvm-ce environment needed to build truffleruby (jvm-ce for now, but i'm trying like hell to get native image builds working - they seem to assume RHEL though and dont find libgraal on Arch and all JVMs are apparently not-JVMCI-enabled... or more likely a PEBKAC concern). Currently finalizing ports of OpenProject 12.5 and 13. Metasploit is probably next, though that's a **much** bigger lift since we might have more Ruby code than you guys :wink:

**Comment by Segaja** [comment]
> I have asked @Segaja to bring Ruby to current on Arch for well over a year and he doesn't seem keen on it - there's a lot of work involved in dealing with the packaged gems and its not like he's paid to do this. As of right now, Rails apps on Arch need to be containerized into another userspace since Ruby is effectively stuck in 2020 on the platform.

For the record I am willing to do it but we still have a final decision within Arch on how to handle ruby properly while also keeping aligned with our policy of not running software which might have security issues (CVEs). We have a couple of ideas but the decisions are still out.
once we have a decision it will take some time to implement it. Most likely when we do the ruby version on Arch will jump from `3.0` to `3.2` directly.
