### ISSUE TITLE
Ruby -c does not detect unsupported syntax (false positive)

### ISSUE THREAD

**Issue by sempervictus** [oracle/truffleruby#3330]
Running `/usr/lib/jvm/java-21-graalvm/bin/ruby -c somefile.rb` produces `Syntax OK` despite the file containing pattern-matching case statements which the interpreter cannot resolve (`syntax error, unexpected keyword_in`). This creates a false positive for tests trying to ensure that the resulting application is TruffleRuby-compatible.

**Comment by sempervictus** [comment]
This seems a bit more nefarious than i previously thought - https://github.com/oracle/truffleruby/blob/master/doc/user/compatibility.md does not seem to mention the whole "TruffleRuby doesnt do pattern matches" piece which is a pretty big deal especially when the interpreter validates the syntax.

Is there an effort somewhere to get this working?

**Comment by eregon** [comment]
Docs updated in https://github.com/oracle/truffleruby/commit/e16a0c2ab0be7e868cbe56c6364d26e27d3c505e

**Comment by sempervictus** [comment]
Thank you for the detailed explanation - looking forward to common parser and full(ish) compatibility with MRI syntax. Been a while since i've been free of the GIL in production.

**Comment by eregon** [comment]
Fixed for 24.0
