### ISSUE TITLE
gem ruby-debug-ide will not install

### ISSUE THREAD

**Issue by whitehorsesoft** [oracle/truffleruby#3359]
With TruffleRuby 23.1.1, the gem *ruby-debug-ide* will not install. 

```bash
> ruby --version
# truffleruby 23.1.1, like ruby 3.2.2, Oracle GraalVM Native [x86_64-linux]
```

Error log attached.
[gem.err.log](https://github.com/oracle/truffleruby/files/13703350/gem.err.log)

**Comment by eregon** [comment]
It's fixed by https://github.com/ruby-debug/ruby-debug-ide/pull/240.
It needs a release of the gem (feel free to ask it there).

**Comment by eregon** [comment]
Until then a way to deal with this is to use `gem 'ruby-debug-ide', platforms: :mri` in Gemfile.
