### ISSUE TITLE
Inconsistent Kernel#format output for a float between CRuby/JRuby and TruffleRuby

### ISSUE THREAD

**Issue by piotrmurach** [oracle/truffleruby#3360]
There is a difference in how the `Kernel#format` works for float numbers on CRuby/JRuby versus TruffleRuby.

On CRuby/JRuby rounding `0.000005` to 5 decimal places works as expected:

```ruby
format "%5.5f", 0.000005
# => "0.00001"
```

The same on TruffleRuby results in:

```ruby
format "%5.5f", 0.000005
# => "0.00000"
```

The 'critical' point at which the rounding breaks down is around 3 decimal places for value with 4 decimal places. When you reduce precision down to 2 decimal places for a value with 3 decimal points, the rounding starts to work as expected:

```ruby
format "%5.2f", 0.005
# => " 0.01"
```

I spotted this issue in the [tty-progressbar CI](https://github.com/piotrmurach/tty-progressbar/actions/runs/7121172615/job/19760515779).

**Comment by eregon** [comment]
Thanks for the report.

I'm sure of the details anymore, but at least for "round half to even" 0.00000 would be the correct result.
Probably `Kernel#{sprintf,format}` is not "round half to even" then.

**Comment by eregon** [comment]
From this:
```
irb(main):001:0> "%.5f" % 0.000004r
=> "0.00000"
irb(main):002:0> "%.5f" % 0.000005r
=> "0.00001"
irb(main):003:0> "%.5f" % 0.000006r
=> "0.00001"
irb(main):004:0> "%.5f" % -0.000006r
=> "-0.00001"
irb(main):005:0> "%.5f" % -0.000005r
=> "-0.00001"
irb(main):006:0> "%.5f" % -0.000004r
=> "-0.00000"
irb(main):007:0> "%.5f" % 0.000015r
=> "0.00002"
irb(main):008:0> "%.5f" % 0.000025r
=> "0.00003"
irb(main):009:0> "%.5f" % -0.000025r
=> "-0.00003"
irb(main):010:0> "%.5f" % -0.000015r
=> "-0.00002"
```
It looks like CRuby rounds "half away from zero".

TruffleRuby uses Java's DecimalFormat, which default to round to even, but can be changed to `HALF_UP` which seems to match CRuby's behavior.

**Comment by eregon** [comment]
FWIW I noticed on CRuby 3.2:
```
irb(main):017:0> "%.6f" % 0.0000006
=> "0.000001"
irb(main):022:0> "%.6f" % 0.0000005
=> "0.000000"
```
And on TruffleRuby the second one is 0.00001, which at first sight looks more correct.

Maybe it's explained by this:
```
irb(main):023:0> "%.40f" % 0.0000005
=> "0.0000004999999999999999773740559129431293"
```
But then there is also:
```
irb(main):027:0> "%.50f" % 0.000005
=> "0.00000500000000000000040901526957015654772931156913"
```
So it's probably quite arbitrary for how far sprintf looks for whether it's half.

**Comment by eregon** [comment]
Looking at:
```
irb(main):004:0> "%.5f" % 0.000005
=> "0.00001"
irb(main):005:0> "%.5f" % 0.000015
=> "0.00002"
irb(main):006:0> "%.5f" % 0.000025
=> "0.00002"
irb(main):007:0> "%.5f" % 0.000035
=> "0.00004"
irb(main):008:0> "%.5f" % 0.000045
=> "0.00004"
irb(main):009:0> "%.5f" % 0.000055
=> "0.00006"
irb(main):010:0> "%.5f" % 0.000065
=> "0.00006"
irb(main):011:0> "%.5f" % 0.000075
=> "0.00008"
irb(main):012:0> "%.5f" % 0.000085
=> "0.00008"
```

It looks more clearly like a CRuby bug/inconsistency for `0.000005`, or a traditional pitfall of inexact floating point numbers.

I think it's best to keep round-half-to-even in TruffleRuby, as it is, as this should be closer to CRuby on average than round-half-up.
OTOH it does not seem reasonable to replicate the rounding bugs or deep implementation details about what is considered half.

FWIW I pushed my WIP to https://github.com/oracle/truffleruby/compare/master...eregon:truffleruby:bd/fix-rounding-sprintf

**Comment by eregon** [comment]
Float formatting is very prone to such errors and can never be perfect.
One solution is to use `BigDecimal#to_s` or `Kernel#{sprintf,format}` with rationals instead.

TruffleRuby currently deals with Rational by converting them to Float for `Kernel#{sprintf,format}`, so the second does not help, but that is something we could probably implement by extracting the precision and calling `.round` with that value (not trivial though as it kind of breaks encapsulation of conversion & formatting).
