### ISSUE TITLE
rb_enc_interned_str_cstr isn't implemented

### ISSUE THREAD

**Issue by tenderlove** [oracle/truffleruby#3408]
Hi, I want to [use rb_enc_interned_str_cstr](https://github.com/sparklemotion/sqlite3-ruby/pull/486) but it seems like that function isn't available on Truffle Ruby so our [build fails](https://github.com/sparklemotion/sqlite3-ruby/actions/runs/7647176710/job/20837558139?pr=486). Would it be possible to implement that please?

Thanks.

**Comment by eregon** [comment]
Thanks, we'll add it soon.
However I see https://github.com/sparklemotion/sqlite3-ruby/actions/runs/7647176710/job/20837558139?pr=486 uses the latest release and not truffleruby-head, so you might either want to switch to truffleruby-head in that CI (or wait the next release) or use `have_func` to check if it's available + fallback (e.g. `rb_str_new* + rb_funcall(str, "-@")`).

**Comment by tenderlove** [comment]
> `have_func` to check if it's available + fallback (e.g. `rb_str_new* + rb_funcall(str, "-@")` (`rb_fstring` is unfortunately not public although TruffleRuby does implement it).

ah great. I'll do this. Thank you!

**Comment by andrykonchin** [comment]
Fixed in Merged in https://github.com/oracle/truffleruby/commit/88cbf96a837042dd47682b29c68f407c682d5ce3.
