### ISSUE TITLE
Slow download speeds

### ISSUE THREAD

**Issue by wieczorek1990** [oracle/truffleruby#3466]
Hello,

I wanted to experiment with `truffleruby` therefore I did try to download with `rvm` or `rbenv`,
but the download speeds through those programs were too slow.

Maybe putting the release artifacts on GitHub is a way not to lose users at the beginning of their journey.
Other modern way is to put the release on DockerHub (Oracle Linux | Alpine | Fedora).

Best,
Łukasz Wieczorek

**Comment by eregon** [comment]
It is on GitHub, e.g. https://github.com/oracle/truffleruby/releases/tag/graal-23.1.2
And also documented how to install without Ruby managers in the README: 
https://github.com/oracle/truffleruby/blob/master/README.md#getting-started
https://github.com/oracle/truffleruby/blob/master/doc/user/installing-truffleruby.md
And there are Docker images too.

**Comment by wieczorek1990** [comment]
Downloading through docker. Maybe it is something on my end with this
download being slow too.

W dniu niedz., 25.02.2024 o 18:18 Benoit Daloze ***@***.***>
napisał(a):
