### ISSUE TITLE
Gem::DependencyResolutionError: conflicting dependencies b (~> 2.0) and b (>= 0)

### ISSUE THREAD

**Issue by martinemde** [oracle/truffleruby#3477]
I was making a small fix to the rubygems tests and triggered a bug in truffleruby.

The original somewhat unrelated bug was reported in https://github.com/rubygems/rubygems/issues/7493, but it caused a fix that produced this incompatibility.

The ignored block meant the dependency wasn't added, however, adding it produces a failure in truffleruby and jruby. I tried a few variations on the test, using `"1.0"` vs `1` for both versions or neither of them.

[Here](https://github.com/rubygems/rubygems/actions/runs/8104936668/job/22152461359?pr=7494) is one of the test runs.

This seems like a legitimate bug because `>= 0` is compatible with `~> 2`.

**Comment by eregon** [comment]
There seems to be the same test failure on JRuby: https://github.com/rubygems/rubygems/actions/runs/8104936668/job/22152461045?pr=7494#step:8:537
So I would think it's a bug of the PR or existing logic, or maybe just a flaky test. It could also be a race condition that happens on JRuby and TruffleRuby but less likely on CRuby.

**Comment by martinemde** [comment]
Thanks for taking a look @eregon! I'll dig more. The jruby bug does seem to indicate it's possible to fix in rubygems. Sorry for the false positive.
