### ISSUE TITLE
Update Docker Images with v24 release

### ISSUE THREAD

**Issue by ollym** [oracle/truffleruby#3499]
https://github.com/graalvm/container/pkgs/container/truffleruby
Is getting a bit out of date, would be great to have it updated to v24

**Comment by eregon** [comment]
It moved, it's at
https://github.com/graalvm/container/blob/master/truffleruby-community/README.md
https://github.com/graalvm/container/pkgs/container/truffleruby-community
now, which this repo's README links to.

The page you linked also says in the README below that the `truffleruby` image is deprecated/replaced by `truffleruby-community`.
