### ISSUE TITLE
Java exceptions not caught by bare rescue

### ISSUE THREAD

**Issue by mohamedhafez** [oracle/truffleruby#3620]
I made a simple Java class that raises a java exception just to see how TruffleRuby handles them, and ran the following code in IRB: 

```ruby
irb(main):002:0>   Java.import "MyJavaTest"
=> #<Polyglot::ForeignClass[Java] type MyJavaTest>
irb(main):003:0> r=nil
=> nil
irb(main):004:1> begin
irb(main):005:1>   MyJavaTest.test_java_exception
irb(main):006:1> rescue
irb(main):007:1>   puts "in rescue: #{$!.class}"
irb(main):008:1>   r = $!
irb(main):009:0> end
MyJavaTest.java:5:in `test_java_exception': / by zero (Polyglot::ForeignException: java.lang.ArithmeticException)
        from (irb):2:in `<main>'         
        from <internal:core> core/kernel.rb:409:in `Kernel#loop'
        from <internal:core> core/throw_catch.rb:36:in `Kernel#catch'
	from <internal:core> core/throw_catch.rb:36:in `Kernel#catch'
	from /Users/mohamed/.rbenv/versions/truffleruby+graalvm-24.0.1/lib/gems/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from <internal:core> core/kernel.rb:378:in `Kernel#load'
	from /Users/mohamed/.rbenv/versions/truffleruby+graalvm-24.0.1/bin/irb:44:in `<main>'
irb(main):010:0> 
irb(main):011:0> r
=> nil
irb(main):012:0> 
```

Under JRuby I can then access that exception object in `r`, and with Ruby exceptions of course the exception object is available in `r`

I'm running JVM standalone truffleruby:
`truffleruby 24.0.1, like ruby 3.2.2, Oracle GraalVM JVM [aarch64-darwin]`

MyJavaTest.java:
```java
public class MyJavaTest {
    public static int test_java_exception() {
        int result = 12 / 0;
        return result;
    }
}
```

**Comment by eregon** [comment]
`Polyglot::ForeignException` inherits from `Exception`:
```
irb(main):002:0> Polyglot::ForeignException.ancestors
=> 
[Polyglot::ForeignException,                                                
 Polyglot::ExceptionTrait,                                                  
 Polyglot::ObjectTrait,                                                     
 Exception,                                                                 
 Object,                                                                    
 PP::ObjectMixin,                                                           
 Kernel,                                                                    
 BasicObject]  
```

So you would need `rescue Exception` or `rescue Polyglot::ForeignException`.
(`rescue` without anything means `rescue StandardError)

Can you try with `rescue Exception`?

**Comment by mohamedhafez** [comment]
Agh my apologies, missed that section. It's exactly as you said, and it works as intended, my mistake!

**Comment by eregon** [comment]
Maybe we should have Polyglot::ForeignException inherit from StandardError, e.g. for compatibility with JRuby.

I am not sure which is best, there are pros and cons to each approach, e.g. one might not want to rescue an exception from LLVM/NFI/another language with just a `rescue` which intended to catch only Ruby StandardError's.

**Comment by mohamedhafez** [comment]
@eregon Hmm yeah I would really prefer that personally, just because I was hoping to set up my code base to be able to easily switch between JRuby and TruffleRuby, just so I can easily evaluate which one is better for my app going forward when new improvements are made in either one. (it doesn't look like it would be too difficult actually!)

I'd argue that for those of us pulling in libraries from other language, what if something routine goes wrong, for example in my case some kind of network error when using [Google's Firebase SDK](https://github.com/firebase/firebase-admin-java). I would think that would fit the spirit of a StandardError, much more than some kind of exceptional thing that should usually crash a program (which seems to me to be what most Exceptions that aren't StandardErrors seem to be Ruby)

I could always just convert all my bare `rescue` statements to be `rescue StandardError, Polyglot::ForeignException` though and just stub out Polyglot::ForeignException in JRuby, it's just a little cumbersome

**Comment by eregon** [comment]
Right, I'll reopen this to consider changing that then.

**Comment by mohamedhafez** [comment]
I wonder if maybe having some errors like the compilation errors from LLVM inheriting from `Exception`, while more general java runtime errors inherit from `StandardError` could be a good way to balance concerns? just a thought

**Comment by eregon** [comment]
That's not really possible currently because InteropLibrary does not have a notion of "more critical/fatal exceptions or not", so we have to pick the superclass in general (doing it per language does not feel right either).

**Comment by eregon** [comment]
@andrykonchin Could you try changing the superclass of `Polyglot::ForeignException` to `StandardError` and see what needs to change & what can be simplified?
I think we probably should not do that for 24.1 though, it seems late in the release cycle for such a change.

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/744778c585529dff8032d79507ae2ec38037909a
