### ISSUE TITLE
rb_mutex_synchronize should pass the return value as-is

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#3624]
Found by @jeremyevans through:
* https://github.com/jeremyevans/etc/actions/runs/10012691202/job/27678723077
* https://github.com/jeremyevans/etc/commit/7c2b4342b9da0df542c4b118571a04cdde98a5ec
* https://github.com/ruby/etc/pull/40

So in this change, `VALUE rb_mutex_synchronize(VALUE mutex, VALUE (*func)(VALUE arg), VALUE arg);` is used.
But that function is poorly typed, every `VALUE` in there should be `void*` instead, except for `VALUE mutex`.
That is, both `arg` and the return value of `func` can be arbitrary things, not necessary Ruby values/handles.

We already pass `arg` as-is, but we unwrap+wrap the return value, which I highly suspect is the cause of that error in CI.
So we should remove the unwrap+wrap for `rb_mutex_synchronize`.

**Comment by andrykonchin** [comment]
Fixed in 0654e664e9e1ee86eb39e73796d8cb5e410c1e63
