### ISSUE TITLE
Mise / ASDF plugin for TruffleRuby to streamline adoption and improve dev ergonomics

### ISSUE THREAD

**Issue by ylluminate** [oracle/truffleruby#3667]
Given the fact that DHH has advertised [Mise](https://mise.jdx.dev/) as his go-to for Rubies management:
- https://x.com/dhh/status/1832091997743763887
- https://omakub.org/#what-else

And the fact that Mise doesn't allow (neither [will it support such from what they've said](https://github.com/jdx/mise/issues/1737#issuecomment-2351383158)):
```
mise install truffleruby+graalvm@latest
```
I think it could help visibility, adoption and general developer ergonomics if you could please make an ASDF plugin (https://github.com/mise-plugins) so both ASDF and Mise users can easily install and keep the latest version up-to-date...

NOTE: I do realize you could do this: https://github.com/oracle/truffleruby/blob/master/doc/user/ruby-managers.md#asdf-with-asdf-ruby-plugin

But I'm talking about a more ergonomic method dedicated to TruffleRuby that facilitates keeping it updated without having to think. I personally would like to keep an always updated version available since I have a semi-automated approach to updating my packages on macOS that updates both Homebrew, Mise, MacPorts, etc.

**Comment by eregon** [comment]
TBH I'm not sure we (as developers in general) need yet another generic installer which adds another level of complexity by having `mise` using `asdf` using `ruby-build`. That seems a poor user experience to me.
In other words, my recommendation is: just use rbenv or ruby-build + chruby: https://eregon.me/blog/2021/06/04/review-of-ruby-installers-and-switchers.html
Of course people are free to use what they want, but I don't plan to update more than the existing 3 well-established Ruby installers on a release of TruffleRuby.

So I don't think it makes so much sense to track this here.
If people want to contribute to mise to make it better, sure, I just don't see this as a truffleruby-related issue but as a mise issue.
