### ISSUE TITLE
Symbol lookup error: rb_str_strlen

### ISSUE THREAD

**Issue by Th3-M4jor** [oracle/truffleruby#3697]
Had this error come up in [CI](https://github.com/Th3-M4jor/retf/actions/runs/11535842043/job/32111338096?pr=2) while was writing my own Erlang ETF parser for Ruby.

I tested locally against `truffleruby 24.2.0-dev-0e05bfe4, like ruby 3.2.4, Oracle GraalVM JVM [x86_64-linux]` and had the same error.

It appears to be defined here
https://github.com/oracle/truffleruby/blob/b359f4c54c4085ea13390443b62da36d387fba13/lib/cext/include/ruby/internal/intern/string.h#L1189

but does not have a matching implementation in [TruffleRuby's string.c](https://github.com/oracle/truffleruby/blob/b359f4c54c4085ea13390443b62da36d387fba13/src/main/c/cext/string.c)

**Comment by eregon** [comment]
Thank you for the report.

A workaround is to use `rb_funcall(str, rb_intern("size"), 0)`.

This should be an easy fix if anyone wants to contribute it.
