### ISSUE TITLE
`rb_hash_bulk_insert()` is not exposed in `ruby.h`

### ISSUE THREAD

**Issue by byroot** [oracle/truffleruby#3705]
Ref: https://github.com/ruby/json/pull/678

I can see it's in the internal `hash.h`, but it's not exposed in `ruby.h`.

cc @eregon

**Comment by eregon** [comment]
It's declared in https://github.com/oracle/truffleruby/blob/11986d002d36b5971c10a4c37550980b20ce960f/lib/cext/include/ruby/internal/intern/hash.h#L259 which should be included by `ruby.h`.
But we don't implement that function yet.
