### ISSUE TITLE
Best way to install with custom Dockerfile?

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#3719]
I'm trying to get truffleruby installed via Docker on my M1 Mac. I can't really import the existing images out there, I'd like to get it installed on Ubuntu. The start of my Dockerfile looks like this:

```
FROM registry.somewherexxx.net/xyz/ubuntu24:latest

USER root

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    libmagic-dev \
    gnupg2 \
    build-essential \
    freetds-dev \
    shared-mime-info \
    postgresql \
    libpq-dev \
    libyaml-dev \
    git \
    vim

ENV PATH ~/.rbenv/bin:$PATH
RUN git clone https://github.com/rbenv/rbenv.git ~/.rbenv
RUN git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build

RUN rbenv init
RUN rbenv install truffleruby-24.1.1
RUN rbenv global truffleruby-24.1.1
```

However, this seems to choke with

```
rbenv init
unsupported shell: "rosetta"
```
What's the best way to install truffleruby like this?

**Comment by andrykonchin** [comment]
If you are looking for an example of Dockerfile, there is an [official one](https://github.com/graalvm/container/blob/master/truffleruby-community/Dockerfile.debian) and [not official](https://github.com/flavorjones/truffleruby/blob/master/tool/dockerfiles/stable.dockerfile). Installing without any versions manager is described in the [Installing TruffleRuby](https://github.com/oracle/truffleruby/blob/master/doc/user/installing-truffleruby.md) document.

> rbenv init
> unsupported shell: "rosetta"

It seems to me like an `rbenv` issue so it might make sense to report it there.
