### ISSUE TITLE
Marshal.dump loses Data instance attributes

### ISSUE THREAD

**Issue by gillisd** [oracle/truffleruby#3726]
When marshalling and unmarshalling instances of Data classes in truffleruby 24.2.0-dev-49a44754, the attribute values are lost and become nil, though the object structure is preserved:

```ruby
Klass = Data.define(:foo, :bar)
test = Klass.new(foo: 1, bar: 2)
loaded = Marshal.load(Marshal.dump(test))

test.foo   # => 1
loaded.foo # => nil

test.bar   # => 2
loaded.bar # => nil
```

Expected behavior: The loaded object should preserve the original instance attribute values.

TruffleRuby's test suite explicitly excludes this test with the message:

```ruby
exclude :test_marshal, "<#<data TestData::Klass foo=1, bar=2>> expected but was <#<data TestData::Klass foo=nil, bar=nil>>."
```
<br>
Is this the intended behavior for marshalling Data objects?

**Comment by andrykonchin** [comment]
Thank you for the report, we'll look into it.

Yes, it's definitely an issue and it should be fixed.

**Comment by gillisd** [comment]
You rock, thank you!
