### ISSUE TITLE
NameError: uninitialized constant File::SHARE_DELETE

### ISSUE THREAD

**Issue by n-rodriguez** [oracle/truffleruby#3745]
Hi there!

`logger` gem has been released with support of log file rotation on Windows (https://github.com/ruby/logger/commit/7b6146fee6d35ed47c68f482b81206ddf6e1e9c3) and now CI fails :

Backtrace :

```sh
NameError:
  uninitialized constant File::SHARE_DELETE
# ./vendor/bundle/truffleruby/3.2.4.24.1.0.1/gems/logger-1.6.3/lib/logger/log_device.rb:73:in `const_missing'
# ./vendor/bundle/truffleruby/3.2.4.24.1.0.1/gems/logger-1.6.3/lib/logger/log_device.rb:73:in `<class:LogDevice>'
# ./vendor/bundle/truffleruby/3.2.4.24.1.0.1/gems/logger-1.6.3/lib/logger/log_device.rb:7:in `<class:Logger>'
# ./vendor/bundle/truffleruby/3.2.4.24.1.0.1/gems/logger-1.6.3/lib/logger/log_device.rb:5:in `<top (required)>'
# ./vendor/bundle/truffleruby/3.2.4.24.1.0.1/gems/logger-1.6.3/lib/logger.rb:19:in `<top (required)>'
# ./vendor/bundle/truffleruby/3.2.4.24.1.0.1/gems/faraday-2.12.2/lib/faraday/response/logger.rb:4:in `<top (required)>'
# ./vendor/bundle/truffleruby/3.2.4.24.1.0.1/gems/faraday-2.12.2/lib/faraday/response.rb:90:in `<top (required)>'
# ./vendor/bundle/truffleruby/3.2.4.24.1.0.1/gems/faraday-2.12.2/lib/faraday.rb:19:in `<top (required)>'
# ./lib/ovh_rest.rb:7:in `<top (required)>'
# ./lib/ovh-rest.rb:3:in `<top (required)>'
# ./spec/spec_helper.rb:28:in `<top (required)>'
# ./spec/ovh_rest/client_spec.rb:3:in `<top (required)>'
No examples found.
```

It seems that `File::SHARE_DELETE` is only available on Windows in Truffleruby : https://github.com/oracle/truffleruby/blob/master/spec/ruby/core/file/shared/unlink.rb#L51

Thank you!

**Comment by andrykonchin** [comment]
Yeah, indeed. Thank you!

`File::SHARE_DELETE` is meaningful only on Windows and has `0` value on other platforms. And TruffleRuby does not declare it at all as far as Windows is not supported. But it seems this is incorrect and the constant should be declared.

**Comment by andrykonchin** [comment]
Fixed in 08fdec7a3531a889b13d1680502d717ec2de04a8

**Comment by ksr-13** [comment]
I have 
ruby -v
truffleruby 24.2.0-dev-01ebb356, like ruby 3.3.5, GraalVM CE Native [arm64-darwin23]
installed via rvm.
I am getting the error
truffleruby-head@TR/gems/logger-1.6.3/lib/logger/log_device.rb:73:in `const_missing': uninitialized constant File::SHARE_DELETE (NameError)

What is the workaround till 24.2.0 release?

**Comment by andrykonchin** [comment]
Looks like the `truffleruby 24.2.0-dev-01ebb356` version doesn't contain the fix.

The SHA1 `01ebb356` points at commit https://github.com/oracle/truffleruby/commit/01ebb356aab60e12ab9a4d0f14144c25c13beb7b that was merged on Dec 10, 2024. But a commit with the fix is 08fdec7a3531a889b13d1680502d717ec2de04a8 that was created on Dec 16, 2024.

**Comment by n-rodriguez** [comment]
> What is the workaround till 24.2.0 release?

@ksr-13 https://github.com/ONLYOFFICE-QA/ooxml_parser/pull/1427/files

**Comment by eregon** [comment]
We should add truffleruby to ruby/logger CI and propose a workaround there so it works on the current release.
@andrykonchin Can you do that?
