### ISSUE TITLE
SortedSet not using bintree (rbtree)

### ISSUE THREAD

**Issue by prdn** [oracle/truffleruby#702]
Hello,

I'm keep testing truffleruby advances and it's amazing the progress you make every month.
I'm playing with `SortedSet` but (apologies if I'm wrong) to use the `mri` ruby implementation, that is quite slow.
Do you have plans to integreate a java based rbtree?
Or it will work out of the box as soon as truffleruby will support C gems?

Thanks

**Comment by chrisseaton** [comment]
`rbtree` is used if it's installed, isn't it? Does that mechanism not work on TruffleRuby? Or are you saying `rbtree` can't be installed or used in TruffleRuby? Do you know how `rbtree` works on Java if it's a C extension?

We use the same version of `SortedSet` as all other implementations, and we wouldn't normally want to replace Ruby code with Java.

Have you done any benchmarking of `SortedSet` you can share?

**Comment by prdn** [comment]
@chrisseaton the issue is that `rbtree` is a pure C implementation with bindings, with no fallback
Here `stdlib` sortedset implementation tries to load the gem https://github.com/graalvm/truffleruby/blob/master/lib/mri/set.rb#L607
I expect that loading it will fail since it's a C extension.

So I wonder if that will be automatically fixed when truffleruby will support C extensions

**Comment by chrisseaton** [comment]
Isn't this the fallback?

https://github.com/graalvm/truffleruby/blob/31b87ad21152ca55cb6d1c573adc55ccc7f9299e/lib/mri/set.rb#L621

**Comment by prdn** [comment]
yes, but check here:
https://github.com/graalvm/truffleruby/blob/31b87ad21152ca55cb6d1c573adc55ccc7f9299e/lib/mri/set.rb#L672

the `.each` does a `to_a` and `sort`

**Comment by chrisseaton** [comment]
I see that the fallback is slower - but it's still there isn't it? There is a fallback.

I will see if we can install and run the `rbtree` gem. Do you know where the source repo is now? RubyGems links to RubyForge which is dead.

**Comment by prdn** [comment]
I unpacked the `gem` directly.
Sorry for not having expressed my concern correctly. Yes, my concern is that is slower.

**Comment by prdn** [comment]
ps @chrisseaton `SortedSet` are really important to build complex and fast applications, so having it working fast is a game changer imho

**Comment by eregon** [comment]
@prdn Do you have examples of applications/libraries using SortedSet? I have rarely seen it used if at all.
But of course it's still good to get compatibility with `rbtree`.

**Comment by prdn** [comment]
@eregon not sure if there are open source projects that are using it as a key feature.
It's really important when you build scripts that read a lot of data from a file and they need to organise them in an in-memory sorted data structure and perform fast search / analysis
Really `rbtree` is the important piece and for financial analysis scripts is really important.

**Comment by chrisseaton** [comment]
I'm simplifying this issue to #1343 'Get the `rbtree` gem working'.

TruffleRuby is trying to use `rbtree`, so I don't think there is really an issue here beyond not being able to install it.

```
$ ~/Documents/graalvm-1.0.0-rc1/Contents/Home/bin/ruby -Xlog.load -Xlog.feature_location -rset -e 'SortedSet.new([1, 2, 3])'
[ruby] INFO starting search from graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/truffle/truffle/lazy-rubygems.rb:20 for feature set...
[ruby] INFO current directory: /Users/chrisseaton/Documents/test
[ruby] INFO from load path graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/ruby/site_ruby/2.3.0...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/ruby/site_ruby/2.3.0/set.rb...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/ruby/site_ruby/2.3.0/set.su...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/ruby/site_ruby/2.3.0/set...
[ruby] INFO from load path graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/truffle...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/truffle/set.rb...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/truffle/set.su...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/truffle/set...
[ruby] INFO from load path graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/patches/stdlib...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/patches/stdlib/set.rb...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/patches/stdlib/set.su...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/patches/stdlib/set...
[ruby] INFO from load path graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/mri...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/mri/set.rb...
[ruby] INFO found in graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/mri/set.rb
[ruby] INFO loading graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/mri/set.rb
[ruby] INFO starting search from graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/truffle/truffle/lazy-rubygems.rb:20 for feature rbtree...
[ruby] INFO current directory: /Users/chrisseaton/Documents/test
[ruby] INFO from load path graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/ruby/site_ruby/2.3.0...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/ruby/site_ruby/2.3.0/rbtree.rb...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/ruby/site_ruby/2.3.0/rbtree.su...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/ruby/site_ruby/2.3.0/rbtree...
[ruby] INFO from load path graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/truffle...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/truffle/rbtree.rb...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/truffle/rbtree.su...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/truffle/rbtree...
[ruby] INFO from load path graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/patches/stdlib...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/patches/stdlib/rbtree.rb...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/patches/stdlib/rbtree.su...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/patches/stdlib/rbtree...
[ruby] INFO from load path graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/mri...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/mri/rbtree.rb...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/mri/rbtree.su...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/mri/rbtree...
[ruby] INFO from load path graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/json/lib...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/json/lib/rbtree.rb...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/json/lib/rbtree.su...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/json/lib/rbtree...
[ruby] INFO from load path graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/rbtree.rb...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/rbtree.su...
[ruby] INFO trying graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/rbtree...
[ruby] INFO not found
...
```

However I just realised that RubyGems uses `set`, which loads `rbtree` which will cause Sulong to be loaded for every invocation of `ruby`. That's probably not ideal for us and we might want to prevent that.

**Comment by prdn** [comment]
Thanks
