### ISSUE TITLE
No backtrace with two nested rescue

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#706]
```ruby
def raiser
  raise "foo"
end

def intermediate
  begin
    raiser
  rescue => e
    p e.backtrace
  end
end

def catcher
  begin
    intermediate
  rescue
    nil
  end
end

catcher
```

gives

```
["(omitted as the rescue expression was pure; use -Xbacktraces.omit_unused=false to disable)"]
```

Probably the nested rescue should re-enable backtraces in such a case.

**Comment by eregon** [comment]
Note: using Truffle's lazy exceptions (GR-7848) would be a great way to solve this, and makes this optimization redundant :)

**Comment by nirvdrum** [comment]
We've adopted lazy backtraces and it looks to me like this issue is resolved. Please reopen if you see otherwise.

**Comment by eregon** [comment]
Yes, indeed, I fixed this but forgot to close the issue.
