### ISSUE TITLE
cext.rb does not need to be loaded in core

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#799]
See https://github.com/graalvm/truffleruby/pull/796/files#r154308609

The linker should only be loaded when linking,
and the rest of `cext.rb` could be loaded when `ruby.su` is loaded.

**Comment by chrisseaton** [comment]
Didn't you fix this?

**Comment by eregon** [comment]
Yes indeed, I forgot about this issue.
https://github.com/oracle/truffleruby/pull/901/commits/b023b268497dd352ae2ce187eb3ec19818664f12 fixed it.
